### PR TITLE
Stop editor settings import with no selected item

### LINKED ISSUE #14315: Perform Import in Editor Settings Manager can be used without file selection
**Describe the bug**
It is possible to import settings in the Editor Settings Manager while no file was selected. This leads to the Manager closing docked Tools in the Editor.

This issue occurs on both Windows and Linux.

**Steps to reproduce**
1. Open the Editor
2. Open Edit -> Editor Settings -> Editor Settings Manager
3. Click on the 'Perform Import' button on the bottom of the Manager

**Expected behavior**
The button is unusable without Layout file selection.

**Actual behavior**
The Manager closes every docked Tool in the Editor.

**Screenshots/Video**
2023-01-31 12-00-01.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
adc2f3f

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 11 22H2
 - CPU: I7-11700f
 - GPU: Geforce RTX3070 MSI
 - Memory: 32GB

### PR DESCRIPTION
**Pull request by sphrose**
## What does this PR do?

This PR fixes #14315. It disables the import button unless a valid layout item is selected.

## How was this PR tested?
Manual testing.

### CODE REVIEW

File: Code/Editor/SettingsManagerDialog.cpp [hunk 1]
```diff
@@ -42,6 +42,11 @@ CSettingsManagerDialog::CSettingsManagerDialog(QWidget* pParent)
     connect(ui->m_readBtn, &QAbstractButton::clicked, this, &CSettingsManagerDialog::OnReadBtnClick);
     connect(ui->m_importBtn, &QAbstractButton::clicked, this, &CSettingsManagerDialog::OnImportBtnClick);
     connect(ui->m_closeAllToolsBtn, &QAbstractButton::clicked, this, &CSettingsManagerDialog::OnCloseAllTools);
+
+    connect(ui->m_layoutListBox, &QListWidget::itemSelectionChanged, this, &CSettingsManagerDialog::OnSelectionChanged);
+
+    // Diable import button until a layout is selected.
```
Comment (jiaweig-amzn) [inline Code/Editor/SettingsManagerDialog.cpp:48]: Nit: Disable

**Review by jiaweig-amzn — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]
