### PR TITLE
Don't connect to TagGlobalRequestBus from editor tag component

### LINKED ISSUE #9771: UI Canvas asset uses ui editor instead of game view for changes.
**Describe the bug**
When you use a ui canvas asset and say you hook up an image on button click to change color, if you go into game view and click the button, the image will change color, if you have the asset opened up in the ui editor and play in game view and click the button nothing happens in the editor, but in the ui editor the image changes color. So it prioritizes changes even in game view to the editor's ui editor, and these changes get saved after leaving game view.

**Steps to reproduce**
1. Go to UI Editor and make a new graph with an image, and tag component, and another with script canvas component.
2. Click on the script canvas component and create a new graph that has On Graph Start --> Time Delay (1 tick) --> Get entity by tag (tag name from ui image) --> change color (ui image) and pick a color.
3. Close the UI Editor and play the game in game view, everything should work fine.
4. Now open the UI Editor and try again in game view and you should see nothing happen in game view, but look at the ui editor and see how it has changed their instead. Which also saves the changes made so the color will stay when leaving game view.
5. See error

**Expected behavior**
All game view actions are done in game view, and not utilizing other editors (ui editor) while in game view.

**Actual behavior**
A clear and concise description of what actually happened.
The UI editor when opened with the canvas is used instead of game view which alters any parameter changed in game view which makes development with the ui impossible in most use cases.

**Assets required**
Provide sample assets needed to reproduce the issue.
N/A

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.
N/A

**Found in Branch**
Name of or link to the branch where the issue occurs.
Development Branch

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by michabr**
The editor version of the tag component was connecting to the TagGlobalRequestBus which returns the entityIds of all the entities with a specified tag. Since the editor component's tag is the same as the runtime component's tag, a runtime script can get access to an editor component in game mode and change it.

Level entities are not actually affected by this issue because the level entities are deactivated during game mode, but UI canvas entities are affected because each UI canvas has its own entity context and doesn't need to deactivate during game mode.

I've looked through the codebase and didn't find any editor code that was actually making requests on the TagGlobalRequestBus, so this change shouldn't break anything. PostFxLayerComponentController uses the TagComponentRequestBus, EditorTagComponentRequestBus and TagGlobalNotificationBus but those take entityId into account. With this change, we won't need the restriction of deactivating editor components during game mode.

Fixes #9771. 

Signed-off-by: michabr <82236305+michabr@users.noreply.github.com>

### CODE REVIEW

**Review by lumberyard-employee-dm — APPROVED** [review]

File: Gems/LmbrCentral/Code/Source/Scripting/EditorTagComponent.cpp [hunk 1]
```diff
@@ -113,15 +113,15 @@ namespace LmbrCentral
 
         TagComponentNotificationsBus::Event(entityId, &TagComponentNotificationsBus::Events::OnTagAdded, tag);
         TagGlobalNotificationBus::Event(tag, &TagGlobalNotificationBus::Events::OnEntityTagAdded, entityId);
-        TagGlobalRequestBus::MultiHandler::BusConnect(tag);
+        // Intentionally don't connect to the TagGlobalRequestBus for the editor component because its bus Id and params are
+        // not tied to any entity Id. This can collide with the runtime tag component which will have the same tag name
```
Comment (srikappa-amzn) [inline Gems/LmbrCentral/Code/Source/Scripting/EditorTagComponent.cpp:117]: It feels weird to add a comment about a bus that is not being connected to. I recommend that you remove this since the reasoning can be tracked via this PR and commit history.

**Review by srikappa-amzn — APPROVED** [review]

File: Gems/LmbrCentral/Code/Source/Scripting/EditorTagComponent.cpp (hunk 1 above)
Comment (kberg-amzn) [reply Gems/LmbrCentral/Code/Source/Scripting/EditorTagComponent.cpp:117]: Actually this is subtle. The comment is probably a really, really good idea.
