### PR TITLE
Check that AssetBrowser is focused before auto renaming.

### LINKED ISSUE #13990: Asset Browser: Prompts for renames on newly created assets is confusing with 2 Asset Browsers open
**Describe the bug**
Prompts for renames on newly created assets is confusing with 2 Asset Browsers open.

**Steps to reproduce**
1. Launch the Editor and open a new or existing level.
2. Open the Asset Browser if necessary.
3. Right-click any asset and select "Open in another Asset Browser".
4. Right-click any folder, and create any new asset.

**Expected behavior**
Newly created asset prompts user to rename the asset before finalizing.

**Actual behavior**
In one of the open Asset Browsers, the user is prompted to rename the asset, however this doesn't always occur in the currently active/focused Asset Browser, causing confusion.

**Screenshots/Video**
https://user-images.githubusercontent.com/82226555/211667158-6d761fda-83d1-49ce-b307-3b6680a5b5d2.mp4

**Found in Branch**
development@ 7fcff4cfcdaa983e0756cf3215ec96f2f6ef3d75

### PR DESCRIPTION
**Pull request by sphrose**
## What does this PR do?

This PR resolves #13990. Each AssetBrowser checks whether the focused widget is a descendant before entering the renaming functionality.

## How was this PR tested?

Manual testing.

### CODE REVIEW

**Review by dtamkin1 — APPROVED** [review]

File: Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp [hunk 1]
```diff
@@ -329,6 +329,15 @@ AzAssetBrowserWindow::AzAssetBrowserWindow(QWidget* parent)
...
         [this](const QModelIndex& index)
         {
+            // If multiple AssetBrowsers are open, only the focused browser should perform the rename.
+            QWidget* focusWidget = QApplication::focusWidget();
+
+            auto children = this->findChildren<QWidget*>();
+            if (!children.contains(focusWidget))
+            {
+                return;
+            }
```
Comment (cgalvan) [inline Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp:339]: Could make this even more concise by using https://doc.qt.io/qt-6/qwidget.html#isAncestorOf
```suggestion
            QWidget* focusWidget = QApplication::focusWidget();
            if (!isAncestorOf(focusWidget))
            {
                return;
            }
```

**Review by AMZN-alexpete — APPROVED** [review]
