### PR TITLE
Fixed LC crash by preventing graphs from staying open after they are no longer in prefab focus.

### LINKED ISSUE #5085: Editor crashes after adding entities to a prefab through the Landscape Canvas tool
**Describe the bug**
Entities can be added to a prefab via the Landscape Canvas tool even outside of the Focus Mode. Editor crashes more frequently after rapidly adding entities.

**Steps to reproduce**
1. Create a prefab and press the Edit button.
2. Add a Landscape Canvas component and press the Edit button.
3. Close the Focus Mode of the edited prefab.
4. Add multiple components to a graph in quick succession.

**Expected behavior**
Editor remains stable. Entities with components are added to a prefab or prefabs cannot be modified outside the Focus mode.

**Actual behavior**
Editor crashes.

**Call Stack Trace:**
```
25) 00007FF96CD7C347 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FF96F1551B0 (ntdll) : memset
23) 00007FF96F13C766 (ntdll) : _C_specific_handler
22) 00007FF96F1520CF (ntdll) : _chkstk
21) 00007FF96F101454 (ntdll) : RtlRaiseException
20) 00007FF96F150BFE (ntdll) : KiUserExceptionDispatcher
19) 00007FF951E3140A (VCRUNTIME140) : memcpy
18) 00007FF94B086B7D (Qt5Core) : QSortFilterProxyModel::recursiveFilteringEnabledChanged
17) 00007FF94B089BEB (Qt5Core) : QSortFilterProxyModel::sortRoleChanged
16) 00007FF94B08263A (Qt5Core) : QSortFilterProxyModel::`default constructor closure'
15) 00007FF94B07BECA (Qt5Core) : QSortFilterProxyModel::qt_static_metacall
14) 00007FF94B0C0E17 (Qt5Core) : QObject::qt_static_metacall
13) 00007FF94B061042 (Qt5Core) : QAbstractItemModel::endRemoveRows
12) D:\Git\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\UI\Outliner\EntityOutlinerListModel.cpp (1379) : AzToolsFramework::EntityOutlinerListModel::OnEntityInfoUpdatedRemoveChildEnd
11) D:\Git\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1360) : AZ::Internal::EBusContainer<AzToolsFramework::EditorEntityInfoNotifications,AzToolsFramework::EditorEntityInfoNotifications,0,1>::Dispatcher<AZ::EBus<AzToolsFramework::EditorE
10) D:\Git\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Entity\EditorEntityModel.cpp (511) : AzToolsFramework::EditorEntityModel::RemoveChildFromParent
 9) D:\Git\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Entity\EditorEntityModel.cpp (554) : AzToolsFramework::EditorEntityModel::ReparentChild
 8) D:\Git\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Entity\EditorEntityModel.cpp (390) : AzToolsFramework::EditorEntityModel::RemoveEntity
 7) D:\Git\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Entity\EditorEntityModel.cpp (602) : AzToolsFramework::EditorEntityModel::EntityDeregistered
 6) D:\Git\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1360) : AZ::Internal::EBusContainer<AzToolsFramework::ToolsApplicationEvents,AzToolsFramework::ToolsApplicationEvents,0,1>::Dispatcher<AZ::EBus<AzToolsFramework::ToolsApplicationEvent
 5) D:\Git\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Application\ToolsApplication.cpp (478) : AzToolsFramework::ToolsApplication::RemoveEntity
 4) D:\Git\o3de\Code\Framework\AzCore\AzCore\Component\Entity.cpp (97) : AZ::Entity::~Entity
 3) 00007FF9009E8544 (EditorLib) : AZ::Entity::`scalar deleting destructor'
 2) D:\Git\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Prefab\Instance\Instance.cpp (302) : AzToolsFramework::Prefab::Instance::ClearEntities
 1) D:\Git\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Prefab\Instance\InstanceSerializer.cpp (179) : AzToolsFramework::Prefab::JsonInstanceSerializer::Load
```

**Screenshots/Video**

https://user-images.githubusercontent.com/86952009/139246059-9854bbd7-61a6-4d1a-b488-b3f3fec14d10.mp4

**Found in Branch**
stabilization/2110 (https://github.com/o3de/o3de/commit/caab78d9300762b283cf60856753fd090367e193)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version 10
- CPU Intel I5-9600k
- GPU RTX 2060
- Memory 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/7433630/Editor.log)
[error.log](https://github.com/o3de/o3de/files/7433631/error.log)
[dump.zip](https://github.com/o3de/o3de/files/7433632/dump.zip)

### PR DESCRIPTION
**Pull request by cgalvan**
Fixes #5085 

Prevent crash in the Entity Outliner by preventing the user from modifying entities/components through Landscape Canvas after the graph corresponding to that entity is no longer in prefab focus. Tested modifying a Landscape Canvas component on the root instance, inside a prefab, and inside nested prefabs.

Signed-off-by: Chris Galvan <chgalvan@amazon.com>

### CODE REVIEW

File: Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp [hunk 1]
```diff
@@ -2500,6 +2506,24 @@ namespace LandscapeCanvasEditor
         }
     }
 
+    void MainWindow::OnPrefabFocusChanged()
+    {
+        // Make sure to close any open graphs that aren't currently in p refab focus
```
Comment (AMZN-daimini) [inline Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp:2511]: nit: _p refab_

**Review by AMZN-daimini — APPROVED** [review]
Hum maybe not the most elegant solution, but it does the job for now.
We can discuss what the proper UX should look like after this release :)

**Review by tjmichaels — APPROVED** [review]

File: Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp (hunk 1 above)
Comment (cgalvan) [reply Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp:2511]: Whoops thanks will fix! And yes I agree about coming up with a more elegant experience after release.
