### PR TITLE
Fixed creating entities in the viewport logic to use hit test detection.

### LINKED ISSUE #2498: [CRITICAL] When creating entities via the Entity Outliner (right click), they are created under the ground
**Describe the bug**
When you right click in the Entity Outliner window and select 'Create Entity' the created entity is created under the ground.  This behavior is very troublesome because snapping-to-surface doesn't work so you have to manually set the entity z position or turn on grid-snapping and move it with the mouse.

**To Reproduce**
1. Open a level in the editor 
2. Move the editor camera out of the ground so you can see the ground surface
2. Right click in the Entity Outliner window and select 'Create Entity'

**Expected behavior**
The position of the created entity is on the surface of the ground

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da474357f3d0ae9d9c3e884a397ccdcaec7e9be6 (development)

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by cgalvan**
Fixes #2498 

Updated the logic when creating entities via the right-click menu in the viewport to use the same hit detection as dragging/dropping into the viewport from the Asset Browser.
NOTE: The previous logic being used for ViewToWorld currently has all of the input params for hit test as unused, so I'm guessing we are deprecating this function, from a quick search it looks like mostly legacy editor stuff (Editor/Objects) for CBaseObject is what is using those calls. If we do want to go the route of fixing that API so it works though I'm open to that.

CreateEntitiesInViewport

Also fixed a warning message due to an argument being passed to tr() that wasn't formatted to take any arguments as input anymore.

Signed-off-by: Chris Galvan <chgalvan@amazon.com>

### CODE REVIEW

**Review by AMZN-daimini — APPROVED** [review]

**Comment by AMZN-alexpete** [comment]
Nice!

File: Code/Editor/Viewport.cpp [hunk 1]
```diff
@@ -1154,6 +1137,29 @@ bool QtViewport::HitTest(const QPoint& point, HitContext& hitInfo)
...
+        pos = ViewToWorld(point, &hitTerrain);
+        if (hitTerrain)
+        {
+            pos.z = GetIEditor()->GetTerrainElevation(pos.x, pos.y);
+        }
+        pos = SnapToGrid(pos);
+    }
+
+    return AZ::Vector3(pos.x, pos.y, pos.z);
+}
```
Comment (hultonha) [inline Code/Editor/Viewport.cpp:1161]: I think it's great this is fixed but one thing I'm a bit concerned about is we're still relying on a lot of legacy functionality here. Ideally we'd not be relying on `GetIEditor->GetTerrainElevation` (what is that even returning? Is it just coincidence it returns the position where the ground mesh is now? If you move that mesh does this now fail?). I think we really need a task to kill a lot more of this legacy functionality and use the new AZ Viewport work (we have `ViewportScreen` for `ScreenToWorld/WorldToScreen` etc.. as well) and use intersection queries against atom meshes, potentially using the InstersectorBus that exists (we use this in the new camera). Hopefully it's something we can pick-up in the coming months.

Comment (cgalvan) [reply Code/Editor/Viewport.cpp:1161]: I totally agree, to be clear though in this case the "else" case isn't actually being used. There was a bug similar to this awhile back for drag/drop assets into the viewport where I rewrote the QtViewport::HitTest method to indeed use the new viewport interaction queries, so all I did for this was move the existing code to a new method so I could use it as well for the right-click create entity. The fallback else case that is calling GetTerrainElevation isn't being hit in the gif I show above, that was just there from legacy. I left it alone for now because there might indeed be something that is relying on it, but I agree we should do a pass sooner rather than later and get rid of the legacy logic still lurking around.

Comment (hultonha) [reply Code/Editor/Viewport.cpp:1161]: Okay perfect thanks for clarifying - I'd say it'd be good to just delete the `GetIEditor()->GetTerrainElevation` as even if it's being called, if we get the right answer it's by chance 😛 Totally agree would be great to do another pass to remove some of this legacy code. Cheers!

Comment (mbalfour-amzn) [reply Code/Editor/Viewport.cpp:1161]: So... just a bit of color around GetTerrainElevation.  I'm totally great with it being removed since it's completely a legacy remnant, but FWIW that function _will_ actually work as-is with the new terrain system going in.  Back in LY 1.x, we started the refactor for the new terrain system, so we put the new terrain bus in place as a part of extracting the legacy terrain system into a gem.  The GetTerrainElevation method calls that new terrain bus, so with the new terrain system we'll build, if you have a terrain in your level, it will get the actual height of the terrain at that point.

Comment (hultonha) [reply Code/Editor/Viewport.cpp:1161]: Haha okay nice 🙂 Good to know! (though I dream of a day when `GetIEditor` no longer exists 😜)
