### PR TITLE
Ensure render geometry is refreshed when the mesh component controller is moved

### LINKED ISSUE #6450: RenderGeometry OnGeometryChanged not called when EditorMeshComponent transform is changed
**Describe the bug**

The sypmtom of the bug is when using the Surface Manipulator, intersections with meshes appear to fail after moving them. This occurs because `OnGeometryChanged` is not called from the `MeshComponentController::OnTransformedChanged` call so the render geometry is never refreshed.

**Steps to reproduce**

1. Create a new level
2. Add a new entity with a mesh component (EntityA)
3. Duplicate the entity (EntityB)
4. Translate EntityB to a new location
5. Attempt to use the `SurfaceManipulator` to place EntityA on EntityB

**Expected behavior**

EntityA's transform will snap to the intersection point on EntityB

**Actual behavior**

EntityA does not intersect with EntityB after it has been moved (default distance will be used if no intersection was found)

**Assets required**

Any mesh

**Screenshots/Video**

https://user-images.githubusercontent.com/82228511/146397621-e17450e7-7480-4048-9fef-545f86950613.mp4

**Found in Branch**

Development

### PR DESCRIPTION
**Pull request by hultonha**
Fixes #6450 (see ticket for more details)

Test added:

```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from MeshComponentControllerFixture
[ RUN      ] MeshComponentControllerFixture.IntersectionNotificationBusIsNotifiedWhenMeshComponentControllerTransformIsModified
[       OK ] MeshComponentControllerFixture.IntersectionNotificationBusIsNotifiedWhenMeshComponentControllerTransformIsModified (203 ms)
[----------] 1 test from MeshComponentControllerFixture (203 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (217 ms total)
[  PASSED  ] 1 test.
```

Note: There are no changes other than some tidy-up in `Intersector.h`, the main change is in `MeshComponentController.cpp` line `295`. For completeness we may also want to call `OnGeometryChanged` when the model changes. This perhaps should be added in `HandleModelChange`, any input/suggestions would be appreciated. Thanks!)

Update: PR is now ready for review and includes a Unit Test. I've included @amznestebanpapp to review the CMakeLists.txt changes (to add a test target to `AtomLyIntegration`) and I'd be grateful if @gadams3 could take a look too.

Question for the Atom team: When running the test, `RPI::Scene::GetFeatureProcessorForEntity<MeshFeatureProcessorInterface>(entityId)` returns `nullptr` (it is not instantiated) so I've added a `AZ_TEST_START_TRACE_SUPPRESSION` to the test to catch an `AZ_Error` that's thrown. If anyone has a suggestion on if it's possible to either decouple this or instantiate the `SystemComponent` that provides this functionality please let me know. It might be possible to instantiate the `SystemComponent` but it's in another Gem (I think Atom RPI) which I'd need to add as a dependency and load from the test fixture. I think what I have is okay but happy to work with someone to try and improve it. Thanks!

### CODE REVIEW

File: Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp [hunk 1]
```diff
@@ -286,6 +292,11 @@ namespace AZ
             if (m_meshFeatureProcessor)
             {
                 m_meshFeatureProcessor->SetTransform(m_meshHandle, world, m_cachedNonUniformScale);
+                // ensure the render geometry is kept in sync with any changes to the entity the mesh is on
+                AzFramework::RenderGeometry::IntersectionNotificationBus::Event(
+                    FindOwningContextId(m_entityComponentIdPair.GetEntityId()),
```
Comment (invertednormal) [inline Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp:297]: The context shouldn't change after activation, so it may be worth caching that so you don't need to look it up again.

**Review by invertednormal — COMMENTED** [review]
Looks good, thanks for the clean-ups. Just one suggestion.

File: Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp (hunk 1 above)
Comment (hultonha) [reply Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp:297]: Good shout! @AMZN-AlexOteiza mentioned something very similar too 😝 I'll update this, going to try and bind the actual bus function which might be faster still. Cheers! 👍

Comment (hultonha) [reply Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp]: Now updated

**Comment by invertednormal** [comment]
>Question for the Atom team: When running the test, >RPI::Scene::GetFeatureProcessorForEntity<MeshFeatureProcessorInterface>(entityId) returns nullptr (it is not instantiated) so ?>I've added a AZ_TEST_START_TRACE_SUPPRESSION to the test to catch an AZ_Error that's thrown. If anyone has a suggestion >on if it's possible to either decouple this or instantiate the SystemComponent that provides this functionality please let me >know. It might be possible to instantiate the SystemComponent but it's in another Gem (I think Atom RPI) which I'd need to >add as a dependency and load from the test fixture. I think what I have is okay but happy to work with someone to try and >improve it. Thanks!

The component is trying to find the correct feature processor, which requires the the RPI::Scene, AZFramework::Scene,  and render pipeline to be set up. That would be really hard to replicate in a testing environment. I think the way you did it works well enough for now.

Long term it should be possible to have a testing environment for Atom features that sets up the render pipeline on a null renderer backend so at least all the components and feature processors would think they're working.

**Review by invertednormal — APPROVED** [review]
Looks good. It's unfortunate that all we can really test currently is that the bus was notified, not that it's sending correct data. With a null feature processor it's just going to notify with null aabbs.

File: Gems/AtomLyIntegration/CommonFeatures/Code/CMakeLists.txt [hunk 2]
```diff
@@ -115,6 +114,25 @@ if(PAL_TRAIT_BUILD_HOST_TOOLS)
             Legacy::EditorCommon
     )
 
+    ly_add_target(
+        NAME AtomLyIntegration_CommonFeatures.Editor GEM_MODULE
+        NAMESPACE Gem
+        FILES_CMAKE
+            atomlyintegration_commonfeatures_shared_files.cmake
```
Comment (amznestebanpapp) [inline Gems/AtomLyIntegration/CommonFeatures/Code/CMakeLists.txt:121]: just so others know, this file was already there (it just has the Module file)

**Review by amznestebanpapp — APPROVED** [review]

File: Gems/AtomLyIntegration/CommonFeatures/Code/CMakeLists.txt (hunk 2 above)
Comment (hultonha) [reply Gems/AtomLyIntegration/CommonFeatures/Code/CMakeLists.txt:121]: Thanks for calling it out, come to think of it should I remove `Module.cpp` from `atomlyintegration_commonfeatures_editor_files.cmake` now?

**Comment by hultonha** [comment]
> Looks good. It's unfortunate that all we can really test currently is that the bus was notified, not that it's sending correct data. With a null feature processor it's just going to notify with null aabbs.

That's true... though ideally that's all I actually want to test with this (trying to be minimal). The Intersector system will keep a list of these dirty entityIds and then later refresh their bounds internally when next requested. But really that should be its own test which would be easier to mock on its own (I've (jokingly 😛) asked @AlexOteiza to make a PR when he has time but might be a little while 😉). It's on my list otherwise 🙂

**Comment by hultonha** [comment]
> > Question for the Atom team: When running the test, >RPI::Scene::GetFeatureProcessorForEntity(entityId) returns nullptr (it is not instantiated) so ?>I've added a AZ_TEST_START_TRACE_SUPPRESSION to the test to catch an AZ_Error that's thrown. If anyone has a suggestion >on if it's possible to either decouple this or instantiate the SystemComponent that provides this functionality please let me >know. It might be possible to instantiate the SystemComponent but it's in another Gem (I think Atom RPI) which I'd need to >add as a dependency and load from the test fixture. I think what I have is okay but happy to work with someone to try and >improve it. Thanks!
> 
> The component is trying to find the correct feature processor, which requires the the RPI::Scene, AZFramework::Scene, and render pipeline to be set up. That would be really hard to replicate in a testing environment. I think the way you did it works well enough for now.
> 
> Long term it should be possible to have a testing environment for Atom features that sets up the render pipeline on a null renderer backend so at least all the components and feature processors would think they're working.

That would be really nice, and I think would be possible. There's a way to have tests load other Gems that @greerdv worked on and we use in a few places. If there's more we want to test in future it could be worth doing this and getting more of the environment setup. Appreciate the feedback and understanding on this being solid enough for now, cheers! 👍

**Comment by invertednormal** [comment]
> > Looks good. It's unfortunate that all we can really test currently is that the bus was notified, not that it's sending correct data. With a null feature processor it's just going to notify with null aabbs.
> 
> That's true... though ideally that's all I actually want to test with this (trying to be minimal). The Intersector system will keep a list of these dirty entityIds and then later refresh their bounds internally when next requested. But really that should be its own test which would be easier to mock on its own (I've (jokingly 😛) asked @AlexOteiza to make a PR when he has time but might be a little while 😉). It's on my list otherwise 🙂

Oh yeah, totally agree with the precision testing, just mentioning that we can't write tests for other aspects of this yet :)

File: Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp [hunk 3]
```diff
@@ -287,6 +295,11 @@ namespace AZ
             {
                 m_meshFeatureProcessor->SetTransform(m_meshHandle, world, m_cachedNonUniformScale);
             }
+
+            // ensure the render geometry is kept in sync with any changes to the entity the mesh is on
+            AzFramework::RenderGeometry::IntersectionNotificationBus::Event(
```
Comment (amzn-tommy) [inline Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp:300]: Why not have the intersector listen to TransformNotificationBus::OnTransformChanged and dirty the entity whenever the transform changes? Otherwise every component that handles the IntersectionRequestBus needs to know to put this call in OnTransformChanged.

**Comment by AlexOteiza** [comment]
A bit late to the party but I think it may be worth to expose this EBus to behavior context (may be interesting editor artists scripts) and write an automated tests for this one.

**Comment by hultonha** [comment]
> A bit late to the party but I think it may be worth to expose this EBus to behavior context (may be interesting editor artists scripts) and write an automated tests for this one. Something I can commit to do, but no ETA for now :P

Thanks for the suggestion @AlexOteiza! 😄 (lovely to hear from you too by the way 🙂) That sounds like a cool idea, definitely ping me if you do find time to get to this! I know @AMZN-alexpete recently added some picking logic to the BehaviorContext that could be useful to check out as a reference - https://github.com/o3de/o3de/pull/6903
