### PR TITLE
fixed prefab adapter DOM update to fire regardless of update type

### LINKED ISSUE #17066: DPE Inspector sometimes doesn't refresh to show override edits
**Describe the bug**

DPE Inspector occasionally does not refresh itself to show override edits. If I manually force the Inspector to refresh (switching entity selection), you notice that the edits are then visible.

Notes:
1. It happens to some component types and property types. It doesn't happen to Transform Component
2. The Entity Outliner always displays the correct state of override edit.

**Steps to reproduce**
1. Create an entity
2. Add `Fly Camera Input`, `Camera` components to that entity
3. Create a prefab out of that entity
4. Select that entity and make override edits

**Expected behavior**

The DPE Inspector should always reflect the override edits.

**Actual behavior**

The DPE Inspector doesn't always reflect the override edits.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/11157226/17afa0c6-41f0-43cb-b163-8497d5774dd7

Note that every time I made the override edit, the Outliner always showed the status correctly.

**Found in Branch**

https://github.com/o3de/o3de/tree/point-release/23101

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**

https://github.com/o3de/o3de/commit/cfa481a2359ca1645963a942a524a0182037613c

**Desktop/Device**
* Device: PC
* OS: Windows 10
* CPU: AMD Ryzen 5950x
* GPU: NVIDIA RTX 3070
* Memory: 64 GB

### PR DESCRIPTION
**Pull request by alexmontAmazon**
## What does this PR do?
- move the dom update code out of the InProgressEdit and into the general case, so that it happens for the FinishedEdit case as well
- Fixes #17066 

## How was this PR tested?
Locally, in the Editor project

### CODE REVIEW

**Review by lumberyard-employee-dm — APPROVED** [review]

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabComponentAdapter.cpp [hunk 1]
```diff
@@ -203,6 +150,57 @@ namespace AzToolsFramework::Prefab
...
+        AZ::Dom::Path serializedPath = propertyChangeInfo.path / AZ::Reflection::DescriptorAttributes::SerializedPath;
+
+        AZ::Dom::Path relativePathFromOwningPrefab(PrefabDomUtils::EntitiesName);
+        relativePathFromOwningPrefab /= m_entityAlias;
+        relativePathFromOwningPrefab /= PrefabDomUtils::ComponentsName;
+        relativePathFromOwningPrefab /= m_componentAlias;
+
+        AZ::Dom::Value serializedPathValue = GetContents()[serializedPath];
+        AZ_Assert(
+            serializedPathValue.IsString(), "PrefabComponentAdapter::UpdateDomContents - SerialziedPath attribute value is not a string.");
```
Comment (AMZN-alexpete) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabComponentAdapter.cpp:162]:
```suggestion
            serializedPathValue.IsString(), "PrefabComponentAdapter::UpdateDomContents - SerializedPath attribute value is not a string.");
```

**Review by AMZN-alexpete — APPROVED** [review]
