### PR TITLE
Sphrose/asset browser list mode context menu

### LINKED ISSUE #13472: Asset Browser: No file management options are available for assets filtered through via search
**Describe the bug**
No file management options are available for assets filtered through via search.

**Steps to reproduce**
1. Launch the Asset Browser.
2. Type in the search box for a known asset, such as PinkFlower.prefab.
3. Once filtered to, right-click the found asset.

**Expected behavior**
User is able to perform expect right-click context menu options on the filtered asset.

**Actual behavior**
No context menu appears on right-click

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
4ddd58442cb8a4d46ad053796e3b6f66fb9852ce

### PR DESCRIPTION
**Pull request by sphrose**
## What does this PR do?

This PR fixes #13472 by duplicating the context menu from the AssetBrowserTreeView in the TableView.

## How was this PR tested?

All menu items were tested to ensure they behaved correctly.

### CODE REVIEW

**Review by dtamkin1 — APPROVED** [review]

File: Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp [hunk 1]
```diff
@@ -412,8 +413,22 @@ void AzAssetBrowserRequestHandler::AddContextMenuActions(QWidget* caller, QMenu*
...
+    AssetBrowserTreeView* treeView = qobject_cast<AssetBrowserTreeView*>(caller);
+    if (treeView)
+    {
+        calledFromAssetBrowser = treeView->GetIsAssetBrowserMainView();
+    }
+
+    AssetBrowserTableView* tableView = qobject_cast<AssetBrowserTableView*>(caller);
+    if (tableView)
+    {
+        calledFromAssetBrowser |= tableView->GetIsAssetBrowserMainView();
```
Comment (dtamkin1) [inline Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp:428]: Just out of curiosity, why did you decide to use a bitwise or assignment instead of an `=` here?

Comment (sphrose) [reply Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp:428]: I was being over cautious: there should never be an instance of treeView being set at the same time as tableView, so the or is irrelevant really.

**Review by cgalvan — APPROVED** [review]
