### PR TITLE
Fix renderpass compatibility validation error on Atom_RHI.Vulkan

### LINKED ISSUE #12142: [PC][Quest2] Vulkan validation error: VUID-vkCmdDrawIndexed-renderPass-02684
**Steps to reproduce**
1. Necessary repos:
    o3de/o3de:development https://github.com/o3de/o3de
    o3de/o3de-extras:development https://github.com/o3de/o3de-extras
    aws-lumberyard-dev/o3de-atom-sampleviewer:openxr https://github.com/aws-lumberyard-dev/o3de-atom-sampleviewer/tree/openxr
2. Build editor and launcher on PC on profile with AtomSampleViewer project
3. Run Asset Processor to build assets
4. Connect Quest 2 to PC via cable an open Quest Link.
5. Run a default level with the launcher using options "-rhi=vulkan -rhi-device-validation=enable -openxr=enable -sample=RHI/OpenXr"
6. Check log

**Expected behavior**
No vulkan errors

**Actual behavior**
_<13:47:39> [Error] (vkDebugMessage) - [ERROR][Validation] Validation Error: [ VUID-vkCmdDrawIndexed-renderPass-02684 ] Object 0: handle = 0x661d03000000041a, type = VK_OBJECT_TYPE_RENDER_PASS; Object 1: handle = 0xbb26cd00000003e6, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x8cb637c2 | vkCmdDrawIndexed: RenderPasses incompatible between active render pass w/ VkRenderPass 0x661d03000000041a[] with a dependencyCount of 2 and pipeline state object w/ VkRenderPass 0xbb26cd00000003e6[] with a dependencyCount of 0. The Vulkan spec states: The current render pass must be compatible with the renderPass member of the VkGraphicsPipelineCreateInfo structure specified when creating the VkPipeline bound to VK_PIPELINE_BIND_POINT_GRAPHICS (https://vulkan.lunarg.com/doc/view/1.3.224.1/windows/1.3-extensions/vkspec.html#VUID-vkCmdDrawIndexed-renderPass-02684)_

_<13:47:39> [Error] (vkDebugMessage) - [ERROR][Validation] Validation Error: [ VUID-vkCmdDraw-renderPass-02684 ] Object 0: handle = 0x114987000000041e, type = VK_OBJECT_TYPE_RENDER_PASS; Object 1: handle = 0x1a87c70000000245, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x50685725 | vkCmdDraw: RenderPasses incompatible between active render pass w/ VkRenderPass 0x114987000000041e[] with a dependencyCount of 1 and pipeline state object w/ VkRenderPass 0x1a87c70000000245[] with a dependencyCount of 0. The Vulkan spec states: The current render pass must be compatible with the renderPass member of the VkGraphicsPipelineCreateInfo structure specified when creating the VkPipeline bound to VK_PIPELINE_BIND_POINT_GRAPHICS (https://vulkan.lunarg.com/doc/view/1.3.224.1/windows/1.3-extensions/vkspec.html#VUID-vkCmdDraw-renderPass-02684)_

**Found in Branch**
o3de/o3de:development 25d1b023df
o3de/o3de-extras:development afd898e
aws-lumberyard-dev/o3de-atom-sampleviewer:openxr 45dcef8

**Desktop/Device (please complete the following information):**
 - Device: [PC]
 - OS: [Windows]
 - Version [10]
 - CPU [Ryzen Threadripper 3970X]
 - GPU [NVidia RTX 2080Ti]
 - Memory [48GB]

### PR DESCRIPTION
**Pull request by akioCL**
* Replace external subpass dependencies for renderpasses with normal barriers to avoid compatibility issues with pipeline renderpasses.

Fixes #12142
Signed-off-by: Akio Gaule <10719597+akioCL@users.noreply.github.com>

## What does this PR do?

Fixes a Vulkan validation error due to renderpass incompatibility between the command list renderpass and the pipeline renderpass. The incompatibility is due to subpass dependencies present in the command list renderpass. This dependencies are added during the barrier optimization procress. By replacing the external dependencies with normal barriers we get rid of the incompatibility.  
More info in: [KhronosGroup/Vulkan-Docs#726](https://github.com/KhronosGroup/Vulkan-Docs/issues/726)

## How was this PR tested?

Run AVS with Vulkan and the latest validation layers enabled. No validation errors were found.

### CODE REVIEW

File: Gems/Atom/RHI/Vulkan/Code/Source/RHI/Scope.cpp [hunk 1]
```diff
@@ -370,6 +361,16 @@ namespace AZ
                 return false;
             }
 
+            const RHI::ScopeAttachment* scopeAttachment =
+                slot == BarrierSlot::Prologue ? barrier.m_attachment->GetPrevious() : barrier.m_attachment->GetNext();
+
+            // We don't optimize external barriers because they cause renderpass incompatiblity with the pipeline renderpass.
+            // The subpass dependencies added by the optimization causes the incompatibility.
+            if (!scopeAttachment || scopeAttachment->GetScope().GetFrameGraphGroupId() != GetFrameGraphGroupId())
```
Comment (moudgils) [inline Gems/Atom/RHI/Vulkan/Code/Source/RHI/Scope.cpp:369]: Will this cause a perf drop?

**Review by moudgils — APPROVED** [review]
