### PR TITLE
Made the ScriptCanvasApplication toggleable with a cmake setting

### LINKED ISSUE #19347: Script Canvas: Make the ScriptCanvasApplication configurable
**Describe the bug**
Script Canvas was changed from being an in-editor tool to a standalone executable tool. This is desirable to support realtime debugging of realtime graphs.

Unfortunately, this change introduced issues that need to be addressed to maintain the tool's quality, performance, and stability.

This task is to change the ScriptCanvas cmake configuration such that it may still be enabled to work on the ScriptCanvasApplication project, but to keep it as an in-editor tool during the time the issues are addressed. 

The work will be tracked in this project: https://github.com/orgs/o3de/projects/77

### PR DESCRIPTION
**Pull request by lsemp3d**
## What does this PR do?

The ScriptCanvas standalone application change had some quality, stability, and performance issues that need to be addressed before the change can be permanently enabled, these are being tracked in this project: github.com/orgs/o3de/projects/77

Closes #19347

To toggle the ScriptCanvas standalone application the CMake option `SCRIPTCANVAS_BUILD_STANDALONE_APPLICATION` needs to be enabled and rebuild.

## How was this PR tested?

Built with and without the `SCRIPTCANVAS_BUILD_STANDALONE_APPLICATION` option and verified that the ScriptCanvas editor worked as expected in each configuration

### CODE REVIEW

File: Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp [hunk 1]
```diff
@@ -361,6 +361,11 @@ namespace ScriptCanvasEditor
     // MainWindow
     ////////////////
 
+    MainWindow::MainWindow(QWidget* parent)
```
Comment (guillaume-haerinck) [inline Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp:366]: can be behind the ifdef as well so that we don't forget to remove it later

**Review by guillaume-haerinck — APPROVED** [review]
thanks for taking care of that, follow-up to https://github.com/o3de/o3de/pull/18722 for other reviewers
