### PR TITLE
Initial fix for geometry being intersected when not visible

### LINKED ISSUE #2790: Viewport - Shapes are still selectable even with Gizmos disabled
**Describe the bug**
In the Editor, it is still possible to select shapes in the viewport even when the Gizmos are disabled (and as such shapes are not visible).

**To Reproduce**
1. Create an entity with a mesh, and another entity with a shape containing it
image
2. Click on the mesh entity - it should select the shape (correctly)
3. Press on the "Toggle viewport helpers" button in the top toolbar of the viewport to disable gizmo icons and shapes
image
4. Clear the selection, then click on the mesh again

**Expected behavior**
The Mesh is selected

**Actual behavior**
The Shape is still selected despite not being visible

**Screenshots**
gizmoShapes

### LINKED ISSUE #5294: Editor_re:Invent_Bug - Shapes are selectable in the viewport even when they are not displayed.
**Describe the bug**
Currently, Shape Components are only displayed in the viewport if the "Toggle Viewport Helpers" option is enabled on the top right. Nonetheless, even when they are not visible, clicking in the area occupied by the shape still selects the entity. This is quite confusing since the user may be trying to select the actual visible entities behind it.

Similarly, if the shape is part of a prefab, the shape will not be visualized even if the "Toggle Viewport Helpers" option is enabled (since helpers drawing is limited to the currently focused prefab) but the shape is still selectable (and will select the owning prefab).

**Steps to reproduce**
1. Load a Level
2. Create an entity
3. Add a Shape Component to it
4. Disable the "Toggle Viewport Helpers" option (top right of the viewport toolbar)
5. Deselect the entity, then click where the shape was.

**Expected behavior**
The entity is not selected, and if there's an entity behind it, that entity is selected.

**Actual behavior**
The entity with the Shape Component is selected.

**Screenshots/Video*
shapeSelection
*

### PR DESCRIPTION
**Pull request by hultonha**
This fixes an issue where intersections between shapes and mouse clicks happen even when helpers are off and the shapes are not visible.

Note: Not _all_ components that are affected have been updated, the only other example right now is the `SplineComponent`. This is implemented in a way that does not impact other components with bounds that do not disappear when helpers are disabled (e.g. `MeshComponent`).

Fixes #5294
Fixes #2790

```
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from All/ShapeComponentIndirectCallManipulatorViewportInteractionFixtureParam
[ RUN      ] All/ShapeComponentIndirectCallManipulatorViewportInteractionFixtureParam.ShapeIntersectionOnlyHappensWithHelpersEnabled/0
[       OK ] All/ShapeComponentIndirectCallManipulatorViewportInteractionFixtureParam.ShapeIntersectionOnlyHappensWithHelpersEnabled/0 (303 ms)
[ RUN      ] All/ShapeComponentIndirectCallManipulatorViewportInteractionFixtureParam.ShapeIntersectionOnlyHappensWithHelpersEnabled/1
[       OK ] All/ShapeComponentIndirectCallManipulatorViewportInteractionFixtureParam.ShapeIntersectionOnlyHappensWithHelpersEnabled/1 (298 ms)
[----------] 2 tests from All/ShapeComponentIndirectCallManipulatorViewportInteractionFixtureParam (603 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (603 ms total)
[  PASSED  ] 2 tests.
```

Update: Another potential (future) fix for this may be to have components that are no longer visible completely disconnect from `EditorComponentSelectionRequestsBus` while the helpers are not showing... It's essentially an optimization but could be a pretty useful one and will be easier to write after this initial change with tests.

### CODE REVIEW

**Review by cgalvan — APPROVED** [review]

File: Code/Framework/AzToolsFramework/AzToolsFramework/API/ComponentEntitySelectionBus.h [hunk 1]
```diff
@@ -8,91 +8,99 @@
...
-        virtual bool SupportsEditorRayIntersect() { return false; }
+        //! @brief Returns true if the component overrides EditorSelectionIntersectRay method,
+        //! otherwise selection will be based only on AABB test.
+        //! @return True if EditorSelectionIntersectRay method is implemented.
+        virtual bool SupportsEditorRayIntersect()
+        {
+            return false;
+        }
+
+        virtual bool SupportsEditorRayIntersectViewport([[maybe_unused]] const AzFramework::ViewportInfo& viewportInfo)
```
Comment (moraaar) [inline Code/Framework/AzToolsFramework/AzToolsFramework/API/ComponentEntitySelectionBus.h:68]: A doxygen comment would be nice for `SupportsEditorRayIntersectViewport` to know the difference with `SupportsEditorRayIntersect`, which says it'll return true if `EditorSelectionIntersectRay` is overridden, is it suppose to be the same for this new function or something else?

File: Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorSelectionUtil.cpp [hunk 2]
```diff
@@ -95,11 +95,12 @@ namespace AzToolsFramework
             entityId,
             [mouseInteraction, &entityPicked, &closestDistance, viewportId](EditorComponentSelectionRequests* handler) -> bool
             {
-                if (handler->SupportsEditorRayIntersect())
+                const auto viewportInfo = AzFramework::ViewportInfo{ viewportId };
```
Comment (moraaar) [inline Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorSelectionUtil.cpp:98]: `viewportInfo` is not used outside the `if`, seems like it could be moved inside to reduce the scope where `viewportInfo` is seen.

File: Gems/LmbrCentral/Code/Tests/EditorShapeComponentIntersectionTests.cpp [hunk 3]
```diff
@@ -0,0 +1,113 @@
...
+        : public ShapeComponentIndirectCallManipulatorViewportInteractionFixture
+        , public ::testing::WithParamInterface<IntersectionQueryOutcome>
+    {
+    public:
+        void SetUpEditorFixtureImpl() override
+        {
+            ShapeComponentIndirectCallManipulatorViewportInteractionFixture::SetUpEditorFixtureImpl();
+
+            auto* entity1 = AzToolsFramework::GetEntityById(m_entityId1);
+            entity1->Deactivate();
```
Comment (moraaar) [inline Gems/LmbrCentral/Code/Tests/EditorShapeComponentIntersectionTests.cpp:72]: I can see useful here to ASSERT that `entity1` is not `nullptr`, in case the base class changes in the future and child classes are missed to be updated (unlikely, but it could happen and it'll be easier to detect).

**Review by moraaar — APPROVED** [review]
Looks good. I put a few comments, but nothing blocking.

File: Code/Framework/AzToolsFramework/AzToolsFramework/API/ComponentEntitySelectionBus.h (hunk 1 above)
Comment (hultonha) [reply Code/Framework/AzToolsFramework/AzToolsFramework/API/ComponentEntitySelectionBus.h:68]: That's a good call, I'll add some additional info 👍

File: Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorSelectionUtil.cpp (hunk 2 above)
Comment (hultonha) [reply Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorSelectionUtil.cpp:98]: `viewportInfo` is passed in as an argument to `SupportsEditorRayIntersectViewport` which is why it's outside right now

File: Gems/LmbrCentral/Code/Tests/EditorShapeComponentIntersectionTests.cpp (hunk 3 above)
Comment (hultonha) [reply Gems/LmbrCentral/Code/Tests/EditorShapeComponentIntersectionTests.cpp:72]: Hmm you could be right, but my philosophy is that is not what the test is verifying, so I don't really want that mixed in here (there should, and I hope is, a test to verify this elsewhere to ensure it doesn't break). For that reason I'd rather leave it for now (or possibly add an `AZ_Assert` as a sanity check, but not an actual test assert)

File: Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorSelectionUtil.cpp (hunk 2 above)
Comment (moraaar) [reply Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorSelectionUtil.cpp:98]: I missed that one, sorry.

File: Gems/LmbrCentral/Code/Tests/EditorShapeComponentIntersectionTests.cpp (hunk 3 above)
Comment (hultonha) [reply Gems/LmbrCentral/Code/Tests/EditorShapeComponentIntersectionTests.cpp]: This is now updated :+1:

File: Code/Framework/AzToolsFramework/AzToolsFramework/API/ComponentEntitySelectionBus.h (hunk 1 above)
Comment (hultonha) [reply Code/Framework/AzToolsFramework/AzToolsFramework/API/ComponentEntitySelectionBus.h:71]: Updated the comment 👍

File: Gems/LmbrCentral/Code/Source/Shape/EditorBaseShapeComponent.cpp [hunk 4]
```diff
@@ -129,35 +140,47 @@ namespace LmbrCentral
...
+    }
+
+    bool EditorBaseShapeComponent::SupportsEditorRayIntersectViewport(const AzFramework::ViewportInfo& viewportInfo)
+    {
+        bool helpersVisible = false;
+        AzToolsFramework::ViewportInteraction::ViewportSettingsRequestBus::EventResult(
+            helpersVisible, viewportInfo.m_viewportId,
+            &AzToolsFramework::ViewportInteraction::ViewportSettingsRequestBus::Events::HelpersVisible);
+        return helpersVisible;
+    }
```
Comment (AMZN-daimini) [inline Gems/LmbrCentral/Code/Source/Shape/EditorBaseShapeComponent.cpp:182]: Would there be a way to also support entity containers? Right now, we don't display helpers for entities that are descendants of closed entity containers. Sounds like this would only work for the "helpers disabled" case.

(It could be a follow-up change honestly, this works as a stand-alone change)

**Review by AMZN-daimini — APPROVED** [review]
