### PR TITLE
Fix issue with mouse input for viewport camera

### LINKED ISSUE #2802: [CRITICAL] (Editor) Editor camera rotation is sluggish and difficult to use
**Describe the bug**
The editor camera now has a nice ease in-out movement, but this ease in-out has also been applied to rotation which is not good and makes camera rotation feel sluggish and "drunk".  My recommendation is to disable all camera rotation easing when moving the camera in the editor viewport via mouse input - it's fine to leave it when zooming to an object using the 'z' key.  

**To Reproduce**
1. Rotated the camera in the editor viewport

**Expected behavior**
Camera rotation is precise and easy to control and doesn't lag or overshoot

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da47435

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by hultonha**
Fixes #2802

This resolves an issue identified by @amzn-jillich and @AMZN-alexpete. This PR adds the option to disable all rotation smoothing and also ensure that even with smoothing enabled, no drift occurs while rotating the camera (there is also a new integration test for this).

Adding `sig-presentation` as I've added a mock for the WindowRequests interface.

Before fix:

```
D:/o3de/Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp(164): error: Value of: cameraRotation.GetRotation()
Expected: is close (X: 0, Y: 0, Z: 0, W: 1)
  Actual: (X: -0.00999935, Y: -0.000100001, Z: 0.0099998, W: 0.9999) (of type class AZ::Quaternion)
[  FAILED  ] ModularViewportCameraControllerFixture.Mouse_movement_does_not_accumulate_excessive_drift_in_modular_viewport_camera (10239 ms)
[----------] 1 test from ModularViewportCameraControllerFixture (10240 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (10245 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ModularViewportCameraControllerFixture.Mouse_movement_does_not_accumulate_excessive_drift_in_modular_viewport_camera
```

```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ModularViewportCameraControllerFixture
[ RUN      ] ModularViewportCameraControllerFixture.Mouse_movement_does_not_accumulate_excessive_drift_in_modular_viewport_camera
[       OK ] ModularViewportCameraControllerFixture.Mouse_movement_does_not_accumulate_excessive_drift_in_modular_viewport_camera (207 ms)
[----------] 1 test from ModularViewportCameraControllerFixture (208 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (211 ms total)
[  PASSED  ] 1 test.
```

### CODE REVIEW

File: Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp [hunk 1]
```diff
@@ -147,15 +159,18 @@ namespace AzFramework
             m_scrollDelta = scroll->m_delta;
         }
 
-        m_handlingEvents = m_cameras.HandleEvents(event, m_motionDelta, m_scrollDelta);
+        m_handlingEvents =
+            m_cameras.HandleEvents(event, ed_cameraSystemUseCursor ? m_cursorState.CursorDelta() : m_motionDelta, m_scrollDelta);
```
Comment (bosnichd) [inline Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp:163]: Are you noticing a significant difference between the two options?

**Review by bosnichd — APPROVED** [review]

**Review by NicholasVanSickle — APPROVED** [review]
Very nice, thanks for getting some testing integrated here!

File: Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp (hunk 1 above)
Comment (hultonha) [reply Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp:163]: Yeah it's massive unfortunately 🙁 I still think there's actually a bug lurking somewhere that we should be able to fix... as _in theory_ the behavior should be the same! But when using the editor (if you mouse over something, right click and wave the mouse around for a while, and then move it back to where you started, with the CursorDelta there's essentially no perceivable drift (checking in pitch/yaw of Go To Position will be 0, 0) but with the `motionDelta` way there's usually drift in pitch and yaw...) I haven't ripped the code out as I would like to investigate further at some point, but I've decided this is a good placeholder for now (and can be tested by flipping the CVar at runtime).

File: Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ModularViewportCameraController.h [hunk 2]
```diff
@@ -18,9 +18,22 @@ namespace AtomToolsFramework
 {
     class ModularViewportCameraControllerInstance;
 
+    //! A reduced ViewportContext interface for use by the ModularViewportCameraController.
+    //! @note This extra indirection is used to facilitate testing the ModularViewportCameraController.
+    class ModularCameraViewportContext
```
[the remark this answers is not in the document]
Comment (hultonha) [reply Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ModularViewportCameraController.h:23]: I did go down the route of trying to instantiate a `ViewportContextManager` (but right now it has a private constructor and you need the whole `RPISystem` to be created...). It might be possible we can simplify it in future but with this we can limit what actually needs to be instantiated in the test which is nice. If there are more examples of setting up the RPI system for testing it would be interesting to see. Thanks!

**Review by cgalvan — APPROVED** [review]

File: Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp [hunk 3]
```diff
@@ -0,0 +1,165 @@
...
+        // When
+        // move mouse diagonally to top right, then to bottom left and back repeatedly
+        auto current = start;
+        auto halfDelta = QPoint(200, -200);
+        for (int diagonals = 0; diagonals < 80; ++diagonals)
+        {
+            for (int i = 0; i < 50; ++i)
+            {
+                MousePressAndMove(m_rootWidget.get(), current, halfDelta / 50, Qt::MouseButton::RightButton);
+                m_controllerList->UpdateViewport({ TestViewportId, AzFramework::FloatSeconds(0.01666f), AZ::ScriptTimePoint() });
```
Comment (AMZN-alexpete) [inline Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp:144]: Would an additional test that uses differing framerates be useful?  I don't mean random frametimes, but some preset array of frametimes that are not exactly 60fps that is looped through on each mouse move

File: Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp [hunk 4]
```diff
@@ -0,0 +1,165 @@
...
+
+        // When
+        // move mouse diagonally to top right, then to bottom left and back repeatedly
+        auto current = start;
+        auto halfDelta = QPoint(200, -200);
+        for (int diagonals = 0; diagonals < 80; ++diagonals)
+        {
+            for (int i = 0; i < 50; ++i)
+            {
+                MousePressAndMove(m_rootWidget.get(), current, halfDelta / 50, Qt::MouseButton::RightButton);
```
Comment (AMZN-alexpete) [inline Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp:143]: 50 should probably be some local constant

File: Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp (hunk 1 above)
Comment (bosnichd) [reply Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp:163]: No worries, if it works it works:) I guess it's now also consistent with the old editor viewport which we discovered used the delta between the cursor position instead of the raw mouse movement values like I originally thought. Would be interesting to know why it behaves so differently, but I wouldn't spend too much time on it if this gives us what we need.

**Review by AMZN-alexpete — APPROVED** [review]
Just some minor suggestions

File: Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp (hunk 4 above)
Comment (hultonha) [reply Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp:143]: Good call! Will fix :+1:

File: Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp (hunk 3 above)
Comment (hultonha) [reply Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp:144]: That's an interesting idea, it shouldn't be too hard to make this a parameterized test and have it vary based on `deltaTime` - I think I'd rather do that than just add a separate test but it might be better to do that as a separate PR. I'll do a fast follow-up with that transformation so we can see the changes more clearly in the diff (as right now this file is an add).

File: Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp (hunk 1 above)
Comment (hultonha) [reply Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp:163]: I've got a good test case locally now (basically we can accumulate both the `cursorState.CursorDelta()`s and `motionDeltas` in two separate accumulators, and then break when they first diverge).

There does seem to be some issues around conversions between floating point and integer values - something I noticed is you might sometimes have a value like `6.999999f` which when doing the standard `aznumeric_cast` to `int` will return `6` as all the extra precision is just thrown away. I had some success with using `AZStd::round` which will return `7` in this case but I still think there's an issue somewhere.

I'm going to fix some more pressing issues but I would like to circle back to this again as it really feels like there's something I don't fully understand (and really want to! 😝)

**Comment by hultonha** [comment]
Just an FYI with these changes, things don't work correctly when enabling 'capture cursor' but I'll be fixing that in the next PR 🙂 Hopefully won't be long 👍
