### PR TITLE
AttributeInvocable non-void instance call wrapper

### LINKED ISSUE #13830: When using lambdas with Attributes in the EditContext, the lambda signature requires a void* handler
**Describe the bug**
When trying to use a lambda with an Attribute in an EditContext, the expectation is that it would have a signature that receives a typed instance of the class, similar to passing a member function in. Instead, the lambda is required to receive a void*.

**Steps to reproduce**
1. Change the code for the AttributeData_WithCallableType_Succeeds in AzCore/Tests/Serialization.cpp to the following. The only change to the method is changing `AZ::AttributeInvoker invoker` to `AZ::AttributeReader invoker`:
```
    TEST_F(Serialization, AttributeData_WithCallableType_Succeeds)
    {
        constexpr AZ::Crc32 invokableCrc = AZ_CRC_CE("Invokable");
        constexpr AZ::Crc32 nonInvokableCrc = AZ_CRC_CE("NonInvokable");
        auto ReadFloat = [](SerializeTestClasses::BaseNoRtti* instance) -> float
        {
            auto noRttiInstance = instance;
            if (!noRttiInstance)
            {
                ADD_FAILURE() << "BaseNoRtti instance object should not be nullptr";
                return 0.0f;
            }
            EXPECT_FALSE(noRttiInstance->m_data);
            return 2.0f;
        };

        m_serializeContext->Class<SerializeTestClasses::BaseNoRtti>()
            ->Attribute(invokableCrc, ReadFloat)
            ->Attribute(nonInvokableCrc, 4.0f)
            ;

        SerializeTestClasses::BaseNoRtti baseNoRttiInstance;
        baseNoRttiInstance.Set();
        auto classData = m_serializeContext->FindClassData(azrtti_typeid<SerializeTestClasses::BaseNoRtti>());
        ASSERT_NE(nullptr, classData);
        AZ::Attribute* attribute = AZ::FindAttribute(invokableCrc, classData->m_attributes);
        ASSERT_NE(nullptr, attribute);
        AZ::AttributeReader invoker(&baseNoRttiInstance, attribute);
        float value = 0;
        EXPECT_TRUE(invoker.Read<float>(value));
        EXPECT_FLOAT_EQ(2.0f, value);

        AZ::Attribute* nonInvokeAttribute = AZ::FindAttribute(nonInvokableCrc, classData->m_attributes);
        ASSERT_NE(nullptr, nonInvokeAttribute);
        invoker = { &baseNoRttiInstance, nonInvokeAttribute };
        value = {};
        EXPECT_TRUE(invoker.Read<float>(value));
        EXPECT_FLOAT_EQ(4.0f, value);
    }
```
2. Run the unit test. Observe it failing.
3. Change the ReadFloat definition to start with the following:
```
        auto ReadFloat = [](void* instance) -> float
        {
            auto noRttiInstance = (SerializeTestClasses::BaseNoRtti*)instance;
```
4. Run the unit test. Observe it succeeding.

**Expected behavior**
The first unit test change succeeds, the second one fails.

**Actual behavior**
The AttributeReader type creates an AttributeInvoker<void>, so when the invoker.Read() call is made, the AZ::Internal::AttributeRead() method tries to cast the attribute to an AttributeInvokable<float(void*&)> instead of an AttributeInvokable<float(BaseNoRtti*&)>, so the cast only succeeds if the lambda takes in a void*.

Ideally this would successfully call the lambda with a strongly-typed instance pointer. 

Even better, it should warn if the lambda is defined with the wrong parameters and print the expected function signature instead of just silently ignoring it.

**Found in Branch**
development

### PR DESCRIPTION
**Pull request by lumberyard-employee-dm**
## What does this PR do?

Added the GetVoidInstanceAttributeInvocable function which returns a smart pointer that either wraps the existing attribute instance in a deleter that is a no-op or if the Attribute is of type `AttributeInvocable` wrap that wraps a functor stored inside of it with another function that can call the original with the first argument replaced with a void*.

It is the responsibility of the caller to verify that correct instance type is passed supplied when using the wrapped attribute with an AttributeReader. This is due to needing to perform static_cast from a `void*` instance to the original first argument type in order to make the function call.

fixes #13830

Fixed the creation of the GenericValueList attribute in the EditContext whenever an EnumValues attribute is reflected.
It now properly replicates an `EnumValues` attribute that stores data in an `AZStd::vector<Edit::EnumConstant<EnumType>` to a GenericValueList attribute that stores the data in an `AZStd::vector<AZStd::pair<EnumType, AZStd::string>>`

This allow all querying of the value, description pairs for a combobox to be serviced through a Unified API.
This is done by just using the `GenericValueList` attribute.
The Legacy ReflectedPropertyEditor still uses `EnumValues` attribute for querying the list of (enum value -> enum description) entries.

## How was this PR tested?

Added a UnitTest to validate that the GetUnsafeAttributeReader was able to call a lambda function that accepted a class type as the first parameter.

### CODE REVIEW

**Review by amzn-tmryan — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]

File: Code/Framework/AzCore/Tests/Serialization.cpp [hunk 1]
```diff
@@ -5712,6 +5712,39 @@ namespace UnitTest
         EXPECT_FLOAT_EQ(4.0f, value);
     }
 
+    TEST_F(Serialization, AttributeInvocable_UsingVoidPointerInstance_Succeeds)
+    {
+        constexpr AZ::Crc32 invokableCrc = AZ_CRC_CE("Invokable");
```
Comment (burelc-amzn) [inline Code/Framework/AzCore/Tests/Serialization.cpp:5717]: `constexpr` variables are still stack variables, there's nothing here that is forcing this to be evaluated in a `constexpr` context (like a `static_assert`). This should be `static constexpr` instead.

File: Code/Framework/AzCore/AzCore/RTTI/AttributeReader.h [hunk 2]
```diff
@@ -165,27 +177,53 @@ namespace AZ
...
-            return Internal::AttributeInvoke<RetType>(m_attribute, m_instancePointer, AZStd::forward<Args>(args)...);
+            using DecayInstType = AZStd::remove_cvref_t<InstType>;
+            if constexpr (AZStd::is_pointer_v<DecayInstType> && AZStd::is_void_v<AZStd::remove_pointer_t<DecayInstType>>)
+            {
+                // Forward the void* as an rvalue so it is not a void*&
+                return Internal::AttributeInvoke<RetType>(m_attribute, static_cast<DecayInstType>(m_instance), AZStd::forward<Args>(args...));
+            }
+            else
+            {
+                return Internal::AttributeInvoke<RetType>(m_attribute, m_instance, AZStd::forward<Args>(args...));
```
Comment (burelc-amzn) [inline Code/Framework/AzCore/AzCore/RTTI/AttributeReader.h:204]: These lines have the ellipsis in the wrong place:
```suggestion
                return Internal::AttributeInvoke<RetType>(m_attribute, static_cast<DecayInstType>(m_instance), AZStd::forward<Args>(args)...);
            }
            else
            {
                return Internal::AttributeInvoke<RetType>(m_attribute, m_instance, AZStd::forward<Args>(args)...);
```

Comment (burelc-amzn) [inline Code/Framework/AzCore/AzCore/RTTI/AttributeReader.h:204]: These lines have the ellipsis in the wrong place:
```suggestion
                return Internal::AttributeInvoke<RetType>(m_attribute, static_cast<DecayInstType>(m_instance), AZStd::forward<Args>(args)...);
            }
            else
            {
                return Internal::AttributeInvoke<RetType>(m_attribute, m_instance, AZStd::forward<Args>(args)...);
```

File: Code/Framework/AzCore/Tests/Serialization.cpp (hunk 1 above)
Comment (lumberyard-employee-dm) [reply Code/Framework/AzCore/Tests/Serialization.cpp:5717]: No actually, this variable is being evaluated compile time by MSVC, GCC and Clang due to the `constexpr` keyword, now it is being placed on the stack however, because there is no const.
https://godbolt.org/z/GqjY44KMM

File: Code/Framework/AzCore/AzCore/RTTI/AttributeReader.h (hunk 2 above)
Comment (lumberyard-employee-dm) [reply Code/Framework/AzCore/AzCore/RTTI/AttributeReader.h:204]: I'll fix this.

**Review by burelc-amzn — APPROVED** [review]

File: Code/Framework/AzCore/Tests/Serialization.cpp [hunk 3]
```diff
@@ -5712,6 +5712,39 @@ namespace UnitTest
         EXPECT_FLOAT_EQ(4.0f, value);
     }
 
+    TEST_F(Serialization, AttributeInvocable_UsingVoidPointerInstance_Succeeds)
+    {
+        static constexpr AZ::Crc32 invokableCrc = AZ_CRC_CE("Invokable");
```
[the remark this answers is not in the document]
Comment (spham-amzn) [reply Code/Framework/AzCore/Tests/Serialization.cpp:5717]: You are both correct! https://wikidiff.com/invokable/invocable

**Review by spham-amzn — APPROVED** [review]

**Comment by spham-amzn** [comment]
Is this compilable with gcc/g++ ?

**Comment by lumberyard-employee-dm** [comment]
> Is this compilable with gcc/g++ ?

Yes it is.

File: Code/Framework/AzCore/AzCore/RTTI/ReflectContext.h [hunk 4]
```diff
@@ -132,8 +134,87 @@ namespace AZ
 
         friend OnDemandReflectionOwner;
     };
-
+}
     // Attributes to be used by reflection contexts
+    // Forward declare UnsafeAttributeInvoker here so that it can be used as return value for
+    // GetUnsafeAttributeInvoker function below, but it is implemented in AttributeReader.h to avoid
+    // a circular include
```
Comment (amzn-tmryan) [inline Code/Framework/AzCore/AzCore/RTTI/ReflectContext.h:141]: Comment might be stale.

**Review by amzn-tmryan — APPROVED** [review]

File: Code/Framework/AzCore/AzCore/RTTI/AttributeReader.h [hunk 5]
```diff
@@ -72,54 +84,54 @@ namespace AZ
             {
                 if constexpr (AZStd::is_integral_v<DestType> && !AZStd::is_same_v<DestType, bool>)
                 {
-                    if (AttributeRead<bool, DestType, Args...>(value, attr, instance, args ...))
+                    if (AttributeRead<bool, DestType, Args...>(value, attr, AZStd::forward<InstType>(instance), args...))
```
[the remark this answers is not in the document]
Comment (lumberyard-employee-dm) [reply Code/Framework/AzCore/AzCore/RTTI/AttributeReader.h:86]: Arguments should not be forwarded.
The parameters are `const&` here.

[the remark this answers is not in the document]
Comment (lumberyard-employee-dm) [reply Code/Framework/AzCore/AzCore/RTTI/AttributeReader.h:86]: You know what, I see don't a reason why the arugments here need to be a `const&` reference since only once of the Attribute functions calls will eventually be invoked.

[the remark this answers is not in the document]
Comment (lumberyard-employee-dm) [reply Code/Framework/AzCore/AzCore/RTTI/AttributeReader.h:86]: Actually I realize the problem now.
The `AttributeFunction` types have an specific signature.
i.e `AttributeFunction<int(void*, AZStd::string)>`

The problem is forwarding the arguments pass the reference type for the arguments to the AttributeRead function, where the cast would fail.
i.e `AttributeFunction<int(void*, AZStd::string&)>` can't cast an `AttributeFunction<int(void*, AZStd::string)>` with the **&** as they are two completely unrelated types
