### PR TITLE
MultiplayerConnectionViewportMessage Shouldn't Have a Public API

### LINKED ISSUE #10614: Multiplayer Connection Viewport Message SystemComponent Shouldn't Have Public Interface
**Describe the bug**
[MultiplayerConnectionViewportMessageSystemComponent.cpp](https://github.com/o3de/o3de/pull/10538/files/77d834407579a23e808e96e3fe01b46d6bb0c39e#diff-89fb7ed1f9d99d36dbf19fc07ca6f16b3779d7ba0d8705eca17a06aa1e7c97e7) currently uses a public interface to display information when the editor is connecting to the server. This public API gives a false sense that this class is to be used by anyone, when in reality it should be a closed off and instead display exactly what is required of it by receiving the necessary events from the editor.
Note: Once connected to the server, the connection status logic is all driven internally.

Tasks:
+ Remove [IMultiplayerConnectionViewportMessage.h](https://github.com/o3de/o3de/pull/10538/files/77d834407579a23e808e96e3fe01b46d6bb0c39e#diff-6fc762cbd31146f25fe8ce28e67d42b7b7af511ed95517fd0fcfd0dcee474780)
+ Instead update editor to send notifications during key events when connecting to a server. [Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp](https://github.com/o3de/o3de/pull/10538/files/77d834407579a23e808e96e3fe01b46d6bb0c39e#diff-89fb7ed1f9d99d36dbf19fc07ca6f16b3779d7ba0d8705eca17a06aa1e7c97e7) can then listen for these events.

### PR DESCRIPTION
**Pull request by AMZN-Gene**
## What does this PR do?
Clean up MP Connection Viewport Message system to not have a public interface as it was confusing users. This system is really for displaying specific events, so added a Notification Bus to the EditorServerBus which the ViewportMessageSystem can handle appropriately

Fixes #10614 

## How was this PR tested?
Opened up editor and entered playmode a few times to see everything working the same.

### CODE REVIEW

File: Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerEditorServerBus.h [hunk 1]
```diff
@@ -24,4 +24,38 @@ namespace Multiplayer
...
+        static const AZ::EBusAddressPolicy AddressPolicy = AZ::EBusAddressPolicy::Single;
+
+        //! Notification when the Editor has successfully opened the editor server.
+        virtual void OnServerLaunched() {}
+
+        //! Notification when the Editor has failed to open the editor server.
+        //! Might have failed for various reasons, this is a catch-all.
+        virtual void OnServerLaunchFail() {}
+        
+        //! Notification when the Editor attempts a tpc connection to the server.
```
Comment (AMZN-puvvadar) [inline Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerEditorServerBus.h:41]:
```suggestion
        //! Notification when the Editor attempts a tcp connection to the server.
```

Typo: tpc -> tcp

File: Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerEditorServerBus.h [hunk 2]
```diff
@@ -24,4 +24,38 @@ namespace Multiplayer
...
+        //! Note: It's possible multiple connection attempts are needed if the user starts and stops editor playmode a lot of times because the server port take a few seconds to be free.
```
Comment (AMZN-puvvadar) [inline Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerEditorServerBus.h:42]:
```suggestion
        //! Note: It's possible multiple connection attempts are needed if the user starts and stops editor play mode repeatedly because the server port takes a few seconds to free.
```

File: Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerEditorServerBus.h [hunk 3]
```diff
@@ -24,4 +24,38 @@ namespace Multiplayer
...
+        virtual void OnEditorSendingLevelData() {}
+
+        //! Notification when the Editor has sent all the level data successful and is now fully connected to the multiplayer simulation.
+        virtual void OnConnectToSimulationSuccess() {}
+
+        //! Notification when the Editor has sent all the level data successful but for some reason it fails to connect to normal multiplayer simulation.
+        //! @param serverPort The server port. This is useful information since user might be trying to connect to the wrong port.
+        virtual void OnConnectToSimulationFail([[maybe_unused]]uint16_t serverPort) {}
+
+        //! Notification when the Editor multiplayer playmode is over; therefore ending the multiplayer simulation.
```
Comment (AMZN-puvvadar) [inline Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerEditorServerBus.h:56]:
```suggestion
        //! Notification when the Editor multiplayer play mode is over; therefore ending the multiplayer simulation.
```

File: Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp [hunk 4]
```diff
@@ -45,11 +45,13 @@ namespace Multiplayer
     {
         AZ::RPI::ViewportContextNotificationBus::Handler::BusConnect(
             AZ::RPI::ViewportContextRequests::Get()->GetDefaultViewportContextName());
+        MultiplayerEditorServerNotificationBus::Handler::BusConnect();
     }
 
     void MultiplayerConnectionViewportMessageSystemComponent::Deactivate()
     {
         AZ::RPI::ViewportContextNotificationBus::Handler::BusDisconnect();
+        MultiplayerEditorServerNotificationBus::Handler::BusDisconnect();
```
Comment (AMZN-puvvadar) [inline Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp:54]: NP: We usually disconnect in reverse order from Connect to ensure any potential dependencies are honored. This probably isn't an issue here but it'd be good to maintain that order.

File: Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp [hunk 5]
```diff
@@ -328,9 +325,8 @@ namespace Multiplayer
             return;
         }
         
-        AZStd::string sending_leveldata_message = "Editor is sending the editor-server the level data packet.";
-        AZ::Interface<IMultiplayerConnectionViewportMessage>::Get()->DisplayCenterViewportMessage(("(3/3) " + sending_leveldata_message).c_str());
-        AZ_Printf("MultiplayerEditor", sending_leveldata_message.c_str())
+        MultiplayerEditorServerNotificationBus::Broadcast(&MultiplayerEditorServerNotificationBus::Events::OnEditorSendingLevelData);
+        AZ_Printf("MultiplayerEditor", "Editor is sending the editor-server the level data packet.")
```
Comment (AMZN-puvvadar) [inline Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp:329]: NP: Favor AZ_TracePrintf for the utility around disabling its output

File: Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp [hunk 6]
```diff
@@ -409,10 +405,8 @@ namespace Multiplayer
     {
         ++m_connectionAttempts;
 
-        char message[64];
-        azsnprintf(message, 64, "(2/3) Editor tcp connection attempt #%i.", m_connectionAttempts);
-        AZ::Interface<IMultiplayerConnectionViewportMessage>::Get()->DisplayCenterViewportMessage(message);
-        AZ_Printf("MultiplayerEditor", message)
+        MultiplayerEditorServerNotificationBus::Broadcast(&MultiplayerEditorServerNotificationBus::Events::OnEditorConnectionAttempt, m_connectionAttempts);
+        AZ_Printf("MultiplayerEditor", "Editor tcp connection attempt #%i.", m_connectionAttempts)
```
Comment (AMZN-puvvadar) [inline Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp:409]: NP: Same here

File: Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp [hunk 7]
```diff
@@ -183,4 +169,39 @@ namespace Multiplayer
...
+
+    void MultiplayerConnectionViewportMessageSystemComponent::OnEditorConnectionAttempt(uint16_t connectionAttempts)
+    {
+        m_centerViewportDebugText = AZStd::fixed_string<128>::format("(2/3) Editor tcp connection attempt #%i.", connectionAttempts);
+    }
+
+    void MultiplayerConnectionViewportMessageSystemComponent::OnConnectToSimulationFail(uint16_t serverPort)
+    {
+        m_centerViewportDebugText = AZStd::fixed_string<128>::format("EditorServerReady packet was received, but connecting to the editor-server's network simulation failed! Is the editor and server using the same sv_port (%i)?", serverPort);
+    }
```
[the remark this answers is not in the document]
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp:196]: It's nicer to read them directly in line though right? You thinking to reuse them where they are similar to the AZPrints debug log?

File: Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp (hunk 5 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp]: cool cool fixed!

File: Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp (hunk 6 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp]: fixed!

File: Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp (hunk 4 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp:53]: i like it! fixed :)

File: Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerEditorServerBus.h (hunk 3 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerEditorServerBus.h]: fixed! (both "playmode" instances)

File: Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerEditorServerBus.h (hunk 2 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerEditorServerBus.h]: fixed!

File: Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerEditorServerBus.h (hunk 1 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerEditorServerBus.h]: nice catch!

File: Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp]: Fixed!

File: Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp [hunk 8]
```diff
@@ -20,6 +20,13 @@ namespace Multiplayer
 {
     constexpr float defaultConnectionMessageFontSize = 0.7f;
     const AZ::Vector2 viewportConnectionBottomRightBorderPadding(-40.0f, -40.0f);
+    const char* centerViewportDebugTitle = "Multiplayer Editor";
+    const char* clientStatusTitle = "Multiplayer Client Status:";
+    const char* onServerLaunchedMessage = "(1/3) Launching server...";
+    const char* onServerLaunchFailMessage = "(1/3) Could not launch editor server.\nSee console for more info.";
+    const char* onEditorConnectionAttemptMessage = "(2/3) Editor tcp connection attempt #%i.";
+    const char* OnEditorSendingLevelDataMessage = "(3/3) Editor is sending the editor-server the level data packet.";
+    const char* onConnectToSimulationFailMessage = "EditorServerReady packet was received, but connecting to the editor-server's network simulation failed! Is the editor and server using the same sv_port (%i)?";
```
Comment (AMZN-puvvadar) [inline Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp:29]: You should either be doing constexpr char[] or constexpr AZStd::string_view here. I'm not actually sure how well string_view would play with AZStd::string::format though.

**Review by AMZN-Olex — APPROVED** [review]

File: Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp (hunk 8 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp]: roger! i see :D fixed!

**Review by AMZN-puvvadar — APPROVED** [review]

File: Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.h [hunk 9]
```diff
@@ -12,19 +12,27 @@
...
     //! System component that draws viewport messaging as the editor attempts connection to the editor-server while starting up game-mode.
     class MultiplayerConnectionViewportMessageSystemComponent final
         : public AZ::Component
-        , public AZ::Interface<IMultiplayerConnectionViewportMessage>::Registrar
         , public AZ::RPI::ViewportContextNotificationBus::Handler
+        , MultiplayerEditorServerNotificationBus::Handler
     {
     public:
-        AZ_COMPONENT(MultiplayerConnectionViewportMessageSystemComponent, "{7600cfcf-e380-4876-aa90-8120e57205e9}", IMultiplayerConnectionViewportMessage);
+        static constexpr char CENTER_VIEWPORT_DEBUG_TITLE[] = "Multiplayer Editor";
```
Comment (kberg-amzn) [inline Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.h:27]: The all upper-case thing is code convention for macros only I thought? #define SOMETHING_THATS_A_MACRO some_value

Comment (kberg-amzn) [reply Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.h:27]: I also wonder if we have any plans for a localizable string database for tooling like the editor..

Comment (AMZN-puvvadar) [reply Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.h:27]: Good point, I believe these should all be upper camel case.

Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.h]: Good call out! That's what I thought too, but a search for "constexpr char" inside of Gems/Multiplayer were all caps T.T
The other constexpr's are normal casing though, I bet that was just a mistake... I'll keep proper standards and stick with normal casing. Fixed!
