### PR TITLE
Make GetSurfacePoints output a SurfacePointList

### LINKED ISSUE #17528: GetSurfacePoints ScriptCanvas Node Does Not Return Data
**Describe the bug**
In the GetSurfacePoints node, the SurfacePointList should be an out reference, but the node doesn't actually return the list as expected and is expecting it as an input.

**Assets required**
No additional assets required. This bug can be reproduced on a minimal project with the ScriptCanvas Gem enabled.

**Expected behavior**
The node should return the SurfacePointList, not require it as input, and a subsequent node should be able to connect to GetSurfacePoints to receive that data.

**Actual behavior**
Subsequent nodes cannot receive the out data, because GetSurfacePoints does not return anything, and it expects SurfacePointList as an input.

**Screenshots/Video**
No out data:
image

Nothing to connect to subsequent nodes:
image

Validation fails, because it's expecting an input for SurfacePointsList:
image

**Found in Branch**
dev

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[f1c7eee](https://github.com/o3de/o3de/commit/f1c7eeedfeba9f68c95c385ed75ad1e6db5932a9)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11, build 22631
 - CPU Ryzen 7 2700X
 - GPU Radeon RX 6950 XT
 - Memory 64GB

**Additional Context**
This was brought up in a discussion in [the Discord server](https://discord.com/channels/805939474655346758/869974333009854464/1210001851076845588).

### PR DESCRIPTION
**Pull request by ShaunaGordon**
## What does this PR do?

This change wraps the GetSurfacePoints event handler in a lambda so that it returns a SurfacePointList as expected, making this node usable in ScriptCanvas.

Fixes #17528

**Before**
307125076-58151fcd-b3e9-46de-8619-49c690933ab9

**After**
image

## How was this PR tested?

Right now, nothing I've found can actually consume this function's output, so the best test I've found is to run the editor in a debugger, put the GetSurfacePoints node onto ScriptCanvas (see that the node has a return value now) and inspect the return value to ensure the SurfacePointList is populated and returned.

### CODE REVIEW

**Review by mbalfour-amzn — APPROVED** [review]

File: Gems/SurfaceData/Code/Source/SurfaceDataSystemComponent.cpp [hunk 1]
```diff
@@ -59,7 +59,14 @@ namespace SurfaceData
...
                 ->Attribute(AZ::Script::Attributes::Module, "surface_data")
-                ->Event("GetSurfacePoints", &SurfaceDataSystemRequestBus::Events::GetSurfacePoints)
+                ->Event(
+                    "GetSurfacePoints",
+                    [](SurfaceData::SurfaceDataSystem* handler, const AZ::Vector3& inPosition, const SurfaceTagVector& desiredTags) -> SurfaceData::SurfacePointList
+                    {
+                        SurfaceData::SurfacePointList result;
+                        handler->GetSurfacePoints(inPosition, desiredTags, result);
+                        return result;
+                    })
```
Comment (mbalfour-amzn) [inline Gems/SurfaceData/Code/Source/SurfaceDataSystemComponent.cpp:69]: Actually, thinking about this further, while this code is exactly correct for turning the list into an output, the SurfacePointList structure is going to be a difficult one to expose and work with from script.

As an alternative, you could change this to return a vector, and add some code after the GetSurfacePoints() call to call result.EnumeratePoints to add all the results to the vector. Since only one input position is passed in, you don't need to worry about which output points map to which input points. (This is a trickier problem when getting the surface points from a region)

The code would look _roughly_ like this, I think:
```
                    [](SurfaceData::SurfaceDataSystem* handler, const AZ::Vector3& inPosition, const SurfaceTagVector& desiredTags) -> AZStd::vector<SurfacePoint>
                    {
                        AZStd::vector<SurfacePoint> result; 
                        SurfaceData::SurfacePointList surfacePoints;
                        handler->GetSurfacePoints(inPosition, desiredTags, surfacePoints);
points.EnumeratePoints(
                [this, &result](
                    [[maybe_unused]] size_t inPositionIndex, const AZ::Vector3& position, const AZ::Vector3& normal,
                    const SurfaceData::SurfaceTagWeights& masks) -> bool
                {
                    result.emplace_back(position, normal, masks);
                    return true;
                });
                        return result;
                    })

```

**Review by mbalfour-amzn — APPROVED** [review]

**Review by gadams3 — APPROVED** [review]
