### PR TITLE
Adds Configure Gems Options to Project Dropdown + Misc. Project Manager Fixes

### LINKED ISSUE #2905: [Usability] Project Manager: Add "Configure Gems" as a project context menu option
**Describe the bug**
Add "Configure Gems" as a menu option in the project config drop-down menu, right after "Edit Project Settings...". It is the most common project configuration action I make, but I currently have to go through 2 clicks to get there: 

Edit Project Settings... -> Configure Gems button

suggestion

### PR DESCRIPTION
**Pull request by AMZN-nggieber**
Also makes projects settings scroll-able.
Fixes license eliding issues in gem inspector.

ICwpfI37Yk

OvzFQ1PwOZ

o3de_nBk0WUpONW

Closes #2905

### CODE REVIEW

File: Code/Tools/ProjectManager/Source/UpdateProjectCtrl.cpp [hunk 1]
```diff
@@ -94,6 +94,16 @@ namespace O3DE::ProjectManager
         return ProjectManagerScreen::UpdateProject;
     }
 
+    bool UpdateProjectCtrl::ContainsScreen(ProjectManagerScreen screen)
+    {
+        return screen == GetScreenEnum() || screen == ProjectManagerScreen::GemCatalog;
```
Comment (AMZN-alexpete) [inline Code/Tools/ProjectManager/Source/UpdateProjectCtrl.cpp:99]: should this also check GemRepos?

Comment (AMZN-nggieber) [reply Code/Tools/ProjectManager/Source/UpdateProjectCtrl.cpp:99]: Yea that's the point of leaving it out. We don't want to advertise jumping to it from any other screen here. I'll add a comment about that though.

**Review by AMZN-Phil — APPROVED** [review]

File: Code/Tools/ProjectManager/Source/UpdateProjectCtrl.cpp [hunk 2]
```diff
@@ -117,6 +128,16 @@ namespace O3DE::ProjectManager
             m_stack->setCurrentWidget(m_gemRepoScreen);
             Update();
         }
+        else if (screen == ProjectManagerScreen::GemCatalog)
+        {
+            m_stack->setCurrentWidget(m_gemCatalogScreen);
```
Comment (AMZN-alexpete) [inline Code/Tools/ProjectManager/Source/UpdateProjectCtrl.cpp:133]: huh, if QStackWidget has a signal for when the current widget changes we could just call Update every time that fires to avoid having to paste Update() all over.

**Review by AMZN-alexpete — APPROVED** [review]
Great fixes!
