### PR TITLE
Fix for tiny rendered viewport(s) when switching to/from different multiple viewports

### LINKED ISSUE #9725: Linux: When switching to multi-viewport or vice versa, the rendered display area in each viewport is tiny
**Describe the bug**
On Linux, when you switch to a different viewport layout, the rendered viewport is tiny and is not sized to the viewport window size. This can be corrected by adjusting the editor window size (forcing a resize signal)

**Steps to reproduce**
1. Go to 'View->Viewport->Configure Layout'
2. Select any viewport that is different than the current one
3. Observe the tiny rendered window when switched

**Expected behavior**
When switching to any new viewport configuration, each viewport window should reneder correctly and fit to the size of the viewport

**Actual behavior**
When switching to any new viewport configuration,

**Assets required**
N/A

**Screenshots/Video**

https://user-images.githubusercontent.com/82231385/169915993-a4336aa5-646e-479f-b885-b470c36b1a15.mp4

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux 
 - Version Ubuntu 20.04.3 LTS
 - CPU Threadripper
 - GPU RTX 3070]
 - Memory 64GB

**Additional context**
None

### PR DESCRIPTION
**Pull request by spham-amzn**
Fixes #9725 

**Root Cause**
When running the editor on Linux (with Vulkan), events to resize or showPlatform will trigger the swap chain to perform a resize. The showPlatform event will trigger a resize and create a new swapchain with the size, but when querying vulkan for the surface capabilities, Qt may not have updated its surface yet so it returns size of 100 x 30. A subsequent resize will correctly set the size because the surface that Qt presents is ready at this point. But it appears that the actual qt viewport widget did not invalidate so it was still showing the old swap chain, with the 100 x 30. 

**Fix**
The last few events on Linux after the viewport change is an 'UpdateLater' event. By using this event, this will invoke the resize event again, this time forcing an invalidate to occur and show the updated swap chain with the proper size

**Note**
There is a concern that this may incur a lot of unnecessary resize events, but it should be protected since the underlying resize logic will only trigger if the size actually changed, otherwise there will be no swapchain changes if there was actually no resize that occurred.

### CODE REVIEW

File: Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp [hunk 1]
```diff
@@ -222,12 +222,19 @@ namespace AtomToolsFramework
...
             case QEvent::Resize:
-            case QEvent::ShowToParent: //This event exists to capture the case where a resize event is missed "after" the underlying surface is modified by Qt (Seen during level load in Editor)
+
+            // This event exists to capture the case where a resize event is missed "after" the underlying surface is 
+            // modified by Qt (Seen during level load in Editor)
+            case QEvent::ShowToParent:  
+
+            // Qt is sending this event as the final events after a viewport change. This even needs to trigger a 
+            // resize at this point or else the swapchain won't be resized  to the correct viewport size(s) on vulkan.
+            case QEvent::UpdateLater:
```
Comment (spham-amzn) [inline Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp:232]: Debating whether or not to wrap this with an #if defined (AZ_PLATFORM_LINUX) or not.

Comment (GraphiteSIX) [reply Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp:232]: @spham-amzn Not sure if you saw my comment in  (#9107) because it was closed but the small viewport issue is on  windows Vulkan  so maybe test on that windows to see, otherwise it needs its own fix.

**Review by hultonha — APPROVED** [review]
Awesome find @spham-amzn! 👍

**Review by moudgils — APPROVED** [review]

File: Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp (hunk 1 above)
Comment (spham-amzn) [reply Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp:232]: @GraphiteSIX Verified that this fixes the issue on Windows as well. Its not just a Linux issue, its a vulkan specific issue
