### PR TITLE
Prevent annoying dialog upon opening material editor

### LINKED ISSUE #19612: Bug: Document could not be opened
**Describe the bug**
Open Material Canvas or Material Editor. The error should display as follows

Image

Occurring in two different machines. 50% chance it will break and block the editor, preventing you from working or crashing the system. Attempted to debug the problem, it started to reboot the system and logging me out, the crash of the system could be memory or graphics limitation on my potatoes hardware...

**Assets required**
Nothing specific. Just open the editors. Maybe it is the default asset or starting asset missing?

**Steps to reproduce**
1. Open Material Canvas or Material Editor
2. See the error displayed

**Expected behavior**
No error should display

**Found in**
Noticed it at Developer branch 77f842fcdfaae480941abf7d742c4ad30d24baf5 

**Desktop/Device (please complete the following information):**
Device: PC
OS: EOS
CPU AMD Ryzen 2700X
GPU NVidia 1060
Memory 32GB

**Additional context**
Guessing here... But this could be related to the impactful changes made to materials and shaders last year (around June), since some of my materials and prefabs created in early 2025 are also not working/displaying correctly.

### PR DESCRIPTION
**Pull request by guillaume-haerinck**
## What does this PR do?

Close https://github.com/o3de/o3de/issues/19612.
Not yet sure on what caused the regression (will have a quick look at the history), likely something in CommandLine::GetNumMiscValues(), but either way its still important to have this safe-guard.

## How was this PR tested?

Local windows build.
- Open material editor, opens as expected
- Double click on a material to open material editor, opens as expected with the material in edit
- Double click on a material from content browser with material editor opened, new tab opens

### CODE REVIEW

File: Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentApplication.cpp [hunk 1]
```diff
@@ -128,6 +128,8 @@ namespace AtomToolsFramework
         for (size_t openDocumentIndex = 0; openDocumentIndex < openDocumentCount; ++openDocumentIndex)
         {
             const AZStd::string openDocumentPath = commandLine.GetMiscValue(openDocumentIndex);
+            if (openDocumentPath.empty())
```
Comment (nick-l-o3de) [inline Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentApplication.cpp:131]: I hate to nitpick here but our style guide does require blocks, especially continue blocks, to be inside a `{ parentheses }` block

**Review by nick-l-o3de — APPROVED** [review]

**Review by nick-l-o3de — APPROVED** [review]
