### PR TITLE
Handled additional missing custom attributes

### LINKED ISSUE #16068: DPE Inspector: Asset fields missing open in editor button
**Describe the bug**
Any asset fields that register the optional "Open in XXX" editor button are missing.

This issue has been found in the following components:
Input component, PhysX Dynamic Rigid Body, Lua Script

**Steps to reproduce**

1. Launch the Editor with the DPE enabled:
`Editor.exe --ed_enableDPE=true`
2. Open a new or existing level.
3. Create a new entity.
4. Add a `Input ` component to the entity.

**Expected behavior**
Input field should have "Open in Asset Editor" button.

**Actual behavior**
Input field missing the "Open in Asset Editor" button.

### PR DESCRIPTION
**Pull request by cgalvan**
## What does this PR do?

Fixes #16068 and #16078 

In my previous PR (https://github.com/o3de/o3de/pull/16244), I fixed an issue with generic attributes that aren't explicitly registered not being passed on to handlers properly. At the time, this only supported primitive data types for the attributes (e.g. int, bool, string, etc...). This fix extends the support to also handle opaque values and callbacks.

Here are some example components where this crops up:

BEFORE (Material component is missing custom widget for the material preview thumbnail, which is passed as a custom attribute, and on the Script Canvas component the button to open a script in the Script Canvas Editor doesn't work)
Material_BEFORE
ScriptCanvasOpenAsset_BEFORE

AFTER:
MaterialAndSCOpen_AFTER

## How was this PR tested?

Tested the repro of the mentioned issues, as well as ad-hoc testing (e.g. tested other components with "Open in ... Editor" buttons for assets).

### CODE REVIEW

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h [hunk 1]
```diff
@@ -286,6 +286,38 @@ namespace AzToolsFramework
...
+                        if (!marshalledAttribute)
+                        {
+                            if (attributeIt->second.IsOpaqueValue() && attributeIt->second.GetOpaqueValue().is<AZ::Attribute*>())
+                            {
+                                AZ::Attribute* attribute = AZStd::any_cast<AZ::Attribute*>(attributeIt->second.GetOpaqueValue());
+                                marshalledAttribute = AZStd::shared_ptr<AZ::Attribute>(
+                                    attribute,
+                                    [](AZ::Attribute*)
+                                    {
+                                    });
```
Comment (dtamkin1) [inline Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h:303]: Just out of curiosity, what are the two empty lambda functions used for?

**Review by dtamkin1 — APPROVED** [review]

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h [hunk 2]
```diff
@@ -286,6 +286,38 @@ namespace AzToolsFramework
...
+                            {
+                                auto typeField = attributeIt->second.FindMember(AZ::Attribute::GetTypeField());
+                                if (typeField != attributeIt->second.MemberEnd() && typeField->second.IsString() &&
+                                    typeField->second.GetString() == AZ::Attribute::GetTypeName())
+                                {
+                                    AZ::Attribute* attribute =
+                                        AZ::Dom::Utils::ValueToTypeUnsafe<AZ::Attribute*>(attributeIt->second[AZ::Attribute::GetAttributeField()]);
+                                    marshalledAttribute = AZStd::shared_ptr<AZ::Attribute>(
+                                        attribute,
+                                        [](AZ::Attribute*)
```
Comment (alexmontAmazon) [inline Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h:315]: nit: maybe just make one empty lambda here and pass it to both spots

**Review by alexmontAmazon — APPROVED** [review]

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h (hunk 1 above)
Comment (cgalvan) [reply Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h:303]: This is for the delete context so that it will be a noop, since the attribute deletion will be handled separately.
