### PR TITLE
DPE | Layout classes rewrite to fix refresh issues with containers.

### LINKED ISSUE #17275: Custom gem and component: Deleting the last member of a vector makes the field unusable
**Describe the bug**
Custom made component.  Made a AZStd::vector<AZ::EntityId> m_exampleOfEntities; as the component input field. 

**Steps to reproduce**
1. Create a new gem and component. Followed the instructions from o3de.org: https://docs.o3de.org/docs/user-guide/programming/components/create-component/
3. header (component.h) add
 AZStd::vector<AZ::EntityId> m_exampleOfEntities;
4. source (component.cpp) add a field in the component 
->Field("Example of multiple entities IDs", &Custom088Component::m_exampleOfEntities)
6. source (component.cpp) add a field in the editcontext 
->Attribute("ChangeNotify", AZ_CRC("RefreshValues", 0x28e720d4))
->DataElement(AZ::Edit::UIHandlers::Default, &Custom088Component::m_exampleOfEntities, "Example of entities list", "")
7. Cmake, build the project, run the project.
8. Add the custom component to an entity.
9. Add an entity to the list/vector
10. Delete all members from that list/vector
11. Issue: The field is now unusable. User must remove the component and add it again.

**Expected behavior**
Deleting all members of the list/vector should return the field to its original state. Allowing the addition of new members to the list/vector.

**Actual behavior**
The field is unusable and the component must be removed and added again to return to the original state.

**Screenshots/Video of the code**
cppComponent088test1

**Screenshots/Video of the component in runtime**
cppComponent088test2

**Found in Branch**
point-release/23101 and developer

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/4d025be7592121801aabbb6a0afaac20100a2ab2

**Desktop/Device:**
 - Device: [e.g. PC]
- OS: [e.g. Windows]
- Version [e.g. 11]
- CPU [e.g. AMD Ryzen 2700X ]
- GPU [ NVidia 1060]
- Memory [e.g. 32GB]

**Additional context**
It is a quality-of-life bug-fix. Nothing prevents the users from continuing their workflow

### PR DESCRIPTION
**Pull request by AMZN-daimini**
Fixes #17275

Rewrites the DPE Layout class to be more straightforward, since the missing refreshes were due to edge cases tied to overly complex logic.
Verified that the new code fixes issues like buttons and labels disappearing when clearing containers.
Some container bugs are still present, but they were verified to be unrelated to this change and will be addressed separately.

dpeClearAllFix

### CODE REVIEW

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/ContainerActionButtonHandler.cpp [hunk 1]
```diff
@@ -18,43 +18,72 @@ namespace AzToolsFramework
...
+
         switch (m_action)
         {
         case ContainerAction::AddElement:
-            setIcon(s_iconAdd);
-            setToolTip("Add new child element");
-            break;
+            {
+                setIcon(s_iconAdd);
+                setToolTip("Add new child element");
```
Comment (spham-amzn) [inline Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/ContainerActionButtonHandler.cpp:46]: Should do a _tr here too
```suggestion
                setToolTip(tr("Add new child element"));
```

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h [hunk 2]
```diff
@@ -77,11 +76,20 @@ namespace AzToolsFramework
...
-        AZStd::vector<AZStd::vector<size_t>> m_sharePriorColumn;
+        // Contains the indices of all widgets that start a new column.
+        AZStd::unordered_set<size_t> m_columnStarts;
 
     private:
+        void CloseColumn(
+            QHBoxLayout* currentColumnLayout,
+            QRect& itemGeometry,
+            int& currentColumnCount,
+            const int columnWidth,
```
Comment (spham-amzn) [inline Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h:87]: nit: Don't really need a `const` here, unless you really want to prevent this function from modifying the parameter value inside of the function,

**Review by spham-amzn — APPROVED** [review]
Minor comments

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp [hunk 3]
```diff
@@ -196,177 +196,205 @@ namespace AzToolsFramework
...
+                        currentColumnCount,
+                        columnWidth,
+                        (currentColumnNonStretchedWidgetsCount == currentColumnWidgetsCount),
+                        startSpacer,
+                        endSpacer
+                    );
+                }
+
+                // Create new column.
+                currentColumnLayout = new QHBoxLayout;
```
Comment (alexmontAmazon) [inline Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp:360]: in the long run, we don't want any sub-layouts in this class. This is a layout, it should be able to do all its child placement itself.

**Review by alexmontAmazon — APPROVED** [review]
definitely an improvement, thank you! As noted, eventually this class shouldn't need to hold any layouts, as it can do its child placement itself without the extra overhead.

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h (hunk 2 above)
Comment (AMZN-daimini) [reply Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h:87]: I'm gonna touch this function in the next PR, I'll fix it then.
