### PR TITLE
Multiplayer Client-Server Fix

### LINKED ISSUE #9622: Multiplayer Connection Wont Work Unless Server Already Has Level Loaded
**Describe the bug**
Multiplayer wont properly replicate to the client if the server isn't already inside a level when the player joins. This is confusing since you'd expect servers to be able to switch levels

**Steps to reproduce**
1. Open ServerLauncher and run > host
2. Open GameLauncher and run > connect
3. ServerLauncher > loadlevel SampleBase

**Only a very specific order of commands will work:**
Server > host > loadlevel
Game > connect

**Expected behavior**
A player spawns into client and server and client is able to control the player in the new level

**Actual behavior**
After loading into the level no player is spawned. Network entities (include level entities and player) dont spawn in for the client
ServerLauncher warning occurs "No active NetworkPlayerSpawnerComponents were found on player spawn request."

**Found in Branch**
Development latest (May 19, 2022)

**Desktop/Device (please complete the following information):**
 - OS: Ubuntu

### LINKED ISSUE #10824: [Network] Hosting in a Game Launcher is broken
**Describe the bug**
Game Launcher is not able to act as a network host when using `host` command.

**Steps to reproduce**
1. Create a multiplayer project or use o3de-multiplayersample
2. Launch AP
3. Launch game launcher
4. In a game launcher, bring up imgui console and enter `host` command
5. Then load a level, for example `loadlevel samplebase` if you using o3de-multiplayersample

**Expected behavior**
Game launcher acts as a network host and able to host a level.

**Actual behavior**
Host command fails.
Loading a level afterwards results in a broken level.

**Screenshots/Video**
image

**Found in Branch**
o3de-multiplayersample development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows

### PR DESCRIPTION
**Pull request by AMZN-Gene**
Fix for multiplayer client-server and a fix for players connecting before host has started a level.
Stores user information in case a net player spawner isn't ready when a player connets, and tries spawning again once a level has loaded, and thus network player spawners have activated.

Signed-off-by: Gene Walters <genewalt@amazon.com>

Coincides with a MultiplayerSample game update https://github.com/o3de/o3de-multiplayersample/pull/176

Resolves #9622 
Resolves #10824 

_Here's a video of server calling host and then a client connecting before the host calls loadlevel. The host waits 10 seconds before calling loadlevel, at which point he then loads the level and you see the player is spawned in._
https://user-images.githubusercontent.com/32776221/181814224-a5228c05-77df-47b3-b429-efd87f6bdf0a.mp4

## How was this PR tested?
Opened GameLauncher and called HOST command and ensured an autonomous player appeared.

Unit Test Coverage of Multiplayer increased by 2%
Unit Test Coverage of MultiplayerSystemComponent specifically increased by 10%
**Before**
image
**After**
image

_Test Coverage Percentage generated using [OpenCppCoverage](https://github.com/OpenCppCoverage/OpenCppCoverage/releases/tag/release-0.9.9.0)_
> OpenCppCoverage.exe --export_type html:MultiplayerTestReport --modules *Multiplayer* --sources Multiplayer --excluded_sources Tests -- D:/prj/MultiplayerSample/build/windows/bin/profile/AzTestRunner.exe D:/prj/MultiplayerSample/build/windows/bin/profile/Multiplayer.Tests.dll AzRunUnitTests

### CODE REVIEW

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp [hunk 1]
```diff
@@ -29,20 +29,18 @@
...
 #include <AzFramework/Visibility/IVisibilitySystem.h>
-#include <AzFramework/Visibility/EntityBoundsUnionBus.h>
 
 #include <AzNetworking/Framework/INetworking.h>
 #include <AzFramework/Process/ProcessWatcher.h>
 
 #include <cmath>
 #include <AzCore/Debug/Profiler.h>
 
+#pragma optimize("",off)
```
Comment (AMZN-Olex) [inline Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp:43]: Cleanup

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp [hunk 2]
```diff
@@ -1384,4 +1416,5 @@ namespace Multiplayer
         AZ::Interface<IMultiplayer>::Get()->Terminate(DisconnectReason::TerminatedByUser);
     }
     AZ_CONSOLEFREEFUNC(disconnect, AZ::ConsoleFunctorFlags::DontReplicate, "Disconnects any open multiplayer connections");
-}
+} // namespace Multiplayer
+#pragma optimize("", on)
```
Comment (AMZN-Olex) [inline Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp:1420]: Cleanup

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h [hunk 3]
```diff
@@ -140,13 +139,19 @@ namespace Multiplayer
         void DumpStats(const AZ::ConsoleCommandContainer& arguments);
         //! @}
 
+        //! AzFramework::RootSpawnableNotificationBus::Handler
+        //! @{
+        void OnRootSpawnableReady([[maybe_unused]] AZ::Data::Asset<AzFramework::Spawnable> rootSpawnable, [[maybe_unused]] uint32_t generation) override;
```
Comment (AMZN-Olex) [inline Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h:144]: You don't need maybe_unused in the declaration.

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp [hunk 4]
```diff
@@ -1294,6 +1298,34 @@ namespace Multiplayer
...
+    {
+        SpawnPlayersWaitingToBeSpawned();
+    }
+
+    void MultiplayerSystemComponent::SpawnPlayersWaitingToBeSpawned()
+    {
+        IMultiplayerSpawner* spawner = AZ::Interface<IMultiplayerSpawner>::Get();
+        if (!spawner)
+        {
+            AZLOG_ERROR("Attempting to spawn players on level load failed. No IMultiplayerSpawner found. Ensure one is registered.");
```
Comment (AMZN-Olex) [inline Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp:1311]: Is this from lack of the right components on the level, or from a lack of some Multiplayer gem interfaces?

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp [hunk 5]
```diff
@@ -1294,6 +1298,34 @@ namespace Multiplayer
...
+            return;
+        }
+
+        for (const auto& [id, datum] : m_playersWaitingToBeSpawned)
+        {
+            NetworkEntityHandle controlledEntity = spawner->OnPlayerJoin(id, datum);
+
+            // If there wasn't any spawner available, wait until a level loads and check again
```
Comment (AMZN-Olex) [inline Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp:1319]: Aren't we already at this point past the level load?

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp (hunk 4 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp:1297]: This is from the lack of the right component. NetworkPlayerSpawner components will register themselves on activate. Since the ServerClient calls host before calling load-level, there aren't any NetworkPlayerSpawner components active yet :)

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp (hunk 5 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp]: Thanks, fixed!

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h (hunk 3 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h]: thank you, fixed!

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp (hunk 2 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp]: thanks, done!

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp (hunk 1 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp]: boom, fixed

File: Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayerSpawner.h [hunk 6]
```diff
@@ -41,11 +41,14 @@ namespace Multiplayer
 
         virtual ~IMultiplayerSpawner() = default;
 
+        //! Callback to inject logic after the network player entity is created, but before the it's components are activated
```
Comment (AMZN-Olex) [inline Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayerSpawner.h:44]: its* components

**Comment by AMZN-Olex** [comment]
Is this unittest-able?

File: Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayerSpawner.h (hunk 6 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayerSpawner.h]: thank you! fixed :)

**Comment by AMZN-Gene** [comment]
> Is this unittest-able?

Open to suggestions! Lots of situations to test, like...
Starting ClientServer. Connecting to DedicatedServer before level is loaded. Connecting and then disconnecting to server before the player has a chance to spawn.

Could I stand up the real MultiplayerSystem component, and then create a mock spawner than doesn't return any entities in order to make sure the real MultiplayerSystem component handles all that properly? Or would that not be a unit test and instead make an integration test?

**Comment by AMZN-Gene** [comment]
> Is this unittest-able?
Thanks!
Unit tests added for client server starting when there is and isn't a spawner available

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp [hunk 7]
```diff
@@ -599,28 +597,26 @@ namespace Multiplayer
...
+
+                controlledEntity = spawner->OnPlayerJoin(packet.GetTemporaryUserId(), datum, preActivationCallback);
+                if (controlledEntity.Exists())
+                {
+                    StartServerToClientReplication(packet.GetTemporaryUserId(), controlledEntity, connection);
+                }
+                else
+                {
+                    // If there wasn't any spawner available, wait until a level loads and check again
+                    m_playersWaitingToBeSpawned.push_back(PlayerWaitingToBeSpawned{ packet.GetTemporaryUserId(), datum, connection });
```
Comment (AMZN-Olex) [inline Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp:613]: Tip: you can do use emplace_back and temporary skip object creation in such cases.

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp [hunk 8]
```diff
@@ -888,17 +884,33 @@ namespace Multiplayer
...
-                    if (replicationWindow)
+                    // Check if this disconnected player was waiting to be spawned, and therefore, doesn't have a controlled player entity yet.
+                    bool playerSpawned = true;
+                    for (auto it = m_playersWaitingToBeSpawned.begin(); it != m_playersWaitingToBeSpawned.end(); ++it)
                     {
-                        const ReplicationSet& replicationSet = replicationWindow->GetReplicationSet();
-                        spawner->OnPlayerLeave(connectionData->GetPrimaryPlayerEntity(), replicationSet, reason);
+                        if (it->connection && it->connection->GetConnectionId() == connection->GetConnectionId())
+                        {
+                            m_playersWaitingToBeSpawned.erase(it--);
```
Comment (AMZN-Olex) [inline Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp:893]: That is technically an undefined behavior.
https://en.cppreference.com/w/cpp/container/vector/erase
```
Invalidates iterators and references at or after the point of the erase, including the end() iterator.


Return value
Iterator following the last removed element.

If pos refers to the last element, then the [end()](https://en.cppreference.com/w/cpp/container/vector/end) iterator is returned.

If last==end() prior to removal, then the updated [end()](https://en.cppreference.com/w/cpp/container/vector/end) iterator is returned.

If [first, last) is an empty range, then last is returned.
```

So the right pattern to use here is:
```
it = m_playersWaitingToBeSpawned.erase(it);
```

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp [hunk 9]
```diff
@@ -1260,38 +1278,75 @@ namespace Multiplayer
...
-        if (!entityHandle.Exists())
+        if (entityList.empty())
         {
             AZLOG_WARN("Attempting to enable autonomous control for an invalid entity");
             return;
         }
 
-        entityHandle.GetNetBindComponent()->SetOwningConnectionId(connectionId);
-        if (connectionId == InvalidConnectionId)
+        for (NetworkEntityHandle subEntity : entityList)
```
Comment (AMZN-Olex) [inline Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp:1289]: const ref&

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp [hunk 10]
```diff
@@ -1260,38 +1278,75 @@ namespace Multiplayer
...
-                    subEntityNetBindComponent->SetOwningConnectionId(connectionId);
-                    if (connectionId == InvalidConnectionId)
-                    {
-                        subEntityNetBindComponent->SetAllowAutonomy(true);
-                    }
-                }
+            NetworkEntityHandle controlledEntity = spawner->OnPlayerJoin(playerWaitingToBeSpawned.userId, playerWaitingToBeSpawned.agent, preActivationCallback);
+            if (!controlledEntity.Exists())
+            {
+                AZLOG_WARN("Attempting to spawn players on level load failed.");
```
Comment (AMZN-Olex) [inline Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp:1324]: I would consider printing additional details here, such as `userId`.

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp [hunk 11]
```diff
@@ -1260,38 +1278,75 @@ namespace Multiplayer
...
         }
+
+        m_playersWaitingToBeSpawned.clear();
+    }
+
+    void MultiplayerSystemComponent::StartServerToClientReplication(uint64_t userId, NetworkEntityHandle controlledEntity, IConnection* connection)
+    {
+        ServerToClientConnectionData* connectionData = reinterpret_cast<ServerToClientConnectionData*>(connection->GetUserData());
+        AZStd::unique_ptr<IReplicationWindow> window = AZStd::make_unique<ServerToClientReplicationWindow>(controlledEntity, connection);
+        connectionData->GetReplicationManager().SetReplicationWindow(AZStd::move(window));
```
Comment (AMZN-Olex) [inline Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp:1342]: null check?

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp [hunk 12]
```diff
@@ -982,24 +996,28 @@ namespace Multiplayer
...
-            IMultiplayerSpawner* spawner = AZ::Interface<IMultiplayerSpawner>::Get();
-            NetworkEntityHandle controlledEntity;
-            if (spawner)
+            if (IMultiplayerSpawner* spawner = AZ::Interface<IMultiplayerSpawner>::Get())
             {
                 // Route to spawner implementation
                 MultiplayerAgentDatum datum;
                 datum.m_agentType = MultiplayerAgentType::ClientServer;
-                controlledEntity = spawner->OnPlayerJoin(0, datum);
+                const int userId = 0;
```
Comment (AMZN-puvvadar) [inline Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp:1004]: NP: uint64_t

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp [hunk 13]
```diff
@@ -1260,38 +1278,75 @@ namespace Multiplayer
...
-        entityHandle.GetNetBindComponent()->SetOwningConnectionId(connectionId);
-        if (connectionId == InvalidConnectionId)
+        for (NetworkEntityHandle subEntity : entityList)
         {
-            entityHandle.GetNetBindComponent()->SetAllowAutonomy(true);
+            if (NetBindComponent* netbindComponent = subEntity.GetNetBindComponent())
+            {
+                netbindComponent->SetOwningConnectionId(connectionId);
+
+                if (connectionId == InvalidConnectionId)
```
Comment (AMZN-puvvadar) [inline Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp:1295]: Can you add a comment explaining what's happening here? In a vacuum, Setting AllowAutonomy to true when the connection ID is invalid may seem odd to readers

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp (hunk 10 above)
Comment (AMZN-puvvadar) [reply Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp:1324]: I'd also indicate that it's a Multiplayer level to disambiguate from other spawning logs.

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp (hunk 9 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp]: updated, the logic to enable autonomous was moved to happen before entity activation in the helper function NetworkEntityManager::CreateAutomonousPlayer

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp (hunk 10 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp]: good idea, fixed!

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp (hunk 12 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp]: thanks, fixed!

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp (hunk 13 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp]: Good call! Added (now comment lives in NetworkEntityManager where autonomy is granted.

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp (hunk 8 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp]: thank you! fixed!

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp (hunk 7 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp]: thank you!

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h [hunk 14]
```diff
@@ -192,9 +191,14 @@ namespace Multiplayer
...
-            MultiplayerAgentDatum agent;
-            AzNetworking::IConnection* connection;
+            PlayerWaitingToBeSpawned(uint64_t userId, MultiplayerAgentDatum agent, AzNetworking::IConnection* connection)
+                : m_userId(userId), m_agent(agent), m_connection(connection)
+            {
+            }
+
+            uint64_t m_userId;
+            MultiplayerAgentDatum m_agent;
+            AzNetworking::IConnection* m_connection;
```
Comment (AMZN-puvvadar) [inline Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h:201]: NP: Default to nullptr

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp [hunk 15]
```diff
@@ -982,24 +1001,34 @@ namespace Multiplayer
...
-            NetworkEntityHandle controlledEntity;
-            if (spawner)
+            if (IMultiplayerSpawner* spawner = AZ::Interface<IMultiplayerSpawner>::Get())
             {
                 // Route to spawner implementation
                 MultiplayerAgentDatum datum;
                 datum.m_agentType = MultiplayerAgentType::ClientServer;
-                controlledEntity = spawner->OnPlayerJoin(0, datum);
+                datum.m_id = InvalidConnectionId;
+                constexpr uint64_t userId = 0;
```
Comment (AMZN-puvvadar) [inline Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp:1010]: constexpr seems like overkill here. I would just go with const.

Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp]: fixed!

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h (hunk 14 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h]: good call, thank you. fixed!

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp (hunk 11 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp]: thanks, fixed!

**Review by AMZN-Olex — APPROVED** [review]

**Review by kberg-amzn — APPROVED** [review]
This looks like it was caused by an ordering change of some kind? Previously we raised that allow autonomous flag prior to activating the host player entity I believe, which is why all the logic surrounding it was so simple by comparison. It's no longer possible for us to handle the host player in this manner after the prefab changes? We have to spawn the player first, and then deactivate/reactivate later with autonomous functionality enabled?

The change looks good if ordering is now mandatory. Otherwise the large amount of logic needed to handle the more asynchronous flows are certain to cause a lot more issues long-term.

**Comment by AMZN-Gene** [comment]
> This looks like it was caused by an ordering change of some kind? Previously we raised that allow autonomous flag prior to activating the host player entity I believe, which is why all the logic surrounding it was so simple by comparison. It's no longer possible for us to handle the host player in this manner after the prefab changes? We have to spawn the player first, and then deactivate/reactivate later with autonomous functionality enabled?
> 
> The change looks good if ordering is now mandatory. Otherwise the large amount of logic needed to handle the more asynchronous flows are certain to cause a lot more issues long-term.

Game developers pass the player entity back to Multiplayer. It is definitely possible to put the burden on users to enable autonomous before activation. Both Network::CreateEntityImmediate and SpawnableInterface allow users to inject logic before activation happens. Would it be better to just error if the flag is set after activation? Users would then be responsible and the error could guide them on what to do.

**Comment by kberg-amzn** [comment]
> Seeing as developers might also do special checks for IsAutonomous inside of Component::OnActivate() as opposed to just ComponentController::OnActivate(), placing the burden on devs might be the way to go (it's only possible to activate/deactivate controllers, not multiplayer components). Also recall, this will only burden devs that use ClientServer (granted this will likely become everyone once editor is updated to support client-server for fast start up)

Hrm, that's a difficult call. I definitely like the 'detect current conditions and react appropriately' as ordering is something customers may decide to play around with, and it's nice if things 'just work'. I'm mostly concerned about the fragility of having lots of code moving forward. Multiplayer is one of those things that's so complicated that keeping the lower foundational layers super lean and mean usually pays off disproportionately over the long run.

**Comment by AMZN-Gene** [comment]
> > Seeing as developers might also do special checks for IsAutonomous inside of Component::OnActivate() as opposed to just ComponentController::OnActivate(), placing the burden on devs might be the way to go (it's only possible to activate/deactivate controllers, not multiplayer components). Also recall, this will only burden devs that use ClientServer (granted this will likely become everyone once editor is updated to support client-server for fast start up)
> 
> Hrm, that's a difficult call. I definitely like the 'detect current conditions and react appropriately' as ordering is something customers may decide to play around with, and it's nice if things 'just work'. I'm mostly concerned about the fragility of having lots of code moving forward. Multiplayer is one of those things that's so complicated that keeping the lower foundational layers super lean and mean usually pays off disproportionately over the long run.

Also, requiring users to enable autonomy would also rule out players simply just being some entities that exist in the level because there's no way to stop entities from activating. Editor used to have "Dont Activate on Level Start", not sure where that went, ha.

**Comment by kberg-amzn** [comment]
> Also, requiring users to enable autonomy before activation would also rule out players simply just being some entities that exist in the level because there's no way to stop entities from activating. Editor used to have "Dont Activate on Level Start", not sure where that went, ha.

Yeah, good point.. I've approved your changes, they're probably the best trade-off of flexibility and complexity. :thumbsup:
