### PR TITLE
Thumbnail view context menu and hotkeys

### LINKED ISSUE #14392: Asset Browser: Selecting an asset in Thumbnail view and using the Delete hotkey deletes the entire directory
**Describe the bug**
Selecting an asset in Thumbnail view and using the Delete hotkey deletes the entire directory.

**Steps to reproduce**
1. Launch the Editor and enable WIP Asset Browser features via the Console:
```
ed_useWIPAssetBrowserDesign true
```
2. Open the Asset Browser, and switch to Thumbnail View if necessary.
3. Navigate to any folder, and select any asset in the Thumbnail View pane.
4. Press the Delete hotkey.

**Expected behavior**
Selected asset is deleted.

**Actual behavior**
The entire current directory is deleted

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
c8d69fb61c196601651391f4e22d1408971052d8

### LINKED ISSUE #14396: Asset Browser: Duplicate/Rename hotkey shortcuts do not function in Thumbnail View
**Describe the bug**
Duplicate/Rename hotkey shortcuts do not function in Thumbnail View

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
1. Launch the Editor and enable WIP Asset Browser features via the Console:
```
ed_useWIPAssetBrowserDesign true
```
2. Open the Asset Browser, and switch to Thumbnail View if necessary.
3. Select any asset in the Thumbnail View pane.
4. CTRL-D to Duplicate the asset.
5. Press F2 to Rename the asset.

**Expected behavior**
Asset can be duplicated/renamed via hotkey.

**Actual behavior**
Nothing happens.

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
c8d69fb61c196601651391f4e22d1408971052d8

### LINKED ISSUE #14397: Asset Browser: Context menu does not function on assets in Thumbnail View
**Describe the bug**
Context menu does not function on assets in Thumbnail View

**Steps to reproduce**
1. Launch the Editor and enable WIP Asset Browser features via the Console:
```
ed_useWIPAssetBrowserDesign true
```
2. Open the Asset Browser, and switch to Thumbnail View if necessary.
3. Select any asset in Thumbnail View pane.
4. Right-click the asset.

**Expected behavior**
Context menu opens, allowing users to perform several actions.

**Actual behavior**
No context menu opens.

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
c8d69fb61c196601651391f4e22d1408971052d8

### PR DESCRIPTION
**Pull request by dtamkin1**
## What does this PR do?

- Implement duplicate, delete, move, and rename actions in the thumbnail view
- Implement hotkey shortcuts for the above actions
- Implement right click context menu for assets and the empty view space
- Fix the view updating when new assets are added or removed
- Changes all uses of `AZStd::vector<AzToolsFramework::AssetBrowser::AssetBrowserEntry*>& entries)` to `AZStd::vector<const AzToolsFramework::AssetBrowser::AssetBrowserEntry*>& entries)`

Fixes #14396
Fixes #14392 
Fixes #14397
Fixes the remaining work in #14394

x9CydWR5E6

## How was this PR tested?

Locally by using the new actions in the thumbnail view

### CODE REVIEW

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp [hunk 1]
```diff
@@ -71,6 +76,82 @@ namespace AzToolsFramework
...
+              duplicateAction->setShortcutContext(Qt::WidgetWithChildrenShortcut);
+              connect(
+                  duplicateAction,
+                  &QAction::triggered,
+                  this,
+                  [this]()
+                  {
+                      DuplicateEntries();
+                  });
+              addAction(duplicateAction);
```
Comment (cgalvan) [inline Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp:153]: Would be nice to register these actions using the new action manager, but I understand this is copied from the other views so this could be done in a follow-up PR.

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp [hunk 2]
```diff
@@ -71,6 +76,82 @@ namespace AzToolsFramework
...
+
+              if (AzToolsFramework::IsNewActionManagerEnabled())
+              {
+                  if (auto hotKeyManagerInterface = AZ::Interface<AzToolsFramework::HotKeyManagerInterface>::Get())
+                  {
+                      // Assign this widget to the Editor Asset Browser Action Context.
+                      hotKeyManagerInterface->AssignWidgetToActionContext(
+                          EditorIdentifiers::EditorAssetBrowserActionContextIdentifier, this);
+                  }
+              }
```
Comment (cgalvan) [inline Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp:114]: This is already being done in the tree view, so we shouldn't register again in the thumbnail view. Ideally, this would be refactored to move the shortcuts all to the top level asset browser widget instead of the individual views and be registered with the new action manager, but that can be done in a future pass.

**Review by cgalvan — APPROVED** [review]

**Review by sphrose — APPROVED** [review]

**Comment by jckand-amzn** [comment]
Looks good. All linked bugs were resolved via this change.
