### PR TITLE
Added automatic bounding box expansion, fixed several bugs in the aabb calculations and removed node OBBs

### LINKED ISSUE #2523: EMotion FX: Static bounding volume not correct and mesh-based one not moving
* Static bounding volume does not fit the character's bind pose correctly.
* Mesh-based bounding volume does not move at all when the character is animating.
* When static bounding volume is shown, the dynamic options like "Update frequency" should not be shown.

1. Add new entity
2. Add actor component and load any actor
3. Enable "Draw bounds"
4. Add simple motion component and select any motion
5. Enable "Preview in Editor" and "Loop motion"
6. Change "Bounds type" in actor component to "Mesh vertex based"

**Expected behavior**
Static bounding volume after step 3 should fit the character's bind pose.
Mesh based bounds should animate along with the character.

### PR DESCRIPTION
**Pull request by amzn-jillich**
* Static bounding box was not correct. The static bounding box was calculated before the model asset was available and thus was incorrect.
* Hiding/showing attributes depending on bounding box should be automatically updated.
image
* Added new percentage based box expansion. This can be used to add a tolerance area to the calculated bounding box to avoid clipping the character too early.
image
* Fixed bug with mesh-based aabbs (it was never updating, even when auto update was enabled)
* Removed collision mesh aabb color from render option
* Converted the EMFX Mesh to use AZ::Aabb instead of MCore::AABB
* Ported RenderPlugin from MCore::AABB to AZ::Aabb
* Ported the render plugin, render update callback and render widget to use AZ::Aabb
* Removed OBBs from Actor including the node infos
* Removed OBB rendering helpers and color options
* Removed MCore::OBB.h/.inl/.cpp files
* Saving node chunk v2 (without OBB information) and adapting the chunk processor and importer to it
* Add bounding volume expansion to the actor instance
* Increased version in the actor group exporter to automatically reprocess all actors

image

Closes #2523

### CODE REVIEW

File: Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp [hunk 1]
```diff
@@ -62,39 +62,40 @@ namespace EMotionFX
...
-                        ->EnumAttribute(ActorInstance::BOUNDS_STATIC_BASED, "Static bounds (source-asset bounds)")
-                        ->EnumAttribute(ActorInstance::BOUNDS_NODE_BASED, "Bone position-based")
-                        ->EnumAttribute(ActorInstance::BOUNDS_NODEOBB_BASED, "Bone local bounding box-based")
-                        ->EnumAttribute(ActorInstance::BOUNDS_MESH_BASED, "Render mesh vertex position-based (VERY EXPENSIVE)")
-
-                        ->DataElement(0, &ActorComponent::BoundingBoxConfiguration::m_autoUpdateBounds,
+                                      "The method used to compute the Actor bounding box. NOTE: ordered by least expensive to compute to most expensive to compute.")
+                            ->EnumAttribute(ActorInstance::BOUNDS_STATIC_BASED, "Static (Recommended)")
+                            ->EnumAttribute(ActorInstance::BOUNDS_NODE_BASED, "Bone position-based")
+                            ->EnumAttribute(ActorInstance::BOUNDS_MESH_BASED, "Mesh vertex-based (Expensive)")
```
Comment (yuriy0) [inline Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp:70]: As we know, mesh-based bbox calculation is expensive and the typical user should be *very* wary of using this option. 

In some extremely rare edge cases, this may be the only way to do get the desired result. although this PR should in theory eliminate the last of those edge cases.

Dissuading users from picking a "bad" option is difficult, but I think that all caps "VERY EXPENSIVE" communicates the danger better than "Expensive".

File: Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp [hunk 2]
```diff
@@ -62,39 +62,40 @@ namespace EMotionFX
...
+                            ->Attribute(AZ::Edit::Attributes::ChangeNotify, AZ::Edit::PropertyRefreshLevels::EntireTree)
+                        ->DataElement(AZ::Edit::UIHandlers::Default, &ActorComponent::BoundingBoxConfiguration::m_expandBy,
+                            "Expand by",
+                            "Percentage that the calculated bounding box should be automatically expanded with. "
+                            "This can be used to add a tolerance area to the calculated bounding box to avoid clipping the character too early. "
+                            "A static bounding box together with the expansion is the recommended way for maximum performance. (Default = 25%)")
+                            ->Attribute(AZ::Edit::Attributes::Suffix, " %")
+                            ->Attribute(AZ::Edit::Attributes::Min, 0.0f)
```
Comment (yuriy0) [inline Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp:78]: Expanding by a negative percentage should effectively contract the bbox. It's important that if a parameter has a range of sensible values, it may take all values in that range, even if the use case for some values isn't clear. The math in ActorInstance will work for [-1, inf), although -1 is totally useless as it causes the actor to never render, so a minimum of e.g. -0.99 is more realistic.

Maybe a soft-min of 0 instead to cover the "expected" use case.

**Review by lsemp3d — APPROVED** [review]

File: Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp (hunk 1 above)
Comment (amzn-jillich) [reply Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp:70]: Changed it back to caps

File: Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp (hunk 2 above)
Comment (amzn-jillich) [reply Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp]: Good point. I changed it to -100+tolerance ~ -99.999% as the UI values are in % and get converted to normalized values internally. This basically allows it to shrink to a super small aabb but not scale it negatively.

**Review by yuriy0 — APPROVED** [review]

File: Gems/EMotionFX/Code/EMotionFX/Rendering/Common/RenderUtil.cpp [hunk 3]
```diff
@@ -238,12 +238,12 @@ namespace MCommon
...
-        const AZ::Vector3       min     = box.GetMin();// + (box.GetMin()-center).Normalized()*0.005f;
-        const AZ::Vector3       max     = box.GetMax();// + (box.GetMax()-center).Normalized()*0.005f;
-        const float             scale   = box.CalcRadius() * 0.1f;
+        const AZ::Vector3       min     = box.GetMin();
+        const AZ::Vector3       max     = box.GetMax();
+        const float             radius  = AZ::Vector3(box.GetMax() - box.GetMin()).GetLength() * 0.5f;
+        const float             scale   = radius * 0.1f;
         const AZ::Vector3       up      = AZ::Vector3(0.0f, 1.0f, 0.0f) * scale;
         const AZ::Vector3       right   = AZ::Vector3(1.0f, 0.0f, 0.0f) * scale;
         const AZ::Vector3       front   = AZ::Vector3(0.0f, 0.0f, 1.0f) * scale;
```
Comment (burelc-amzn) [inline Gems/EMotionFX/Code/EMotionFX/Rendering/Common/RenderUtil.cpp:249]: Nit: `p` below, on line 252, can be `const`, if it is declared like this:

```
const AZStd::array p {
    AZ::Vector3{min.GetX(), min.GetY(), min.GetZ()},
    AZ::Vector3{max.GetX(), min.GetY(), min.GetZ()},
    AZ::Vector3{max.GetX(), min.GetY(), max.GetZ()},
    AZ::Vector3{min.GetX(), min.GetY(), max.GetZ()},
    AZ::Vector3{min.GetX(), max.GetY(), min.GetZ()},
    AZ::Vector3{max.GetX(), max.GetY(), min.GetZ()},
    AZ::Vector3{max.GetX(), max.GetY(), max.GetZ()},
    AZ::Vector3{min.GetX(), max.GetY(), max.GetZ()},
};
```

File: Gems/EMotionFX/Code/EMotionFX/Rendering/Common/RenderUtil.h [hunk 4]
```diff
@@ -735,7 +720,7 @@ namespace MCommon
          * @param radius The radius of the sphere.
          * @return A pointer to the newly created util sphere mesh.
          */
-        static UtilMesh* CreateSphere(float radius, uint32 numSegments = 8);
+        static UtilMesh* CreateSphere(float radius, uint32 numSegments = 5);
```
Comment (burelc-amzn) [inline Gems/EMotionFX/Code/EMotionFX/Rendering/Common/RenderUtil.h:723]: What's up with changing this default?

**Review by burelc-amzn — APPROVED** [review]

File: Gems/EMotionFX/Code/EMotionFX/Pipeline/RCExt/Actor/ActorGroupExporter.cpp [hunk 5]
```diff
@@ -48,7 +48,10 @@ namespace EMotionFX
             AZ::SerializeContext* serializeContext = azrtti_cast<AZ::SerializeContext*>(context);
             if (serializeContext)
             {
-                serializeContext->Class<ActorGroupExporter, AZ::SceneAPI::SceneCore::ExportingComponent>()->Version(2);
+                // Increasing the version number of the actor group exporter will make sure all actor products will be force re-generated.
+                // Version history:
+                // v3: Introduced Actor_Nodes2 (replaced Actor_Nodes) and Actor_Node2 (replaced Actor_Node)
```
[the remark this answers is not in the document]
Comment (amzn-jillich) [reply Gems/EMotionFX/Code/EMotionFX/Pipeline/RCExt/Actor/ActorGroupExporter.cpp:53]: Removed

File: Gems/EMotionFX/Code/EMotionFX/Rendering/Common/RenderUtil.cpp [hunk 6]
```diff
@@ -238,12 +238,12 @@ namespace MCommon
...
     // render selection gizmo around the given AABB
-    void RenderUtil::RenderSelection(const MCore::AABB& box, const MCore::RGBAColor& color, bool directlyRender)
+    void RenderUtil::RenderSelection(const AZ::Aabb& box, const MCore::RGBAColor& color, bool directlyRender)
     {
-        //const Vector3 center  = box.CalcMiddle();
-        const AZ::Vector3       min     = box.GetMin();// + (box.GetMin()-center).Normalized()*0.005f;
-        const AZ::Vector3       max     = box.GetMax();// + (box.GetMax()-center).Normalized()*0.005f;
-        const float             scale   = box.CalcRadius() * 0.1f;
+        const AZ::Vector3       min     = box.GetMin();
+        const AZ::Vector3       max     = box.GetMax();
```
[the remark this answers is not in the document]
Comment (amzn-jillich) [reply Gems/EMotionFX/Code/EMotionFX/Rendering/Common/RenderUtil.cpp:244]: Added

File: Gems/EMotionFX/Code/EMotionFX/Rendering/Common/RenderUtil.cpp (hunk 3 above)
Comment (amzn-jillich) [reply Gems/EMotionFX/Code/EMotionFX/Rendering/Common/RenderUtil.cpp:249]: Changed

File: Gems/EMotionFX/Code/EMotionFX/Rendering/Common/RenderUtil.h (hunk 4 above)
Comment (amzn-jillich) [reply Gems/EMotionFX/Code/EMotionFX/Rendering/Common/RenderUtil.h:723]: Good spot, should have commented that in the PR actually. These are used for rendering line-based skeletons and heavily drop performance (due to the really bad way we render these). As they are super small anyway, I decreased the number of segments to trade that with some higher fps. This will all be replaced/removed with the Atom viewport changes - we'll use the aux geom and remove the Util meshes from here entirely. For line-based skeleton, we shouldn't even render spheres, but just scaled points or something similar.
