### PR TITLE
AudioSystem Gem Shutdown Fixes

### LINKED ISSUE #11554: [GameLauncher] Crash during Quit/Shutdown from a level with audio objects
**Describe the bug**
Crash during the `Audio::SystemRequest::Shutdown` request being processed in the GameLauncher application.  

**Assets required**
I reproduced this with Wwise set up and a looping sound added.  Used a level with an entity set to play the looping sound.
TBD - I can possibly provide this later.

**Steps to reproduce**
1. Enable AudioEngineWwise Gem (and all prerequisite setup)
2. A looping sound is added to the Wwise project and everything is set up on the O3DE side to play it.
3. Also add an `AudioListenerComponent` to the Camera entity.
4. Create a new level
5. Add AudioTriggerComponent to an entity and assign the looping sound to play immediately
6. Setup "autoexec" behavior to load this level at startup
7. Run GameLauncher application
8. While the sound is playing, open Console (~) and type 'quit'

**Expected behavior**
Sounds are stopped, application exits cleanly.

**Actual behavior**
Crashes with `Exception thrown: read access violation. **rhs** was 0x10.`

Callstack (Audio Thread, snipped for brevity):
```
 	AudioSystem.dll!AZStd::pair<unsigned __int64,Audio::CATLListenerObject *>::pair<unsigned __int64,Audio::CATLListenerObject *>(const AZStd::pair<unsigned __int64,Audio::CATLListenerObject *> & rhs) Line 127	C++
 	AudioSystem.dll!Audio::CAudioListenerManager::Release() Line 733	C++
 	AudioSystem.dll!Audio::CAudioTranslationLayer::ReleaseImplComponent() Line 814	C++
>	AudioSystem.dll!`Audio::CAudioTranslationLayer::ProcessRequest'::`2'::<lambda_1>::operator()<Audio::SystemRequest::Shutdown &>(Audio::SystemRequest::Shutdown & request) Line 131	C++
<SNIP>
 	AudioSystem.dll!Audio::CAudioSystem::InternalUpdate() Line 215	C++
 	AudioSystem.dll!Audio::CAudioThread::Run() Line 48	C++
<SNIP>
 	AudioSystem.dll!AZStd::Internal::thread_run_function(void * param) Line 38	C++
 	ucrtbased.dll!00007ffaa5694c7c()	Unknown
 	kernel32.dll!00007ffb466d54e0()	Unknown
 	ntdll.dll!00007ffb4802485b()	Unknown
```

Callstack (Main Thread, snipped for brevity):
```
 	ntdll.dll!00007ffb480c40b4()	Unknown
 	KernelBase.dll!00007ffb45752a0e()	Unknown
>	AudioSystem.dll!AZStd::binary_semaphore::acquire() Line 60	C++
 	AudioSystem.dll!Audio::CAudioSystem::PushRequestBlocking(AZStd::variant<...> && request) Line 136	C++
 	AudioSystem.dll!Audio::CAudioSystem::Release() Line 295	C++
 	AudioSystem.dll!AudioSystemGem::AudioSystemGemSystemComponent::Release() Line 205	C++
<SNIP>
 	CrySystem.dll!CSystem::ShutDown() Line 398	C++
 	CrySystem.dll!CSystem::~CSystem() Line 267	C++
 	CrySystem.dll!CSystem::`scalar deleting destructor'(unsigned int)	C++
 	AudioProject.GameLauncher.exe!O3DELauncher::Run(const O3DELauncher::PlatformMainInfo & mainInfo) Line 610	C++
 	AudioProject.GameLauncher.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 33	C++
 	AudioProject.GameLauncher.exe!invoke_main() Line 107	C++
 	AudioProject.GameLauncher.exe!__scrt_common_main_seh() Line 288	C++
 	AudioProject.GameLauncher.exe!__scrt_common_main() Line 331	C++
 	AudioProject.GameLauncher.exe!WinMainCRTStartup(void * __formal) Line 17	C++
 	kernel32.dll!00007ffb466d54e0()	Unknown
 	ntdll.dll!00007ffb4802485b()	Unknown
```

**Screenshots/Video**
N/A

**Found in Branch**
`development` latest

**Desktop/Device (please complete the following information):**
 - Device: PC 
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen Threadripper 3970X
 - GPU NVIDIA RTX 3070
 - Memory 64GB

### LINKED ISSUE #11557: [GameLauncher] Crash during Quit/Shutdown when deactivating AudioProxyComponent
**Describe the bug**
When quitting from a level that has an `AudioProxyComponent`, there's a nullptr de-reference in that component's `Deactivate`. 

**Assets required**
N/A

**Steps to reproduce**
1. Create a level and add an AudioTriggerComponent and AudioProxyComponent to an entity
2. Make this level load in autoexec
3. Run GameLauncher
4. Open Console (~) and type 'quit'

**Expected behavior**
Components are deactivated properly, clean shutdown

**Actual behavior**
A nullptr de-reference on the `IAudioSystem` interface because audio systems were torn down before the entity is deactivated.

Callstack (Main Thread):
```
 	AudioSystem.dll!Audio::CAudioProxy::Release() Line 314	C++
 	LmbrCentral.dll!LmbrCentral::AudioProxyComponent::Deactivate() Line 81	C++
 	[Inline Frame] OpenXRTest.GameLauncher.exe!AZ::Entity::DeactivateComponent(AZ::Component & component) Line 400	C++
>	OpenXRTest.GameLauncher.exe!AZ::Entity::Deactivate() Line 236	C++
 	OpenXRTest.GameLauncher.exe!AZ::Entity::Reset() Line 108	C++
 	OpenXRTest.GameLauncher.exe!AZ::Entity::~Entity() Line 98	C++
 	OpenXRTest.GameLauncher.exe!AZ::Entity::`scalar deleting destructor'(unsigned int)	C++
 	OpenXRTest.GameLauncher.exe!AZ::ComponentApplication::Destroy() Line 742	C++
 	OpenXRTest.GameLauncher.exe!AzFramework::Application::Stop() Line 266	C++
 	OpenXRTest.GameLauncher.exe!O3DELauncher::Run(const O3DELauncher::PlatformMainInfo & mainInfo) Line 615	C++
 	OpenXRTest.GameLauncher.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 36	C++
 	[Inline Frame] OpenXRTest.GameLauncher.exe!invoke_main() Line 102	C++
 	OpenXRTest.GameLauncher.exe!__scrt_common_main_seh() Line 288	C++
 	kernel32.dll!00007ffb466d54e0()	Unknown
 	ntdll.dll!00007ffb4802485b()	Unknown
```

Log:
```
[Warning] (ATL) - ATL ReleaseImplComponent - Shutting down the audio implementation failed!
[Warning] (ATL) - ATL ReleaseImplComponent - Releasing the audio implementation failed!
The thread 0x4ed8 has exited with code 0 (0x0).
'OpenXRTest.GameLauncher.exe' (Win32): Unloaded 'D:\code\o3de-extras\Projects\OpenXRTest\build\vs2022\bin\profile\CrySystem.dll'
Exception thrown: read access violation.
**AZ::Interface<Audio::IAudioSystem>::Get**(...) returned nullptr.

The program '[36440] OpenXRTest.GameLauncher.exe' has exited with code 0 (0x0).
```

**Screenshots/Video**
N/A

**Found in Branch**
`development` latest

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen Threadripper 3970X
 - GPU NVIDIA RTX 3070
 - Memory 64GB

### PR DESCRIPTION
**Pull request by amzn-phist**
## What does this PR do?

This addresses a couple instances of shutdown crashes in GameLauncher related to audio Gems.
One fixes how a container of objects was being destructed.
The other changes the lifetime of the `IAudioSystem` interface, so that it's constructed earlier and destructed later. This prevents nullptr dereference.

fixes #11554 
fixes #11557

## How was this PR tested?

Run GameLaunchers for projects with and without audio setups.
Quit from levels with and without audio playing.
Ran Editor and exit.

### CODE REVIEW

File: Code/Legacy/CrySystem/SystemInit.cpp [hunk 1]
```diff
@@ -352,39 +352,31 @@ bool CSystem::InitFileSystem_LoadEngineFolders(const SSystemInitParams&)
...
-    {
-        Audio::Gem::AudioSystemGemRequestBus::BroadcastResult(result, &Audio::Gem::AudioSystemGemRequestBus::Events::Initialize, &initParams);
-    }
-    else
-    {
-        Audio::Gem::AudioSystemGemRequestBus::BroadcastResult(result, &Audio::Gem::AudioSystemGemRequestBus::Events::Initialize, nullptr);
-    }
 
-    if (result)
+    bool shouldInitializeAudioSystem = (!initParams.bPreview && !initParams.bUnattendedMode);
```
Comment (lumberyard-employee-dm) [inline Code/Legacy/CrySystem/SystemInit.cpp:364]: Why not just always initialize this in the SystemComponent of the Audio Gem and use a settings registry entry for the determining if the audio system should initialize.

The bPreview and bUanttendedMode parameters seem unrelated to Audio system and I think it would be better if the Audio system had an explicit option.

Afterwards we can just strip out this code.

Comment (amzn-phist) [reply Code/Legacy/CrySystem/SystemInit.cpp:364]: Removing these dependencies is what I was hoping to simplify this to.  I was looking into these options and couldn't tell for sure whether these options are being used.

`bPreview` mode appears to preview files.  But it only applies to legacy file types "chr", "skin", "cdf", "cgf", ... (see `IsPreviewableFileType`).  I can probably remove the dependency on that option.
`bUnattendedMode` appears to be set when exporting.  Do we still use export levels?  I don't think so.

If these appear to be useless, I'll remove them and simplify this.

Comment (lumberyard-employee-dm) [reply Code/Legacy/CrySystem/SystemInit.cpp:364]: No we don't export levels at all anymore.
For the old AZ::IO::Archive format, we create the PAK via the zip command to compress a levels files.
`bPreview` appears useless.

Also even if those legacy were being previewed in some kind of special Editor mode, what harm would their be to have the Audio system active?

Comment (amzn-phist) [reply Code/Legacy/CrySystem/SystemInit.cpp:364]: I think the intention was that disabling full audio init trims the fat in these modes.  Harmless if it's there, but it's unnecessary.

I'll remove this stuff.

File: Code/Legacy/CryCommon/IAudioSystem.h [hunk 2]
```diff
@@ -578,43 +578,32 @@ namespace Audio
     namespace Gem
     {
         ///////////////////////////////////////////////////////////////////////////////////////////////
-        // Used for initializing and releasing the audio system (AudioSystem/ATL) code.
-        class AudioSystemGemRequests
+        // Audio initialization loads resources that may not be ready until after
+        // component application (and AP) is fully up, so it is delayed until CSystem::Init.
+        // Similarly, release is called in CSystem::ShutDown.
+        class SystemBusInterface
```
Comment (lumberyard-employee-dm) [inline Code/Legacy/CryCommon/IAudioSystem.h:584]: Well the ComponentLifecycle "CriticalAssetsComponent" event can be used to make sure the AP has processed assets.

There would be no dependency on CSystem::Init.

[Here](https://github.com/o3de/o3de/blob/development/Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp#L150-L158) is how the Atom Bootstrap gem module uses that event to Initialize a window

File: Code/Legacy/CrySystem/SystemInit.cpp [hunk 3]
```diff
@@ -350,37 +350,20 @@ bool CSystem::InitFileSystem_LoadEngineFolders(const SSystemInitParams&)
...
 
 //////////////////////////////////////////////////////////////////////////
-bool CSystem::InitAudioSystem(const SSystemInitParams& initParams)
+bool CSystem::InitAudioSystem()
 {
-    if (!Audio::Gem::AudioSystemGemRequestBus::HasHandlers())
+    if (!Audio::Gem::SystemRequestBus::HasHandlers())
     {
-        // AudioSystem Gem has not been enabled for this project.
+        // AudioSystem Gem has not been enabled for this project/configuration (e.g. Server).
```
Comment (lumberyard-employee-dm) [inline Code/Legacy/CrySystem/SystemInit.cpp:357]: A Simpler approach is instead of using the CSystem::InitAudioSystem function.

The AudioSystemGemSystemComponent can in it's `Activate` function register for the "CriticalAssetsCompiled" lifecycle event and then just initialize the Audio system there.

File: Code/Legacy/CrySystem/System.cpp [hunk 4]
```diff
@@ -392,7 +392,7 @@ void CSystem::ShutDown()
 
     // Audio System Shutdown!
     // Shut down audio as late as possible but before the streaming system and console get released!
-    Audio::Gem::AudioSystemGemRequestBus::Broadcast(&Audio::Gem::AudioSystemGemRequestBus::Events::Release);
+    Audio::Gem::SystemRequestBus::Broadcast(&Audio::Gem::SystemRequestBus::Events::Release);
```
Comment (lumberyard-employee-dm) [inline Code/Legacy/CrySystem/System.cpp:395]: This Release can be done in the Deactivate of `AudioSystemGemSystemComponent`
This would remove the dependency on System.cpp

File: Code/Legacy/CryCommon/IAudioSystem.h (hunk 2 above)
Comment (amzn-phist) [reply Code/Legacy/CryCommon/IAudioSystem.h:584]: What is considered to be a "critical asset"?  Does it still depend on the `JobDescriptor::m_critical` flag in the builder?  In terms of startup, when the application waits on `CompileCriticalAssets`, is it going to return after all `m_critical` jobs have run, or when all jobs are done?

This is the direction I want to go eventually.  Can even go further and do most of the audio initialization early, but leave the loading of assets until after we get a signal from AP that things are ready.

**Review by lumberyard-employee-dm — APPROVED** [review]

**Review by lawsonamzn — APPROVED** [review]
While I'd prefer to see less dependence on CryLegacy that is indeed a "bigger thread" to pull than we need to right at this instant.
Longer term we wouldn't wait for critical assets anyway, we'd have the system demand the assets it needs, blockingly if necessary.
