### PR TITLE
Fixed Asset Browser path related context menu options.

### LINKED ISSUE #2433: Asset Browser: "Open in Explorer" does not navigate to the desired file
In the Asset Browser, selecting "Open in Explorer" open the explorer, but it doesn't target the desired file

image

**To Reproduce**
1. Go to the Asset Browser
2. Find any asset
3. Right click on it and select "Open in Explorer"
4. Explorer window opens, but not at the desired location

**Expected behavior**
Explorer will open at the asset's folder

### LINKED ISSUE #2533: Asset Browser Open In Explorer Broken
**Describe the bug**
Asset Browser Open In Explorer does not work

**To Reproduce**
1. Right click entry in asset browser
2. Click open in explorer
3. Explorer opens "This computer"

**Expected behavior**
Explorer opens in the directory of the selected item

### LINKED ISSUE #2558: Copy Path To Clipboard doesn't work
The "Copy Path To Clipboard" menu option in the Asset Browser doesn't work. 

**To Reproduce**
1. Launch the Editor
2. Right-click on an item in the Asset Browser
3. Select "Copy Path To Clipboard"
4. Paste in a text editor

**Expected behavior**
The full path to the item that was selected is pasted.

**Actual behavior**
The root and file name are pasted but none of the intermediate directories.

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

### PR DESCRIPTION
**Pull request by cgalvan**
Most of the path-related context menu options in the Asset Browser were not working. Fixed the logic to make sure it deals with a full, normalized path, which removed some guess-work the former logic was trying to do with files vs. folders.

Tested the following context menu options on both files and folders and verified they now perform the expected behaviors:

- Open in Explorer
- Copy Name to Clipboard
- Copy Path to Clipboard

Also tested the additional context menu options specific for files (e.g. Open in Asset Editor, Open in associated application, etc...)

Fixes #2533
Fixes #2433 
Fixes #2558 

Signed-off-by: Chris Galvan <chgalvan@amazon.com>

### CODE REVIEW

**Review by tjmichaels — APPROVED** [review]

File: Code/Editor/Util/FileUtil.cpp [hunk 1]
```diff
@@ -1900,76 +1900,25 @@ IFileUtil::ECopyTreeResult   CFileUtil::MoveTree(const QString& strSourceDirecto
...
-QString CFileUtil::PopupQMenu(const QString& filename, const QString& fullGamePath, QWidget* parent)
+void CFileUtil::PopulateQMenu(QWidget* caller, QMenu* menu, const AZStd::string& fullGamePath)
 {
-    QStringList extraItemsFront;
-    return PopupQMenu(filename, fullGamePath, parent, nullptr, extraItemsFront);
+    PopulateQMenu(caller, menu, fullGamePath, nullptr);
 }
 
-QString CFileUtil::PopupQMenu(const QString& filename, const QString& fullGamePath, QWidget* parent, [[maybe_unused]] bool* pIsSelected, const QStringList& extraItemsFront)
+void CFileUtil::PopulateQMenu(QWidget* caller, QMenu* menu, const AZStd::string& fullGamePath, bool* isSelected)
```
Comment (hultonha) [inline Code/Editor/Util/FileUtil.cpp:1908]: suggestion: Is it worth making this an `AZStd::string_view` instead of an `AZStd::string`?

File: Code/Editor/Util/FileUtil.cpp [hunk 2]
```diff
@@ -1900,76 +1900,25 @@ IFileUtil::ECopyTreeResult   CFileUtil::MoveTree(const QString& strSourceDirecto
...
-
-void CFileUtil::PopulateQMenu(QWidget* caller, QMenu* menu, const QString& filename, const QString& fullGamePath)
-{
-    PopulateQMenu(caller, menu, filename, fullGamePath, nullptr);
-}
-
-void CFileUtil::PopulateQMenu(QWidget* caller, QMenu* menu, const QString& filename, const QString& fullGamePath, bool* isSelected)
-{
-    QString fullPath;
+    QString fullPath(fullFilePath.c_str());
```
Comment (hultonha) [inline Code/Editor/Util/FileUtil.cpp:1914]: related: Here we can then do `QString fullPath(fullFilePath.data(), fullFilePath.size());` I'm pretty sure

**Review by hultonha — APPROVED** [review]
Looks good, I just have one minor suggestion :+1:

File: Code/Editor/Util/FileUtil.cpp (hunk 1 above)
Comment (cgalvan) [reply Code/Editor/Util/FileUtil.cpp]: Sure thing!

File: Code/Editor/Util/FileUtil.cpp (hunk 2 above)
Comment (cgalvan) [reply Code/Editor/Util/FileUtil.cpp:1914]: So I did update to use string_view instead of string, but this line had to stay the same because it's not coming from the parameter, it's from the local variable that gets created above because I have to pass it to the Path::Normalize method first.

Comment (hultonha) [reply Code/Editor/Util/FileUtil.cpp:1914]: Ah okay got you, actually you still might be able to use `.data()` and `.size()` with string too, that'll save having to first calculate the length of the string with `c_str()` if I'm not mistaken, but it's probably a micro optimization (can be useful in some cases though)
