### PR TITLE
Entering the Game Mode when the SlideAlongAxisBasedOnAngle in the Camera Rig is set results in an assert

### LINKED ISSUE #3959: [Assert] Entering the Game Mode when the SlideAlongAxisBasedOnAngle in the Camera Rig is set results in an assert
**Describe the bug**
It has been noticed that entering the Game Mode when the SlideAlongAxisBasedOnAngle in the Camera Rig is set results in an assert.

**To Reproduce**
1. Create an entity.
2. Add Camera Rig component to it.
3. In the Look-at Behavior add SlideAlongAxisBasedOnAngle setting.
4. Enter the Game Mode.

**Expected behavior**
The Game Mode launches without issues.

**Desktop/Device:**
Device: PC
OS: Windows
Version 10
CPU Intel I5-9600k
GPU RTX 2060
Memory 16GB

**Additional context**

assert52
```
File: C:/O3DE/o3de/Gems/StartingPointCamera/Code/Source/StartingPointCamera/StartingPointCameraUtilities.cpp: 
Condition:'void __cdecl Camera::MaskComponentFromNormalizedVector(class AZ::Vector3 &,enum Camera::VectorComponentType)'
MaskComponentFromNormalizedVector: VectorComponentType - unexpected value
Line: 52
```
https://user-images.githubusercontent.com/86952009/132332082-0e5fe832-fbf4-4cf4-ae8f-269f30fc72b0.mp4

### PR DESCRIPTION
**Pull request by AMZN-Igarri**
fixes #3959 
Also after a discussion on the issue's thread we ended up switching from a Dropdown to individual CheckBoxes for each vector component.
CameraRig

### CODE REVIEW

File: Gems/StartingPointCamera/Code/Source/CameraLookAtBehaviors/SlideAlongAxisBasedOnAngle.cpp [hunk 1]
```diff
@@ -23,7 +23,9 @@ namespace Camera
                 ->Version(1)
```
Comment (hultonha) [inline Gems/StartingPointCamera/Code/Source/CameraLookAtBehaviors/SlideAlongAxisBasedOnAngle.cpp:23]: update: As you're changing the serialized data you'll need to bump the version number here...

In some cases it's also necessary to write a version converter (to update the old data to the new format), but if this isn't widely used and we're not yet committing to stability this change might be okay - worth double checking though with who owns this component/gem)

File: Gems/StartingPointCamera/Code/Source/StartingPointCamera/StartingPointCameraUtilities.cpp [hunk 2]
```diff
@@ -26,38 +26,27 @@ namespace Camera
         return "";
     }
 
-    //////////////////////////////////////////////////////////////////////////
-    /// This methods will 0 out a vector component and re-normalize it
-    //////////////////////////////////////////////////////////////////////////
-    void MaskComponentFromNormalizedVector(AZ::Vector3& v, VectorComponentType vectorComponentType)
+    void MaskComponentFromNormalizedVector(AZ::Vector3& v, bool ignoreX, bool ignoreY, bool ignoreZ)
```
Comment (hultonha) [inline Gems/StartingPointCamera/Code/Source/StartingPointCamera/StartingPointCameraUtilities.cpp:29]: question: Before it looked like it was only possible to ignore one axis at a time, but now we can ignore all 3 at the same time? What happens if you do this? Will this 'freeze' the camera?

**Review by hultonha — COMMENTED** [review]
Change mostly looks good but I have a couple of questions/suggestions

File: Gems/StartingPointCamera/Code/Source/StartingPointCamera/StartingPointCameraUtilities.cpp (hunk 2 above)
Comment (AMZN-Igarri) [reply Gems/StartingPointCamera/Code/Source/StartingPointCamera/StartingPointCameraUtilities.cpp:29]: Right now it will throw a warning that you are trying to normalize a zero vector and return that zero vector. Maybe it could be a good idea to always have at least one checkbox activated.

**Review by jonawals — APPROVED** [review]
Nothing more to add.

File: Gems/StartingPointCamera/Code/Source/StartingPointCamera/StartingPointCameraUtilities.cpp (hunk 2 above)
Comment (hultonha) [reply Gems/StartingPointCamera/Code/Source/StartingPointCamera/StartingPointCameraUtilities.cpp:29]: This is probably okay for now, in a perfect would it would be nice to avoid it, but in practice it's likely not a huge issue (so long as nothing bad happens, I take it the camera will then just not move?)

**Review by hultonha — APPROVED** [review]

**Comment by amzn-leenguy** [comment]
Good work.
