### PR TITLE
Fixed physx material ids being set to null when used in a prefab

### LINKED ISSUE #7550: Physics entities with assigned physics materials do not retain them when their Prefab is spawned via Script Canvas
**Describe the bug**
If a Prefab of a physics entity with a custom physics material assigned is spawned, it does not retain its properties. It should be noted that the same Prefab placed manually in the level keeps its physics material properties.

**Steps to reproduce**
1. Go to Tools > PhysX Configuration (PREVIEW).
2. In the Physics Materials section click the "Edit asset" button to the far right of the "Physics Material Library" property.
3. In the .physmaterial opened in the Asset Browser click the + (Add new child element) in the top right.
4. Change the created child element's properties: set the Restitution to 1.0, and Restitution combine to "Maximum" and save the .physmaterial asset.
5. Create a platform entity (PhysX Shape Collider, Box Shape - make sure the Game View property is enabled, and the X and Y dimensions are set to 5).
6. Create a Rigid Body entity (PhysX Shape Collider, Sphere Shape - make sure the Game View property is enabled, PhysX Rigid Body).
7. In the Rigid Body entity's PhysX Shape Collider component set the Physics Materials > Entire object property to the material saved in step 4.
8. Place the Rigid Body entity above the platform entity and enter the Game Mode to verify that it continually bounces.
9. Right-click the Rigid Body entity, select the "Create Prefab..." from the dropdown menu and save the prefab.
10. Create a Spawn entity (With only the Script Canvas component) above the platform entity next to the Rigid Body entity.
11. In the Script Canvas recreate the script shown below under the **Assets required** section (Spawn Script Canvas).
12. Attach the created Script Canvas graph to the entity created in step 10.
13. Enter the Game Mode.

**Expected behavior**
Both physics Prefabs show the same behavior.

**Actual behavior**
Spawned Prefab does retain the physics material properties of the original Prefab.

**Assets required**
Spawn Script Canvas
SpawnScriptCanvas

**Video**

https://user-images.githubusercontent.com/86952082/153427022-3bbdef0c-82dc-4f45-a374-7613edd1cc42.mp4

**Found in Branch**
Development (1c3a619)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

### PR DESCRIPTION
**Pull request by moraaar**
The `OnReadEnd` function of the serialization of `MaterialSelection` class tries to validate the material ids after serialization by looking into the material library. The problem was when executed in the context of Asset Builder (due to a prefab), the material library is never loaded by the physics system because it's expecting the event "CriticalAssetsCompiled", which is not fired at asset processor time.

Fixed by adding a protection in `OnReadEnd` to only validate the material ids if it's not an asset builder. That way when prefabs are processing the data it will only write the ids out, and during editor/launcher it will validate it against the library.

Fixes #7550 

Signed-off-by: moraaar <moraaar@amazon.com>

### CODE REVIEW

**Review by AMZN-daimini — APPROVED** [review]

**Review by gadams3 — APPROVED** [review]

**Review by NicholasVanSickle — APPROVED** [review]
Nice job tracing this!

File: Code/Framework/AzFramework/AzFramework/Physics/Material.cpp [hunk 1]
```diff
@@ -47,7 +47,26 @@ namespace Physics
...
+        bool IsAssetBuilder() const
+        {
+            AZ::SerializeContext* serializeContext = nullptr;
+            AZ::ComponentApplicationBus::BroadcastResult(serializeContext, &AZ::ComponentApplicationBus::Events::GetSerializeContext);
+
+            // TypeId of AssetBuilderComponent
+            const char* typeIDAssetBuilderComponent = "{04332899-5d73-4d41-86b7-b1017d349673}";
+
+            return serializeContext
+                && serializeContext->FindClassData(AZ::TypeId::CreateString(typeIDAssetBuilderComponent));
```
Comment (lumberyard-employee-dm) [inline Code/Framework/AzFramework/AzFramework/Physics/Material.cpp:69]: You could just query for the SettingsRegistry for the assetbuilder specialization.
Here is how you can do it: https://github.com/o3de/o3de/pull/8800#discussion_r846351409

Comment (moraaar) [reply Code/Framework/AzFramework/AzFramework/Physics/Material.cpp:69]: Thanks @lumberyard-employee-dm for the suggestion. I'll pass on this change for now since I've already tested and verified the current solution works in all scenarios and PhysX Material Library is going to go away soon anyway (so this code will be removed). I'll keep your method in mind if I have to do a similar operation again in the future. Cheers.
