### PR TITLE
EMotion FX: Move character to origin & fix for move groundplane while follow character is disabled

### LINKED ISSUE #7757: [FR] [Animation Viewport] Right click options
Animation viewport should support right click option.
Right click option should include: Reset character. Camera options.

### PR DESCRIPTION
**Pull request by amzn-jillich**
* Fixed a bug with moving the ground plane while follow mode is disabled.
* Changed the "Reset Character" option to not re-create the entire entities and render objects, but just move the character to the origin which is what the former "Reset Transform" option did.
* Only showing the option in case a character is actually loaded.

Resolves #7757

Signed-off-by: Benjamin Jillich <jillich@amazon.com>

### CODE REVIEW

**Review by cgalvan — APPROVED** [review]

File: Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.cpp [hunk 1]
```diff
@@ -278,6 +277,8 @@ namespace EMStudio
             AtomToolsFramework::ModularViewportCameraControllerRequestBus::Event(
                 GetViewportId(), &AtomToolsFramework::ModularViewportCameraControllerRequestBus::Events::SetCameraPivotAttached,
                 m_renderer->GetCharacterCenter());
+
+            m_renderer->UpdateGroundplane();
```
Comment (amzn-rhhong) [inline Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.cpp:281]: In theory the character can still run away from the ground in this case.
Scenario: Camera not following character, character running away from the center and further from the ground. Do we want to see 
1) Ground moving around with the character 
2) Ground stay still and the character eventually run off the grid

I think this change is ok, user probably expected to run off the grid in this case.

**Review by amzn-rhhong — APPROVED** [review]
