### PR TITLE
Fixed PreviewRenderer material update crash.

### LINKED ISSUE #18629: Crash using Material Editor and clicking on the viewport
**Describe the bug**
There is a crash when modifying a material using the Material Editor and then clicking on the viewport.

1. Drag/drop an FBX into the viewport
2. Add a Material Component
3. Select an existing material
4. Open Material Editor
5. Modify a material property (e.g. Tile X/Y)
6. Save with Ctrl+S
7. Click on the main viewport

```
>	CommonFeaturesAtom.Editor.dll!AZ::Render::MaterialComponentController::InitializeMaterialInstancePostTick(AZ::Data::Asset<AZ::Data::AssetData> asset) Line 314	C++
 	[Inline Frame] CommonFeaturesAtom.Editor.dll!AZ::Render::MaterialComponentController::InitializeMaterialInstance::__l2::<lambda_1>::operator()() Line 362	C++
 	[Inline Frame] CommonFeaturesAtom.Editor.dll!AZStd::Internal::INVOKE(AZ::Render::MaterialComponentController::InitializeMaterialInstance::__l2::<lambda_1> &&) Line 208	C++
 	[Inline Frame] CommonFeaturesAtom.Editor.dll!AZStd::invoke(AZ::Render::MaterialComponentController::InitializeMaterialInstance::__l2::<lambda_1> &&) Line 54	C++
 	[Inline Frame] CommonFeaturesAtom.Editor.dll!AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::TickEvents,AZ::TickEvents>,AZ::BusInternal::EBusImplTraits<AZ::TickEvents,AZ::TickEvents>>::QueueFunction::__l5::<lambda_1>::operator()() Line 875	C++
 	[Inline Frame] CommonFeaturesAtom.Editor.dll!AZStd::Internal::INVOKE(AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::TickEvents,AZ::TickEvents>,AZ::BusInternal::EBusImplTraits<AZ::TickEvents,AZ::TickEvents>>::QueueFunction::__l5::<lambda_1> &) Line 208	C++
 	[Inline Frame] CommonFeaturesAtom.Editor.dll!AZStd::invoke(AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::TickEvents,AZ::TickEvents>,AZ::BusInternal::EBusImplTraits<AZ::TickEvents,AZ::TickEvents>>::QueueFunction::__l5::<lambda_1> &) Line 54	C++
 	[Inline Frame] CommonFeaturesAtom.Editor.dll!AZStd::Internal::function_util::invoke_void_return_wrapper<void>::call(AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::TickEvents,AZ::TickEvents>,AZ::BusInternal::EBusImplTraits<AZ::TickEvents,AZ::TickEvents>>::QueueFunction::__l5::<lambda_1> &) Line 41	C++
 	CommonFeaturesAtom.Editor.dll!AZStd::Internal::function_util::get_invoker<void __cdecl(void),AZStd::Internal::function_util::function_obj_tag,AZStd::stateless_allocator>::call<`AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::TickEvents,AZ::TickEvents>,AZ::BusInternal::EBusImplTraits<AZ::TickEvents,AZ::TickEvents>>::QueueFunction<`AZ::Render::MaterialComponentController::InitializeMaterialInstance'::`2'::<lambda_1>>'::`5'::<lambda_1>>(AZStd::Internal::function_util::function_buffer & function_obj_ptr) Line 148	C++
```

**Screenshots/Video**
https://github.com/user-attachments/assets/e41a1518-e89e-4774-b735-4f919a2ac421

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository** 960211ff287fc80d2f75849718277cccef31e2f5

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU 13th Gen Intel I9-13900k
 - GPU GeForce RTX 2070 SUPER
 - Memory 48Gb

### LINKED ISSUE #18630: Pure Virtual Function Call creating a new prefab
**Describe the bug**
Creating a straightforward prefab is resulting in a Pure Virtual Function call

1. Drag an FBX into the viewport
2. Add a Material Component
3. Assign an existing material
4. Right click on the newly created entity 
5. Select "Create Prefab"

**Screenshots/Video**
https://github.com/user-attachments/assets/68e4401a-d7ea-4e87-94eb-365e632a30c4

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository** 960211ff287fc80d2f75849718277cccef31e2f5

**Desktop/Device (please complete the following information):**
    Device: PC
    OS: Windows
    Version 11
    CPU 13th Gen Intel I9-13900k
    GPU GeForce RTX 2070 SUPER
    Memory 48Gb

### PR DESCRIPTION
**Pull request by galibzon**
## What does this PR do?

Fixed PreviewRenderer material update crash.

Fixes #18629
Fixes #18630

The crash was originated by `AtomToolsFramework::PreviewRenderer`. And the easiest way to reproduce was by making changes to an active material asset using the MaterialEditor. Order of events for the crash: The MaterialComponentController owned by AtomToolsFramework::PreviewRenderer, detects a change in the material asset and it enqueues MaterialComponentController::InitializeMaterialInstancePostTick in the TickBus which captures the `this` address. Then immediately `MaterialComponentController::Deactivate()` is called. Later, in the next TickBus event, `MaterialComponentController::InitializeMaterialInstancePostTick` is executed with the same `this` pointer that was destroyed in the previous frame.

Solution, added a std:queue<Asset> to MaterialComponentController where all notified assets are stored. The lambda function was removed so there's no storage of the `this` pointer anymore. Then, when the MaterialComponentController is Deactivated, all queued assets are safely released and there's no lambda function to execute in the next Tick.

## How was this PR tested?

Using AutomatedTesting project, before the fix both cases described in #18629 and #18630 were 100% reproducible with DX12 and Vulkan. After this fix both DX12 and Vulkan work well and no more crashes.

### CODE REVIEW

**Review by gadams3 — COMMENTED** [review]
I don't remember the post tick init or capturing the this pointer.
We should avoid capturing this pointers for queued calls that can't be cleared on destruction, like tick bus or system tick bus queue function calls. The object could be destroyed before the function is called.

I wonder about adding a setting to materials, models, etc to disable hot reloading within the preview renderer.

**Comment by galibzon** [comment]
> I don't remember the post tick init or capturing the this pointer. We should avoid capturing this pointers for queued calls that can't be cleared on destruction, like tick bus or system tick bus queue function calls. The object could be destroyed before the function is called.
> 
> I wonder about adding a setting to materials, models, etc to disable hot reloading within the preview renderer.

I added those recently to avoid a deadlock caused by StreamImage AsyncUploadQueue. No worries now. With this change there's no more capture to the `this` pointer.

**Review by gadams3 — COMMENTED** [review]
Where was deactivate being called? Was this all in the same call stack?

File: Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h [hunk 1]
```diff
@@ -124,6 +125,24 @@ namespace AZ
...
+            // 3. Start the instantiation of a new StreamingImage.
+            // 4. StreamingImage asynchronously queues work in the "Seconday Copy Queue".
+            // 5. StreamingImage waits until the work completes.
+            // 6. The thread of "Seconday Copy Queue" gets a new work item, which may hold a reference
+            //    to an old StreamingImage.
+            // 7. The old StreamingImage gets destroyed and it calls AssetBus::MultiHandler::BusDisconnect(GetAssetId());
+            // 8. When calling AssetBus::MultiHandler::BusDisconnect(GetAssetId()); it tries to lock the same mutex
+            //    from step 1. But the mutex is already locked on Main Thread in step 1.
+            // 9. The "Seconday Copy Queue" thread deadlocks and never completes the work.
+            // 10. Main thread is also deadlocked waiting for "Seconday Copy Queue" to complete.
```
Comment (lsemp3d) [inline Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h:143]: typo on: `Secondary`

**Comment by galibzon** [comment]
> Where was deactivate being called? Was this all in the same call stack?

Deactive was being called by the scene in the PreviewRenderer, which had its own MaterialComponentController. Most likely the scene was being destroyed in that context. But I'm familiar with the PReviewRenderer.

**Review by lsemp3d — APPROVED** [review]

**Review by gadams3 — APPROVED** [review]

**Review by antonmic — APPROVED** [review]
