### PR TITLE
Fixed compile errors in Vector2/3/4 unit tests

### LINKED ISSUE #11026: Development Branch Build Fails to Compile
**Describe the bug**
The development branch build is failing to compile
https://jenkins.build.o3de.org/job/O3DE/job/development/2835/

**Steps to reproduce**
1. Look at the Development branch https://jenkins.build.o3de.org/job/O3DE/job/development/
2. Click on build [#2835](https://jenkins.build.o3de.org/job/O3DE/job/development/2835/) or [#2836](https://jenkins.build.o3de.org/job/O3DE/job/development/2836/)
3. Notice the builds failed to compile

Alternate step:
1. Attempt to compile profile locally
2. Notice the build fails to compile

**Expected behavior**

**Actual behavior**
Build failure
[2022-08-02T16:32:51.126Z] D:/workspace/o3de/Code/Framework/AzCore/Tests/Math/Vector4Tests.cpp:418:12: error: redefinition of 'AngleTestArgs'

**Found in Branch**
Development at https://github.com/o3de/o3de/commit/5c84cc20c1abedec2bf063971eafe7220c5bc9e1

**Desktop/Device (please complete the following information):**
N/A

### PR DESCRIPTION
**Pull request by cgalvan**
## What does this PR do?

Fixes #11026 

Fixed redefinition of struct/fixture names in `Vector2/3/4` unit tests, causing compile errors.

## How was this PR tested?

Verified local unity build now compiles and ran `AzCore` unit tests.

Signed-off-by: Chris Galvan <chgalvan@amazon.com>

### CODE REVIEW

**Review by AMZN-daimini — APPROVED** [review]

**Review by AMZN-stankowi — APPROVED** [review]

**Comment by pollend** [comment]
Oh, sorry I just left and didn't get a chance to test it before I left should of mentioned it in the PR.

File: Code/Framework/AzCore/Tests/Math/Vector2Tests.cpp [hunk 1]
```diff
@@ -437,84 +437,84 @@ namespace UnitTest
         const float infinity = std::numeric_limits<float>::infinity();
         EXPECT_FALSE(AZ::Vector2(infinity, infinity).IsFinite());
     }
-    struct AngleTestArgs
+    struct Vector2AngleTestArgs
```
Comment (pollend) [inline Code/Framework/AzCore/Tests/Math/Vector2Tests.cpp:440]: there is a redefinition error but I didn't see it because these were in isolation ...

**Review by AMZN-alexpete — APPROVED** [review]

**Review by pollend — APPROVED** [review]
