### PR TITLE
Fixed the crash by clear out the item and map array

### LINKED ISSUE #4114: EmotionFX: Pressing the record button a couple of times when the "record states only" option is selected crashes the Editor
**Describe the bug**
Recording states in the Time View of the Animation Editor may result in a crash. The issue is more likely to occur when the "Record states only" option is selected right after adding the Actor, Motion Set and the Anim Graph to the Workspace. Otherwise, a crash occurs only after pressing the record button repeatedly.

**To Reproduce**
1. Open the Animation Editor.
2. Add an Actor, a corresponding Motion Set and Anim Graph.
3. In the Time View pane, press the cog icon and select "Record states only".
4. Press the record button a few times.

**Expected behavior**
The Editor remains stable.

**Call Stack Trace:**
```
25) 00007FFD45F9C247 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FFD48515270 (ntdll) : memset
23) 00007FFD484FC776 (ntdll) : _C_specific_handler
22) 00007FFD4851217F (ntdll) : _chkstk
21) 00007FFD484C1454 (ntdll) : RtlRaiseException
20) 00007FFD48510CAE (ntdll) : KiUserExceptionDispatcher
19) 00007FFCC342E02D (EMotionFX.Editor) : DetachEnvironment
18) 00007FFCC342C5C8 (EMotionFX.Editor) : DetachEnvironment
17) 00007FFCC3434C34 (EMotionFX.Editor) : DetachEnvironment
16) 00007FFCF9334CEE (Qt5Widgets) : QOpenGLWidget::redirected
15) 00007FFCF9307F4A (Qt5Widgets) : QWidget::event
14) 00007FFCC3432B1E (EMotionFX.Editor) : DetachEnvironment
13) 00007FFCF92E49B0 (Qt5Widgets) : QApplicationPrivate::notify_helper
12) 00007FFCF92E3A33 (Qt5Widgets) : QApplication::notify
11) 00007FFCF99F1B4A (Qt5Core) : QCoreApplication::notifyInternal2
10) 00007FFCF930755E (Qt5Widgets) : QWidgetPrivate::drawWidget
 9) 00007FFCF930D5B7 (Qt5Widgets) : QWidgetPrivate::paintSiblingsRecursive
 8) 00007FFCF93076B7 (Qt5Widgets) : QWidgetPrivate::drawWidget
 7) 00007FFCF930D5B7 (Qt5Widgets) : QWidgetPrivate::paintSiblingsRecursive
 6) 00007FFCF93076B7 (Qt5Widgets) : QWidgetPrivate::drawWidget
 5) 00007FFCF930D5B7 (Qt5Widgets) : QWidgetPrivate::paintSiblingsRecursive
 4) 00007FFCF93076B7 (Qt5Widgets) : QWidgetPrivate::drawWidget
 3) 00007FFCF930D5B7 (Qt5Widgets) : QWidgetPrivate::paintSiblingsRecursive
 2) 00007FFCF930D4E5 (Qt5Widgets) : QWidgetPrivate::paintSiblingsRecursive
 1) 00007FFCF93076B7 (Qt5Widgets) : QWidgetPrivate::drawWidget
```

**Desktop/Device:**
Device: PC
OS: Windows
Version 10
CPU Intel I5-9600k
GPU RTX 2060
Memory 16GB

**Additional context**

https://user-images.githubusercontent.com/86952009/133252198-801bc55b-d1b3-4aa1-a6d8-df49d4fb9ecd.mp4

[Editor.log](https://github.com/o3de/o3de/files/7161593/Editor.log)
[error.log](https://github.com/o3de/o3de/files/7161594/error.log)
[dump.zip](https://github.com/o3de/o3de/files/7161595/dump.zip)

### PR DESCRIPTION
**Pull request by amzn-rhhong**
Signed-off-by: rhhong <rhhong@amazon.com>

Resolves #4114

### CODE REVIEW

**Review by amzn-jillich — APPROVED** [review]
Can you link the corresponding GHI please?
Fix looks good, did you test the recorder and recorder viz?

File: Gems/EMotionFX/Code/EMotionFX/Source/Recorder.cpp [hunk 1]
```diff
@@ -1421,7 +1421,10 @@ namespace EMotionFX
...
     void Recorder::ExtractNodeHistoryItems(const ActorInstanceData& actorInstanceData, float timeValue, bool sort, EValueType valueType, AZStd::vector<ExtractedNodeHistoryItem>* outItems, AZStd::vector<size_t>* outMap) const
     {
-        // clear the map array
+        // Clear the item array and map array 
+        outItems->clear();
+        outMap->clear();
+
         const size_t maxIndex = CalcMaxNodeHistoryTrackIndex(actorInstanceData);
         outItems->resize(maxIndex + 1);
         for (size_t i = 0; i <= maxIndex; ++i)
```
Comment (burelc-amzn) [inline Gems/EMotionFX/Code/EMotionFX/Source/Recorder.cpp:1430]: This is clearing the `outItems` vector, destroying all the contained objects, then resizing it back up again, which default constructs a bunch of `ExtractedNodeHistoryItem`s, then looping to explicitly set the values for each element to 0, which is already done by the default construction.
* You shouldn't need to call `outItems->clear()` here, because of the `resize()` call that happens immediately afterwards
* You should be able to remove the following `for` loop, it doesn't really do anything

Where was this crashing? I'm not understanding how this would prevent a crash, it seems to me that regardless of if you call `outItems->clear()` and `outMap->clear()`, at the end of this function, their sizes will be `maxIndex + 1`.

**Comment by amzn-rhhong** [comment]
Resolves #4114

File: Gems/EMotionFX/Code/EMotionFX/Source/Recorder.cpp [hunk 2]
```diff
@@ -1421,17 +1421,16 @@ namespace EMotionFX
     // extract sorted active items
     void Recorder::ExtractNodeHistoryItems(const ActorInstanceData& actorInstanceData, float timeValue, bool sort, EValueType valueType, AZStd::vector<ExtractedNodeHistoryItem>* outItems, AZStd::vector<size_t>* outMap) const
     {
-        // clear the map array
+        // Reinit the item array.
         const size_t maxIndex = CalcMaxNodeHistoryTrackIndex(actorInstanceData);
         outItems->resize(maxIndex + 1);
         for (size_t i = 0; i <= maxIndex; ++i)
```
Comment (burelc-amzn) [inline Gems/EMotionFX/Code/EMotionFX/Source/Recorder.cpp:1427]: Might as well use a range-for loop here instead, then delete line 1429:
```suggestion
        for (ExtractedNodeHistoryItem& item : *outItems)
```

**Review by burelc-amzn — APPROVED** [review]
