### PR TITLE
Fixed titles/sub-titles in LC nodes not working in debug

### LINKED ISSUE #4872: Landscape Canvas: Node titles in Debug configuration are garbage values
**Describe the bug**
Node titles in Debug configuration are garbage values.

**Steps to reproduce**
1. Build the Editor to launch AutomatedTesting in Debug configuration.
2. Launch the Editor.
3. Open Landscape Canvas, and add any node to the open graph.

**Expected behavior**
Node titles are legible.

**Actual behavior**
Node titles are garbage values.

**Screenshots/Video**
landscapecanvas2

**Found in Branch**
development@151d0a33c20

### PR DESCRIPTION
**Pull request by cgalvan**
## What does this PR do?

Fixes #4872 

The titles/sub-titles of the Landscape Canvas nodes were being stored as static QString's but then were returning as `TITLE.toUtf8().constData()` which is pointing at freed memory, leading to garbage string values being displayed in debug builds. These were static since they needed to be accessed before the nodes were actually created in order to populate the node palettes, but because of this they were actually being constructed too early to take advantage of Qt's translation system anyways, so have switched them all to `const char*`. This will also unblock current ongoing efforts to optimize rapidjson, for which the new memory allocator is stricter on using freed memory.

There is a future backlog task to move the node generation to be data-driven which will simplify this even further.

## How was this PR tested?

Launched debug Editor and verified all the node titles/sub-titles show up correctly now.

Signed-off-by: Chris Galvan <chgalvan@amazon.com>

### CODE REVIEW

**Review by AMZN-daimini — APPROVED** [review]

**Review by mbalfour-amzn — APPROVED** [review]

**Comment by spham-amzn** [comment]
Yeah, toUtf8() returns a QByteArray object (which isnt static), so the const data is only valid for the time it is called. I've seen toUtf8() miss-used in other places in the past, maybe we should do a sweep of them

File: Gems/LandscapeCanvas/Code/Source/Editor/Core/Core.h [hunk 1]
```diff
@@ -40,11 +40,11 @@ namespace LandscapeCanvas
...
-    static const QString VEGETATION_AREA_TITLE = QObject::tr("Vegetation Area");
-    static const QString TERRAIN_TITLE = QObject::tr("Terrain");
+    static const char* GRADIENT_TITLE = "Gradient";
+    static const char* GRADIENT_GENERATOR_TITLE = "Gradient";
+    static const char* GRADIENT_MODIFIER_TITLE = "Gradient Modifier";
+    static const char* VEGETATION_AREA_TITLE = "Vegetation Area";
+    static const char* TERRAIN_TITLE = "Terrain";
 
     // Connection slot labels
     static const QString PREVIEW_BOUNDS_SLOT_LABEL = QObject::tr("Preview Bounds");
```
Comment (gadams3) [inline Gems/LandscapeCanvas/Code/Source/Editor/Core/Core.h:50]: Do these also need to be updated?

**Review by gadams3 — APPROVED** [review]

File: Gems/LandscapeCanvas/Code/Source/Editor/Core/Core.h (hunk 1 above)
Comment (spham-amzn) [inline Gems/LandscapeCanvas/Code/Source/Editor/Core/Core.h:50]: Won't we run into the same problem with the rest of these static const QStrings here?

Comment (cgalvan) [reply Gems/LandscapeCanvas/Code/Source/Editor/Core/Core.h:50]: See above comment

Comment (spham-amzn) [reply Gems/LandscapeCanvas/Code/Source/Editor/Core/Core.h:50]: Since the global statics aren't taking advantage of the translation system anyways, they should also be converted to const strings to avoid the issue entirely

**Review by lawsonamzn — APPROVED** [review]
