### PR TITLE
AZ EnvironmentVariable boolean operator fixes

### LINKED ISSUE #9274: The `ModuleManager.SequentialLoadTest` test fails when run after the `ModuleManager.Test` test in debug configurations
**Describe the bug**
The `ModuleManager.SequentialLoadTest` test fails when run after the `ModuleManager.Test` test in debug configurations

**Steps to reproduce**
1. Build `AzCore.Tests` in debug on Linux
2. Execute the `ModuleManager.SequentialLoadTest` test individually, note that it passes
```
$ bin/debug/AzTestRunner bin/debug/libAzCore.Tests.so AzRunUnitTests --gtest_filter=ModuleManager.SequentialLoadTest
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ModuleManager
[ RUN      ] ModuleManager.SequentialLoadTest
[       OK ] ModuleManager.SequentialLoadTest (83 ms)
[----------] 1 test from ModuleManager (83 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (83 ms total)
[  PASSED  ] 1 test.
```
3. Execute all the `ModuleManager` tests, observe the same test now fails:
```
$ bin/debug/AzTestRunner bin/debug/libAzCore.Tests.so AzRunUnitTests --gtest_filter=ModuleManager.*
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from ModuleManager
[ RUN      ] ModuleManager.Test
[       OK ] ModuleManager.Test (84 ms)
[ RUN      ] ModuleManager.SequentialLoadTest
/home/ANT.AMAZON.COM/burelc/ws/main/Code/Framework/AzCore/./AzCore/Module/Environment.h:438: Failure
You are using an invalid variable, the owner has removed it!
pure virtual method called
terminate called without an active exception
Aborted
```

**Expected behavior**
The test always passes

**Actual behavior**
The test changes behavior depending on the previous state

**Found in Branch**
`development` at commit 98d424124c

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux
 - Version Ubuntu 20.04

**Additional context**
Callstack:
```
 thread #1, name = 'AzTestRunner', stop reason = signal SIGABRT
  * frame #0: 0x00007ffff7afd34c libc.so.6`__pthread_kill_implementation + 284
    frame #1: 0x00007ffff7ab04b8 libc.so.6`raise + 24
    frame #2: 0x00007ffff7a9a534 libc.so.6`abort + 211
    frame #3: 0x00007ffff7e147ee libstdc++.so.6`__gnu_cxx::__verbose_terminate_handler() (.cold) at vterminate.cc:95:10
    frame #4: 0x00007ffff7e20c4c libstdc++.so.6`__cxxabiv1::__terminate(void (*)()) at eh_terminate.cc:48:15
    frame #5: 0x00007ffff7e20cb9 libstdc++.so.6`std::terminate() at eh_terminate.cc:58:15
    frame #6: 0x00007ffff7e21a47 libstdc++.so.6`__cxxabiv1::__cxa_pure_virtual() at pure.cc:50:18
    frame #7: 0x00007fffeec74aef libAzCoreTestDLL.so`AZ::Module::operator new(size=72) at Module.h:36:9
    frame #8: 0x00007fffeec74059 libAzCoreTestDLL.so`::CreateModuleClass() at DLLMainTest.cpp:117:12
    frame #9: 0x00007ffff512e969 libAzCore.Tests.so`AZ::ModuleManager::LoadDynamicModule(this=0x0000555557d60278)::$_3::operator()() const at ModuleManager.cpp:499:47
    frame #10: 0x00007ffff512e7ed libAzCore.Tests.so`decltype(f=0x0000555557d60278)::$_3&>(fp)()) AZStd::Internal::INVOKE<AZ::ModuleManager::LoadDynamicModule(char const*, AZ::ModuleInitializationSteps, bool)::$_3&>(AZ::ModuleManager::LoadDynamicModule(char const*, AZ::ModuleInitializationSteps, bool)::$_3&) at invoke_traits.h:208:20
    frame #11: 0x00007ffff512e72d libAzCore.Tests.so`AZStd::invoke_result<AZ::ModuleManager::LoadDynamicModule(char const*, AZ::ModuleInitializationSteps, bool)::$_3&>::type AZStd::invoke<AZ::ModuleManager::LoadDynamicModule(f=0x0000555557d60278)::$_3&>(AZ::ModuleManager::LoadDynamicModule(char const*, AZ::ModuleInitializationSteps, bool)::$_3&) at invoke.h:55:16
    frame #12: 0x00007ffff512e6bd libAzCore.Tests.so`AZ::Outcome<void, AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::allocator> > AZStd::Internal::function_util::invoke_void_return_wrapper<AZ::Outcome<void, AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::allocator> > >::call<AZ::ModuleManager::LoadDynamicModule(args=0x0000555557d60278)::$_3&>(AZ::ModuleManager::LoadDynamicModule(char const*, AZ::ModuleInitializationSteps, bool)::$_3&) at function_template.h:31:28
    frame #13: 0x00007ffff512e5c5 libAzCore.Tests.so`AZ::Outcome<void, AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::allocator> > AZStd::Internal::function_util::get_invoker<AZ::Outcome<void, AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::allocator> > (function_obj_ptr=0x0000555557d60278), AZStd::Internal::function_util::function_obj_tag, AZStd::allocator>::call<AZ::ModuleManager::LoadDynamicModule(char const*, AZ::ModuleInitializationSteps, bool)::$_3>(AZStd::Internal::function_util::function_buffer&) at function_template.h:171:28
    frame #14: 0x00007ffff516b28c libAzCore.Tests.so`AZStd::function_intermediate<AZ::Outcome<void, AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::allocator> > >::operator(this=0x0000555557d60270)() const at function_template.h:603:16
    frame #15: 0x00007ffff5136e6d libAzCore.Tests.so`AZStd::function<AZ::Outcome<void, AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::allocator> > ()>::operator(this=0x0000555557d60270)() const at function_template.h:683:31
    frame #16: 0x00007ffff51299ba libAzCore.Tests.so`AZ::ModuleManager::LoadDynamicModule(this=0x00005555577f6390, modulePath="AzCoreTestDLL", lastStepToPerform=CreateClass, maintainReference=true) at ModuleManager.cpp:552:40
    frame #17: 0x00007ffff41f846c libAzCore.Tests.so`decltype(f=0x00007fffffffd080, arg0=0x00007fffffffce48, args=<no value available>, args=0x00007fffffffd07f, args=0x00007fffffffd07e)).*fp(InvokeTraits::forward<char const (&) [14]>(fp1), InvokeTraits::forward<AZ::ModuleInitializationSteps>(fp1), InvokeTraits::forward<bool>(fp1))) AZStd::Internal::INVOKE<AZ::Outcome<AZStd::shared_ptr<AZ::ModuleData>, AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::allocator> > (AZ::ModuleManagerRequests::*)(char const*, AZ::ModuleInitializationSteps, bool), AZ::ModuleManagerRequests*&, char const (&) [14], AZ::ModuleInitializationSteps, bool, void>(AZ::Outcome<AZStd::shared_ptr<AZ::ModuleData>, AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::allocator> > (AZ::ModuleManagerRequests::*&&)(char const*, AZ::ModuleInitializationSteps, bool), AZ::ModuleManagerRequests*&, char const (&) [14], AZ::ModuleInitializationSteps&&, bool&&) at invoke_traits.h:177:20
    frame #18: 0x00007ffff41f82b1 libAzCore.Tests.so`AZStd::invoke_result<AZ::Outcome<AZStd::shared_ptr<AZ::ModuleData>, AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::allocator> > (AZ::ModuleManagerRequests::*)(char const*, AZ::ModuleInitializationSteps, bool), AZ::ModuleManagerRequests*&, char const (&) [14], AZ::ModuleInitializationSteps, bool>::type AZStd::invoke<AZ::Outcome<AZStd::shared_ptr<AZ::ModuleData>, AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::allocator> > (f=0x00007fffffffd080, args=0x00007fffffffce48, args=<no value available>, args=0x00007fffffffd07f, args=0x00007fffffffd07e)(char const*, AZ::ModuleInitializationSteps, bool), AZ::ModuleManagerRequests*&, char const (&) [14], AZ::ModuleInitializationSteps, bool>(AZ::Outcome<AZStd::shared_ptr<AZ::ModuleData>, AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::allocator> > (AZ::ModuleManagerRequests::*&&)(char const*, AZ::ModuleInitializationSteps, bool), AZ::ModuleManagerRequests*&, char const (&) [14], AZ::ModuleInitializationSteps&&, bool&&) at invoke.h:55:16
    frame #19: 0x00007ffff41f7e83 libAzCore.Tests.so`void AZ::EBusEventProcessingPolicy::CallResult<AZ::Outcome<AZStd::shared_ptr<AZ::ModuleData>, AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::allocator> >, AZ::Outcome<AZStd::shared_ptr<AZ::ModuleData>, AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::allocator> > (AZ::ModuleManagerRequests::*)(char const*, AZ::ModuleInitializationSteps, bool), AZ::ModuleManagerRequests*&, char const (&) [14], AZ::ModuleInitializationSteps, bool>(results=0x00007fffffffd428, func=0x00007fffffffd080, iface=0x00007fffffffce48, args=<no value available>, args=0x00007fffffffd07f, args=0x00007fffffffd07e)(char const*, AZ::ModuleInitializationSteps, bool), AZ::ModuleManagerRequests*&, char const (&) [14], AZ::ModuleInitializationSteps&&, bool&&) at Policies.h:431:23
    frame #20: 0x00007ffff3ee45bf libAzCore.Tests.so`void AZ::Internal::EBusContainer<AZ::ModuleManagerRequests, AZ::ModuleManagerRequests, (AZ::EBusAddressPolicy)0, (AZ::EBusHandlerPolicy)0>::Dispatcher<AZ::EBus<AZ::ModuleManagerRequests, AZ::ModuleManagerRequests> >::BroadcastResult<AZ::Outcome<AZStd::shared_ptr<AZ::ModuleData>, AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::allocator> >, AZ::Outcome<AZStd::shared_ptr<AZ::ModuleData>, AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::allocator> > (results=0x00007fffffffd428, func=0x00007fffffffd080, args=<no value available>, args=0x00007fffffffd07f, args=0x00007fffffffd07e)(char const*, AZ::ModuleInitializationSteps, bool), char const (&) [14], AZ::ModuleInitializationSteps, bool>(AZ::Outcome<AZStd::shared_ptr<AZ::ModuleData>, AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::allocator> >&, AZ::Outcome<AZStd::shared_ptr<AZ::ModuleData>, AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::allocator> > (AZ::ModuleManagerRequests::*&&)(char const*, AZ::ModuleInitializationSteps, bool), char const (&) [14], AZ::ModuleInitializationSteps&&, bool&&) at BusContainer.h:1556:29
    frame #21: 0x00007ffff3e64e3f libAzCore.Tests.so`UnitTest::ModuleManager_SequentialLoadTest_Test::TestBody(this=0x00005555577f87f0) at Module.cpp:294:17
    frame #22: 0x00007ffff5ca48b3 libAzCore.Tests.so`void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(object=0x00005555577f87f0, method=21 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00, location="the test body")(), char const*) at gtest.cc:2501:12
    frame #23: 0x00007ffff5c86b16 libAzCore.Tests.so`testing::Test::Run(this=0x00005555577f87f0) at gtest.cc:2517:5
    frame #24: 0x00007ffff5c87878 libAzCore.Tests.so`testing::TestInfo::Run(this=0x000055555760e510) at gtest.cc:2693:11
    frame #25: 0x00007ffff5c87f3c libAzCore.Tests.so`testing::TestCase::Run(this=0x000055555760e410) at gtest.cc:2811:28
    frame #26: 0x00007ffff5c9401d libAzCore.Tests.so`testing::internal::UnitTestImpl::RunAllTests(this=0x00005555570ebf40) at gtest.cc:5177:43
    frame #27: 0x00007ffff5ca6a88 libAzCore.Tests.so`bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(object=0x00005555570ebf40, method=60 3d c9 f5 ff 7f 00 00 00 00 00 00 00 00 00 00, location="auxiliary test code (environments or event listeners)")(), char const*) at gtest.cc:2501:12
    frame #28: 0x00007ffff5c93d06 libAzCore.Tests.so`testing::UnitTest::Run(this=0x00007ffff7a67fb0) at gtest.cc:4786:10
    frame #29: 0x00007ffff4b86582 libAzCore.Tests.so`RUN_ALL_TESTS() at gtest.h:2341:46
    frame #30: 0x00007ffff4b55025 libAzCore.Tests.so`::AzRunUnitTests(argc=1, argv=0x00007fffffffe718) at Main.cpp:16:1
    frame #31: 0x0000555556759e09 AzTestRunner`FunctionHandle::operator(this=0x00005555576ad5f0, argc=2, argv=0x00007fffffffe718)(int, char**) at Platform_Linux.cpp:80:16
    frame #32: 0x000055555563f74a AzTestRunner`AzTestRunner::wrapped_command_arg_main(argc=2, argv=0x00007fffffffe718) at main.cpp:166:22
    frame #33: 0x000055555563fa07 AzTestRunner`AzTestRunner::wrapped_main(argc=4, argv=0x00007fffffffe718) at main.cpp:196:20
    frame #34: 0x000055555563fa6f AzTestRunner`main(argc=4, argv=0x00007fffffffe718) at platform_host_main.cpp:15:18
    frame #35: 0x00007ffff7a9b310 libc.so.6`__libc_start_call_main + 128
    frame #36: 0x00007ffff7a9b3c1 libc.so.6`__libc_start_main@@GLIBC_2.34 + 129
    frame #37: 0x000055555563efc5 AzTestRunner`_start + 37
```

### PR DESCRIPTION
**Pull request by lumberyard-employee-dm**
Updated the EnvironmentVariable class boolean checks.

The `operator bool` and `operator!` now check if the EnvironmentVariableHolderType type is non-nullptr and is in a constructed state.

This makes it consistent with the `operator*` and `operator->` methods and allows the construct as follows to always work
```
if (environmentVariable)
{
   auto value = *environmentVariable;
}
```

Also removed the `Construct` environment variable class as it allows invoking the constructor over an already constructed value stored in the EnvironmentVariableHolder.

The `Construct` function itself required the EnvironmentVariable to be in a very specific state where the EnvironmentVariable has been constructed before and the destroyed in order to use safely.

The function that should be used to re-create an environment variable is the `AZ::Environment::CreateVariable` function.

fixes #9274 

Also updated the AzCore Serialization and Streamer test to write out the a temporary directory instead of the current working directory to prevent pollution of test files within the user's working directory.

### CODE REVIEW

File: Gems/WhiteBox/Code/Tests/WhiteBoxPhysicsTest.cpp [hunk 1]
```diff
@@ -47,7 +47,7 @@ namespace UnitTest
 
     void EditorWhiteBoxPhysicsTestEnvironment::AddGemsAndComponents()
     {
-        AddDynamicModulePaths({"PhysX.Editor.Gem"});
+        AddDynamicModulePaths({"PhysX.Editor"});
```
Comment (amzn-sj) [inline Gems/WhiteBox/Code/Tests/WhiteBoxPhysicsTest.cpp:50]: The [output name](https://github.com/o3de/o3de/blob/7b659cd0fbf274254ab19d658840b98ae17b6228/Gems/PhysX/Code/CMakeLists.txt#L126) for this gem is `PhysX.Editor.Gem`. This was needed for the client gem module because on some platforms, the name of the 3rdParty lib and the gem lib ended up being the same. It's not needed for tools but it looks like it was updated anyway.

**Review by amzn-phist — APPROVED** [review]

File: Gems/WhiteBox/Code/Tests/WhiteBoxPhysicsTest.cpp (hunk 1 above)
Comment (lumberyard-employee-dm) [reply Gems/WhiteBox/Code/Tests/WhiteBoxPhysicsTest.cpp:50]: I'll change it back.
It actually is trying to load the PhysX.Editor.Gem.dll file during the test.

**Review by amzn-sj — APPROVED** [review]
