### PR TITLE
Table view and Thumbnail view fixes

### LINKED ISSUE #15168: No context menu in table view
**Describe the bug**
When right clicking an asset in the thumbnail view, no context menu is populated

**Steps to reproduce**
1. Open the WIP Asset Browser
2. Go to the table view
3. Right click on any asset

**Expected behavior**
Context menu with appropriate actions populates

**Actual behavior**
Nothing happens

### LINKED ISSUE #15169: Hotkeys don't work in table view
**Describe the bug**
Rename/Delete/Duplicate hotkeys do not work in the table view

**Steps to reproduce**
1. Open WIP Asset Browser
2. Go to table view
3. Select an asset
4. Press F2, Ctrl + D, or Del

**Expected behavior**
Asset prompts for rename, is deleted or duplicated

**Actual behavior**
Nothing happens

### LINKED ISSUE #15170: Table view and thumbnail view double click doesn't work
**Describe the bug**
Double clicking an asset in the table view and thumbnail view does not open the asset.
Double clicking a folder in table view does not navigate to that folder.

**Steps to reproduce**
1. Open the WIP Asset Browser
2. Go to table view or thumbnail view
3. Double click on an asset

**Expected behavior**
If it's a folder in table view, expected to navigate to that folder. If it's an asset in either view, expected to open that asset

**Actual behavior**
Nothing happens

### LINKED ISSUE #15171: Engine or project folder can be modified via Asset Browser
**Describe the bug**
There is an option in the Asset Browser to either rename or delete any folder, including the Engine and Project folders as well, both of which cause disruptions in Editor's functionality.

This issue occurs both on Windows and Linux, as well as both Stabilization/2305 and Development.

**Steps to reproduce**
1. Open the Editor.
2. Right click on the registered Engine or Project folder.
3. Attempt to rename or delete the folder in the Asset Browser.

**Expected behavior**
Deleting or renaming the Engine or project specific folders isn't possible.

**Actual behavior**
Attempting to rename the folder causes the Editor to freeze or Asset Processor to crash.
Deleting the folder causes disruptions in the Engine functionality.

**Screenshots/Video**
[Video](https://user-images.githubusercontent.com/110163473/225914622-54ac80e7-d291-4584-bd82-370e702d8e1a.mp4)

**Found in Branch**
Stabilization/2305

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
db92736

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 11 21H2
- CPU: I7-11700f
- GPU: Geforce RTX3070 MSI
- Memory: 32GB

### LINKED ISSUE #15204: Table view and thumbnail view are initialized to the wrong directory
**Describe the bug**
The table view and thumbnail view display the wrong directory folder if there is already a selection in the tree view.

**Steps to reproduce**
1. Select an item in the asset browser
2. Enable the WIP Asset Browser

**Expected behavior**
The assets displayed in the thumbnail / table view are the currently selected assets

**Actual behavior**
The assets from the automated testing folder are selected

### PR DESCRIPTION
**Pull request by dtamkin1**
## What does this PR do?

Adds the following features to the table view:
- Right click on an asset or empty space for a context menu popup
- Delete, Rename, Move, and Duplicate actions
- F2 / Del / Ctrl + D hotkeys to trigger the above actions
- Double on a folder to open that folder, double click on an asset to open that asset
- Prompt the user to rename a newly created asset

Adds the following fixes to the thumbnail view:
- Double click on an asset to open that asset
- View is initialized to the correct directory

Misc:
-  No longer able to modify the engine folder or the project folder
- Select the first folder in the tree view if there is currently no selected folder

Fixes #15168 
Fixes #15169 
Fixes #15170 
Fixes #15171 
Fixes #15204 

Editor_97obqU05Uy

## How was this PR tested?

Locally

### CODE REVIEW

File: Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.cpp [hunk 1]
```diff
@@ -31,16 +31,44 @@ namespace AzQtComponents
...
         m_showSearchResultsMode = searchMode;
     }
 
+    void AssetFolderTableView::mousePressEvent(QMouseEvent* event)
+    {
+        const auto p = event->pos();
+        if (auto idx = indexAt(p); !idx.isValid())
+        {
+            selectionModel()->clear();
+            return;
```
Comment (alexmontAmazon) [inline Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.cpp:49]: nit: this is a bit small for an early return, can you just make the TableView::mousePressEvent(event) an else clause and remove the return?

File: Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.cpp [hunk 2]
```diff
@@ -31,16 +31,44 @@ namespace AzQtComponents
...
+    }
+
+    void AssetFolderTableView::mouseDoubleClickEvent(QMouseEvent* event)
+    {
+        const auto p = event->pos();
+        if (auto idx = indexAt(p); idx.isValid())
+        {
+            selectionModel()->select(idx, QItemSelectionModel::SelectionFlag::ClearAndSelect);
+            emit doubleClicked(idx);
+            return;
```
Comment (alexmontAmazon) [inline Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.cpp:61]: don't need this...

File: Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.cpp [hunk 3]
```diff
@@ -31,16 +31,44 @@ namespace AzQtComponents
...
+        }
+    }
+
+    void AssetFolderTableView::contextMenuEvent(QContextMenuEvent* event)
+    {
+        const auto p = event->pos();
+        emit tableContextMenu(indexAt(p));
+        return;
```
Comment (alexmontAmazon) [inline Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.cpp:69]: or this...

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserExpandedTableView.cpp [hunk 4]
```diff
@@ -69,13 +180,121 @@ namespace AzToolsFramework
...
         {
             return m_expandedTableViewWidget;
         }
 
+         void AssetBrowserExpandedTableView::SetName(const QString& name)
+        {
+            m_name = name;
+        }
+
+        QString& AssetBrowserExpandedTableView::GetName()
```
Comment (alexmontAmazon) [inline Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserExpandedTableView.cpp:205]: could be const

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserExpandedTableView.cpp [hunk 5]
```diff
@@ -69,13 +180,121 @@ namespace AzToolsFramework
...
+        {
+            return m_name;
+        }
+
+        void AssetBrowserExpandedTableView::SetIsAssetBrowserMainView()
+        {
+            SetName(ExpandedTableViewMainViewName);
+        }
+
+        bool AssetBrowserExpandedTableView::GetIsAssetBrowserMainView()
```
Comment (alexmontAmazon) [inline Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserExpandedTableView.cpp:215]: const

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserExpandedTableView.cpp [hunk 6]
```diff
@@ -69,13 +180,121 @@ namespace AzToolsFramework
...
+        {
+            return GetName() == ExpandedTableViewMainViewName;
+        }
+
+        void AssetBrowserExpandedTableView::SetExpandedTableViewActive(bool isActiveView)
+        {
+            m_isActiveView = isActiveView;
+        }
+
+        bool AssetBrowserExpandedTableView::GetExpandedTableViewActive()
```
Comment (alexmontAmazon) [inline Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserExpandedTableView.cpp:225]: const

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserExpandedTableView.h [hunk 7]
```diff
@@ -33,11 +34,16 @@ namespace AzToolsFramework
...
+            Q_OBJECT
         public:
             AZ_CLASS_ALLOCATOR(ExpandedTableViewDelegate, AZ::SystemAllocator);
             ExpandedTableViewDelegate(QWidget* parent = nullptr);
 
             void paint(QPainter* painter, const QStyleOptionViewItem& option, const QModelIndex& index) const override;
+            QWidget* createEditor(QWidget* parent, const QStyleOptionViewItem& option, const QModelIndex& index) const override;
+
+        signals:
+            void renameTableEntry(const QString& value) const;
```
Comment (alexmontAmazon) [inline Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserExpandedTableView.h:46]: hmmm... I guess a signal is const, but we don't usually do this by convention. I'm surprised this compiles, since Qt's MOC is what actually generates this funciton, and I doubt it adds the const qualifier...

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserViewUtils.cpp [hunk 8]
```diff
@@ -197,6 +203,13 @@ namespace AzToolsFramework
             return QDir(path.data()).entryList(QDir::NoDotAndDotDot | QDir::AllEntries).isEmpty();
         }
 
+        bool AssetBrowserViewUtils::IsEngineOrProjectFolder(AZStd::string_view path)
```
Comment (alexmontAmazon) [inline Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserViewUtils.cpp:206]: I think this could be const

File: Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.cpp (hunk 1 above)
Comment (dtamkin1) [reply Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.cpp:49]: done!

File: Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.cpp (hunk 2 above)
Comment (dtamkin1) [reply Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.cpp:61]: Well the default double click behavior for this table view tries to edit the asset in whatever column was clicked on, which is why I'm overriding it and just emitting the double click signal

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserExpandedTableView.h (hunk 7 above)
Comment (dtamkin1) [reply Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserExpandedTableView.h:46]: Sounds good, will remove the const

**Review by cgalvan — APPROVED** [review]

File: Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.cpp (hunk 2 above)
Comment (alexmontAmazon) [reply Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.cpp:64]: sorry, I meant, don't need this return statement which is at the bottom of the function.

File: Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.cpp (hunk 3 above)
Comment (alexmontAmazon) [reply Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.cpp]: again, sorry, I was unclear. I meant, you don't need a return statement at the bottom of a function.

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserViewUtils.cpp (hunk 8 above)
Comment (alexmontAmazon) [reply Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserViewUtils.cpp:206]: ahh yes, didn't realize it was static. Please disregard...
