### PR TITLE
Fixed Name::SetNameLiteral on Android

### LINKED ISSUE #10608: [Android] Name assert: Attempted to construct name literal on a different thread from the first initialized static name
**Describe the bug**
Launching a default level on Android the following error appears in the log:

````
2022-07-11 11:46:33.148 6521-6560/org.o3de.OpenXRTest I/System: Trace::Assert
     E:/Amazon/GitHub/o3de/Code/Framework/AzCore/AzCore/Name/Name.cpp(207): (517333306544) 'void AZ::Name::SetNameLiteral(AZStd::string_view)'
2022-07-11 11:46:33.148 6521-6560/org.o3de.OpenXRTest I/System: Attempted to construct name literal on a different thread from the first initialized static name, this is unsafe
````

After modifying the assert to print more information, it indicated it's the name **"-fixed name dictionary deferred head-"** what has issues with:

````
2022-07-11 11:46:33.148 6521-6560/org.o3de.OpenXRTest I/System: Trace::Assert
     E:/Amazon/GitHub/o3de/Code/Framework/AzCore/AzCore/Name/Name.cpp(207): (517333306544) 'void AZ::Name::SetNameLiteral(AZStd::string_view)'
2022-07-11 11:46:33.148 6521-6560/org.o3de.OpenXRTest I/System: Attempted to construct name literal '-fixed name dictionary deferred head-' on a different thread (517333306544) from the first initialized static name (532865967360), this is unsafe
````

**Steps to reproduce**
1. Run default level on Android

**Expected behavior**
No asserts happen when running a default level on Android

**Actual behavior**
The name **"-fixed name dictionary deferred head-"** causes an assert because it's being initialized from different threads.

**Found in Branch**
Development 5801ff7ad1beca136eb28a16ce90bd16694d2a80

**Desktop/Device (please complete the following information):**
 - Device: [Samsung] 
 - OS: [Android]
 - Version [12]

### PR DESCRIPTION
**Pull request by moraaar**
Signed-off-by: moraaar <moraaar@amazon.com>

## What does this PR do?

Fixes #10608

Sets `native_thread_invalid_id` to 0 to match the same invalid value as linux.

What was happening is that due to the way the variables were initialized `s_staticNameListThread` arrived with value 0 and it wasn't the same as `native_thread_invalid_id` (value used by `AZStd::thread::id` in its default constructor), so it never got to assign `s_staticNameListThread` to the current thread id.

## How was this PR tested?

Build and run default level on pc and android without crashing.

### CODE REVIEW

**Review by amzn-phist — APPROVED** [review]
LGTM.  I don't understand why it would use `LONG_MIN` as a default thread id if Linux was also 0.  Maybe someone else knows more.

File: Code/Framework/AzCore/AzCore/Name/Name.cpp [hunk 1]
```diff
@@ -19,7 +19,10 @@
 
 namespace AZ
 {
-    AZStd::thread::id Name::s_staticNameListThread{};
+    static const AZStd::thread::id InvalidThreadId;
```
Comment (lumberyard-employee-dm) [inline Code/Framework/AzCore/AzCore/Name/Name.cpp:22]: This constant is not needed.
The code just can compare against `AZStd::thread::id{}`

File: Code/Framework/AzCore/AzCore/Name/Name.cpp [hunk 2]
```diff
@@ -224,11 +227,15 @@ namespace AZ
...
+
+        if (s_staticNameListThread == InvalidThreadId)
         {
-            s_staticNameListThread = AZStd::this_thread::get_id();
+            s_staticNameListThread = thisThreadId;
         }
-        AZ_Assert(s_staticNameListThread == AZStd::this_thread::get_id(), "Attempted to construct a name literal on a different thread from the first initialized static name, this is unsafe");
+        AZ_Assert(s_staticNameListThread == thisThreadId,
+                  "Attempted to construct name literal '%.*s' on a different thread from the first initialized static name, this is unsafe",
+                  AZ_STRING_ARG(name));
```
Comment (lumberyard-employee-dm) [inline Code/Framework/AzCore/AzCore/Name/Name.cpp:238]: This assert should removed.
This makes it so that SetNameLiteral asserts if it is ever called on a thread that isn't the main one.
It is perfectly valid to link Names to a linked list on other threads

Comment (moraaar) [reply Code/Framework/AzCore/AzCore/Name/Name.cpp:238]: ok, I'll remove it then.

File: Code/Framework/AzCore/AzCore/Name/Name.cpp (hunk 1 above)
Comment (lumberyard-employee-dm) [reply Code/Framework/AzCore/AzCore/Name/Name.cpp:22]: Ok, then can you move it to the SetNameLiteral function and make it constexpr?

File: Code/Framework/AzCore/AzCore/Name/Name.cpp (hunk 2 above)
Comment (moraaar) [reply Code/Framework/AzCore/AzCore/Name/Name.cpp:238]: Actually, `s_staticNameListThread` was only used for this, so it can be removed altogether.

File: Code/Framework/AzCore/AzCore/Name/Name.cpp (hunk 1 above)
Comment (moraaar) [reply Code/Framework/AzCore/AzCore/Name/Name.cpp:22]: I've removed the variable since `s_staticNameListThread` was removed too.

**Review by lumberyard-employee-dm — APPROVED** [review]
Changes look good
