### PR TITLE
Action Manager | Introduce expander menu for toolbars

### LINKED ISSUE #15351: Double right arrow button `>>` on the Viewport Toolbar is not functional
**Describe the bug**
When the Editor window is not Maximized and the User shrinks the Viewport Toolbar horizontally, some menus are hidden and a double right arrow button (>>) appears, but it is not functional. Making the menus inaccessible in a smaller Editor window.
This issue occurs on Stabilization and Development branches on Windows and Linux.

**Steps to reproduce**
1. Launch the O3DE Editor.
2. If the Editor window is maximized, restore it.
3. Shrink the Editor window horizontally so the `>>` button appears on the Viewport Toolbar.
4. Press the `>>` button.

**Expected behavior**
A dropdown menu appears.

**Actual behavior**
The button in not functional.

**Screenshots/Video**

https://user-images.githubusercontent.com/99716227/227493081-37058e1a-d9cb-4a6d-9ebf-a84d9d240c67.mp4

**Found in Branch**
Stabilization

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
 (f7f388f)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 11
 - CPU AMD Ryzen 5 5600H
 - GPU NVIDIA GeForce RTX 3070 Laptop GPU
 - Memory 16GB

### PR DESCRIPTION
**Pull request by AMZN-daimini**
## What does this PR do?

Fixes #15351

Fixes the expander menu for collapsed toolbars so that it correctly shows the hidden toolbar items.

## How was this PR tested?

Manual testing.

Before (no menu is shown)
image

After
image

### CODE REVIEW

File: Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ToolBar/EditorToolBar.cpp [hunk 1]
```diff
@@ -13,14 +13,110 @@
...
+                            if (auto widgetAction = qobject_cast<QWidgetAction*>(action))
+                            {
+                                if (auto toolButton = qobject_cast<QToolButton*>(widgetAction->defaultWidget());
+                                    toolButton && toolButton->menu())
+                                {
+                                    menu->addMenu(s_menuManagerInternalInterface->GetMenu(action->objectName().toStdString().c_str()));
+                                }
+                                else
+                                {
+                                    if (QWidget* widget = s_actionManagerInternalInterface->GenerateWidgetFromWidgetAction(
```
Comment (hultonha) [inline Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ToolBar/EditorToolBar.cpp:81]: suggestion: Maybe could also move some of this logic to a separate function (again to help with the nesting)

File: Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ToolBar/EditorToolBar.h [hunk 2]
```diff
@@ -31,6 +33,22 @@ namespace AzToolsFramework
     class MenuManagerInternalInterface;
     class ToolBarManagerInterface;
 
+    class ToolBarExpanderWatcher : public QObject
+    {
+    public:
+        ToolBarExpanderWatcher(QObject* parent);
```
Comment (hultonha) [inline Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ToolBar/EditorToolBar.h:39]: update: Please add `explicit` to avoid implicit conversions

**Review by hultonha — COMMENTED** [review]
Overall looks good, but I do think the `eventFilter` function could be simplified a bit, it does look quite complicated to me. It might be tricky to do but just thought it might be worth another look before we merge. Thanks!

File: Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ToolBar/EditorToolBar.cpp [hunk 3]
```diff
@@ -13,14 +13,110 @@
...
+                    auto parentWidget = new QWidget();
+
+                    for (auto action : toolbar->actions())
+                    {
+                        if (!toolbar->widgetForAction(action)->isVisible())
+                        {
+                            if (auto widgetAction = qobject_cast<QWidgetAction*>(action))
+                            {
+                                if (auto toolButton = qobject_cast<QToolButton*>(widgetAction->defaultWidget());
+                                    toolButton && toolButton->menu())
```
[the remark this answers is not in the document]
Comment (AMZN-daimini) [reply Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ToolBar/EditorToolBar.cpp:75]: Did an early out.

File: Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ToolBar/EditorToolBar.cpp (hunk 1 above)
Comment (AMZN-daimini) [reply Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ToolBar/EditorToolBar.cpp:81]: I tried to adjust the nesting a little bit, but I wanted to avoid additional functions if possible. It should be more readable now tho.

File: Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ToolBar/EditorToolBar.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (hultonha) [reply Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ToolBar/EditorToolBar.cpp]: Nice one thanks!

File: Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ToolBar/EditorToolBar.cpp (hunk 1 above)
Comment (hultonha) [reply Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ToolBar/EditorToolBar.cpp]: Okay understood, thanks for having another look at it 👍

**Review by hultonha — APPROVED** [review]
