### PR TITLE
Action Manager | Change initialization timing to properly work in automation tests

### LINKED ISSUE #12930: Action Manager: Python tests run before Action Manager is properly setup
**Describe the bug**
Python tests run before Action Manager is properly setup. This results in test failures for tests that validate menu options are present. At the time the tests run, the only menu item available is the AWS menu, which doesn't appear to have been converted for use with the new Action Manager.

**Steps to reproduce**
1. Update your AutomatedTesting\Registry\editorpreferences.setreg file to include the following under O3DE:
```
		"ActionManager": {
			"EnableNewActionManager": true
		}
```
2. Run the main Editor test suite:
```
python.cmd -m pytest [Path to AutomatedTesting]/Gem/PythonTests/editor/TestSuite_Main.py --build-directory [Path to build directory]
```

**Expected behavior**
Menu tests run successfully, or at least get further than they currently do with the ActionManager enabled.

**Actual behavior**
Tests fail fast due to the Menus they search for not being found when the ActionManager is active.

```
E   [editor_test.log]  <12:45:19> (python_test) - QAction not found for main menu item 'Edit'
```

**Found in Branch**
development@ 7e843fd1708f78a763754f7e319182a1832b5094

### PR DESCRIPTION
**Pull request by AMZN-daimini**
## What does this PR do?

Fixes #12930

Moves timing of initialization hooks for the Action Manager earlier in the process to make sure they're triggered before python tests execution.

### CODE REVIEW

**Review by jckand-amzn — APPROVED** [review]

File: Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ActionManagerSystemComponent.cpp [hunk 1]
```diff
@@ -77,7 +77,7 @@ namespace AzToolsFramework
     {
     }
 
-    void ActionManagerSystemComponent::NotifyEditorInitialized()
+    void ActionManagerSystemComponent::NotifyMainWindowInitialized(QMainWindow* /* mainWindow */)
```
Comment (hultonha) [inline Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ActionManagerSystemComponent.cpp:80]: nit/suggestion: Prefer `[[maybe_unused]]` here for parameter

**Review by hultonha — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]
