### PR TITLE
EMotionFX: Resetting motion sets is not registered in the Motions pane which may lead to a crash

### LINKED ISSUE #3761: EMotionFX: Resetting motion sets is not registered in the Motions pane which may lead to a crash
**Describe the bug**
It has been noticed that resetting motion sets is incorrectly registered in the Motions pane. Motions related to the reset motion set are still visible but cannot be interacted with. New motions can be loaded and added to the non-existing motion set which results in a crash.
Please note that switching between the panes updates the reset status and the issue does not occur afterwards.

**To Reproduce**
1. Open the Animation Editor.
2. Add the Cowboy's motion set.
3. Navigate to the Motions pane.
4. Navigate to *File > Reset* and only select **Motion Sets**.
5. Load a different motion in the Motions pane.
6. Press RMB on the loaded motion and select **Add to selected Motion Sets**.

**Expected behavior**
Motions related to the reset motion set are still active.
It is not possible to add any motions to the non-existing motion sets.

**Call Stack Trace:**
```
25) 00007FFEF5B8C247 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FFEF8135270 (ntdll) : memset
23) 00007FFEF811C776 (ntdll) : _C_specific_handler
22) 00007FFEF813217F (ntdll) : _chkstk
21) 00007FFEF80E1454 (ntdll) : RtlRaiseException
20) 00007FFEF8130CAE (ntdll) : KiUserExceptionDispatcher
19) 00007FFEF80BFAAD (ntdll) : RtlEnterCriticalSection
18) C:\O3DE\o3de\Gems\EMotionFX\Code\EMotionFX\Source\MotionSet.cpp (286) : EMotionFX::MotionSet::BuildIdStringList
17) C:\O3DE\o3de\Gems\EMotionFX\Code\EMotionFX\Tools\EMotionStudio\Plugins\StandardPlugins\Source\MotionWindow\MotionListWindow.cpp (628) : EMStudio::MotionListWindow::OnAddMotionsInSelectedMotionSets
16) 00007FFEB1DB0DB9 (Qt5Core) : QObject::qt_static_metacall
15) 00007FFEB3B45DCF (Qt5Widgets) : QAction::activate
14) 00007FFEB3C9C698 (Qt5Widgets) : QMenu::actionGeometry
13) 00007FFEB3C9C473 (Qt5Widgets) : QMenu::actionGeometry
12) 00007FFEB3CA1C51 (Qt5Widgets) : QMenu::mouseReleaseEvent
11) 00007FFEB3B77B02 (Qt5Widgets) : QWidget::event
10) 00007FFEB3C9DC37 (Qt5Widgets) : QMenu::event
 9) 00007FFEB3B549B0 (Qt5Widgets) : QApplicationPrivate::notify_helper
 8) 00007FFEB3B528D0 (Qt5Widgets) : QApplication::notify
 7) 00007FFEB1D91B4A (Qt5Core) : QCoreApplication::notifyInternal2
 6) 00007FFEB3B55BC5 (Qt5Widgets) : QApplicationPrivate::sendMouseEvent
 5) 00007FFEB3BA024A (Qt5Widgets) : QSizePolicy::QSizePolicy
 4) 00007FFEB3B9E80E (Qt5Widgets) : QSizePolicy::QSizePolicy
 3) 00007FFEB3B549B0 (Qt5Widgets) : QApplicationPrivate::notify_helper
 2) 00007FFEB3B53A33 (Qt5Widgets) : QApplication::notify
 1) 00007FFEB1D91B4A (Qt5Core) : QCoreApplication::notifyInternal2
```

**Desktop/Device:**
Device: PC
OS: Windows
Version 10
CPU Intel I5-9600k
GPU RTX 2060
Memory 16GB

**Additional context**

https://user-images.githubusercontent.com/86952009/131502837-a4c5400a-ad48-4621-97e9-b9d76c8836c3.mp4

[error.log](https://github.com/o3de/o3de/files/7083915/error.log)
[Editor.log](https://github.com/o3de/o3de/files/7083916/Editor.log)
[error_2.zip](https://github.com/o3de/o3de/files/7083927/error_2.zip)

### PR DESCRIPTION
**Pull request by amzn-jillich**
Remove motion set callback was missing and the window wasn't updated in case it was hidden.

Resolves #3761

Signed-off-by: Benjamin Jillich <jillich@amazon.com>

### CODE REVIEW

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetsWindowPlugin.cpp [hunk 1]
```diff
@@ -139,20 +135,20 @@ namespace EMStudio
...
     {
-        GetCommandManager()->RemoveCommandCallback(m_createMotionSetCallback, false);
-        GetCommandManager()->RemoveCommandCallback(m_reinitCallback, false);
+        for (MCore::Command::Callback* callback : m_callbacks)
+        {
+            GetCommandManager()->RemoveCommandCallback(callback, false);
+            delete callback;
+        }
+
         GetCommandManager()->RemoveCommandCallback(m_adjustMotionSetCallback, false);
```
Comment (amzn-rhhong) [inline Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetsWindowPlugin.cpp:146]: Is it too much to ask to put other callback also in the m_callbacks array for consistency?

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetsWindowPlugin.cpp [hunk 2]
```diff
@@ -393,12 +393,7 @@ namespace EMStudio
         }
 
         MotionSetsWindowPlugin* motionSetsPlugin = (MotionSetsWindowPlugin*)plugin;
-
-        // is the plugin visible? only update it if it is visible
-        if (motionSetsPlugin->GetDockWidget()->visibleRegion().isEmpty() == false)
```
Comment (amzn-rhhong) [inline Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetsWindowPlugin.cpp:398]: what's wrong with this logic

**Review by lsemp3d — APPROVED** [review]

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetsWindowPlugin.cpp (hunk 1 above)
Comment (amzn-jillich) [reply Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetsWindowPlugin.cpp:146]: Will change, good call.

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetsWindowPlugin.cpp (hunk 2 above)
Comment (amzn-jillich) [reply Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetsWindowPlugin.cpp:398]: There would be no problem with it, in case the selection model is clearly separated from the plugin/UI and could be separately updated. This is not the case though and the context menu in the motions window is relying on a fully up to date selection model in the motion set plugin. In case the motion set window is hidden while a motion set gets removed, the selection model would be invalid and that's why the incorrect context menu appears and leads to the reported crash.

The long-term solution is to separate the selection model but that is out of scope for the bug fix and we should reiterate on that thought after we removed the motion plugin (which will hopefully be happening in the shorter-/mid-term).

**Review by amzn-rhhong — APPROVED** [review]
