### PR TITLE
Animation Editor: Creating Motion Sets does not increment them correctly

### LINKED ISSUE #4111: Animation Editor: Creating Motion Sets does not increment them correctly
**Describe the bug**

Creating Motion Sets via the "+" button does not increment them correctly. Clicking the button creates every second Motion Set. If the user deselects a newly created Motion Set and then clicks the "+" button or uses _RMB -> Add Motion Set_, the Motion Sets are created correctly.

Please refer to the attached video for more information.

**To Reproduce**

1. Open the Animation Editor.
2. Go to the Motion Sets tab.
3. Click on the "+" button several times.

**Expected behavior**
Motion Sets are incremented correctly in all circumstances.

**Desktop/Device:**

- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16 GB

https://user-images.githubusercontent.com/86952318/133241622-3367efe6-e8c1-4c45-b83a-af0eea681b6a.mp4

### PR DESCRIPTION
**Pull request by amzn-jillich**
Resolves #4111

Signed-off-by: Benjamin Jillich <jillich@amazon.com>

### CODE REVIEW

File: Gems/EMotionFX/Code/EMotionFX/Source/MotionSet.cpp [hunk 1]
```diff
@@ -726,10 +726,15 @@ namespace EMotionFX
...
+        for (const MotionSet* motionSet : m_childSets)
         {
-            return total + motionSet->GetIsOwnedByRuntime();
-        });
+            if (!motionSet->GetIsOwnedByRuntime())
+            {
+                ++childSetSize;
+            }
+        }
+        return childSetSize;
```
Comment (burelc-amzn) [inline Gems/EMotionFX/Code/EMotionFX/Source/MotionSet.cpp:737]: As far as I can tell, these two implementations of this method should produce identical output.
https://godbolt.org/z/3467n15Pr

Can you explain how the old version is incorrect? Are there other uses of `std::accumulate` that we need to update?

Comment (amzn-rhhong) [reply Gems/EMotionFX/Code/EMotionFX/Source/MotionSet.cpp:737]: is it always safe to add a size_t to a boolean value?

Comment (amzn-jillich) [reply Gems/EMotionFX/Code/EMotionFX/Source/MotionSet.cpp]: Checked into it: The issue wasn't the accumulate, but a missing "!" which increased the value in wrong cases. I've still converted back to the old loop but used the add rather than the if, as this results in less code and is simple.

**Review by burelc-amzn — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]
