### PR TITLE
Fix IsSubFolder not validating partial is a folder

### LINKED ISSUE #11712: Asset Processor does not detect changes in external gems
**Describe the bug**
The Asset Processor does not automatically detect changes made in external gems.  It does detect them if a full rescan is performed and it does automatically detect changes in the project and core gems folders.

The setup for my use-case is a little unusual in that I have a Gem group with Gem's inside (like Atom)
```
d:\o3de-multiplayersample-assets\Gems\
    gem.json <-- group gem.json has external_subdirectory entries for gem subdirs
    character_mps\
        gem.json
        Assets\ <-- AP does not detect changes
        Registry\assetprocessor_settings.setreg
    kb3d_mps\
        Assets\ <-- AP does not detect changes
        Registry\assetprocessor_settings.setreg  
```
But I have both the Gem group and `character_mps` Gem paths registered as `external_subdirectories` in the `o3de_manifest.json` and changes are detected with a full rescan.

The `gem.json` for the group gem looks like this
```json
{
    "gem_name": "MPSGems",
    "display_name": "MPS Gems",
    "license": "Apache-2.0 Or MIT",
    "license_url": "https://github.com/o3de/o3de/blob/development/LICENSE.txt",
    "origin": "Open 3D Engine - o3de.org",
    "origin_url": "https://github.com/o3de/o3de-multiplayersample-assets",
    "type": "Code",
    "summary": "Provides multiple gems for the Multiplayer Sample",
    "canonical_tags": [
        "Gem"
    ],
    "user_tags": [
        "Multiplayer"
    ],
    "requirements": "",
    "documentation_url": "",
    "external_subdirectories": [
        "character_mps",
        "kb3d_mps",
        "landscape_mps",
        "level_art_mps",
        "particlefx_mps",
        "pbr_material_pack_mps",
        "props_mps"
    ],
    "dependencies": [
        "character_mps",
        "kb3d_mps",
        "landscape_mps",
        "level_art_mps",
        "particlefx_mps",
        "pbr_material_pack_mps",
        "props_mps"
    ]
}
```

**Steps to reproduce**
1. Open the Editor for a project that has an external Gem with an Assets folder
2. Open the Asset Processor
3. Add an .fbx asset to the external Gem's Asset folder

**Expected behavior**
The asset is picked up by the Asset Processor and processed

**Actual behavior**
The asset is not detected, nor are changes to existing assets detected in the external gem

**Screenshots/Video**
image

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by AMZN-alexpete**
Signed-off-by: Alex Peterson <26804013+AMZN-alexpete@users.noreply.github.com>

## What does this PR do?

Fixes #11712 which is an issue where assets in external gem folders were not being watched for changes by the Asset Processor. This was a result of faulty logic in the Asset Processor that incorrectly assumed those folders were subfolders of the project.

Specifically, `IsSubFolder` considered `C:\o3de-multiplayersample-assets\gems\somegem` to be a subdirectory of `C:\o3de-multiplayersample`

This change also adds a unit test

I chose not to use `AZ::IO::Path` to avoid the cost of extra allocations converting `QStrings` to `AZ::IO::Path` (or similar) types.  `IsSubFolder` is called on every detected change for both folders and files, not just when adding watch folders.
 
## How was this PR tested?

1. Created a unit test
1. Verified changes in folders that were previously ignored were watched by Asset Processor and that additions/changes and deletions were detected.

### CODE REVIEW

File: Code/Tools/AssetProcessor/native/FileWatcher/FileWatcher.cpp [hunk 1]
```diff
@@ -30,6 +30,15 @@ static bool IsSubfolder(const QString& folderA, const QString& folderB)
         return c == AZ::IO::WindowsPathSeparator || c == AZ::IO::PosixPathSeparator;
     };
 
+    // if folderB doesn't end in a slash, make sure folderA has one at the appropriate location to
+    // avoid matching a partial path that isn't a folder e.g.
+    // folderA = c:/folderWithLongerName
+    // folderB = c:/folder
+    if (!isSlash(folderB[folderB.length() - 1]) && !isSlash(folderA[folderB.length()]))
```
Comment (tkothadev) [inline Code/Tools/AssetProcessor/native/FileWatcher/FileWatcher.cpp:37]: is this only forward slash or also backward slash?

**Review by cgalvan — APPROVED** [review]

**Review by AMZN-stankowi — APPROVED** [review]
