### PR TITLE
fix for #9829 (inertia tensor getting inverted incorrectly)

### LINKED ISSUE #9829: Bug Report: The PhysX rigid body UI component falsely computes the inverse of the inertia
**Describe the bug**
The PhysX rigid body UI component falsely computes the inverse of the inertia that is provided by the user. It might be that the inverse is shown to the UI, but internally the correct value is stored

**Steps to reproduce**
1. Launch the O3DE editor
2. Add a mesh component e.g. a cyilinder 
3. Add a PhysX rigid body component e.g. a 
4. Add a hinge joint between the entity and its parent
5. Deselect the 'compute mass' property from the rigid body component's menu
6. Deselect the 'compute CoM' property from the rigid body component's menu
7. Deselect the 'compute inertia' property
8. Try to add a small value in the X-inertia box e.g. 0.0005.  
9. The UI will automatically compute the inverse of the inertia e.g. 1/0.0005 and show it in the checkbox. It is unclear whether the inertia value is properly stored, meaning this is a purely UI bug

**Expected behavior**
The UI should read the value provided by the user and display it correctly, the internally stored inertia matrix should store the value provided by the user

**Actual behavior**
The UI displays the inverse of the inertia value provided by the user, unclear whether the internal inertial matrix is receiving the user's input 

**Assets required**
No special assets required

**Screenshots/Video**
Attached Video

**Found in Branch**
Found on the development branch , tag fb1fe7534f2c532b5a0e079c34b55368a70c6203

**Desktop/Device (please complete the following information):**
 - Device:  PC
 - OS: Ubuntu
 - Version: 20.04
 - CPU: Intel I9-11900H
 - GPU: NVidia GeForce RTX 3080
 - Memory: 32GB

**Additional context**
No additional contetx

https://user-images.githubusercontent.com/17083612/171013868-7d9b5728-93a0-4656-a660-f1dcbd800df7.mp4

### PR DESCRIPTION
**Pull request by greerdv**
Signed-off-by: greerdv <greerdv@amazon.com>

## What does this PR do?
Fixes #9829 which meant that when the "compute inertia" setting was switched off in the editor rigid body component, and inertia values were added manually, they could get trampled by their inverse values.

## How was this PR tested?
Created a level, tweaked the inertia settings, went into game mode and verified with the PhysX visual debugger that the inertia values were not being inverted. Note however that while testing this #10341 was found, which means that inertia values are not always serialized correctly.

### CODE REVIEW

File: Code/Framework/AzFramework/AzFramework/Physics/Utils.h [hunk 1]
```diff
@@ -36,9 +36,15 @@ namespace Physics
...
+        AZ_INLINE AZ::Matrix3x3 InverseInertiaLocalToWorld(const AZ::Vector3& inverseInertiaDiagonal, const AZ::Matrix3x3& rotationToWorld)
         {
-            return rotationToWorld * AZ::Matrix3x3::CreateDiagonal(diag) * rotationToWorld.GetTranspose();
+            return rotationToWorld * AZ::Matrix3x3::CreateDiagonal(inverseInertiaDiagonal) * rotationToWorld.GetTranspose();
+        }
+
+        /// Helper routine for certain physics engines that don't directly expose this property on rigid bodies.
+        AZ_INLINE AZ::Matrix3x3 InertiaLocalToWorld(const AZ::Vector3& inertiaDiagonal, const AZ::Matrix3x3& rotationToWorld)
+        {
+            return rotationToWorld * AZ::Matrix3x3::CreateDiagonal(inertiaDiagonal) * rotationToWorld.GetTranspose();
```
Comment (moraaar) [inline Code/Framework/AzFramework/AzFramework/Physics/Utils.h:47]: These 2 functions do exactly the same operations to its input parameters. Maybe remove `InverseInertiaLocalToWorld` and leave only `InertiaLocalToWorld`?

Comment (greerdv) [reply Code/Framework/AzFramework/AzFramework/Physics/Utils.h:47]: I deliberately didn't do that to avoid confusion. Even though these two functions do the same thing, this bug happened because inertia and inverse inertia were getting mixed up. I guess I could replace both with a DiagonalMatrixLocalToWorld function or something more generically named.

Comment (moraaar) [reply Code/Framework/AzFramework/AzFramework/Physics/Utils.h]: Finding the right name for it and avoid code duplication seems good to me. Thanks.

**Review by moraaar — APPROVED** [review]

**Review by SergeyAMZN — APPROVED** [review]
