### PR TITLE
Partial fix for Script Canvas Debugger feature

### LINKED ISSUE #9192: Restore and Improve ScriptCanvas Live Logging and Debugging Facilities in terms of new runtime implementation
The ScriptCanvas live logging and debugging facilities have long since fallen into disrepair, and it would benefit users greatly to restore and improve them. Some changes, like https://github.com/o3de/o3de/pull/8623 disable them completely, and simply require interface changes to restore the original functionality of providing a log trace of ScriptCanvas execution. However, it would be better to improve all functionality while restoring it. This could including adding live debugger functionality, adding breakpoints and step over buttons to allow users fine control over their script debugging experience.

### PR DESCRIPTION
**Pull request by guillaume-haerinck**
## What does this PR do?

Work on #9192, #2583, #17643, #10795

Re-enable the script canvas tracing feature (log window will not be able to identify the graph name in this PR, but it will at least show every events for the selected graph(s))

More information about the code architecture is available via [doc-wip.pdf](https://github.com/o3de/o3de/files/15214111/doc-wip.pdf)

https://github.com/o3de/o3de/assets/19243508/8f4bed43-6ca5-4038-b97b-f25d03bd302d

### Changes

- Serialize RemoteToolsEndpointInfo, needed during the ACK between debugger and the ClientTransceiver
- Fix RemoteTools `m_lastTarget` not being set, and add a method to only clear messages at the end of the frame (this should be a temporary workaround)
- Fix remote tool local messages behavior, so that they are serialized as well and use the right channel
- Get and parse RemoteTools message via the Tick event (only way to do so)
- Re-enable and port methods content that were either removed or commented-out (it is likely that some of this stuff need to be totaly removed)
- Port some of TargetManagerClient::Bus::Handler (do not exist anymore) to IRemoteTool events
- Expose `RuntimeDataOverrides` from `RuntimeComponent` (needed to get what was removed from GraphInfo)

### What remains

- In `Message::GraphActivated()` only the timestamp is serialized during SendRemoteToolsMessage, but this structure is much more complex as it contains the runtime data of the graph, and it is used in many other places in the receiving code. Either need to send another message with only the field needed, serialize it properly or refactor the code
- Likely multiple other things

### How to test

You just need to enable the Remote Tools Connection gem for your project.

gem

## How was this PR tested?

On a local dev build against the Newspaper sample

### CODE REVIEW

File: Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingDataAggregator.cpp [hunk 1]
```diff
@@ -325,25 +325,25 @@ namespace ScriptCanvasEditor
...
-//         }
+         bool foundMatch = false;
+ 
+         auto matchedRange = m_registrationMap.equal_range(entityId);
+         for (auto mapIter = matchedRange.first; mapIter != matchedRange.second; ++mapIter)
+         {
+             if (mapIter->second == graphIdentifier)
+             {
+                 foundMatch = true;
+                 AZ_Warning("ScriptCanvas", false, "Received a duplicated registration callback.");
```
Comment (spham-amzn) [inline Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingDataAggregator.cpp:338]: nit: Since this loop is used to detect any matching, we can either `break` out of this loop or switch to `AZ_WarningOnce`.

File: Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindowTreeItems.cpp [hunk 2]
```diff
@@ -205,7 +218,16 @@ namespace ScriptCanvasEditor
         m_inputName = "---";
         m_outputName = "---";
 
-        GeneralAssetNotificationBus::Handler::BusConnect(graphInfo);
+        // Payload sent from remote tool does not serialize the execution state
```
Comment (spham-amzn) [inline Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindowTreeItems.cpp:221]: same as above, do we need to keep this block as why?

File: Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Debugger.cpp [hunk 3]
```diff
@@ -178,7 +195,16 @@ namespace ScriptCanvas
             }
         }
 
-        void ServiceComponent::TargetLeftNetwork(AzFramework::RemoteToolsEndpointInfo info)
+        void ServiceComponent::RemoteToolsEndpointJoined(const AzFramework::RemoteToolsEndpointInfo& info)
+        {
+            // Temporary workaround as info.isSelf() never returns true
+            if (strcmp(info.GetDisplayName(), "Editor.exe") == 0)
```
Comment (spham-amzn) [inline Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Debugger.cpp:201]: This doesn't seem that it will work on Linux/Mac

File: Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Debugger.cpp [hunk 4]
```diff
@@ -762,44 +826,42 @@ namespace ScriptCanvas
         }
 
         void ServiceComponent::RuntimeError([[maybe_unused]] const ExecutionState& executionState, [[maybe_unused]] const AZStd::string_view& description)
-        {
-        }
+                    {
+                    }
```
Comment (spham-amzn) [inline Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Debugger.cpp:830]: alignment (space vs. tab?)

**Review by spham-amzn — APPROVED** [review]

File: Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Debugger.cpp [hunk 5]
```diff
@@ -198,7 +198,9 @@ namespace ScriptCanvas
         void ServiceComponent::RemoteToolsEndpointJoined(const AzFramework::RemoteToolsEndpointInfo& info)
         {
             // Temporary workaround as info.isSelf() never returns true
-            if (strcmp(info.GetDisplayName(), "Editor.exe") == 0)
+            // Self and the client should be equal as script canvas debugging is only supported within the same process for now
```
Comment (AMZN-Gene) [inline Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Debugger.cpp:201]: great comment

File: Code/Framework/AzFramework/AzFramework/ScriptCanvas/ScriptCanvasRemoteDebuggingConstants.h [hunk 6]
```diff
@@ -10,9 +10,9 @@
 #include <AzCore/Name/Name.h>
 #include <AzCore/Name/NameDictionary.h>
 
-namespace ScriptCanvas
+namespace AzFramework
```
[the remark this answers is not in the document]
Comment (guillaume-haerinck) [reply Code/Framework/AzFramework/AzFramework/ScriptCanvas/ScriptCanvasRemoteDebuggingConstants.h]: Got a better approach with latest, no more gem leaks :)

File: Code/Framework/AzFramework/AzFramework/Application/Application.cpp [hunk 7]
```diff
@@ -253,6 +254,8 @@ namespace AzFramework
             {
                 remoteTools->RegisterToolingServiceClient(
                     AzFramework::LuaToolsKey, AzFramework::LuaToolsName, AzFramework::LuaToolsPort);
+                remoteTools->RegisterToolingServiceClient(
```
[the remark this answers is not in the document]
Comment (guillaume-haerinck) [reply Code/Framework/AzFramework/AzFramework/Application/Application.cpp]: Cannot both register a client and host within the same app (It was working in my case but its really not the right way to go). With latest commit it works properly as I'm able to get the self value

File: Gems/RemoteTools/Code/Source/RemoteToolsSystemComponent.cpp [hunk 8]
```diff
@@ -315,33 +329,6 @@ namespace RemoteTools
         AZ::SerializeContext* serializeContext;
         AZ::ComponentApplicationBus::BroadcastResult(serializeContext, &AZ::ComponentApplicationBus::Events::GetSerializeContext);
 
-        // Messages targeted at our own application just transfer right over to the inbox.
-        if (target.IsSelf())
```
Comment (guillaume-haerinck) [inline Gems/RemoteTools/Code/Source/RemoteToolsSystemComponent.cpp:319]: I had to make this change, first to ensure behavior is the same between local and remote (so that there is no bad surprise with message serialization when connecting to remote process) and also because the actual message type is lost if we are not serializing them properly

**Review by lsemp3d — APPROVED** [review]
