### PR TITLE
Fix #19047 - Fix External scripts editor settings

### LINKED ISSUE #19047: External Editors setting(s) do not seem to work correctly in 25.05, at least for Script Files.
**Describe the bug**
When setting an external script file editor in 25.05, it does not seem to do anything.  Opening Lua files still just opens the built-in Lua editor.  Confirmed by another user in the forum.  I'm running the Linux build on CachyOS running kernel 6.15.3.

I have not tested the other external editor settings as of yet, but can once I have a moment.

**Assets required**
- 25.05 release of O3DE
- Created Lua script (content irrelevant)
- External text editor/IDE of choice

**Steps to reproduce**
1. In the editor, go to Edit > Editor Settings > Global Preferences > Files > External Editors.
2. Set the 'Scripts Editor' option to external editor of your choice.
3. Click 'OK'.
4. Open any Lua script from the editor.
5. Observe that the Lua editor launches instead of the specified external editor.

**Expected behavior**
Chosen external editor launches and opens the target script.

**Actual behavior**
The internal Lua editor launches, despite of external editor setting.  No additional output hits the console, nor are any UI popups displayed.  It just seems to ignore the setting.  Occasionally, opening a script will also cause the console to lose all text colors, but this is not consistent, and thus may not be directly related.

**Screenshots/Video**
Image

**Found in Branch**
25.05 release branch

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
46c647db74ede9c95897f40468f3c2cac59f3532

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux (CachyOS)
 - Version Kernel 6.15.3
 - CPU Ryzen 5900x
 - GPU AMD 6900 XT
 - Memory 32GB

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by LafLaurine**
## What does this PR do?

Fix #19047 so that users can open scripts (i.e Lua scripts) with the choosen editor instead of using the built-in by double-clicking on the file.

Also added a new action to the contextual menu "Open with external editor"

image

By default on windows, the "Scripts editor" setting is now empty (it was already the case for Linux).

image

## Further improvments for developer

⚠️  This is mostly a quick fix

- Editor Settings are not up to date. We need to change the logic to settings registry (https://docs.o3de.org/docs/user-guide/settings/). 

- If I understood well, the editor set in the "Scripts editor" setting was never used by the Asset Browser. Whenever you click on "Open with associated application..." it is going through `OpenWithOS` which uses the default application set for the OS to open this kind of file. We might want to improve this system. 
Also, imo, the wording used in the contextual menu is a bit confusing.

## How was this PR tested?

Local build. **Tested on Windows.** 

#### By default, without having a prefered editor set : 

- In the editor, go to Edit > Editor Settings > Global Preferences > Files > External Editors.
- Set the 'Scripts Editor' option to external editor of your choice.
- Click 'OK'.
- Open any Lua script from the editor.
- The Lua script is opened with the built-in Lua Editor 

#### If a editor is set

- In the editor, go to Edit > Editor Settings > Global Preferences > Files > External Editors.
- Set the 'Scripts Editor' option to external editor of your choice (I've tried with notepad).
- Click 'OK'.
- Open any Lua script from the editor.
- The specified external editor (for my test, notepad) in the External Editors is used

### CODE REVIEW

File: Code/Editor/EditorPreferencesPageFiles.cpp [hunk 1]
```diff
@@ -69,7 +69,8 @@ void CEditorPreferencesPage_Files::Reflect(AZ::SerializeContext& serialize)
             ->DataElement(AZ::Edit::UIHandlers::LineEdit, &Files::m_saveLocation, "UI Slice Save location", "Specify the default location to save new UI slices");
 
         editContext->Class<ExternalEditors>("External Editors", "External Editors")
-            ->DataElement(AZ::Edit::UIHandlers::ExeSelectBrowseEdit, &ExternalEditors::m_scripts, "Scripts Editor", "Scripts Text Editor")
+            ->DataElement(AZ::Edit::UIHandlers::ExeSelectBrowseEdit, &ExternalEditors::m_scripts, "Scripts Editor", "Scripts Text Editor (Default to O3DE internal tool when empty)")
+            ->Attribute(AZ::Edit::Attributes::PlaceholderText, "Default to O3DE internal tool when empty")
```
Comment (LafLaurine) [inline Code/Editor/EditorPreferencesPageFiles.cpp:73]: Tried to put a placeholder to have an explanation on why it is empty but seems like it is not applied

File: Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp [hunk 2]
```diff
@@ -1158,6 +1159,18 @@ void AzAssetBrowserRequestHandler::OpenAssetInAssociatedEditor(const AZ::Data::A
         return;
     }
 
+    AzToolsFramework::EditorSettingsAPIRequests::SettingOutcome textEditorScriptSettings;
```
Comment (guillaume-haerinck) [inline Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp]: missing include for EditorSettingsAPIRequests (but might not be required in this file, see below)

File: Code/Editor/Settings.cpp [hunk 3]
```diff
@@ -478,7 +478,7 @@ void SEditorSettings::Save(bool isEditorClosing)
     SaveValue("Settings", "ShowScaleWarnings", viewports.bShowScaleWarnings);
     SaveValue("Settings", "ShowRotationWarnings", viewports.bShowRotationWarnings);
 
-    SaveValue("Settings", "TextEditorScript", textEditorForScript);
+    SaveValue("Settings\\Editor", "TextEditorScript", textEditorForScript);
     SaveValue("Settings", "TextEditorShaders", textEditorForShaders);
```
Comment (guillaume-haerinck) [inline Code/Editor/Settings.cpp]: might as well add "Editor" as you did for the shader, bspaces, textures and animation

File: Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp [hunk 4]
```diff
@@ -1158,6 +1159,18 @@ void AzAssetBrowserRequestHandler::OpenAssetInAssociatedEditor(const AZ::Data::A
...
+    AzToolsFramework::EditorSettingsAPIBus::BroadcastResult(
```
Comment (guillaume-haerinck) [inline Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp]: It seems like that `OpenAssetInAssociatedEditor` will be called for other assets than lua scripts, so you will want to move this logic deeper in the callstack (likely in a new implementation of "AddSourceFileOpeners")

**Review by guillaume-haerinck — COMMENTED** [review]
Thanks for the quick fix !

File: Code/Editor/Settings.cpp (hunk 3 above)
Comment (LafLaurine) [reply Code/Editor/Settings.cpp]: I think they're not used. But it's nice for consistency so you're right. Done :)

File: Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp (hunk 4 above)
Comment (LafLaurine) [reply Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp]: Yeah fair, I've thought about the big scope but it wasn't thought through enough. Moved the logic to the `LuaEditorSystemComponent` . We might want to do this for other type of data later ?

File: Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp [hunk 5]
```diff
@@ -1194,6 +1194,11 @@ void AzAssetBrowserRequestHandler::OpenAssetInAssociatedEditor(const AZ::Data::A
                 }
                 // bind a callback such that when the menu item is clicked, it sets that as the opener to use.
                 menu.addAction(openerDetails.m_iconToUse, QObject::tr(openerDetails.m_displayText.c_str()), mainWindow, [switchToOpener, details = &openerDetails] { return switchToOpener(details); });
+                // Stop looking for openers after finding a prioritized one, as this should be the only one displayed
+                if (openerDetails.m_isPrioritized)
```
Comment (guillaume-haerinck) [inline Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp]: If a prioritized is registered after a non-prioritized both will be shown. Not the end of the world, but would be a tad cleaner to do a loop before (like line 1184) to check if there is a prioritized opener amongst openers, and if so, only ever register the one that is prioritized

**Review by guillaume-haerinck — APPROVED** [review]

File: Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp (hunk 5 above)
Comment (LafLaurine) [reply Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp]: Wasn't thinking about that, you're right! I tried to improve the logic, let me know if that still not covers everything

File: Code/Editor/Settings.cpp [hunk 6]
```diff
@@ -478,11 +478,11 @@ void SEditorSettings::Save(bool isEditorClosing)
...
-    SaveValue("Settings", "TextEditorScript", textEditorForScript);
-    SaveValue("Settings", "TextEditorShaders", textEditorForShaders);
-    SaveValue("Settings", "TextEditorBSpaces", textEditorForBspaces);
-    SaveValue("Settings", "TextureEditor", textureEditor);
-    SaveValue("Settings", "AnimationEditor", animEditor);
+    SaveValue("Settings\\Editor", "TextEditorScript", textEditorForScript);
+    SaveValue("Settings\\Editor", "TextEditorShaders", textEditorForShaders);
+    SaveValue("Settings\\Editor", "TextEditorBSpaces", textEditorForBspaces);
+    SaveValue("Settings\\Editor", "TextureEditor", textureEditor);
+    SaveValue("Settings\\Editor", "AnimationEditor", animEditor);
```
Comment (nick-l-o3de) [inline Code/Editor/Settings.cpp]: I assume backslashes are the only thing that works here (we always prefer forward slashes if possible) due to whatever legacy system is saving these?

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserBus.h [hunk 7]
```diff
@@ -121,14 +121,19 @@ namespace AzToolsFramework
             //! This is the function to call.  If you fill a nullptr in here, then the default operating system behavior will be suppressed
             //! but no opener will be opened.  This will also cause the 'open' option in context menus to disappear if the only openers
             //! are nullptr ones.
-            SourceFileOpenerFunctionType m_opener; 
+            SourceFileOpenerFunctionType m_opener;
+
+            //! Indicates whether this opener should be prioritized when multiple openers are available
+            //! If set to true, this opener will take precedence over others
+            bool m_isPrioritized = false;
```
Comment (nick-l-o3de) [inline Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserBus.h:128]: Is this necessary though, the bus itself has a priority system attached to it.  Could that not be used?  Anything that wants to give priority could insert itself in the front of the list thats returned, by changing its GetPriority() override on the bus.

File: Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp [hunk 8]
```diff
@@ -1182,18 +1182,46 @@ void AzAssetBrowserRequestHandler::OpenAssetInAssociatedEditor(const AZ::Data::A
...
+        };
+
+        // Check if any prioritized opener exists
+        const auto it = std::find_if(
+            openers.begin(),
+            openers.end(),
+            [](const SourceFileOpenerDetails& opener)
+            {
+                return opener.m_opener && opener.m_isPrioritized;
+            });
```
Comment (nick-l-o3de) [inline Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp:1214]: The opener with the highest GetPriority() is always at the front of the list.

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserBus.h (hunk 7 above)
Comment (LafLaurine) [reply Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserBus.h:128]: oh nice, I wasn't aware of this priority system! However, I think that it does not address this specific use case: "If an external editor is set, this opener has priority. Upon double click use this one instead of showing the popup menu with the multiple openers". It is likely that this variable could be better named, like with `SoloOnDoubleClick` or something like that. Did you have anything else in mind ?

File: Code/Editor/Settings.cpp (hunk 6 above)
Comment (LafLaurine) [reply Code/Editor/Settings.cpp]: I thought so as I was copying whats done for other variables in this file, turns out I was wrong. Changed to one forward slash instead. 

We should also do this for other settings as well but might be done with the refactoring of the editor settings mentionned in the PR description
