### PR TITLE
ScriptCanvas: Fix crash on SC editor close

### LINKED ISSUE #18724: ScriptCanvas crashes on exit because of double free of a ptr
**Describe the bug**
There is a memory corruption issue with the ScriptCanvas, if you close it it will crash right away

**Assets required**
None, just open and close the ScriptCanvas. 

**Steps to reproduce**
1. Launch the editor
2. Open ScriptCanvas
3. Close it

**Expected behavior**
Does not crash on exit

**Actual behavior**
Crashes

**Screenshots/Video**

[Editor.log](https://github.com/user-attachments/files/19066513/Editor.log)

**Found in Branch**
Tried on dev branch from ee215524b294e71912386a90ecd904aa92a8300e

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 11
 - CPU: AMD Ryzen 9 5900X
 - GPU: NVidia GTX 1060
 - Memory: 64gb

**Additional Context**

Crashes on this part of code, will need to run with ASAN to know where the issue comes from

```cpp
block_header* bl = ptr_get_block_header(ptr);
// This assert detects a double-free of ptr
HPPA_ASSERT(bl->used());
size_type allocatedBytes = bl->size();
mTotalAllocatedSizeTree -= allocatedBytes;
bl->set_unused();
bl = coalesce_block(bl);
tree_attach(bl);
```

### PR DESCRIPTION
**Pull request by lsemp3d**
## What does this PR do?

When closing the Script Canvas editor, there is a double delete because the tabWidget created during initialization is tracked and destroyed by the parent, if we don't clear out the parent, the owning widget will attempt to delete it which results in a double deletion.

Also simplified the code that tracks the logging, one of the causes for the crash is that a member variable of AssetData class was being kept, this data would get deleted by the asset at some point which left it in an undefined state, when the owning object got deleted it would try to invoke the dtor for the ExecutionLogAsset which was already invalid resulting in the crash.

Closes #18724

### CODE REVIEW

File: Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Logger.h [hunk 1]
```diff
@@ -79,9 +79,9 @@ namespace ScriptCanvas
             bool m_logExecutionOverride = false;
 
 #if defined(SC_EXECUTION_TRACE_ENABLED)
-            ExecutionLogAsset m_logAsset;
+            ExecutionLogData m_logData;
 #endif
-            ScriptCanvas::Debugger::Target m_target;
+            ScriptCanvas::Debugger::Target* m_target;
```
Comment (guillaume-haerinck) [inline Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Logger.h:84]: not for now but might be wise to have a weakptr there in  the future

**Review by guillaume-haerinck — APPROVED** [review]
Thanks for taking the time to look into this :)

File: Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindow.cpp [hunk 2]
```diff
@@ -47,11 +49,13 @@ namespace ScriptCanvasEditor
...
         PivotOnEntities();
+
     }
 
     LoggingWindow::~LoggingWindow()
     {
-
+        // The tabWidget destruction is handled by its parent, if we don't clear the parent, this results in a double deletion
+        m_ui->tabWidget->setParent(nullptr);
     }
```
[the remark this answers is not in the document]
Comment (lsemp3d) [reply Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindow.cpp:57]: you're right, I removed this bit, it's no longer needed. The root case was the issue with the AssetData, this hack essentially made it so that the memory never got released which was incorrect too

File: Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Logger.h (hunk 1 above)
Comment (lsemp3d) [reply Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Logger.h:84]: I'll keep it in mind, don't have time to dive into it more this weekend
