### PR TITLE
Fixed missing assets when entering Play-In-Editor.

### LINKED ISSUE #6771: Script Canvas graphs are not executed by Script Canvas components
**Describe the bug**
Script Canvas graphs are not executed when attached to a Script Canvas component on an entity. Instead an error is printed to the Console - "[Error] (ScriptCanvas) - RuntimeComponent::m_runtimeAsset AssetId: {<ID>} was valid, but the data was not pre-loaded, so this script will not run. It should be noted that no workaround has been found for this issue.

**Steps to reproduce**
1. Go to Tools > Script Canvas.
2. Create a new graph.
3. Create a simple script in it (e.g. On Graph Start -> Print) and save it.
4. Create an entity and add a Script Canvas component to it.
5. Attach the Script Canvas graph saved in step 3 to the Script Canvas component.
6. Enter the Game Mode.

**Expected behavior**
The Script Canvas asset is executed.

**Actual behavior**
An error is printed to the Console and the script does not execute.

**Video**

https://user-images.githubusercontent.com/86952082/148772161-39b27f2c-c8ca-418e-80e6-b30a50ba3197.mp4

**Found in Branch**
Development (5e8c1aa)

**Desktop**
* Device: PC
* OS: Windows
* Version 10
* CPU AMD Ryzen 5 3600
* GPU NVIDIA GeForce RTX 2060 SUPER
* Memory 16GB

### PR DESCRIPTION
**Pull request by AMZN-koppersr**
fixes #6771 

At the root the problem is that some editor-only components store information to construct an asset for the runtime component but not the asset itself. This behavior caused the assets to not be correctly detected in two places.

The first place was due to the recent move to PrefDocument to avoid repeated (de)serialization of the PrefabDOM when converting to spawnables. Due to the caching the change from editor-only component to runtime component didn't record the new asset. This has been fixed by allowing assets to be collected on store as well and to check the cache validity when retrieving the list of referenced assets.

The second problem was with loading assets from the in-memory spawnable that's created for Play-In-Editor. Because the newly created assets wouldn't be loaded they need to be explicitly loaded. The original code used the collected list of assets from the PrefabDocument and checked if they were loaded, depending on hot-reloading to trigger a reload on the actual asset. This turned out to not be universally applicable, so instead the Serialize Context is now used to find all the assets that aren't loaded yet and queues a load. This is a bit more expensive to do, but to offset this cost checks are done to only do any operations on assets that haven't been loaded yet which reduces the number of calls to the Asset Manager.

Signed-off-by: AMZN-koppersr <82230785+AMZN-koppersr@users.noreply.github.com>

### CODE REVIEW

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.h [hunk 1]
```diff
@@ -58,8 +57,8 @@ namespace AzToolsFramework::Prefab::PrefabConversionUtils
         const SpawnableAssets& GetAllInMemorySpawnableAssets() const;
 
     private:
-        void LoadReferencedAssets(AZStd::vector<AZ::Data::Asset<AZ::Data::AssetData>>& referencedAssets);
-
+        void LoadReferencedAssets(SpawnableAssetData& spawnable);
+
```
Comment (NicholasVanSickle) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.h:61]: nit: trailing space

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.cpp [hunk 2]
```diff
@@ -119,6 +119,60 @@ namespace AzToolsFramework
...
+                const Instance& instance,
+                PrefabDom& prefabDom,
+                AZStd::vector<AZ::Data::Asset<AZ::Data::AssetData>>& referencedAssets,
+                StoreFlags flags)
+            {
+                InstanceEntityIdMapper entityIdMapper;
+                entityIdMapper.SetStoringInstance(instance);
+
+                // Need to store the id mapper as both its type and its base type
+                // Meta data is found by type id and we need access to both types at different levels (Instance, EntityId)
```
Comment (NicholasVanSickle) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.cpp:132]: nit: s/Meta data/Metadata/

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.cpp [hunk 3]
```diff
@@ -119,6 +119,60 @@ namespace AzToolsFramework
                 return true;
             }
 
+            bool StoreInstanceInPrefabDom(
```
Comment (NicholasVanSickle) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.cpp:122]: There's a lot of overlap with the other `StoreInstanceInPrefabDom`, it might be worth narrowing to one implementation that takes `referencedAssets` as an optional pointer to avoid implementation drift (this already is the only implementation that adds `AZ::Data::SerializedAssetTracker` to the metadata, which I assume is probably correct but would struggle to audit at a glance).

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabDocument.cpp [hunk 4]
```diff
@@ -158,4 +153,23 @@ namespace AzToolsFramework::Prefab::PrefabConversionUtils
             return false;
         }
     }
+
+    bool PrefabDocument::RefreshPrefabDom() const
```
Comment (NicholasVanSickle) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabDocument.cpp:157]: Currently we just discard the return value for this, and the failure path triggers an assert - it may not be worth keeping the return value around - this otherwise is a nice refactor that makes things clearer

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp [hunk 5]
```diff
@@ -213,63 +212,91 @@ namespace AzToolsFramework::Prefab::PrefabConversionUtils
...
-            asset.BlockUntilLoadComplete();
-
-            if (asset.IsError())
-            {
-                AZ_Error("Prefab", false, "Asset with id %s failed to preload while entering game mode",
-                    asset.GetId().ToString<AZStd::string>().c_str());
-
-                continue;
-            }
+            // Reset the load behavior back to preload because the async load will have caused the behavior to be set to queued. Some assets
```
Comment (NicholasVanSickle) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp:297]: Not for this PR, but it feels like a utility for "blocking load N assets" that handles these nuances for you should exist.

**Review by NicholasVanSickle — COMMENTED** [review]
Nice work fixing this up! I'm a bit concerned about the two `StoreInstanceInPrefabDom` from a maintainability POV, but all of my other comments are non-blocking.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabDocument.h [hunk 6]
```diff
@@ -58,11 +58,13 @@ namespace AzToolsFramework::Prefab::PrefabConversionUtils
...
     private:
         bool ConstructInstanceFromPrefabDom(const PrefabDom& prefab);
+        // Marked const so this function can be called from other const functions. It will only operate on mutable variables.
+        bool RefreshPrefabDom() const;
         
         mutable PrefabDom m_dom;
         AZStd::unique_ptr<AzToolsFramework::Prefab::Instance> m_instance;
         AZStd::string m_name;
-        AZStd::vector<AZ::Data::Asset<AZ::Data::AssetData>> m_referencedAssets;
+        mutable AZStd::vector<AZ::Data::Asset<AZ::Data::AssetData>> m_referencedAssets;
```
Comment (spham-amzn) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabDocument.h:67]: 😮

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp [hunk 7]
```diff
@@ -213,63 +212,91 @@ namespace AzToolsFramework::Prefab::PrefabConversionUtils
...
+                    if (loadBehavior == AZ::Data::AssetLoadBehavior::NoLoad)
+                    {
+                        return false;
+                    }
+
+                    AZ::Data::AssetId assetId = asset->GetId();
+                    AZ::Data::AssetType assetType = asset->GetType();
+
+                    // Always queue load as the next step will stop loading for all PreLoad assets
+                    *asset = AZ::Data::AssetManager::Instance().GetAsset(assetId, assetType, AZ::Data::AssetLoadBehavior::QueueLoad);
```
Comment (mbalfour-amzn) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp:259]: I think you're mixing semantics on the load behavior here.  All you really want (I think) is just to call asset->QueueLoad().  By calling GetAsset(), you're creating a _new_ asset<T> reference, and you're initializing the loadBehavior to QueueLoad, which has nothing to do with the current load.  It just means that the asset is requesting to be Queued whenever the parent owning the asset reference is loaded.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp [hunk 8]
```diff
@@ -213,63 +212,91 @@ namespace AzToolsFramework::Prefab::PrefabConversionUtils
...
-            if (asset.IsError())
-            {
-                AZ_Error("Prefab", false, "Asset with id %s failed to preload while entering game mode",
-                    asset.GetId().ToString<AZStd::string>().c_str());
-
-                continue;
-            }
+            // Reset the load behavior back to preload because the async load will have caused the behavior to be set to queued. Some assets
+            // will complain if they're not set to the correct loading behavior.
+            asset->SetAutoLoadBehavior(AZ::Data::AssetLoadBehavior::PreLoad);
```
Comment (mbalfour-amzn) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp:299]: You shouldn't need this as long as you don't overwrite the LoadBehavior in the above code.

**Review by mbalfour-amzn — CHANGES_REQUESTED** [review]

**Review by AMZN-Gene — APPROVED** [review]

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp [hunk 9]
```diff
@@ -213,63 +212,91 @@ namespace AzToolsFramework::Prefab::PrefabConversionUtils
...
-                AZ_Error("Prefab", false, "Invalid asset found referenced in scene while entering game mode");
-                continue;
-            }
+                if (classData->m_typeId == AZ::GetAssetClassId())
+                {
+                    auto asset = reinterpret_cast<AZ::Data::Asset<AZ::Data::AssetData>*>(object);
+
+                    if (!asset->GetId().IsValid())
+                    {
+                        AZ_Error("Prefab", false, "Invalid asset found referenced in scene while entering game mode");
```
[the remark this answers is not in the document]
Comment (AMZN-alexpete) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp:239]: +1

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.h (hunk 1 above)
Comment (AMZN-koppersr) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.h:61]: Removed.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.cpp (hunk 2 above)
Comment (AMZN-koppersr) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.cpp:132]: Updated

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.cpp (hunk 3 above)
Comment (AMZN-koppersr) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.cpp:122]: Moved the shared logic into an internal function.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabDocument.cpp (hunk 4 above)
Comment (AMZN-koppersr) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabDocument.cpp:157]: It has indeed lost its purpose so replaced the `bool` with a `void`. It can always be added back in again if needed.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp (hunk 5 above)
Comment (AMZN-koppersr) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp:297]: This is probably one of the few places that can make practical use of it as most asset loading is triggered from serialization. On the upside, Asset Streaming does the above trick on a larger scale for any asset dependencies, which is why it's so important dependencies get registered correctly in the AP.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabDocument.h (hunk 6 above)
Comment (AMZN-koppersr) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabDocument.h:67]: The PrefabDocument uses lazy evaluation to avoid needlessly roundtripping to/from JSON. This does mean that some `const` functions need to to just-in-time serialization. The options to make that work is to do a `const_cast` inside the `const` functions or to mark the variables involved with `mutable`. Imho `mutable` is the lesser of these two evils because it uses a language keyword to indicate exactly what variables are breaking constness, while the `const_cast` hides that and essentially says that all member variables break constness.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp (hunk 7 above)
Comment (AMZN-koppersr) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp:259]: You're correct, so I updated it use `QueueLoad`. The focus was more on tricking a `PreLoad` asset to be async loaded through `QueueLoad`. As it turns out explicitly setting the auto load behavior to `QueueLoad` works just as well and later setting it back also makes a lot more sense in that case.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp (hunk 8 above)
Comment (AMZN-koppersr) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp:299]: The new asset was setup with an auto load behavior of `QueueLoad` as that's how the asset was created. Based on your earlier suggestion that was updated, but to still get some overlapping loading going the auto load behavior was explicitly set to `QueueLoad` so it has to be set back here. Practically it shouldn't make a difference after an asset has been loaded, but some code (i.e. in Script Canvas) explicitly checks for the auto load behavior. It doesn't have any side effects as far as I can tell other than keeping track of load flag on the asset.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.cpp [hunk 10]
```diff
@@ -119,6 +119,60 @@ namespace AzToolsFramework
...
+                StoreFlags flags)
+            {
+                InstanceEntityIdMapper entityIdMapper;
+                entityIdMapper.SetStoringInstance(instance);
+
+                // Need to store the id mapper as both its type and its base type
+                // Meta data is found by type id and we need access to both types at different levels (Instance, EntityId)
+                AZ::JsonSerializerSettings settings;
+                settings.m_metadata.Add(static_cast<AZ::JsonEntityIdSerializer::JsonEntityIdMapper*>(&entityIdMapper));
+                settings.m_metadata.Add(&entityIdMapper);
```
[the remark this answers is not in the document]
Comment (AMZN-koppersr) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.cpp:135]: There's a base class that's extended for some specific Prefab behavior. The meta data on the Json Serialization doesn't take inheritance into account and only finds exact matches. In order for both the base and the inherited version to be found it gets registered twice, once as the base class and once as the derived class.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp (hunk 9 above)
[the remark this answers is not in the document]
Comment (AMZN-koppersr) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp:239]: If the id on the asset is invalid it typically means that the entire asset isn't valid so any retrieved data is empty or in a worse case misleading data. That said a bit lower there are two more errors that both were extended to include the asset hint, asset id and asset type.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp [hunk 11]
```diff
@@ -213,63 +212,91 @@ namespace AzToolsFramework::Prefab::PrefabConversionUtils
...
+            
+            if (asset->IsError())
             {
-                AZ_Error("Prefab", false, "Invalid asset found referenced in scene while entering game mode");
-                continue;
-            }
-
-            const AZ::Data::AssetLoadBehavior loadBehavior = asset.GetAutoLoadBehavior();
+                AZ_Error(
+                    "Prefab", false, "Asset with id %s failed to preload while entering game mode",
```
[the remark this answers is not in the document]
Comment (AMZN-koppersr) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp:291]: Yup added those, se previous comment.

**Review by NicholasVanSickle — APPROVED** [review]

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp (hunk 9 above)
[the remark this answers is not in the document]
Comment (AMZN-Gene) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp:239]: Yeah, since the asset was invalid it could be entirely deleted. I was more wondering if we could print the object trying to use the asset? For example, if a prefab, has a script component which is holding ref to a non-existing script asset, could we print the name of the prefab (or even the name of the entity in the prefab) which is storing the bad ref? 🤷‍♀️ maybe we don’t have that info at this point

**Review by mbalfour-amzn — APPROVED** [review]

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp (hunk 8 above)
Comment (mbalfour-amzn) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp:303]: Discussed offline - the QueueLoad() call is enough to get the queueing to happen, the calls to SetAutoLoadBehavior() shouldn't meaningfully affect this loading scenario.  They don't _hurt_ anything, but they're extra code that can be removed.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp (hunk 9 above)
[the remark this answers is not in the document]
Comment (AMZN-koppersr) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp:239]: The owning Spawnable is an in-memory spawnable so it has a placeholder name. Printing that out would add more confusion than it would clarify I think. I extended the message to include the class name that owns the asset, so at least that will help a bit with narrowing down any issues hopefully.

[the remark this answers is not in the document]
Comment (AMZN-Gene) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp:239]: Ah, that makes sense. Thanks @AMZN-koppersr !
