### PR TITLE
Display project engines and versions and allow changing project engine

### LINKED ISSUE #4079: Project Manager does not update the project's name until restarted
**Describe the bug**
It has been noticed that the title of the project is updated only after restarting the Project Manager.

**To Reproduce**
1. Open the Project Manager.
2. Create a project.
3. Change the name of the project.

**Expected behavior**
The name is changed in the projects list.

**Device: PC**
OS: Windows
Version: 10
CPU: Intel I5-9600k
GPU: RTX 2060
Memory: 16GB

**Additional context**

https://user-images.githubusercontent.com/86952009/133065539-0ce477a3-0508-492d-b757-2fd5bb579001.mp4

### LINKED ISSUE #6187: Duplicating and Renaming a project doesn't update name in launcher UI
**Describe the bug**
Duplicating and Renaming a project doesn't update name in launcher UI

**Steps to reproduce**
1. launch o3de
2. duplicate a project to a new folder with the desired new project name
3. edit project settings
4. change the project name of the duplicated project
5. Save
6. Note: you still have two projects of the same name

**Expected behavior**
When duplicating the project and choosing a new folder name, the folder should determine the project name so steps 3, 4, and 5 can be skipped.  The o3de launcher should reflect the changes made during the duplication process.

**Actual behavior**
Project name does not update in launcher UI.
If o3de is exited and restarted the changes made in steps 3, 4 and 5 are reflected.

**Assets required**
Any project on your local machine should see the same results.

**Desktop/Device (please complete the following information):**
 - PC
 - OS: Windows
 -10
 -Intel 
 - NVIDIA GTX 1060
 - 12GB

### LINKED ISSUE #7686: Project Manager: Editing a projects name is not reflected in the Project Manager until restarting it
**Describe the bug**
If the user edits the project settings to change the name of the project, the name change is not reflected in the project list until the user restarts the Project Manager

**Steps to reproduce**
1. Launch the Project Manager
2. Create a new project
3. Open the project hamburger/drop down menu and select "Edit Project Settings..."
4. Change the project name
5. Select "Save"

**Expected behavior**
The newly saved name appears in the Project Manager project list

**Actual behavior**
The newly saved name does not display for the project until the user restarts the Project Manager

**Found in Branch**
Release Installer 2111.2

### LINKED ISSUE #7789: [Project Manager] "Projects" tab color changes unexpectedly when building a project
**Describe the bug**
When the user starts the project build process in the Project Manager, the background color of the tab in the top left corner becomes a strange different color that is unusual and inconsistent.

**Steps to reproduce**
1. Launch Project Manager
2. Create a new project
3. Select Build Project

**Expected behavior**
"Projects" tab remains the darker background color

**Actual behavior**
"Projects" tab background color becomes a lighter grey

**Screenshots/Video**
image

**Found in Branch**
Release Installer 2111.2

### LINKED ISSUE #8953: Issue moving a Project to another Build of o3de engine. Project JSON needs manual adjustment.
**Describe the bug**
Moving a Project to another Build of o3de engine, there are no Project Manager menu items to update the Projects first assigned engine, only a over all engine, This will cause build errors building the project and also project not being able to launch.

The Project.json must be manually adjusted for the project to build and load properly. 

Please see an example, this illustrates two projects in my o3de projects folder, but with mixed engines per project. These must manually be edited to match the current running engine.

**Steps to reproduce**
1. Move a project from one engine to another.
2. Try and build and launched project with different engines in project.json
3. Please see attached.

**Expected behavior**
If you rebuild a project from another build of the engine, the project.json will update the engine to the current engine being used with the project manager.

**Actual behavior**
The project manager has no idea about the loaded projects.json with an engine entry that is not mathing the project managers engine.

**Assets required**
Projects from two different engine builds.

**Screenshots/Video**
image

**Found in Branch**
Production and Development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel I9-9900k
 - GPU  NVidia RTX 2080ti
 - Memory 16GB

**Additional context**

### PR DESCRIPTION
**Pull request by AMZN-alexpete**
o3de_lJavs1EkEW

## What does this PR do?

- Display the current engine name and version in the title bar
- Display the associated engine and engine for each project on the projects tab
- Display an engine combobox in the project settings page where you can change the associated version.  Fixes #8953
- Check o3de-sdk binary paths when attempting to run the editor for a project using another engine
- Add `get_project_engine` python method
- Update `get_engine_projects` to accept an optional `engine_path`
- Update `set_project_properties` to accept an optional `engine` name property - this is currently needed to "register" a global project with an engine.  If you use the `register` function it will modify the engine.json of the specified engine.
- Fix project path comparison (posix vs non-posix)
- Fix some misnamed python functions in registery.py
- Fix #7686 and fix #6187 and fix #4079 project name not updating when changed in project settings page
- Fix #7789 projects tab becoming highlighted blue when building a project

## How was this PR tested?

- created a project in PM then built it, changed it to a different engine, verified build notifications showed and UI was updated.
- verified changing a project path to an equivalent path with different separators doesn't trigger moving the project or break the project build settings logic

### CODE REVIEW

File: Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp [hunk 1]
```diff
@@ -186,19 +186,50 @@ namespace O3DE::ProjectManager
                     // First try <project-build-path>/bin/$<CONFIG> and if that path doesn't exist
                     // try <project-build-path>/bin/$<PLATFORM>/$<CONFIG>
                     buildConfigurationPath /= "bin";
-                    if (editorPath = (buildConfigurationPath / AZ_BUILD_CONFIGURATION_TYPE / "Editor").
+                    auto paths = AZStd::vector<AZ::IO::FixedMaxPath>{
+                        buildConfigurationPath / AZ_BUILD_CONFIGURATION_TYPE / "Editor",
+                        buildConfigurationPath / AZ_TRAIT_OS_PLATFORM_CODENAME / AZ_BUILD_CONFIGURATION_TYPE / "Editor"
+                    };
```
Comment (lumberyard-employee-dm) [inline Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp:192]: This should use an AZStd::array, as there is no need for heap memory allocations.

```suggestion
                    AZStd::array paths = {
                        AZ::IO::FixedMaxPath { buildConfigurationPath / AZ_BUILD_CONFIGURATION_TYPE / "Editor" },
                        AZ::IO::FixedMaxPath { buildConfigurationPath / AZ_TRAIT_OS_PLATFORM_CODENAME / AZ_BUILD_CONFIGURATION_TYPE / "Editor" }
                    };
```

File: Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp [hunk 2]
```diff
@@ -186,19 +186,50 @@ namespace O3DE::ProjectManager
...
+
+                    // always try profile config because that is the default
+                    if (strcmp(AZ_BUILD_CONFIGURATION_TYPE, "profile") != 0)
+                    {
+                        paths.emplace_back(buildConfigurationPath / "profile" / "Editor");
+                        paths.emplace_back(buildConfigurationPath / AZ_TRAIT_OS_PLATFORM_CODENAME / "profile" / "Editor");
+                    }
+
+                    for (auto path : paths)
```
Comment (lumberyard-employee-dm) [inline Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp:201]: This should be a non-const lvalue reference as there is no need to copy the FixedMaxPath.
```suggestion
                    for (auto& path : paths)
```

File: Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp [hunk 3]
```diff
@@ -186,19 +186,50 @@ namespace O3DE::ProjectManager
...
+                }
+            }
+
+            // Attempt to find the Editor in the specified engine's bin folder
+            if(auto engineResult = PythonBindingsInterface::Get()->GetProjectEngine(projectPath.Native().data()); engineResult)
+            {
+                auto engineInfo = engineResult.GetValue<EngineInfo>();
+                if (!engineInfo.m_thisEngine)
+                {
+                    AZ::IO::FixedMaxPath fixedEnginePath{ engineInfo.m_path.toStdString().c_str() };
```
Comment (lumberyard-employee-dm) [inline Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp:217]: This should use toUtf8().constData() to avoid the need to allocate std::string.
It is more performant.
```suggestion
                    AZ::IO::FixedMaxPath fixedEnginePath{ engineInfo.m_path.toUtf8().constData() };
```

File: scripts/o3de/o3de/manifest.py [hunk 4]
```diff
@@ -314,6 +314,24 @@ def get_project_external_subdirectories(project_path: pathlib.Path) -> list:
                         project_object['external_subdirectories'])) if 'external_subdirectories' in project_object else []
     return []
 
+def get_project_engine(project_path: str or pathlib.Path) -> pathlib.Path or None:
```
Comment (lumberyard-employee-dm) [inline scripts/o3de/o3de/manifest.py:317]: There is no reason to allow this function to accept a string.
It should only be a pathlib.Path.
```suggestion
def get_project_engine(project_path: pathlib.Path) -> pathlib.Path or None:
```

File: scripts/o3de/o3de/manifest.py [hunk 5]
```diff
@@ -314,6 +314,24 @@ def get_project_external_subdirectories(project_path: pathlib.Path) -> list:
...
+    project_object = get_project_json_data(project_path=project_path)
+    if project_object:
+        engine_name = project_object.get('engine','')
```
Comment (lumberyard-employee-dm) [inline scripts/o3de/o3de/manifest.py:320]: nitpick: missing space after the comma in the get call.
```suggestion
        engine_name = project_object.get('engine', '')
```

File: scripts/o3de/o3de/manifest.py [hunk 6]
```diff
@@ -314,6 +314,24 @@ def get_project_external_subdirectories(project_path: pathlib.Path) -> list:
...
+        if engine_name:
+            engine_path = get_registered(engine_name=engine_name)
+            if engine_path:
+                return engine_path.as_posix()
+    
+    engine_paths = get_manifest_engines()
+    resolved_project_path = pathlib.Path(project_path).resolve()
+    for engine_path in engine_paths:
+        projects = get_engine_projects(engine_path)
```
Comment (lumberyard-employee-dm) [inline scripts/o3de/o3de/manifest.py:329]: This is code returns an ambiguous engine path and I think should be removed.
A project needs to be registered the engine it is with to avoid this scenario.

It is returning the first engine which has the project registered.

What this means is if for some reason the "engine" field from AutomatedTesting `project.json` was removed, it just return the engine of the first project it finds which may be incorrect.

The query code o3de object code in the manifest is authored in a way to not return ambiguous results.

Just registering an engine again, would move it to the top of the list of "engines" in the `o3de_manifest.json` which change the result of this function.

**Review by lumberyard-employee-dm — CHANGES_REQUESTED** [review]

File: Code/Tools/ProjectManager/Source/ProjectButtonWidget.cpp [hunk 7]
```diff
@@ -331,6 +346,25 @@ namespace O3DE::ProjectManager
...
     }
 
+    void ProjectButton::SetEngine(const EngineInfo& engine)
+    {
+        m_engineInfo = engine;
+        m_engineNameLabel->SetText(m_engineInfo.m_name + " " + m_engineInfo.m_version);
+        m_engineNameLabel->update();
+        m_engineNameLabel->setObjectName(m_engineInfo.m_thisEngine ? "thisEngineLabel" : "otherEngineLabel");
+        m_engineNameLabel->setToolTip(m_engineInfo.m_name + " " + m_engineInfo.m_version + " " + m_engineInfo.m_path);
+        m_engineNameLabel->refreshStyle(); // important for styles to work correctly
```
Comment (lumberyard-employee-dm) [inline Code/Tools/ProjectManager/Source/ProjectButtonWidget.cpp:356]: Doesn't Qt have a [QStandardItemModel](https://doc.qt.io/qt-6/model-view-programming.html) that can update the view when a particular entry within the model changes?

Though that is probably overkill for just a button.

File: Code/Tools/ProjectManager/Source/ProjectButtonWidget.h [hunk 8]
```diff
@@ -88,11 +94,13 @@ namespace O3DE::ProjectManager
         Q_OBJECT
 
     public:
-        explicit ProjectButton(const ProjectInfo& m_projectInfo, QWidget* parent = nullptr);
-        ~ProjectButton() = default;
+        explicit ProjectButton(const ProjectInfo& projectInfo, const EngineInfo& engineInfo, QWidget* parent = nullptr);
```
Comment (lumberyard-employee-dm) [inline Code/Tools/ProjectManager/Source/ProjectButtonWidget.h:97]: This function no longer needs to be explicit now that it accepts two parameters.
```suggestion
        ProjectButton(const ProjectInfo& projectInfo, const EngineInfo& engineInfo, QWidget* parent = nullptr);
```

File: Code/Tools/ProjectManager/Source/ProjectsScreen.cpp [hunk 9]
```diff
@@ -293,20 +279,26 @@ namespace O3DE::ProjectManager
             for (const ProjectInfo& project : projectsVector)
             {
                 ProjectButton* currentButton = nullptr;
-                if (!m_projectButtons.contains(QDir::toNativeSeparators(project.m_path)))
+                auto projectButtonIter = m_projectButtons.find(QDir::toNativeSeparators(project.m_path));
```
Comment (lumberyard-employee-dm) [inline Code/Tools/ProjectManager/Source/ProjectsScreen.cpp:282]: If this is stored as QUrl, then the path separators don't need to be taken into account when looking it up
Classes like QUrland AZ::IO::Path takes care of issues related to hashing paths that have different path separators and cases for Windows path and are much better to use in that case than a QString or AZStd::string.

The `QUrl` class has [fromLocalFile](https://doc.qt.io/qt-5/qurl.html#fromLocalFile) and [toLocalFile](https://doc.qt.io/qt-5/qurl.html#toLocalFile) functions for working with system paths.
As the QHash global functions has an overload that uses accepts a QUrl, https://doc.qt.io/qt-5/qhash.html#qHashx, that can be used as the key instead of a QString

File: Code/Tools/ProjectManager/Source/PythonBindings.cpp [hunk 10]
```diff
@@ -431,6 +439,27 @@ namespace O3DE::ProjectManager
...
+                engines.push_back(EngineInfoFromPath(path));
+            }
+        });
+
+        if (!result.IsSuccess())
+        {
+            return AZ::Failure();
+        }
+
+        std::sort(engines.begin(), engines.end());
```
Comment (lumberyard-employee-dm) [inline Code/Tools/ProjectManager/Source/PythonBindings.cpp:459]: This should use `AZStd::sort`.
```suggestion
        AZStd::sort(engines.begin(), engines.end());
```

File: Code/Tools/ProjectManager/Source/Settings.cpp [hunk 11]
```diff
@@ -148,7 +148,8 @@ namespace O3DE::ProjectManager
 
         // Check if buildPath is listed as successfully built
         AZStd::string projectPath = projectInfo.m_path.toStdString().c_str();
-        if (builtPathsResult.contains(projectPath))
+        AZ::IO::FixedMaxPath lexicallyNormalPath = AZ::IO::FixedMaxPath(projectPath).LexicallyNormal();
+        if (builtPathsResult.contains(lexicallyNormalPath.c_str()))
```
Comment (lumberyard-employee-dm) [inline Code/Tools/ProjectManager/Source/Settings.cpp:152]: A couple of suggestion here.
The buildPathsResult should be an `AZStd::set<AZ::IO::Path>` or unordered_set.

The benefit of doing this is that the contains call below, will use the AZ IO Path comparison operators to determine if two paths are equivalent taking into account any differences in path separators and casing on Windows.
For example
```
AZStd::set<AZ::IO::Path> builtPathsResult{"c:\FoO"};
if (buildPathsResult.contains("C:/foo");
```

By default on Windows, AZ::IO::Path\* uses the WindowsPathSeperator and therefore that contains statement returns true to indicate those paths are equivalent on Windows.
On POSIX systems, AZ::IO::Path\* performs a case sensitive compare and returns false as it should.
That logic can be seen here in the [PathParser.inl](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/IO/Path/PathParser.inl#L585-L652)

A construction of an AZStd::string and an AZ::IO::FixedMaxpath can be avoided by directly passing in the conversion of the `projectInfo.m_path` QString` -> `QByteArray` -> `const char*` to the AZ::IO::PathView constructor.

The PathView is string_viewed back so it doesn't have to construct a `fixed_string<1024>` underneath the hood in order to normalize it and store it and another `fixed_string<1024>`
```suggestion
        AZ::IO::FixedMaxPath lexicallyNormalPath = AZ::IO::PathView(projectInfo.m_path.toUtf8().constData()).LexicallyNormal();
        if (builtPathsResult.contains(AZ::IO::PathView(lexicallyNormalPath)))
```

File: Code/Tools/ProjectManager/Source/Settings.cpp [hunk 12]
```diff
@@ -167,15 +168,16 @@ namespace O3DE::ProjectManager
         bool success = GetBuiltSuccessfullyPaths(builtPathsResult);
 
         AZStd::string projectPath = projectInfo.m_path.toStdString().c_str();
+        AZ::IO::FixedMaxPath lexicallyNormalPath = AZ::IO::FixedMaxPath(projectPath).LexicallyNormal();
```
Comment (lumberyard-employee-dm) [inline Code/Tools/ProjectManager/Source/Settings.cpp:171]: Repeat: the projectInfo.m_path can be converted to a temporary QByteArray that is supplied to AZ::IO::Path, for the normalization of the path so that it can be stored.

Since the path is be inserted into into an `AZStd::set<AZ::IO::Path>`, the lexicallyNormalPath member can be moved into it.

```suggestion
        AZ::IO::Path lexicallyNormalPath = AZ::IO::Path(projectInfo.m_path.toUtf8().constData()).LexicallyNormal();
```

File: Code/Tools/ProjectManager/Source/Settings.cpp [hunk 13]
```diff
@@ -167,15 +168,16 @@ namespace O3DE::ProjectManager
...
         if (successfullyBuilt)
         {
             //Add successfully built path to set
-            builtPathsResult.insert(projectPath);
+            builtPathsResult.insert(lexicallyNormalPath.c_str());
```
Comment (lumberyard-employee-dm) [inline Code/Tools/ProjectManager/Source/Settings.cpp:175]: Changing the `GetBuiltSuccessfullyPaths` function to populate a set or unordered set of `AZ::IO::Path` objects allows the path to be moved directly into the set, avoiding a string copy.

```suggestion
            builtPathsResult.insert(AZStd::move(lexicallyNormalPath));
```

File: Code/Tools/ProjectManager/Source/Settings.cpp [hunk 14]
```diff
@@ -167,15 +168,16 @@ namespace O3DE::ProjectManager
...
         }
         else
         {
             // Remove unsuccessfully built path from set
-            builtPathsResult.erase(projectPath);
+            builtPathsResult.erase(lexicallyNormalPath.c_str());
```
Comment (lumberyard-employee-dm) [inline Code/Tools/ProjectManager/Source/Settings.cpp:180]: Changing the lexicallyNormalPath type to an AZ::IO::Path will avoid the need of the `.c_str()` which prevents an additional construction of an AZ::IO::Path(and underlying AZStd::string member on it).

File: Code/Tools/ProjectManager/Source/UpdateProjectSettingsScreen.cpp [hunk 15]
```diff
@@ -120,6 +131,38 @@ namespace O3DE::ProjectManager
...
+        {
+            for (auto engineInfo : result.GetValue<QVector<EngineInfo>>())
+            {
+                if (!engineInfo.m_name.isEmpty())
+                {
+                    combobox->addItem(
+                        QString("%1 (%2)").arg(engineInfo.m_name, engineInfo.m_path),
+                        QStringList{ engineInfo.m_path, engineInfo.m_name });
+
+                    if (!enginePath.isEmpty() && enginePath == engineInfo.m_path)
```
Comment (lumberyard-employee-dm) [inline Code/Tools/ProjectManager/Source/UpdateProjectSettingsScreen.cpp:156]: Shouldn't the enginePath comparison be wrapped in QDir to deal with any differences in separator(or path case on Windows)?

```suggestion
                    if (!enginePath.isEmpty() && QDir(enginePath) == QDir(engineInfo.m_path))
```

File: scripts/o3de/o3de/project_properties.py [hunk 16]
```diff
@@ -133,6 +137,8 @@ def add_parser_args(parser):
                        help='Sets the name for the project.')
     group.add_argument('-pid', '--project-id', type=str, required=False,
                        help='Sets the ID for the project.')
+    group.add_argument('-en', '--engine-name', type=str, required=False,
+                       help='Sets the engine name for the project.')
```
Comment (lumberyard-employee-dm) [inline scripts/o3de/o3de/project_properties.py:141]: Once the engine name can be set this pretty much becomes the inverse of `o3de.py register --project-path` command.
Which instead of using the current o3de.py script engine path to lookup the engine name from the engine.json and then register it with the project, this instead allows the user to directly set the engine name.

I am good with this change though, as I thought we needed a command that can update the project's registered engine without needing to go through the register logic.

File: Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp [hunk 17]
```diff
@@ -186,19 +186,50 @@ namespace O3DE::ProjectManager
...
+                    if (editorPath = (fixedEnginePath / "bin" / AZ_TRAIT_OS_PLATFORM_CODENAME / "profile" / "Default" / "Editor").
                         ReplaceExtension(AZ_TRAIT_OS_EXECUTABLE_EXTENSION);
                         AZ::IO::SystemFile::Exists(editorPath.c_str()))
                     {
                         return editorPath;
                     }
-                    else if (editorPath = (buildConfigurationPath / AZ_TRAIT_OS_PLATFORM_CODENAME
-                        / AZ_BUILD_CONFIGURATION_TYPE / "Editor").
+                    // next try the default build path
+                    else if (editorPath = (fixedEnginePath / "build" / "windows_vs2019" / "bin" / "profile" / "Editor").
```
Comment (lumberyard-employee-dm) [inline Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp:226]: We shouldn't hardcode "windows_vs2019" into the path check.

This should be queried, especially since the build directory that is used on Windows by **ProjectManager** is hardcoded to "[windows](https://github.com/o3de/o3de/blob/development/Code/Tools/ProjectManager/Platform/Windows/ProjectManagerDefs_windows.cpp#L12)" not "windows_vs2019"

**Review by lumberyard-employee-dm — CHANGES_REQUESTED** [review]

File: Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp (hunk 17 above)
Comment (lumberyard-employee-dm) [reply Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp:226]: Also the implementation for this code search logic on Linux and and Mac is missing.

File: scripts/o3de/o3de/manifest.py (hunk 6 above)
Comment (AMZN-alexpete) [reply scripts/o3de/o3de/manifest.py:329]: Ah I need to include a test for this code anyways to prove what it's doing.

The goal of this code is, given the absolute project path like `c:\o3de\AutomatedTesting` which isn't registered in the `o3de_manifest.json`, find out if it was registered in any `engine.json`, by comparing the absolute path of the project with the absolute path of every project registered with that `engine.json`.

`get_engine_projects` returns an absolute path to the projects - so if the engine is `C:/o3de` and the project is `AutomatedTesting` you get back `C:/o3de/AutomatedTesting`,  and if the engine is `D:/o3de-sdk` and the project is still `AutomatedTesting` you get back `D:/o3de-sdk/AutomatedTesting`.  In both cases, I would compare the passed in absolute project path to see which one is the correct engine.

It's really just a fallback for when a project isn't registered with an engine correctly so likely it can be removed and some kind of warning/error displayed.

File: Code/Tools/ProjectManager/Source/ProjectButtonWidget.cpp (hunk 7 above)
Comment (AMZN-alexpete) [reply Code/Tools/ProjectManager/Source/ProjectButtonWidget.cpp:356]: Yes it does! and we should total be using a model more as we scale up the number of objects and improve performance,  it's on the backlog.

File: Code/Tools/ProjectManager/Source/ProjectsScreen.cpp (hunk 9 above)
Comment (AMZN-alexpete) [reply Code/Tools/ProjectManager/Source/ProjectsScreen.cpp:282]: `project.m_path` is a QString, but I agree we should change it to a path type like QDir or AZ::IO::Path,  QUrl might be more than we need.

File: Code/Tools/ProjectManager/Source/UpdateProjectSettingsScreen.cpp (hunk 15 above)
Comment (AMZN-alexpete) [reply Code/Tools/ProjectManager/Source/UpdateProjectSettingsScreen.cpp:156]: Good catch, that would be safer. This code is currently relying on Python returning the same kind of paths from different functions, but I've already run into instances where that's not guaranteed the same.

File: scripts/o3de/o3de/project_properties.py (hunk 16 above)
Comment (AMZN-alexpete) [reply scripts/o3de/o3de/project_properties.py:141]: We need a way for a user to register a project with the o3de_manifest and specify the engine it should use without updating the actual `engine.json`and this is one way to do that.  The other option I considered was to modify register.py so you can provide something that indicates you don't want to change `engine.json`  like `o3de.py register --project-path <path> --engine-name <name>`  but this may be confusing to users who may think it's just another way to register it with an engine.

File: Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp (hunk 17 above)
Comment (AMZN-alexpete) [reply Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp:226]: My thinking here was, if a user followed our [default build the engine documentation](https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/building-windows/#build-the-engine) which uses "build/windows_vs2019", then the binaries might be there.  This directory is also used in the [documentation for running the editor for a source engine](https://www.o3de.org/docs/welcome-guide/create/creating-projects-using-cli/creating-windows/#build-the-o3de-project).  Thoughts?

Comment (AMZN-alexpete) [reply Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp:226]: The other tricky one is if a user creates their own SDK and distributes it to their team with some build path other than the default, how will Project Manager find the SDK engine binaries on a user's machine where they haven't compiled the project or the engine?  It seems in this case we'd need an entry in the `engine.json` specifying where the relative path to the binaries.

File: Code/Tools/ProjectManager/Source/ProjectsScreen.cpp (hunk 9 above)
Comment (AMZN-alexpete) [reply Code/Tools/ProjectManager/Source/ProjectsScreen.cpp:282]: I started to convert this and other path types to AZ::IO::Path but it ballooned really quickly into a lot of changes so I'm going to address that in a separate PR dedicated to that change alone.

File: Code/Tools/ProjectManager/Source/Settings.cpp (hunk 11 above)
Comment (AMZN-alexpete) [reply Code/Tools/ProjectManager/Source/Settings.cpp:152]: I'm going to leave the Settings changes out of this PR because they are not related to the engine changes and a little extra work is necessary to make sure the settings are backwards compatible.  Tracking with https://github.com/o3de/o3de/issues/10948

File: Code/Tools/ProjectManager/Source/Settings.cpp (hunk 13 above)
Comment (AMZN-alexpete) [reply Code/Tools/ProjectManager/Source/Settings.cpp:175]: I'm going to leave the Settings changes out of this PR because they are not related to the engine changes and a little extra work is necessary to make sure the settings are backwards compatible.  Tracking with https://github.com/o3de/o3de/issues/10948

File: Code/Tools/ProjectManager/Source/Settings.cpp (hunk 14 above)
Comment (AMZN-alexpete) [reply Code/Tools/ProjectManager/Source/Settings.cpp:180]: I'm going to leave the Settings changes out of this PR because they are not related to the engine changes and a little extra work is necessary to make sure the settings are backwards compatible.  Tracking with https://github.com/o3de/o3de/issues/10948

File: Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp (hunk 17 above)
Comment (lumberyard-employee-dm) [reply Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp:226]: We don't need an entry in the `engine.json`, when CMake configures, we generate a Settings [Registry file with the path relative path information to the build directory](https://github.com/o3de/o3de/blob/development/cmake/Projects.cmake#L95-L122) in it when configuring for monolithic builds or on a platform where we don't build any tools application(Android and iOS).

We can just update that logic to always generate by removing the monolithic build checks

Comment (AMZN-alexpete) [reply Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp:226]: It looks like that `project_build_path` setreg key will provide the project binary path, not the engine binary path where the Editor.exe is.

Also, it appears that on Mac we write a `AZ::SettingsRegistryMergeUtils::FilePathKey_InstalledBinaryFolder` key which contains the path to the engine binaries - maybe we could do something similar for the other platforms?

Comment (AMZN-alexpete) [reply Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp:226]: Ah it looks like the version of OSX I have (Catalina) is no longer supported by O3DE le-sigh.

Comment (lumberyard-employee-dm) [reply Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp:226]: Yes we can write out the relative path for the Editor for other platforms into a [BinariesInstallPath.setreg](https://github.com/o3de/o3de/blob/development/cmake/Platform/Mac/Install_mac.cmake#L11-L36) file.

But we shouldn't use the exact logic that is posted in the Install_Mac.cmake script in the install scripts for Linux and Windows.
That logic is using the `CMAKE_RUNTIME_OUTPUT_DIRECTORY` for the binaries directory, where the directory we actually want is the directory where Editor gets output to, which may be a subdirectory of the `CMAKE_RUNTIME_OUTPUT_DIRECTORY`

Also FYI this is the value of @runtime_output_directory@ variable that is being configured into the BinariesInstallPath.setreg: https://github.com/o3de/o3de/blob/development/cmake/Platform/Common/Install_common.cmake#L50

Comment (lumberyard-employee-dm) [reply Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp:226]: What I think we should do is update the template in the [Install_mac.cmake](https://github.com/o3de/o3de/blob/development/cmake/Platform/Mac/Install_mac.cmake#L15-L27) script add a couple of new SettingsRegistry keys. `InstallEditorFolder` and `InstalledAssetProcessorFolder`.

We can look up the RUNTIME_OUTPUT_DIRECTORY properties of the Editor and AssetProcessor TARGETS in cmake to find their exact directory.
```cmake
get_target_property(editor_runtime_output_directory Editor RUNTIME_OUTPUT_DIRECTORY)
get_target_property(assetprocessor_runtime_output_directory AssetProcessor RUNTIME_OUTPUT_DIRECTORY)
```

Putting it all together we can update the `Install_<platform>.cmake` scripts to have the following
```cmake
set(installed_binaries_path_template [[
{
    "Amazon": {
        "AzCore": {
            "Runtime": {
                "FilePaths": {
                    "InstalledBinariesFolder": "@runtime_output_directory@",
                    "InstalledEditorFolder": "@editor_runtime_output_directory@",
                    "InstalledAssetProcessorFolder": "@assetprocessor_runtime_output_directory@"
                }
            }
        }
    }
}]]
)

get_target_property(editor_runtime_output_directory Editor RUNTIME_OUTPUT_DIRECTORY)
get_target_property(assetprocessor_runtime_output_directory AssetProcessor RUNTIME_OUTPUT_DIRECTORY)

# This setreg file will be used by all of our installed app bundles to locate installed
# runtime dependencies. It contains the path to binary install directory relative to 
# the installed engine root.
string(CONFIGURE "${installed_binaries_path_template}" configured_setreg_file)
file(GENERATE
    OUTPUT ${CMAKE_BINARY_DIR}/runtime_install/$<CONFIG>/BinariesInstallPath.setreg
    CONTENT "${configured_setreg_file}"
)
```

Comment (AMZN-alexpete) [reply Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp:226]: In order to make sure we at least get support for Windows & Linux in before we cut the next release branch, I'm going to break out the Mac support into a separate ticket https://github.com/o3de/o3de/issues/10971 and reference these comments as the intended solution.

Comment (lumberyard-employee-dm) [reply Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp:226]: The next release branch is being cut in 4 weeks.

The code I posted would solve the issue for all platforms.
It just needs to be put in the appropriate `Install_mac.cmake`, `Install_linux.cmake` and `Install_windows.cmake` files.

File: scripts/o3de/o3de/manifest.py (hunk 6 above)
Comment (AMZN-alexpete) [reply scripts/o3de/o3de/manifest.py:323]: I've added tests for this code that show it is able to find the engine in the parent folder.

Comment (lumberyard-employee-dm) [reply scripts/o3de/o3de/manifest.py:323]: It would be simpler to just scan upwards from the project path to a directory with an engine.json within it.

That would skip the need to lookup the manifest engines

```python
engine_path = utils.find_ancestor_dir_containing_file(pathlib.PurePath('engine.json'), resolved_project_path)
if engine_path:
    projects = get_engine_projects(engine_path)
    # ...
```

File: scripts/o3de/tests/test_manifest.py [hunk 18]
```diff
@@ -279,3 +302,54 @@ def get_gem_json_data(gem_name: str = None, gem_path: str or pathlib.Path = None
...
+            pytest.param(pathlib.Path('C:/project1'), 
+                'engine2', 
+                {'engine1': pathlib.Path('C:/engine1'), 'engine2': pathlib.Path('D:/engine2')},
+                pathlib.Path('D:/engine2')),
+            pytest.param(pathlib.Path('C:/engine1/project1'), 
+                '', 
+                {'engine1': pathlib.Path('C:/engine1'), 'engine2': pathlib.Path('D:/engine2')},
+                pathlib.Path('C:/engine1')),
+        ]
+    )
```
Comment (lumberyard-employee-dm) [inline scripts/o3de/tests/test_manifest.py:329]: We should add a failure test case as well, for when the project doesn't have an engine registered and it isn't a subpath of engine root directory

File: Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp [hunk 19]
```diff
@@ -186,19 +187,45 @@ namespace O3DE::ProjectManager
...
+            // different engine we must find the Editor executable for that engine
+            if(auto engineResult = PythonBindingsInterface::Get()->GetProjectEngine(projectPath.Native().data()); engineResult)
+            {
+                auto engineInfo = engineResult.GetValue<EngineInfo>();
+                if (!engineInfo.m_thisEngine)
+                {
+                    AZ::IO::FixedMaxPath fixedEnginePath{ engineInfo.m_path.toUtf8().constData() };
+                    // try the default sdk path
+                    // in the future we may be able to use additional .setreg entries to locate an alternate binary path
+                    if (editorPath = (fixedEnginePath / "bin" / AZ_TRAIT_OS_PLATFORM_CODENAME / "profile" / "Default" / "Editor").
```
Comment (lumberyard-employee-dm) [inline Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp:222]: This is fine for now.

File: Code/Tools/ProjectManager/Source/ProjectManagerWindow.cpp [hunk 20]
```diff
@@ -7,14 +7,23 @@
...
     {
-        setWindowTitle(tr("O3DE Project Manager"));
+        if (auto engineInfoOutcome = PythonBindingsInterface::Get()->GetEngineInfo(); engineInfoOutcome)
+        {
+            auto engineInfo = engineInfoOutcome.GetValue<EngineInfo>();
+            setWindowTitle(QString("%1 %2 Project Manager").arg(engineInfo.m_name.toUpper(), engineInfo.m_version));
+        }
+        else
+        {
+            setWindowTitle("O3DE Project Manager");
```
Comment (AMZN-Phil) [inline Code/Tools/ProjectManager/Source/ProjectManagerWindow.cpp:25]: Was the removal of tr here intended?

Comment (AMZN-alexpete) [reply Code/Tools/ProjectManager/Source/ProjectManagerWindow.cpp:25]: It was, but I think my original reason which was to avoid the engine and application name not matching what is in the docs, is not necessary and will add back the tr() so we can translate the app name in the future if we want.

**Review by lumberyard-employee-dm — APPROVED** [review]

**Review by AMZN-Phil — APPROVED** [review]
