### PR TITLE
Fix #18874 - Project manager: Message box when closing if an action is going on

### LINKED ISSUE #18874: Missing Feature - Project Manager exit during build does not prompt "are you sure?"
**Describe the bug**
When building a project in the Project Manager, clicking exit does not prompt you for "You currently have a project bulding, are you sure you want to exit?"

**Assets required**
Project Manager, and project to build.

**Steps to reproduce**
1. Create project.
2. Start  project build.
3. Exit Project Manager
4. Window exits out without any interruptions to preserve the build.

**Expected behavior**
"You currently have a project bulding, are you sure you want to exit?" Y/N

**Actual behavior**
Window exits, build gets interrupted.

**Found in Branch**
24.09.02 Project Manager

**Desktop/Device (please complete the following information):**
 - Windows 10

### PR DESCRIPTION
**Pull request by LafLaurine**
## What does this PR do?

Fix #18874 so that users are aware (by a message box) that they are closing the Project Manager while an action (export or build) is in progress.

image

## How was this PR tested?

Local Windows build.

- Start project build
- Exit project manager
- A message box appears to indicate that an action on a project is going on
- Clicking "Yes" closes the project manager
- Clicking "No" leaves the project manager open
- No message box is showing on close when no action is going on

Same goes on when exporting a project

### CODE REVIEW

File: Code/Tools/ProjectManager/Source/ProjectManagerBuses.h [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+ *
+ */
+
+#pragma once
+
+#include <AzCore/EBus/EBus.h>
+
+namespace O3DE::ProjectManager
+{
+    class ProjectManagerUtilityRequests : public AZ::EBusTraits
```
Comment (LafLaurine) [inline Code/Tools/ProjectManager/Source/ProjectManagerBuses.h:15]: Could have a better name, if you have any idea, please feel free to suggest it

**Review by lsemp3d — APPROVED** [review]

**Review by nick-l-o3de — APPROVED** [review]
