### PR TITLE
Network Heartbeats Sent While Main Thread is Blocked

### LINKED ISSUE #14659: Multiplayer Timeout If Level Load Too Long
Servers will terminate a client connection if the client takes too long to load a level. The default _net_udpDefaultTimeoutMs_ is 10 seconds, the client/server wont send/receive any network traffic during the level load leading the client to disconnect. A real level could take a minute to load and require a loading screen, etc. The network should be able to handle long level load times.

**Steps to reproduce**

1. For the purposes of testing it helps to reduce _net_udpDefaultTimeoutMs_ to something small like 1 second (1000 ms)
2. Ensure timeouts are enabled _net_UdpTimeoutConnections true_
3. Create a level with enough entities to cause a level load time longer than _net_udpDefaultTimeoutMs_
4. Launch a server and begin hosting the large level
5. Open a client and connect

**Expected behavior**
Client connects to the host, loads the large level, and begins the network simulation

**Actual behavior**
The client connects, but is then disconnected after a second because it did not send/receive any network packets while the level was being loaded. The spawnable system should spread out the level load over multiple ticks, or asynchronously so that the multiplayer system can continually send heartbeat packets 
image

**Found in Branch**
development February 17 2023

----
## Research Spike
**Cvars to debug network traffic:**
 --LoggerSystemComponent.EnableLog NET_Acks 
 --LoggerSystemComponent.EnableLog NET_CorePackets 
 --LoggerSystemComponent.EnableLog NET_DebugPacketSend

**Remove Non-Essential Network Traffic**
CorePackets::Heartbeat should be keeping a valid connection alive even during times of lag. As long as the game is running (not crashed, shutdown), heartbeats should persist. As such, it's good to remove other (non-heartbeat) network traffic for debugging.

_Note: This is not to say games _should_ stay connected if the client becomes too laggy. Developers may want to add game logic which terminates a connection should an individual cpu become too laggy to maintain good gameplay._ 

 1. Stop sending _MultiplayerPackets::SyncConsole_
       This is found in MultiplayerSystemComponent.cpp and is the server sending over 1000s of cvars. See related https://github.com/o3de/o3de/issues/16587
 2. Stop sending _MultiplayerPackets::EntityUpdate_. While required for playing a real game, we just want to test heartbeats and EntityUpdates adds a lot of traffic.

### Quick Validations
1. **Question:** Does moving the client code to send _MultiplayerPackets::ReadyForEntityUpdates_ until AFTER the level is loaded resolve this timeout issue? Current _MultiplayerPackets::ReadyForEntityUpdates_ is send once the level begins loading, _OnRootSpawnableAssigned_. _OnRootSpawnableReady_ is the callback once all the entities are finished loading. 
   Answer: No. The timeout still occurs.

2. **Question:** Are we should it's the level load causing the problem?
    Answer: Yes. Removing the _loadlevel_ command from MultiplayerSystemComponent shows that the connect remains alive. Even after disabling _MultiplayerPackets::EntityUpdate_ from being sent, the heartbeat packets keep the connection alive.

### Why Isn't Server Sending Heartbeats As Timeout Draws Near?
After the client begins level loading and goes dark, the server isn't sending any heartbeat requests; ie `CorePackets::HeartbeatPacket(true)`, where `true` signifies that the receiver should sent a heartbeat packet back to acknowledge that it's still alive. I was expecting the server to send heartbeats during the time it's not receiving any traffic from client.

The server does call UdpNetworkInterface::HandleConnectionTimeout, but there's an explicit check which causes only clients to send/request a heartbeat.
`if (udpConnection->GetConnectionRole() != ConnectionRole::Connector)`

<strike>I cannot imagine why the server wouldn't want to request heartbeats during this time of radio silence. </strike>
EDIT: Servers intentional do NOT send request heartbeats in order to hear back if a client is alive. If the server doesn't receive any network traffic from the player for x-seconds, then that UDP connection is disconnected. The player is the one requesting to connect, if they then don't send any information back, the connection is cut. In that sense, it's the client's responsibility to keep itself alive. The server will, however, send a non-request heartbeat if it's received a lot of the packets from the client, but hasn't sent anything back in a while (see cvar [net_UdpMaxUnackedPacketCount](https://github.com/o3de/o3de/blob/9f91681991d21dbd2e9260753d282c3021911159/Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpConnection.cpp#L22)).

There also appears to be a bug around how often `UdpNetworkInterface::HandleConnectionTimeout` is called. It's called once every time _net_udpDefaultTimeoutMs_ milliseconds go by without hearing from the client. This might sound good, but really, the logic to heartbeat ought to be occurring _net_UdpUnackedHeartbeats_ times in-between _net_udpDefaultTimeoutMs_. IE, if the timeout is 10 seconds, and _net_UdpUnackedHeartbeats_ is 5, should we try to send 5 heartbeats during those 10 seconds (1 beat per 2 seconds)?

In either case, even if a heart beat is sent, the client still isn't responding back until the level is finished loading. A responsive client will be a requirement before any other bugs are crushed.

### Current Reading and Handling of Packets
Reading packets off the socket and handling packets occur on 2 separate threads.

**Reading packets** occurs using a `TimedThread` wrapper class that makes it easy to have a time throttled thread. `UdpReaderThread` derives from `TimedThread` and starts updating as soon as it's registered with a UDP socket.
`UdpReaderThread::OnUpdate` is called automatically at regular intervals and packets are read off the socket, and are stored for later when the main thread has time to handle the packets.

**Handling packets** occurs on the main-thread starting with  `NetworkingSystemComponent::OnSystemTick()`. Handling heartbeats is what's also responsible for sending back heartbeat responses, which is why it's important for catching time outs.

Most packets should be handled on the main thread since most will result in game logic. However, core packets aren't broadcast out into the game for anyone to handle, instead they are handled especially by the udp connection's _HandleCorePacket_ function. There are only 5 types of core packets: _InitiateConnectionPacket_, _ConnectionHandshakePacket_, _TerminateConnectionPacket_, _HeartbeatPacket_, and _FragmentedPacket_. _Heartbeat_ is particular is quite self-contained, its only job is to pong-back a heartbeat. 

Moving forward, could heartbeats be moved off the mainthread, and handled directly from the `UdpReaderThread`? To answer this, it's important to know how packets are sent. If packets are sent on the main-thread, then even if we send a pong-heartbeat from  the UDP reader thread, it'll only end up stored in basket once the main-thread is done loading the level.

### Sending Packets from Other Threads?
UdpSocket::SendInternal results in the operating system directly calling the operating system's networking `sendto` from whatever thread the call came from; ie, there is no queuing up of packets to be sent later by the main-thread. Luckily, there's already a precedent set for sending packets from multiple threads; see `sv_multithreadedConnectionUpdates` and `UdpConnection::m_sendPacketMutex`. This existing code allows us to confidently (and safely) send heartbeat packets from another thread.

### Detecting a Heartbeat from Raw Bytes
The socket only receives a raw byte stream from the network. These bytes must be interpreted using AzNetworking to determine which packet is actually being received. Normally this occurs inside of `UdpNetworkInterface::Update()`, but if we want to detect heartbeats as soon as they are received from inside the network reader thread, we'll have to know how packets are interpreted.
Moving forward, we may want to deserialize all incoming packet headers from the reader-thread, just to determine if it's a heartbeat. 

**Heartbeat structure**
1. Encryption: Before reading a packet, it may need to be decoded.
2. Packet Header
   a. Compression: The packet may have undergone compression; header flag can be used to determine if compression is ON or OFF.
   b. Packet Type: Packet type 4 is a heartbeat. `CorePackets::PacketType::HeartbeatPacket = 4`
3. Request Response:
    a. True. A true value means someone is wondering if we're still alive; we should send back a heartbeat right away to let the other side know the app is still running. 
    b. False. A false value means this heartbeat is a pong-packets back to us (the requestor); these are read and tell us the other connect is still alive.

### Performance Impact of Deserializing Headers
We'll need to make sure deserializing all of the packet headers from the reader thread doesn't impact performance. Currently, `UdpNetworkInterface::Update` discards packets if processing packets takes too long (see _net_UdpPacketTimeSliceMs_). If performance is impacted, perhaps we can open a port specifically for heartbeats; we'll know this port is only going to send/receive heartbeats on it. Another option is to at least cache the header information so that `UdpNetworkInterface::Update` doesn't need to re-calculate the header.
`NetworkInterfaceMetrics` should be updated to include a `m_updateHeartbeatsTimeMs`. Tests can be ran to see how much `m_updateHeartbeatsTimeMs` is adding.

### Throttling Reader Thread
@todo
reuse socket?
https://github.com/o3de/o3de/blob/development/Code/Framework/AzNetworking/AzNetworking/Utilities/NetworkCommon.cpp#L64-L69

### PR DESCRIPTION
**Pull request by AMZN-Gene**
UdpHeartbeat thread will check if main thread is blocked and sends a heartbeat packet; ensures server doesn't give up on the client while it's attempting to load the level.

Tested setting the udp timeout (_net_udpDefaultTimeoutMs_) to 2 seconds (normal value is 10 seconds) and using Multiplayer Sample and loading into a level that normally takes around 15-20 seconds. See that heartbeats are received by the server even while the player is bogged down loading the the level and unable to process network traffic.

Fixes #14659

### CODE REVIEW

File: Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpHeartbeatThread.cpp [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+            m_udpNetworkInterfaces.push_back(updNetworkInterface);
+        }
+
+        if (!IsRunning())
+        {
+            Start();
+        }
+    }
+
+    void UdpHeartbeatThread::UnregisterNetworkInterface(UdpNetworkInterface* updNetworkInterface)
```
Comment (AMZN-alexpete) [inline Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpHeartbeatThread.cpp:76]:
```suggestion
    void UdpHeartbeatThread::UnregisterNetworkInterface(UdpNetworkInterface* udpNetworkInterface)
```

File: Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpHeartbeatThread.h [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+    public:
+
+        UdpHeartbeatThread();
+        ~UdpHeartbeatThread() override;
+        void RegisterNetworkInterface(UdpNetworkInterface* udpNetworkInterface);
+        void UnregisterNetworkInterface(UdpNetworkInterface* udpNetworkInterface);
+
+    private:
+
+        //! Helper to determine if a given socket is monitored by this reader thread instance
```
Comment (AMZN-alexpete) [inline Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpHeartbeatThread.h:31]:
```suggestion
```

File: Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpHeartbeatThread.cpp [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+                        connection.SendUnreliablePacket(CorePackets::HeartbeatPacket(false));
+                    }
+                };
+
+                udpInterface->GetConnectionSet().VisitConnections(sendNetworkUpdates);
+            }
+        }
+    }
+
+    void UdpHeartbeatThread::RegisterNetworkInterface(UdpNetworkInterface* updNetworkInterface)
```
Comment (AMZN-alexpete) [inline Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpHeartbeatThread.cpp:63]:
```suggestion
    void UdpHeartbeatThread::RegisterNetworkInterface(UdpNetworkInterface* udpNetworkInterface)
```

File: Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpHeartbeatThread.h [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+        void OnStart() override;
+        void OnStop() override;
+        void OnUpdate(AZ::TimeMs updateRateMs) override;
+
+        AZ_DISABLE_COPY_MOVE(UdpHeartbeatThread);
+
+        AZStd::vector<UdpNetworkInterface*> m_udpNetworkInterfaces;
```
Comment (AMZN-alexpete) [inline Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpHeartbeatThread.h:38]: Do we need multiple network interfaces?  Is there a situation where we are connected to multiple servers?

**Review by AMZN-alexpete — COMMENTED** [review]
Looking good, just a few suggestions.  It looks like this new thread running on server and client - am I reading that right?

File: Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpHeartbeatThread.cpp [hunk 5]
```diff
@@ -0,0 +1,92 @@
...
+                {
+                    if (connection.GetConnectionRole() == ConnectionRole::Connector)
+                    {
+                        connection.SendUnreliablePacket(CorePackets::HeartbeatPacket(false));
+                    }
+                };
+
+                udpInterface->GetConnectionSet().VisitConnections(sendNetworkUpdates);
+            }
+        }
```
Comment (mbalfour-amzn) [inline Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpHeartbeatThread.cpp:60]: 1. Seems like this should lock m_mutex. Right now, I don't think it's providing any protection against multi-threaded access to m_udpNetworkInterfaces.
 
2. Why is this sending a heartbeat for *each* interface that hasn't sent a heartbeat in a while? Is this because the different interfaces might be going to different servers? Some comments explaining the concept of this loop would be helpful here. Also, it's not clear to me, is the assumption that the connections might also be sending heartbeat packets from other threads (like the main thread) as well? If so, that should definitely get spelled out either here or at the top of the file since it's not obvious just from reading this code. Maybe that's what the comments about "sends a heartbeat if the main thread is blocked" is supposed to mean, but if so, I wasn't quite getting that meaning from that comment and this logic. It isn't really clear how it would *only* be sending it here if the main thread is blocked, or for that matter, *why* we wouldn't just send it here all the time.

**Comment by AMZN-Gene** [comment]
> Looking good, just a few suggestions. It looks like this new thread running on server and client - am I reading that right?

Good eye! Yes... technically a server can still be a connector. IE, a server may connect to another server which in turn causes it to the load a level and block main thread.

File: Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpHeartbeatThread.cpp (hunk 5 above)
Comment (AMZN-Gene) [reply Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpHeartbeatThread.cpp:60]: Aye, the name "heartbeat" is unfortunate, because these DO NOT happen at regular intervals like an **actual** heartbeat

The cases a heartbeat is sent is...
_Note: A request heartbeat is packet which when received, the receiver will sent back a heartbeat._

1. Server will send a non-request heartbeat if it has received 10 packets (_net_UdpMaxUnackedPacketCount_) without having sent one back in a while. This is to just acknowledge to the client "hey, you're sending me stuff, I'm still here, but just haven't had a need to send anything back to you in a while"
2. Client will sent a 5 request heartbeats  (_net_UdpUnackedHeartbeats_) over 10 seconds (_net_UdpDefaultTimeoutMs_)  if it's worried the server has died. "Hey server, I'm starting to get worried, you still there?"
3. NEW Connectors (usually clients) will send heartbeats to the server if their mainthread is blocked (example: level loading) and so for sure have not sent any packets in a while. 

This does make me want to fix the system further to simply move more of the logic to the heartbeat thread, instead of what feels more like a one-off patch.

Comment (AMZN-alexpete) [reply Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpHeartbeatThread.cpp:60]: It's more of a "keep alive" than a heartbeat, but I can see that a consistent heartbeat would be wasteful in a typical game scenario where we're constantly receiving frequent network traffic from clients/servers.

Comment (AMZN-alexpete) [reply Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpHeartbeatThread.cpp:60]: I agree we should lock `m_mutex` unless there's some kind of gaurantee no one will try to register/unregister during OnUpdate

File: Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpHeartbeatThread.cpp [hunk 6]
```diff
@@ -0,0 +1,92 @@
...
+    }
+
+    void UdpHeartbeatThread::OnStop()
+    {
+    }
+
+    void UdpHeartbeatThread::OnUpdate([[maybe_unused]]AZ::TimeMs updateRateMs)
+    {
+        AZ::TimeMs currentTime = AZ::GetElapsedTimeMs();
+
```
Comment (AMZN-alexpete) [inline Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpHeartbeatThread.cpp:43]:
```suggestion
        AZ::TimeMs currentTime = AZ::GetElapsedTimeMs();

        AZStd::scoped_lock<AZStd::mutex> lock(m_mutex);
```

File: Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpHeartbeatThread.cpp (hunk 5 above)
Comment (AMZN-Gene) [reply Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpHeartbeatThread.cpp:60]: > It's more of a "keep alive" than a heartbeat, but I can see that a consistent heartbeat would be wasteful in a typical game scenario where we're constantly receiving frequent network traffic from clients/servers.

I'd like to change the packet from CorePackets::Heartbeat to CorePackets::KeepAlive. Conceptually, that's exactly correct.

**Review by AMZN-alexpete — APPROVED** [review]

**Review by lsemp3d — APPROVED** [review]

File: Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpHeartbeatThread.h (hunk 4 above)
Comment (AMZN-Gene) [reply Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpHeartbeatThread.h:37]: Yep! This can even be used for servers connected to other servers (multi-server setup).
