### PR TITLE
Invalidate pointer to prevent undifined behavior in ArticulationLinkComponent

### LINKED ISSUE #945: [Simulation Interfaces][Articulations] Crash on despawnin articulation
**Describe the bug**
When we despawn spawnable with articulation, we crash.

**Assets required**
o3de-extras/development

**Steps to reproduce**
1. Enable SampleRobot Gems
2. Enable Simulation interface 
3. Build and run game launcher
4. Run script:
```shell
# spawn
ros2 service call /set_simulation_state simulation_interfaces/srv/SetSimulationState "{state: {state: 1}}"

ros2 service call /spawn_entity simulation_interfaces/srv/SpawnEntity "{
  name: 'foo', 
  allow_renaming: false,
  uri: 'product_asset:///pandarobot/pandarobot.spawnable'
}"
sleep(5)
#despawn
ros2 service call /delete_entity simulation_interfaces/srv/DeleteEntity "{
  entity: 'foo'
}"
```

**Expected behavior**
Robot appears and despawn 

**Actual behavior**
Crash

**Screenshots/Video**

https://github.com/user-attachments/assets/8d7101f3-62db-420a-9537-bae3ea963ee3

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de)  2505.0  46c647db74ede9c95897f40468f3c2cac59f3532

and [o3de/o3de-extras](https://github.com/o3de/o3de-extras) development

### PR DESCRIPTION
**Pull request by michalpelka**
## What does this PR do?

Fixes https://github.com/o3de/o3de-extras/issues/945

## How was this PR tested?

https://github.com/user-attachments/assets/4d5874f4-01e3-40ad-a102-fb0c8daaee9b

I've ran shell script from https://github.com/o3de/o3de-extras/issues/945

### CODE REVIEW

**Review by pijaro — APPROVED** [review]

File: Gems/PhysX/Core/Code/Source/ArticulationLinkComponent.cpp [hunk 1]
```diff
@@ -550,6 +550,10 @@ namespace PhysX
 
         PHYSX_SCENE_READ_LOCK(pxScene);
 
+        if (!m_articulation)
+        {
+            return;
+        }
         if (m_articulation->isSleeping())
         {
             return;
```
Comment (patrykantosz) [inline Gems/PhysX/Core/Code/Source/ArticulationLinkComponent.cpp]:
```suggestion
        if (!m_articulation || m_articulation->isSleeping())
        {
            return;
```

It should be enough thanks to short-circuit evaluation.

**Review by jhanca-robotecai — APPROVED** [review]
