### PR TITLE
Fix entire file hierarchy being displayed in project centric builds

### LINKED ISSUE #2552: The asset browser shows the root file system of your computer and includes folders just named '\'
**Describe the bug**
If you use project-centric mode, with the project outside the engine, the asset browser shows the entire folder tree including a folder just called '\\'

image

**To Reproduce**
1. Create a project (external to engine)
2. Compile that project  (project centric mode)
3. Open the editor
4. See the asset browser

**Expected behavior**
Not sure what's expected here.  This looks really weird (see screenshot above), my impression was that 'watch folders' for assets could come from many places/drives/locations and the UI is going to be very cluttered and difficult to navigate if each drive is shown all the way down to the root folder, using up valuable space.
**Desktop/Device (please complete the following information):**
 - windows 10 pc

### LINKED ISSUE #13462: Asset Browser: Whole filesystem hierarchy is shown when project is not under engine folder
## Steps to reproduce

1. Create a new project _not_ under the engine folder. E.g. on your desktop
2. Open the project in the Editor

# Expected result

Engine and project assets are shown next to each other in the asset browser, same as when the project is located in the engine folder:

Image

## Actual result

Image

The root of the filesystem is shown in the Asset Browser and the tree is filtered to engine and project assets.

### PR DESCRIPTION
**Pull request by dtamkin1**
Signed-off-by: Daniel Tamkin <jotamkin@amazon.com>

Updates the asset browser and asset picker file hierarchy to only show the folders that contain the engine and the project in a project centric build.
Resolves #13462.
Resolves #2552.

Previous behavior:
image

New behavior:
image

## How was this PR tested?

Manually with a project centric and an engine centric build

### CODE REVIEW

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.h [hunk 1]
```diff
@@ -89,6 +90,7 @@ namespace AzToolsFramework
                 AZStd::unordered_set<AssetBrowserEntry*>& visitedSet);
 
             bool m_isInitialUpdate = false;
+            bool inProjectDirectory = false;
```
Comment (gadams3) [inline Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.h:93]:
```suggestion
            bool m_inProjectDirectory = false;
```

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp [hunk 2]
```diff
@@ -391,6 +393,40 @@ namespace AzToolsFramework
...
+            // If the project is not inside the root engine folder
+            if (!m_projectPath.IsRelativeTo(m_enginePath))
+            {
+                // Update the parent to be the project directory
+                AZ::IO::FixedMaxPath directory;
+                if (absolutePathView.IsRelativeTo(m_projectPath) && !inProjectDirectory)
+                {
+                    for (auto pathIter = m_projectPath.begin(); pathIter != m_projectPath.end(); ++pathIter)
+                    {
+                        if (std::next(pathIter) == m_projectPath.end())
```
Comment (lumberyard-employee-dm) [inline Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp:405]: AZStd::next should be used

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp [hunk 3]
```diff
@@ -391,6 +393,40 @@ namespace AzToolsFramework
...
+                        {
+                            break;
+                        }
+                        directory = directory / *pathIter;
```
Comment (lumberyard-employee-dm) [inline Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp:409]: This logic is just copying the `m_projectPath` to the `directory`
```suggestion
                directory = m_projectPath;
```

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp [hunk 4]
```diff
@@ -391,6 +393,40 @@ namespace AzToolsFramework
...
+                {
+                    for (auto pathIter = m_enginePath.begin(); pathIter != m_enginePath.end(); ++pathIter)
+                    {
+                        if (std::next(pathIter) == m_enginePath.end())
+                        {
+                            break;
+                        }
+                        directory = directory / *pathIter;
+                    }
+                    parent->m_fullPath = directory;
```
Comment (lumberyard-employee-dm) [inline Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp:425]: Same here with the enginePath directory.

All this is doing is copying the m_enginePath variable to parent->m_fullPath
```suggestion
                parent->m_fullPath = m_enginePath;
```

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp (hunk 3 above)
Comment (dtamkin1) [reply Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp:409]: `m_projectPath` returns the path with the project folder, so this logic copies the path leading up to the project folder, which is used as the parent path. I wasn't sure of a better method to get the path without the project folder at the end.

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp (hunk 4 above)
Comment (dtamkin1) [reply Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp:425]: Same as above, this is gets the path leading up to the engine so that we can create the 'o3de' folder as a separate folder

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp (hunk 2 above)
Comment (dtamkin1) [reply Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp:405]: Thanks, I'll fix it

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp (hunk 3 above)
Comment (lumberyard-employee-dm) [reply Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp:409]: There is a [ParentPath](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/IO/Path/Path.h#L202-L206) function that should be used

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp (hunk 4 above)
Comment (lumberyard-employee-dm) [reply Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp:425]: repeat: The AZ::IO::ParentPath function should be used
https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/IO/Path/Path.h#L202-L206

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp (hunk 3 above)
Comment (dtamkin1) [reply Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp:409]: Oh awesome, thank you I'll update it 👍

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp (hunk 4 above)
Comment (dtamkin1) [reply Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp:425]: Thanks, I'll update this

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.h (hunk 1 above)
Comment (dtamkin1) [reply Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.h:93]: I'm using the boolean so that `m_fullPath` isn't reset if we see continuous entries in a row that are relative to the project/engine directory if the directory has already been set correctly

However, it would probably make more sense to just check whether `parent->m_fullPath` is already relative to the correct directory

**Review by lumberyard-employee-dm — APPROVED** [review]

**Review by amzn-tmryan — APPROVED** [review]

**Review by lsemp3d — APPROVED** [review]
