### PR TITLE
Only enable ungroup toolbar button if the selection has a group and…

### LINKED ISSUE #13673: Script Canvas: The Ungroup button is active even if an ungrouped node is selected
**Describe the bug**
The _Ungroup_ button becomes active after any node is selected, even if the node does not belong to any group. 
Pressing the button in such case does not have any effect.

Please refer to the attached video for more details.

**Steps to reproduce**
1. Launch Script Canvas.
2. Add any node to the graphs.
3. Select the node.

**Expected behavior**
The _Ungroup_ button remains grayed out until a Group is selected.

**Actual behavior**
The _Ungroup_ button becomes active when any node is selected.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/207321960-c9b27b15-aec3-46b8-900a-4ee457275886.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
35ee631

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

### PR DESCRIPTION
**Pull request by lsemp3d**
…support ungrouping more than 1 group at a time

Closes #13673

### CODE REVIEW

File: Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/AssetEditorToolbar/AssetEditorToolbar.cpp [hunk 1]
```diff
@@ -179,11 +179,17 @@ namespace GraphCanvas
 
             SceneRequestBus::EventResult(selectedElements, m_activeGraphId, &SceneRequests::GetSelectedNodes);
 
-            if (selectedElements.size() == 1)
+            for (const auto& selectedElement : selectedElements)
```
Comment (gadams3) [inline Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/AssetEditorToolbar/AssetEditorToolbar.cpp:182]: Does this loop need anything before it to capture ungrouping multiple groups as a single undoable operation?

**Review by gadams3 — APPROVED** [review]

File: Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/AssetEditorToolbar/AssetEditorToolbar.cpp (hunk 1 above)
Comment (lsemp3d) [reply Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/AssetEditorToolbar/AssetEditorToolbar.cpp:182]: I could do that, might help with undo/redo, I'll try it

Comment (lsemp3d) [reply Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/AssetEditorToolbar/AssetEditorToolbar.cpp:182]: I tried it, but it did not change the undo/redo behavior and it only adds a touch of complexity, I'll keep the change as is, it's easier to read

**Review by dtamkin1 — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]
