### PR TITLE
fix for ChangeNotify propogation in the DPE-based Inspector

### LINKED ISSUE #16495: DPE Inspector: Changes made with Occlusion Culling Plane component do not take effect when DPE is enabled
**Describe the bug**
Editing *Occlusion Culling Plane* component parameters when DPE is enabled does not change how the component looks like in the Viewport. Once the changes are made and user disables DPE, and then changes one additional parameter in the component, the changes are applied.

The issue occurs on both Windows and Linux.

**Steps to reproduce**
1. Create an entity and add *Occlusion Culling Plane* component to it.
2. Toggle the two available properties in the *Occlusion Culling Plane* and watch how it affects the component in the Viewport.
3. Execute the `ed_enableDPE 1` command in the *Console*.
4. Repeat step 2.

**Expected behavior**
Property changes are reflected on the component in the Viewport.

**Actual behavior**
While DPE is enabled the changes do not take effect.

**Video**

https://github.com/o3de/o3de/assets/86952082/5d569b56-2902-47b2-9dec-cca1d94f1b76

**Found in Branch**
Development (42e8f1f)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
42e8f1f66373a0ea995a564b5ff7500df7fe9bab

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

### PR DESCRIPTION
**Pull request by alexmontAmazon**
## What does this PR do?
- forces  children of group and dummy nodes to inherit (propagate) their changeNotify properties
- fixes #16495 #16498 #16520 

## How was this PR tested?

Locally in the Editor project

### CODE REVIEW

File: Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp [hunk 1]
```diff
@@ -1275,6 +1234,57 @@ namespace AZ::Reflection
...
+
+                    // calling order matters! Add parent's attributes first then existing attribute
+                    if (existingValue)
+                    {
+                        Dom::Value newChangeNotifyValue;
+                        newChangeNotifyValue.SetArray();
+                        addValueToArray(*parentValue, newChangeNotifyValue);
+                        addValueToArray(*existingValue, newChangeNotifyValue);
+                        nodeData.m_cachedAttributes.push_back({ Name(), changeNotifyName, newChangeNotifyValue });
+                    }
```
Comment (lumberyard-employee-dm) [inline Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp:1279]: Uh, shouldn't update the cachedAttribtues at the iterator `it` as that is already an existing ChangeNotify attribute?
```suggestion
                    // calling order matters! Add parent's attributes first then existing attribute
                    if (existingValue)
                    {
                        Dom::Value newChangeNotifyValue;
                        newChangeNotifyValue.SetArray();
                        addValueToArray(*parentValue, newChangeNotifyValue);
                        addValueToArray(*existingValue, newChangeNotifyValue);
                        it->m_value = newChangeNotifyValue;
                    }
```

Comment (alexmontAmazon) [reply Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp:1279]: Good catch! Yep, I was just factoring out that code to a function, but yes, that's certainly a bug in there. I think we're getting away with it because the attributes are read in order and the last one wins.

**Review by lumberyard-employee-dm — APPROVED** [review]

**Review by dtamkin1 — APPROVED** [review]
