### PR TITLE
EMotion FX: Unassigning the actor re-parents the entity to root level

### LINKED ISSUE #9550: Prefabs: Assigning an Actor asset to an Actor component inside of a Prefab breaks the entity's parent
**Describe the bug**
Assigning an Actor asset to an Actor component inside of a Prefab breaks the entity's parent.

**Steps to reproduce**
1. Create a new level.
2. Create a new entity and make a prefab from the entity.
3. Enter Focus Mode on the prefab, and create a new child entity.
4. Add an Actor component to the new child entity.
5. Assign any Actor asset to the Actor component.
6. Observe the entity hierarchy.

**Expected behavior**
Actor asset is assigned, and entity hierarchy is unaffected.

**Actual behavior**
Actor asset is assigned, however the child entity then jumps out of the prefab and has no parent info in the Transform component. This can result in further undesired behavior, such as an Editor crash when entering Game Mode, likely due to the invalid parent.

**Assets required**
AutomatedTesting project has Actor assets that can be used.

**Screenshots**
image

**Found in Branch**
development@a9963ff5405d81fcb583bc58ecf9af6c8e958899

### PR DESCRIPTION
**Pull request by amzn-jillich**
* Fixed a bug where the entity got reset to root level when unassigning the actor when using an attachment component.
* Removed attachment target actor variable that wasn't needed to be cached. (Fixed a crash)
* Code cleaning

Fixes #9550

https://user-images.githubusercontent.com/43751992/171650151-7ac1aa61-9ea8-4dae-b697-e0ad9a3e54b3.mp4

Signed-off-by: Benjamin Jillich <jillich@amazon.com>

### CODE REVIEW

**Review by amzn-rhhong — APPROVED** [review]
good job getting rid of unnecessarily cached ptr!

File: Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp [hunk 1]
```diff
@@ -1084,6 +1086,9 @@ namespace EMotionFX
                 return;
             }
 
+            // Remember the parent entity before we re-parent (attach) it.
+            AZ::TransformBus::EventResult(m_attachmentPreviousParent, GetEntityId(), &AZ::TransformBus::Events::GetParentId);
```
Comment (srikappa-amzn) [inline Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp:1090]: I'm not very familiar with how the EditorActorComponent works but based on my understanding of O3DE's entity component system, you wouldn't need to reparent entities if all you are doing is modifying some component properties. I see that you are caching the previous parent to set it correctly later but my question is why is reparenting needed at all to begin with?

Comment (amzn-jillich) [reply Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp:1093]: That is a good point and I've played around with that: This is actually not needed for attachments using the attachment component, but for skinned attachments. Skinned attachments also need the entity transform to be driven so that the actor instance moves along with that. Skinned attachments don't use the attachment component but is some special setting in the actor component. I'm afraid this is a bigger thing to tackle and out of scope for this bug fix. When doing that, we should directly consolidate some code between the actor and the editor actor component, as we got some duplicated code here due to some tech debt/decision made in the past.

Comment (srikappa-amzn) [reply Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp:1093]: Okay. Approving this since it looks like removing the transform dependency seems like a bit more involved here. I recommend revisiting the skinned attachments logic so that the reparenting logic isn't hardwired into the component logic itself but instead decoupled from it. For example, we can put some guardrails so that skinned attachments can only work if targeting existing parent. Not sure if that'll get the desired ux but just throwing some ideas out there...

**Review by srikappa-amzn — APPROVED** [review]

**Review by hultonha — APPROVED** [review]
Change looks good but I wonder if there's a way to write an integration test to simulate the problem and verify the fix? It's not crucial but it would be great to have a test that simulates the issue we saw here and a way to catch it regressing in future.
