### PR TITLE
Cherry-pick PR #17568 fromdev to point-release/23103

### LINKED ISSUE #15671: [Bug Report] Asset Browser cannot delete asset
**Describe the bug**
I'm unable to delete an asset using the Asset Browser. Specifically, I tried to delete a material and a folder of textures.

**Assets required**
Any assets

**Steps to reproduce**
1. Go to **Asset Browser**
2. Locate an asset and delete it by doing either one of the following:
    - Right-click on an asset to open the context menu and click **Delete asset**
    - Click on an asset and press **Del** key

**Expected behavior**
The asset deletes.

**Actual behavior**
The asset does not delete. As a workaround, I deleted the asset from the file explorer.

**Screenshots/Video**

https://user-images.githubusercontent.com/75444793/231247156-73430cca-7112-4e64-ba47-222d1fc3b9db.mp4

**Found in Branch**
branch: `development`

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
latest commit: `4244bc287a7418c49f4eba569a245b40b9aeda28`

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

### PR DESCRIPTION
**Pull request by nick-l-o3de**
Fixes the bug causing asset browser to be unable to delete/move/etc. (#17568)

* Fixes #15671 - [Bug Report] Asset Browser cannot delete asset
* Adds missing functionality from the Linux ProcessWatcher to indicate the difference between a different problem launching program, and the program not being found.
* Fixes the workflow of the Move/Delete/Rename operations in the Asset Browser to properly return the appropriate error when Source Control is not properly configured.
* Adds a toggle for source control notification in AP, so that if you toggle the Editor to not use Source Control, the AP will not either.
* Uses the same setting in AP as the Editor, to determine whether Source Control should be used or not, and sets it to false by default, just like the Editor.

### CODE REVIEW

**Review by AMZN-daimini — APPROVED** [review]

File: Code/Tools/AssetProcessor/native/AssetManager/AssetRequestHandler.cpp [hunk 1]
```diff
@@ -73,6 +74,36 @@ namespace
...
+    // generic version of BuildFailure, generally assumes that the failure type is a string.
+    template<typename T> 
+    void BuildFailure(T& failure,  AZStd::vector<AZStd::string>& lines)
+    {
+       ParseToLines(lines, failure);
+    }
+
+    // specialized version of BuildFailure, for when the failure type is a MoveFailure, the string will be in m_reason
+    template<> 
+    void BuildFailure(MoveFailure& failure,  AZStd::vector<AZStd::string>& lines)
```
Comment (lemonade-dm) [inline Code/Tools/AssetProcessor/native/AssetManager/AssetRequestHandler.cpp:99]: repeat: the `failure` parameter should be `const MoveFailure&`
```suggestion
    void BuildFailure(const MoveFailure& failure,  AZStd::vector<AZStd::string>& lines)
```

File: Code/Tools/AssetProcessor/native/AssetManager/AssetRequestHandler.cpp [hunk 2]
```diff
@@ -73,6 +74,36 @@ namespace
...
+            {
+                lines.push_back(line);
+                AZ::Debug::Trace::Instance().Output(AssetProcessor::ConsoleChannel, (line + "\n").c_str());
+            },
+            "\n");
+    }
+
+    // generic version of BuildFailure, generally assumes that the failure type is a string.
+    template<typename T> 
+    void BuildFailure(T& failure,  AZStd::vector<AZStd::string>& lines)
```
Comment (lemonade-dm) [inline Code/Tools/AssetProcessor/native/AssetManager/AssetRequestHandler.cpp:92]: The failure parameter should be `const T&` since `ParseToLines` accepts a `const AZStd::string&`
```suggestion
    void BuildFailure(const T& failure,  AZStd::vector<AZStd::string>& lines)
```

**Review by lemonade-dm — APPROVED** [review]

**Comment by nick-l-o3de** [comment]
Will do a local compile test of those changes, then commit.  I'll prepare a cherrypick for the const back to development.
