### PR TITLE
Animation Editor: Motion event colors aren't in sync with the event presets

### LINKED ISSUE #5989: [Animation] Motion Event PresetsThe motion event after the fourth color is added. Only the motion events of the third color can be displayed.
**Describe the bug**
[Animation] Motion Event PresetsThe motion event after the fourth color is added. Only the motion events of the third color can be displayed.

**Steps to reproduce**
1. In the animation editor, select a motion.
2. In the Motion Event window (two Motion Event Presets already exist by default), create two Motion Event Presets with different colors.
3. Drag the four events to an Event Track in Time View.

**Expected behavior**
1. All colors are their own colors.

**Actual behavior**
1. The color of the fourth motion event changes to the color of the third motion event.

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel Xeon Gold 6234]
 - GPU [NVidia RTX 5000]
 - Memory [32GB]
 - Working Branch: Main branch e7f7875

**Additional context**

### PR DESCRIPTION
**Pull request by amzn-jillich**
The motion events in the timeview had the wrong colors assigned as they weren't correctly mapped to the given event presets.

Resolves #5989

Signed-off-by: Benjamin Jillich <jillich@amazon.com>

### CODE REVIEW

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MotionEventPresetManager.cpp [hunk 1]
```diff
@@ -302,25 +302,28 @@ namespace EMStudio
...
                 {
-                    return ((presetData && eventData && *presetData == *eventData) || (!presetData && !eventData));
-                });
-                return thisPresetDataHasMatch != eventDatas.cend();
-            });
-            if (allMatch)
-            {
-                return preset->GetEventColor();
+                    const EMotionFX::EventDataPtr& eventData = eventDatas[i];
+                    const EMotionFX::EventDataPtr& presetData = presetDatas[i];
```
Comment (burelc-amzn) [inline Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MotionEventPresetManager.cpp:318]: The `EventDataSet` is implemented as a `vector`, but it should still be treated as a set and not care about the order. This requires that the event datas in the preset match the order of the event datas in the event. I think using `find_if` (or really, `AZStd::any_of`) is still the best approach here.

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MotionEventPresetManager.cpp [hunk 2]
```diff
@@ -302,25 +302,28 @@ namespace EMStudio
...
+
+                    if (eventData && presetData &&
+                        eventData->RTTI_GetType() == presetData->RTTI_GetType() &&
```
Comment (burelc-amzn) [inline Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MotionEventPresetManager.cpp:321]: The `EventData` subclasses all have to implement `bool Equal(const EventData& rhs)`, which all internally are going to do that RTTI check. So we don't need it here, it is up to the EventData types themselves to determine if they are equal or not.

**Review by burelc-amzn — COMMENTED** [review]
I think that using `all_of` and `any_of` still better communicates the intent of what the code is accomplishing. All the event datas in the preset have to match any event data from the event, with the added constraint that the number of datas match in both.

```cpp
AZ::u32 MotionEventPresetManager::GetEventColor(const EMotionFX::EventDataSet& eventDatas) const
{
    for (const MotionEventPreset* preset : m_eventPresets)
    {
        const EMotionFX::EventDataSet& presetDatas = preset->GetEventDatas();
                                                                                                                                    
        const bool allMatch = presetDatas.size() == eventDatas.size() &&
            AZStd::all_of(presetDatas.cbegin(), presetDatas.cend(), [eventDatas](const EMotionFX::EventDataPtr& presetData)
            {
                return AZStd::any_of(eventDatas.cbegin(), eventDatas.cend(), [presetData](const EMotionFX::EventDataPtr& eventData)
                {
                    return presetData && eventData && *presetData == *eventData;
                });
            });
        if (allMatch)
        {
            return preset->GetEventColor();
        }
    }
                                                                                                                                    
    // Use the same color for all events that are not from a preset.
    return s_unknownEventColor;
}
```

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MotionEventPresetManager.cpp [hunk 3]
```diff
@@ -302,25 +302,28 @@ namespace EMStudio
...
+                        *eventData == *presetData)
+                    {
```
Comment (burelc-amzn) [inline Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MotionEventPresetManager.cpp:323]: The `EventData` subclasses all have to implement `bool Equal(const EventData& rhs)`, which all internally are going to do that RTTI check. So we don't need it here, it is up to the EventData types themselves to determine if they are equal or not.
```suggestion
                    if (eventData && presetData && *eventData == *presetData)
                    {
```

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MotionEventPresetManager.cpp [hunk 4]
```diff
@@ -302,25 +302,28 @@ namespace EMStudio
...
     AZ::u32 MotionEventPresetManager::GetEventColor(const EMotionFX::EventDataSet& eventDatas) const
     {
         for (const MotionEventPreset* preset : m_eventPresets)
         {
-            EMotionFX::EventDataSet commonDatas;
             const EMotionFX::EventDataSet& presetDatas = preset->GetEventDatas();
-            const bool allMatch = AZStd::all_of(presetDatas.cbegin(), presetDatas.cend(), [eventDatas](const EMotionFX::EventDataPtr& presetData)
+
+            const size_t numEventDatas = eventDatas.size();
+            if (numEventDatas == presetDatas.size())
```
[the remark this answers is not in the document]
Comment (amzn-jillich) [reply Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MotionEventPresetManager.cpp:313]: If they aren't the same size, we can early out here as then we don't have a match. Having a different size is a valid case, so an assert wouldn't make sense here in my eyes.

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MotionEventPresetManager.cpp (hunk 3 above)
Comment (amzn-jillich) [reply Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MotionEventPresetManager.cpp:323]: Ah great, thanks. I've replaced the manual checks with the comparison operator for the shared_ptr which calls the class operators in case they are not null.
