### PR TITLE
Fix Multiplayer Editor Invalid Connection

### LINKED ISSUE #8605: EditorServer INetworkInterface::Connect Returns InvalidConnectionId
Multiplayer editor tests are sometimes failing because the editor-server fails to connect to the editor. This was found during AR and seems to occur more often when connecting multiple times rapidly (within a few seconds delay), but sometimes happens on the first try.

MultiplayerEditorConnection.cpp
        _const ConnectionId editorServerToEditorConnectionId =
            m_networkEditorInterface->Connect(IpAddress(LocalHost.data(), editorsv_port, ProtocolType::Tcp));_

The repro happens often on Linux, but there are some instances of this occurring on Windows.

**Steps to reproduce**
1. Run Multiplayer AR tests on Linux
    -  .\python\python.sh -m pytest --build-directory .\build\linux\bin\profile\  $pyfile .\AutomatedTesting\Gem\PythonTests\Multiplayer\TestSuite_Main.py::TestAutomation
    - Note: The above commandline might not work if tests have been moved from TestSuite_Main to TestSuite_Sandox
3. Notice some tests fail with error **[FAILED ] Failure: Failed to find expected line: MultiplayerEditorConnection: Editor-server activation has found and connected to the editor.**

**Expected behavior**
Editor-server should be able to connect to the editor

**Actual behavior**
Editor server fails to connect to editor

**Desktop/Device (please complete the following information):**
 - OS: Linux (often), Windows (rarely)

### PR DESCRIPTION
**Pull request by AMZN-Gene**
Simplify multiplayer editor. Going back to original setup where editor connects and server listens, except this time the editor will keep trying to reconnect if it fails (for example if the server isn't finished launching, or the port isn't available yet)

Tested by:
1) Seeing successful AR python/python.sh -m pytest --build-directory ./AutomatedTesting/build/linux/bin/profile/ ./AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Sandbox.py::TestAutomation
2) Running editor CTRL+G mode
3) Running editor CTRL+G mode and exiting before the server is done loading
4) Running a server by hand and then entering CTLR+G mode
  
Resolves #8605

### CODE REVIEW

File: Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.h [hunk 1]
```diff
@@ -114,5 +115,7 @@ namespace Multiplayer
         AzNetworking::ConnectionId m_editorConnId;
 
         ServerAcceptanceReceivedEvent::Handler m_serverAcceptanceReceivedHandler;
+        AZ::ScheduledEvent m_connectionEvent = AZ::ScheduledEvent([this]{this->Connect();}, AZ::Name("MultiplayerEditorConnect"));
+        int m_connectionAttempts = 0;
```
Comment (AMZN-puvvadar) [inline Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.h:119]: NP: This could probably be a uint8_t or a uint16_t.

**Review by AMZN-puvvadar — APPROVED** [review]

File: Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp [hunk 2]
```diff
@@ -188,6 +189,11 @@ namespace Multiplayer
                 console->PerformCommand("disconnect");
             }
 
+            if (m_connectionEvent.IsScheduled())
+            {
+                m_connectionEvent.RemoveFromQueue();
```
Comment (AMZN-Olex) [inline Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp:194]: It is safe to remove from queue without checking.

**Review by AMZN-Olex — APPROVED** [review]

File: Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp (hunk 2 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp:194]: Good question! IsScheduled is checking if it’s queued to schedule, although technically the check isn’t needed.
