### PR TITLE
The enable-gem command registers gem with project if not registered

### LINKED ISSUE #1967: Gems registered with the Engine SDK and added to a project via the Project Manager do not get built
**Describe the bug**
Gems registered with the engine SDK and added to a project via the Project Manager do not get built.

**To Reproduce**
1. Create a new Gem: `.\scripts\o3de.bat create-gem -gp D:\dev\open3d\MyTestGem`
2. Register Gem with engine: `.\scripts\o3de.bat register -gp D:\dev\open3d\MyTestGem`
3. Open `o3de.exe`, create new project
4. Edit project settings, activate Gem created above (can't select gem in the creation wizard, see #1965)
4. Build project in `o3de.exe`

The Gem gets successfully added to both `o3de_manifest.json` and `enabled_gems.cmake` and can be selected in the Project Manager. However, the Gem is not added to the Visual Studio Solution and therefore does not get built by the Project Manager.

**Expected behavior**
* The Visual Studio Solution should contain the Gem project, so it can be built from source
* The build process in the Project Manager should build the Gem

**Additional context**
This is on an SDK build as described in the official docs, unsure if this also happens on a non-SDK build.

### LINKED ISSUE #2568: Discrepancy in Project Manager gems list when opened via editor versus directly
**Describe the bug**
The list of enabled gems in the Project Manager is different (ie, empty) if you open it via the editor "File->Edit Project Settings..." in the editor vs if you open the project manager directly.

**To Reproduce**
1. Open the editor for any project
2. Click File->Edit Project Settings
3. Click 'Configure Gems'
--> Notice how all the gems show up as disabled even though some are actually enabled.   If you open the project manager directly instead of via the editor, it functions correctly

**Expected behavior**
Whether you open the project manager yourself or via the editor shortcut to it, it should always show you the same view of your project.

 - Device: Windows 10 PC
 
**Additional context**
It is unclear whether this was on a SDK install type of run or a in engine run or whether this matters.

### PR DESCRIPTION
**Pull request by lumberyard-employee-dm**
The o3de.py `enable-gem` command will now register the gem with project that it is being enabled for, if that gem is not registered with the project or engine currently.

Resolves #1967

The "Edit Project Settings" option in the Editor now places double quotes around the project path parameter when launching to make sure paths with spaces in it work.

Fixes #2568

Signed-off-by: lumberyard-employee-dm <56135373+lumberyard-employee-dm@users.noreply.github.com>

### CODE REVIEW

File: Code/Editor/CryEdit.cpp [hunk 1]
```diff
@@ -2901,7 +2901,14 @@ void CCryEditApp::OpenProjectManager(const AZStd::string& screen)
...
     AZ::IO::FixedMaxPathString projectPath = AZ::Utils::GetProjectPath();
-    const AZStd::string commandLineOptions = AZStd::string::format(" --screen %s --project-path %s", screen.c_str(), projectPath.c_str());
+#if !AZ_TRAIT_OS_PLATFORM_APPLE && !AZ_TRAIT_OS_USE_WINDOWS_FILE_PATHS
+    const char* argumentQuoteString = R"(")";
+#else
+    const char* argumentQuoteString = R"(\")";
+#endif
+    const AZStd::string commandLineOptions = AZStd::string::format(R"( --screen %s --project-path %s%s%s")",
+        screen.c_str(),
+        argumentQuoteString, projectPath.c_str(), argumentQuoteString);
```
Comment (AMZN-ScottR) [inline Code/Editor/CryEdit.cpp:2911]: I'm guessing the extra double quote right after the final `%s` is a stray from before the platform specific quote format, yea?

Comment (lumberyard-employee-dm) [reply Code/Editor/CryEdit.cpp:2911]: Yes you are correct.
I'll remove it

**Review by AMZN-alexpete — APPROVED** [review]

**Review by AMZN-ScottR — APPROVED** [review]
