### PR TITLE
Only pause/resume instance propagation for EntityPropertyEditor instead of all RPEs

### LINKED ISSUE #9853: Source Engine built Editor fails to open and create new levels after FBX Settings (PREVIEW) tool window has been opened
**Describe the bug**
Opening the FBX Settings (PREVIEW) tool window hinders the Source Engine built Editor ability to open and create new levels successfully.

Trying to open or create a new level leaves the user with an empty level without any entities.

Please note that this occurs even after the FBX Settings (PREVIEW) tool window was closed and in order to correctly load and create levels after its opening the Editor has to be restarted.

This issue occurs also on Linux platform.

For further information please refer to the attached video and Editor log file.

**Steps to reproduce**

1. Launch the Editor and create a new level.
2. Search for any .fbx object in the Asset Browser (ex. groundplane_512x512m.fbx) .
3. Right click the .fbx asset and select Edit Settings... .
4. Wait until the FBX Settings (PREVIEW) tool opens and close it.
5. Open a new level.

**Expected behavior**
The selected level is correctly opened.

**Actual behavior**
An empty level without any entities is loaded instead of the selected level.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953456/171418734-27e43612-5e34-42f8-8673-f3fca7218eac.mp4

**Found in Branch**
Development (6f9e0be)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 7 2700X
- GPU: AMD Radeon Pro Duo
- Memory: 16GB

**Additional context**

[Editor.log](https://github.com/o3de/o3de/files/8814661/Editor.log)

### PR DESCRIPTION
**Pull request by michabr**
The InstanceUpdateExecutor was listening to PropertyEditorGUIMessages' RequestWrite and OnEditingFinished to pause/resume instance propagation during property editing. However, these messages are sent from any RPE. 

Instead, this PR moves the pausing/resuming of instance propagation to handlers within the EntityPropertyEditor.

Also checked that all AzToolsFramework property handlers send OnEditingFinished.

Fixes #9853. The FBX settings tool uses the RPE and adds its own custom controls that don't send OnEditingFinished events. That won't matter now because we're only pausing/resuming propagation on tools that use the EntityPropertyEditor (Entity Inspector). 

Signed-off-by: abrmich <abrmich@amazon.com>

### CODE REVIEW

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutorInterface.h [hunk 1]
```diff
@@ -34,6 +34,11 @@ namespace AzToolsFramework
             // A notification OnRootPrefabInstanceLoaded will fire during the propagation if root
             // prefab instance is loaded for the first time after this function is called.
             virtual void QueueRootPrefabLoadedNotificationForNextPropagation() = 0;
+
+            // Indicates whether to pause instance propagation or not.
+            //! When making property changes in the entity editor, pausing propagation during
+            //! editing will prevent the user from losing control of the properties they are editing.
+            virtual void SetShouldPauseInstancePropagation(bool shouldPausePropagation) = 0;
```
Comment (AMZN-daimini) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutorInterface.h:41]: nit: Part of the comment does not have doxygen notation.

Also, the function is a setter, not a getter, so "Indicates" is confusing. Maybe it could be `Sets whether to pause instance propagation or not.`?

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyColorCtrl.cpp [hunk 2]
```diff
@@ -400,6 +400,11 @@ namespace AzToolsFramework
             {
                 EBUS_EVENT(PropertyEditorGUIMessages::Bus, RequestWrite, newCtrl);
             });
+        connect(newCtrl, &PropertyColorCtrl::editingFinished, this, [newCtrl]()
+            {
+                AzToolsFramework::PropertyEditorGUIMessages::Bus::Broadcast(
+                    &PropertyEditorGUIMessages::OnEditingFinished, newCtrl);
+            });
         // note:  Qt automatically disconnects objects from each other when either end is destroyed, no need to worry about delete.
```
Comment (AMZN-daimini) [inline Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyColorCtrl.cpp:408]: uber-nit: remove double space in comment

**Review by AMZN-daimini — APPROVED** [review]
Is this tested in any way? It may help catch regressions :D

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutorInterface.h (hunk 1 above)
Comment (michabr) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutorInterface.h:41]: Oh yeah, will change!

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyColorCtrl.cpp [hunk 3]
```diff
@@ -400,7 +400,12 @@ namespace AzToolsFramework
             {
                 EBUS_EVENT(PropertyEditorGUIMessages::Bus, RequestWrite, newCtrl);
             });
-        // note:  Qt automatically disconnects objects from each other when either end is destroyed, no need to worry about delete.
+        connect(newCtrl, &PropertyColorCtrl::editingFinished, this, [newCtrl]()
+            {
+                AzToolsFramework::PropertyEditorGUIMessages::Bus::Broadcast(
+                    &PropertyEditorGUIMessages::OnEditingFinished, newCtrl);
+            });
```
Comment (srikappa-amzn) [inline Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyColorCtrl.cpp:407]: Interesting....how were color pickers working correctly before without this change?

I'm trying to understand why this needs to be added now.

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp [hunk 4]
```diff
@@ -2718,6 +2740,8 @@ namespace AzToolsFramework
             command->SetParent(m_currentUndoOperation);
 
             AfterPropertyModified(node);
+            SetPropertyEditingComplete(node);
```
Comment (srikappa-amzn) [inline Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp:2743]: When does ContextMenuActionSetDataFlag() get called? Why are we only adding the EditingComplete() call here instead of in AfterPropertyModified()?

**Review by srikappa-amzn — APPROVED** [review]
Looks good to me. I have a few clarifying questions about why things were added at a certain place instead of elsewhere.

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp [hunk 5]
```diff
@@ -2701,6 +2722,7 @@ namespace AzToolsFramework
         }
 
         AfterPropertyModified(fieldNode);
+        SetPropertyEditingComplete(fieldNode);
```
Comment (srikappa-amzn) [inline Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp:2725]: When does ContextMenuActionPullFieldData() get called? Why are we only adding the EditingComplete() call here instead of in AfterPropertyModified()?

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp (hunk 4 above)
Comment (michabr) [reply Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp:2743]: I'm not sure when ContextMenuActionSetDataFlag() is called. It looks like slice code to me.

Typically the BeforePropertyModified() and AfterPropertyModified() events are sent from the DPE (part of IPropertyEditorNotify class). They are sent multiple times during editing (ex. moving a slider) while EditingComplete() is sent once at the end of editing. Here in ContextMenuActionSetDataFlag(), it's calling the handlers explicitly, so to have things working the same way, we expect a BeforePropertyModified -> AfterPropertyModified -> BeforePropertyModified -> AfterPropertyModifed -> ... -> EditingComplete.

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp (hunk 5 above)
Comment (michabr) [reply Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp:2725]: Same as above.

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyColorCtrl.cpp (hunk 3 above)
Comment (michabr) [reply Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyColorCtrl.cpp:407]: Color pickers are using the AZColorPropertyHandler which already had the OnEditingFinished hooked up. It's being added now to Vector3ColorPropertyHandler so we have all our AzToolFramework property handlers follow the expected pattern of sending both RequestWrite during editing and OnEditingFinished at the end of editing.
