### PR TITLE
Fixed crash in GroupElementToggle when the hidden attribute was added

### LINKED ISSUE #11232: Attempting to use the Visibility attribute with a GroupElementToggle results in a crash
**Describe the bug**
When reflecting component data to the EditContext, if the component uses a GroupElementToggle and attempts to use the Visibility attribute with it, the Editor will crash when that component is viewed and the Visibility flag is set to "Hide".

**Steps to reproduce**
1. In ImageGradientConfig::Reflect(), add the Visibility attribute to the "Advanced" GroupElementToggle as follows:
```
                    ->GroupElementToggle("Advanced", &ImageGradientConfig::m_advancedMode)
                        ->Attribute(AZ::Edit::Attributes::AutoExpand, false)
                        ->Attribute(AZ::Edit::Attributes::ChangeNotify, AZ::Edit::PropertyRefreshLevels::AttributesAndValues)
                        **->Attribute(AZ::Edit::Attributes::Visibility, AZ::Edit::PropertyVisibility::Hide)**
```
2. Compile and run the Editor.
4. Open or create a level.
5. Create an entity.
6. Add the Image Gradient component to the entity.

**Expected behavior**
The Image Gradient component shows up, doesn't crash, and has the Advanced group hidden.

**Actual behavior**
Crash with the following callstack:
```
>	ComponentEntityEditorPlugin.dll!AzToolsFramework::PropertyRowWidget::RefreshAttributesFromNode(bool initial) Line 648	C++
 	ComponentEntityEditorPlugin.dll!AzToolsFramework::PropertyRowWidget::InitializeToggleGroup(const char * groupName, AzToolsFramework::PropertyRowWidget * pParent, int depth, AzToolsFramework::InstanceDataNode * node, int labelWidth) Line 411	C++
 	ComponentEntityEditorPlugin.dll!AzToolsFramework::ReflectedPropertyEditor::Impl::GetOrCreateLogicalGroupWidget(AzToolsFramework::InstanceDataNode * node, AzToolsFramework::PropertyRowWidget * parent, int depth) Line 525	C++
 	ComponentEntityEditorPlugin.dll!AzToolsFramework::ReflectedPropertyEditor::Impl::AddProperty(AzToolsFramework::InstanceDataNode * node, AzToolsFramework::PropertyRowWidget * pParent, int depth, AZStd::basic_string_view<char,AZStd::char_traits<char>> labelOverride) Line 742	C++
 	ComponentEntityEditorPlugin.dll!AzToolsFramework::ReflectedPropertyEditor::Impl::AddProperty(AzToolsFramework::InstanceDataNode * node, AzToolsFramework::PropertyRowWidget * pParent, int depth, AZStd::basic_string_view<char,AZStd::char_traits<char>> labelOverride) Line 847	C++
 	ComponentEntityEditorPlugin.dll!AzToolsFramework::ReflectedPropertyEditor::Impl::AddProperty(AzToolsFramework::InstanceDataNode * node, AzToolsFramework::PropertyRowWidget * pParent, int depth, AZStd::basic_string_view<char,AZStd::char_traits<char>> labelOverride) Line 847	C++
 	ComponentEntityEditorPlugin.dll!AzToolsFramework::ReflectedPropertyEditor::Impl::AddProperty(AzToolsFramework::InstanceDataNode * node, AzToolsFramework::PropertyRowWidget * pParent, int depth, AZStd::basic_string_view<char,AZStd::char_traits<char>> labelOverride) Line 847	C++
 	ComponentEntityEditorPlugin.dll!AzToolsFramework::ReflectedPropertyEditor::Impl::AddProperty(AzToolsFramework::InstanceDataNode * node, AzToolsFramework::PropertyRowWidget * pParent, int depth, AZStd::basic_string_view<char,AZStd::char_traits<char>> labelOverride) Line 847	C++
 	ComponentEntityEditorPlugin.dll!AzToolsFramework::ReflectedPropertyEditor::InvalidateAll(const char * filter) Line 888	C++
 	[Inline Frame] ComponentEntityEditorPlugin.dll!AzToolsFramework::EntityPropertyEditor::BuildSharedComponentUI(AZStd::vector<AzToolsFramework::EntityPropertyEditor::SharedComponentInfo,AZStd::allocator> &) Line 1734	C++
 	ComponentEntityEditorPlugin.dll!AzToolsFramework::EntityPropertyEditor::UpdateContents() Line 1257	C++
```

Specifically, the groupSourceNode passed in to InitializeToggleGroup() is null, which leads to crash in RefreshAttributesFromNode() when it dereferences a null m_sourceNode.

**Found in Branch**
development

**Notes**
The workaround to this problem is to use the visibility attribute on every element within the group, instead of on the group itself. If every element is hidden, the group (and the toggle) won't appear either. I'm unsure whether or not this workaround is a second bug, since it seems like perhaps the toggle should still appear if that field isn't marked as hidden?

### PR DESCRIPTION
**Pull request by dtamkin1**
Signed-off-by: Daniel Tamkin <jotamkin@amazon.com>

## What does this PR do?

Fixes #11232
Added null dereference to prevent crash when the source node is null in a GroupElementToggle

## How was this PR tested?
Ran the editor to make sure it didn't crash when the hidden visibility attribute was added

### CODE REVIEW

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ReflectedPropertyEditor.cpp [hunk 1]
```diff
@@ -515,7 +515,7 @@ namespace AzToolsFramework
 
                     // Initialized normally if the group does not have a member variable attached to it,
                     // otherwise initialize it as a group that will have a toggle switch.
-                    if (groupElementData->IsClassElement())
+                    if (groupElementData->IsClassElement() || !groupSourceNode)
```
Comment (AMZN-daimini) [inline Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ReflectedPropertyEditor.cpp:518]: nit: comment may need to be updated to match?

**Review by AMZN-daimini — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]

**Review by mbalfour-amzn — APPROVED** [review]

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ReflectedPropertyEditor.cpp (hunk 1 above)
Comment (lsemp3d) [inline Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ReflectedPropertyEditor.cpp:519]: Can you take the opportunity to rename `groupSourceNode` to `m_groupSourceNode` to adhere to the coding guidelines

Comment (dtamkin1) [reply Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ReflectedPropertyEditor.cpp]: Resolved!
