### PR TITLE
make white box collider component incompatible with rigid body component

### LINKED ISSUE #10349: PhysX Rigid Body is not compatible Whitebox Collider
**Describe the bug**
When a user applies a PhysX Rigid Body component to an entity that has the White Box and White Box Collider components, the White Box Collider will not translate with the entity location making it appear that it's not interacting with the world correctly.

**Steps to reproduce**
1. Create a scene with three Entities
2. On the first Entity set the following components
    * Translation: -0.1, 0, 0
    * White Box
    * White Box Collider
3. On the second Entity set the following components
    * Translation: 0.6, 0, 2
    * White Box
    * White Box Collider
4. On the third Entity set the following components
    * Translation: 0, 0, 4
    * Sphere Shape
       * Game View: True
    * Shape Collider
    * PhysX Rigid Body
5. Enter Game Mode and observe that the third entity drops and collides with both entities as it drops
7. Exit Game Mode
8. Modify the second entity to add a PhysX Rigid Body
9. Enter Game Mode
10. Exit Game Mode
11. On the second entity, modify the White Box Body Type to Kinematic
12. Enter Game Mode
13. Swap the location of the second and third entities
14. Enter Game Mode

**Expected behavior**
Simulation executes and second entity will interact with all colliders as expected

**Actual behavior**
Second entity drops and fails to interact with the other entities as expected

**Found in Branch**
Development

**Videos**
First Game Mode Run:

https://user-images.githubusercontent.com/29718640/175729701-98437e89-e025-427b-ae55-337b071987ff.mp4

Second Game Mode Run:

https://user-images.githubusercontent.com/29718640/175730124-b6a77e1d-2826-4ef5-94cc-109020c60673.mp4

Third Game Mode Run: 

https://user-images.githubusercontent.com/29718640/175746808-261e742c-8b9e-40df-a196-497c1b6e3ba3.mp4

Fourth Game Mode Run:

https://user-images.githubusercontent.com/29718640/175749255-6dfeed6d-dcca-4953-ab0d-42d6ef919f13.mp4

### PR DESCRIPTION
**Pull request by greerdv**
Signed-off-by: greerdv <greerdv@amazon.com>

## What does this PR do?
Makes white box collider component incompatible with PhysX rigid body component (because the white box collider creates a rigid body itself, and since it uses a triangle mesh the rigid body can only be static or kinematic). Fixes #10349.

## How was this PR tested?
Manually verified that a rigid body component could not be added to an entity with a white box collider component.

### CODE REVIEW

**Review by hultonha — APPROVED** [review]
LGTM :+1:

File: Gems/WhiteBox/Code/Source/Components/WhiteBoxColliderComponent.cpp [hunk 1]
```diff
@@ -33,6 +33,11 @@ namespace WhiteBox
         }
     }
 
+    void WhiteBoxColliderComponent::GetProvidedServices(AZ::ComponentDescriptor::DependencyArrayType& provided)
+    {
+        provided.push_back(AZ_CRC_CE("PhysicsStaticRigidBodyService"));
```
Comment (moraaar) [inline Gems/WhiteBox/Code/Source/Components/WhiteBoxColliderComponent.cpp:38]: Whitebox gem has a dependency on PhysX, not the other way around. Wouldn't be more appropriate to make whitebox component incompatible with some physics service, instead of making several physics components incompatible with a service added by whitebox?

Sorry if I'm misreading this.

Comment (greerdv) [reply Gems/WhiteBox/Code/Source/Components/WhiteBoxColliderComponent.cpp:38]: I don't think either has a dependency on the other (except that the white box editor tests depend on physx editor). The white box collider does everything it needs to through the AzFramework physics API, so it doesn't need to know about a specific physics backend. So I'd like to not add any reference to PhysX into the white box gem.

Comment (moraaar) [reply Gems/WhiteBox/Code/Source/Components/WhiteBoxColliderComponent.cpp:38]: Had a quick chat with @greerdv. The addition of "PhysicsStaticRigidBodyService" here is the right approach, sadly the status of services in PhysX Gem is a bit odd at the moment as they provide "PhysX..." services when they can be "Physics..." services too. And if that were the case this PR would have been only about WhiteBoxColliderComponent providing "PhysicsStaticRigidBodyService" and that's it, no changes to PhysX gem would have been required.

Approving.

**Review by moraaar — APPROVED** [review]

**Review by pollend — APPROVED** [review]
