### PR TITLE
Fix a crash when reloading AudioControlEditor controls

### LINKED ISSUE #2602: Reloading the Audio Control Editor causes the Editor to crash
**Describe the bug**
It has been noticed, that reloading the Audio Controls Editor via File > Reload causes the Editor to crash. This does not produce a .dmp or error.log file, nor can they be captured using the Visual Studio 2019.

**To Reproduce**
1. Build the package with Wwise SDK attached during Build Configuration.
2. Create a project via Project Manager with all available Gems enabled.
3. Create a level.
4. Go to Tools > Other > Audio Controls Editor.
5. In the Audio Controls Editor go to File > Reload.

**Expected behavior**
The Editor does not crash.

**Video and Editor.log**

https://user-images.githubusercontent.com/86952082/127499578-99c92716-18b4-45ef-8d2e-8da58860a33f.mp4

[Editor.log](https://github.com/o3de/o3de/files/6900856/Editor.log)

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

### PR DESCRIPTION
**Pull request by amzn-phist**
The crash was due to destruction of xml_node that was held in a unique_ptr.
Rapidxml has a very rudimentary memory allocation design, so in most cases dynamic allocations aren't even made.  The memory_pool does all the cleanup in its destructor, so having a unique_ptr run its default_delete was causing the crash.

I tried a couple different options, using a custom deleter, or forcing dynamic allocations.  They all were pretty messy, so I gave in to rapidxml's memory patterns.  It still doesn't sit right with me, since rapidxml doesn't really have any cleanup routines except for complete clear of the memory.

Fixes #2602

### CODE REVIEW

**Review by lawsonamzn — APPROVED** [review]
So I'm okay with these changes as they're basically the least amount of change you have to make to the exisitng system to avoid the crash.

I'd be good to  open a feature issue though, that proposes tying the lifetime of the xml document object + its buffer (basically the scoped document object) to the things that use it, so that it sticks around, as does its memory, until the last thing to use it is gone.  Then all the deep copying can be removed.

File: Gems/AudioSystem/Code/Source/Editor/AudioControl.h [hunk 1]
```diff
@@ -25,46 +25,48 @@ namespace AudioControls
...
+        [[nodiscard]] AZ::rapidxml::xml_node<char>* DeepCopyNode(AZ::rapidxml::xml_node<char>* srcNode)
         {
-            AZStd::unique_ptr<AZ::rapidxml::xml_node<char>> destNode;
-            if (srcNode)
+            if (!srcNode)
+            {
+                return nullptr;
+            }
+
+            XmlAllocator& xmlAlloc(AudioControls::s_xmlAllocator);
```
Comment (lumberyard-employee-dm) [inline Gems/AudioSystem/Code/Source/Editor/AudioControl.h:51]: So none of the memory will be cleaned up until the XmlAllocator goes out of scope?

Comment (amzn-phist) [reply Gems/AudioSystem/Code/Source/Editor/AudioControl.h:51]: Yeah that's one of the pitfalls of this solution.  It will need a bit of further refactor to get to a more sensible lifetime management.  Discussing with @lawsonamzn about it.

**Review by lumberyard-employee-dm — APPROVED** [review]
