### PR TITLE
Fix: Entity Outliner: Outliner is unusable with the Editor in slice mode

### LINKED ISSUE #6972: Entity Outliner: Outliner is unusable with the Editor in slice mode
**Describe the bug**
Outliner is unusable with the Editor in slice mode. Entities are laid out incorrectly, offset from their icons, and selecting entities is difficult.

**Steps to reproduce**
1. Launch the Editor with "EnablePrefabSystem": false set in AutomatedTesting\user\Registry\editorpreferences.setreg
2. Create several new entities in the outliner

**Expected behavior**
Entities are easily selectable in Outliner and appear as expected.

**Actual behavior**
Entities are laid out incorrectly, offset from their icons, and selecting entities is difficult.

**Found in Branch**
development@ffa9cc3a66e7a6d

outliner_offset
f

### PR DESCRIPTION
**Pull request by AMZN-Igarri**
resolves #6972 
Signed-off-by: AMZN-Igarri <82394219+AMZN-Igarri@users.noreply.github.com>

### CODE REVIEW

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/EntryDelegate.cpp [hunk 1]
```diff
@@ -290,7 +290,9 @@ namespace AzToolsFramework
                 {
                     displayString = RichTextHighlighter::HighlightText(displayString, m_assetBrowserFilerModel->GetStringFilter()->GetFilterString());
                 }
+                painter->save();
                 RichTextHighlighter::PaintHighlightedRichText(displayString, painter, optionV4, remainingRect);
+                painter->restore();
```
Comment (AMZN-daimini) [inline Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/EntryDelegate.cpp:296]: As mentioned in private, I would advise to keep the painter save/restore calls inside PaintHighlightedRichText, since the functions signature does not imply that the painter will be changed by the call.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Editor/RichTextHighlighter.cpp [hunk 2]
```diff
@@ -29,11 +29,8 @@ namespace AzToolsFramework
         return highlightedString;
     }
 
-    void RichTextHighlighter::PaintHighlightedRichText(const QString& highlightedString,QPainter* painter, QStyleOptionViewItem option, QRect availableRect)
+    void RichTextHighlighter::PaintHighlightedRichText(const QString& highlightedString,QPainter* painter, QStyleOptionViewItem option, QRect availableRect, QPoint offset /* = QPoint()*/)
     {
-        painter->save();
-        painter->setRenderHint(QPainter::Antialiasing);
```
Comment (cgalvan) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Editor/RichTextHighlighter.cpp:35]: The `painter` save/restore still need to happen inside this method because it modifies the `painter`

**Review by AMZN-daimini — APPROVED** [review]

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp [hunk 3]
```diff
@@ -2367,7 +2367,6 @@ namespace AzToolsFramework
         optionV4.widget->style()->drawControl(QStyle::CE_ItemViewItem, &optionV4, painter);
 
         AzToolsFramework::RichTextHighlighter::PaintHighlightedRichText(entityNameRichText, painter, optionV4, textRect);
-        painter->restore();
```
Comment (cgalvan) [inline Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp]: Looking at the top of this `PaintEntityNameAsRichText` method it actually does a `painter->save()` on line 2312, but then never restores it, so I think we actually should add one here

File: Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/Outliner/OutlinerListModel.cpp [hunk 4]
```diff
@@ -2605,8 +2605,6 @@ void OutlinerItemDelegate::paint(QPainter* painter, const QStyleOptionViewItem&
         AzToolsFramework::RichTextHighlighter::PaintHighlightedRichText(
             entityNameRichText, painter, optionV4, textRect, QPoint(0, verticalOffset));
 
-        painter->restore();
```
Comment (cgalvan) [inline Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/Outliner/OutlinerListModel.cpp]: Looking at the top of this `index.column() == OutlinerListModel::ColumnName` branch it actually does a `painter->save()` on line 2549, but then never restores it, so I think we actually should add one here

**Review by cgalvan — CHANGES_REQUESTED** [review]

**Comment by AMZN-Igarri** [comment]
https://user-images.githubusercontent.com/82394219/150124330-1336d406-07d7-4937-bfab-49921116aece.mp4

**Review by cgalvan — APPROVED** [review]
