### PR TITLE
Fix terrain renderer memory trashing.

### LINKED ISSUE #16889: Terrain World modifications crash on Windows/DX12 only
**Describe the bug**
When editing values in the Terrain World component, the Editor crashes. This only appears to occur on Windows/DX12.

**Steps to reproduce**
1. Create a new level (or open an empty level) in a project with Terrain enabled.
2. Add Terrain World, Terrain World Renderer components to the Level entity.
3. Create a new entity.
4. Add Terrain Layer Spawner, Axis Aligned Box Shape components.
5. Set the Axis Aligned Box Shape size to 1024 x 1024 x 100.
6. Change the Terrain World Min Height value from 0 to -512.

**Expected behavior**
It changes.

**Actual behavior**
It crashes. Callstack as follows:

```
>	Atom_RPI.Editor.dll!AZStd::Internal::function_util::get_invoker<void __cdecl(void),AZStd::Internal::function_util::function_obj_tag,AZStd::stateless_allocator>::call<`AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::Data::AssetEvents,AZ::Data::AssetEvents>,AZ::BusInternal::EBusImplTraits<AZ::Data::AssetEvents,AZ::Data::AssetEvents>>::QueueFunction<void (__cdecl*)(AZ::Data::AssetId const &,void (__cdecl AZ::Data::AssetEvents::*&&)(AZ::Data::AssetId,AZ::Uuid),AZ::Data::AssetId &,AZ::Uuid &),AZ::Data::AssetId const &,void (__cdecl AZ::Data::AssetEvents::*)(AZ::Data::AssetId,AZ::Uuid),AZ::Data::AssetId &,AZ::Uuid &>'::`5'::<lambda_1>>(AZStd::Internal::function_util::function_buffer & function_obj_ptr) Line 147	C++
 	[Inline Frame] EditorLib.dll!AZStd::function_intermediate<void>::operator()() Line 604	C++
 	[Inline Frame] EditorLib.dll!AZStd::function<void __cdecl(void)>::operator()() Line 684	C++
 	EditorLib.dll!AZ::EBusQueuePolicy<1,AZ::EBus<AZ::Data::AssetEvents,AZ::Data::AssetEvents>,AZStd::recursive_mutex>::Execute() Line 267	C++
 	[Inline Frame] EditorLib.dll!AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::Data::AssetEvents,AZ::Data::AssetEvents>,AZ::BusInternal::EBusImplTraits<AZ::Data::AssetEvents,AZ::Data::AssetEvents>>::ExecuteQueuedEvents() Line 366	C++
 	EditorLib.dll!AZ::Data::AssetManager::DispatchEvents() Line 591	C++
 	[Inline Frame] EditorLib.dll!AZStd::Internal::INVOKE(void(AZ::SystemTickEvents::*)() &) Line 177	C++
 	[Inline Frame] EditorLib.dll!AZStd::invoke(void(AZ::SystemTickEvents::*)() &) Line 54	C++
 	[Inline Frame] EditorLib.dll!AZ::EBusEventProcessingPolicy::Call(void(AZ::SystemTickEvents::*)() &) Line 437	C++
 	EditorLib.dll!AZ::Internal::EBusContainer<AZ::SystemTickEvents,AZ::SystemTickEvents,0,1>::Dispatcher<AZ::EBus<AZ::SystemTickEvents,AZ::SystemTickEvents>>::Broadcast<void (__cdecl AZ::SystemTickEvents::*)(void)>(void(AZ::SystemTickEvents::*)() && func) Line 1360	C++
 	EditorLib.dll!AZ::ComponentApplication::TickSystem() Line 1524	C++
 	EditorLib.dll!CCryEditApp::IdleProcessing(bool bBackgroundUpdate) Line 2269	C++
 	EditorLib.dll!CCryEditApp::OnIdle(long lCount) Line 2179	C++
 	EditorLib.dll!Editor::EditorQtApplication::maybeProcessIdle() Line 319	C++
 	[External Code]	
 	EditorLib.dll!CryEditMain(int argc, char * * argv) Line 3837	C++
```

**Found in Branch**
development@fd21058218a1b6f3f10e71e0fba48f85c4902feb

**Additional context**
* This only reproduces on Windows with the DX12 RHI. If I set the RHI to Vulkan, it works correctly.
* The Terrain World Renderer component is required to exist for this to crash. Without that component, it works correctly.
* The callstack _might_ be misleading, I suspect memory corruption that happened to hit this area pretty consistently, but I don't know for sure. There are very few places that call AssetBus::QueueFunction, and they've all worked fine for years, there's no obvious reason why one of those would suddenly get corrupted.
* The crash happens in both debug and profile for me with the same callstack, no additional context/knowledge gained. :(
* Deleting the Sun entity (Directional Light component) seems to prevent the problem from happening as well.

### PR DESCRIPTION
**Pull request by mbalfour-amzn**
## What does this PR do?

Fixes #16889 and #16927 . The sector pointers in the terrain ray tracing data were freed in some cases before they were accessed, causing arbitrary memory to get overwritten. This PR ensures the ray tracing data is freed before the sectors, and adds an assert to validate that assumption.

NOTE: There was a previous PR #16887 submitted to development that hid the issue somewhat, but didn't solve it. When merging point-release changes back to development, any merge conflicts should favor this PR over that one.

## How was this PR tested?

Performed the repro steps in the referenced bugs and verified that they no longer crash.

### CODE REVIEW

**Review by moudgils — APPROVED** [review]

File: Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp [hunk 1]
```diff
@@ -158,9 +158,9 @@ namespace Terrain
         {
             m_parentScene->GetViewTagBitRegistry().ReleaseTag(m_meshMovedFlag);
         }
+        RemoveRayTracedMeshes();
         m_candidateSectors.clear();
         m_sectorsThatNeedSrgCompiled.clear();
-        RemoveRayTracedMeshes();
         m_sectorLods.clear();
         m_xyPositions.clear();
         m_cachedDrawData.clear();
```
Comment (lumberyard-employee-dm) [inline Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp:166]: There are several repeats of this clear logic throughout this file.

Perhaps we can make it safer by having this code in a dedicated function such as `ClearTerrainSectors`?

Comment (lumberyard-employee-dm) [reply Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp:166]: Actually this code is inside of the `TerrainMeshManager::Reset` function.

Can this function be called below then instead of the explicit calls to `RemoveRayTracedMeshes()` followed by `m_sectorLods.clear()`, etc...?

Comment (mbalfour-amzn) [reply Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp]: I went with the first suggestion and consolidated the sector clears into a single method. Reset() clears more than that, so I don't feel comfortable switching everything to use that. It's _probably_ ok, but this is more trivially proveable to be correct.

**Review by lumberyard-employee-dm — APPROVED** [review]
