### PR TITLE
Vulkan: Added trait to turn on/off by platform if swapchain should be recreated when getting a suboptimal flag

### LINKED ISSUE #9397: Android crashes on Samsung Galaxy S21 after a few seconds running a level
**Describe the bug**
Running a level on Samsun Galaxy S21 lead to crash after a few seconds (10 seconds aprox).

This is the error before the crash:

````
2022-05-03 10:50:52.570 27255-27299/org.o3de.MinProject E/BufferQueueProducer: [ViewRootImpl@3e1e331[MinProjectActivity]#0(BLAST Consumer)0](id:6a7700000000,api:1,p:27255,c:27255) setMaxDequeuedBufferCount: bufferCount 65 too large (max 64)
2022-05-03 10:50:52.570 27255-27299/org.o3de.MinProject E/Surface: IGraphicBufferProducer::setBufferCount(65) returned Invalid argument
2022-05-03 10:50:52.570 27255-27299/org.o3de.MinProject E/vulkan: native_window_set_buffer_count(65) failed: Invalid argument (-22)
2022-05-03 10:50:52.570 27255-27299/org.o3de.MinProject I/System: ==================================================================
2022-05-03 10:50:52.570 27255-27299/org.o3de.MinProject I/o3de.MinProjec: <10:50:52> (System) - 
    ==================================================================
2022-05-03 10:50:52.570 27255-27299/org.o3de.MinProject I/LMBR: (System) - 
2022-05-03 10:50:52.570 27255-27299/org.o3de.MinProject I/LMBR: ==================================================================
2022-05-03 10:50:52.571 27255-27299/org.o3de.MinProject I/System: Trace::Assert
     E:/Amazon/GitHub/o3de/Gems/Atom/RHI/Vulkan/Code/Source\RHI/Vulkan.h(95): (482265554096) 'void AZ::Vulkan::AssertSuccess(VkResult)'
2022-05-03 10:50:52.571 27255-27299/org.o3de.MinProject I/o3de.MinProjec: <10:50:52> (System) - Trace::Assert
     E:/Amazon/GitHub/o3de/Gems/Atom/RHI/Vulkan/Code/Source\RHI/Vulkan.h(95): (482265554096) 'void AZ::Vulkan::AssertSuccess(VkResult)'
2022-05-03 10:50:52.571 27255-27299/org.o3de.MinProject I/LMBR: (System) - Trace::Assert
2022-05-03 10:50:52.571 27255-27299/org.o3de.MinProject I/LMBR:  E:/Amazon/GitHub/o3de/Gems/Atom/RHI/Vulkan/Code/Source\RHI/Vulkan.h(95): (482265554096) 'void AZ::Vulkan::AssertSuccess(VkResult)'
2022-05-03 10:50:52.571 27255-27299/org.o3de.MinProject I/System: ASSERT: Vulkan API method failed: Surface lost
2022-05-03 10:50:52.571 27255-27299/org.o3de.MinProject I/o3de.MinProjec: <10:50:52> (System) - ASSERT: Vulkan API method failed: Surface lost
2022-05-03 10:50:52.571 27255-27299/org.o3de.MinProject I/LMBR: (System) - ASSERT: Vulkan API method failed: Surface lost
2022-05-03 10:50:52.571 27255-27299/org.o3de.MinProject I/System: ------------------------------------------------
2022-05-03 10:50:52.571 27255-27299/org.o3de.MinProject I/o3de.MinProjec: <10:50:52> (System) - ------------------------------------------------
2022-05-03 10:50:52.571 27255-27299/org.o3de.MinProject I/LMBR: (System) - ------------------------------------------------
2022-05-03 10:50:52.571 27255-27299/org.o3de.MinProject I/System: ==================================================================
2022-05-03 10:50:52.571 27255-27299/org.o3de.MinProject I/o3de.MinProjec: <10:50:52> (System) - ==================================================================
2022-05-03 10:50:52.571 27255-27299/org.o3de.MinProject I/LMBR: (System) - ==================================================================
2022-05-03 10:50:52.583 27255-27356/org.o3de.MinProject I/o3de.MinProjec: <10:50:52> [Error] (vkDebugMessage) - ERROR: [Validation] Code 0 : Validation Error: [ UNASSIGNED-GeneralParameterError-RequiredParameter ] Object 0: handle = 0x7251c827e0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x99fb7dfd | vkAcquireNextImageKHR: required parameter swapchain specified as VK_NULL_HANDLE
2022-05-03 10:50:52.583 27255-27356/org.o3de.MinProject I/o3de.MinProjec: <10:50:52> [Error] (vkDebugMessage) - ERROR: [Validation] Code 0 : Validation Error: [ VUID-vkAcquireNextImageKHR-swapchain-parameter ] Object 0: handle = 0x7151cd1830, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x4d6f2519 | Invalid VkSwapchainKHR Object 0x0. The Vulkan spec states: swapchain must be a valid VkSwapchainKHR handle (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-swapchain-parameter)
2022-05-03 10:50:52.583 27255-27356/org.o3de.MinProject A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 27356 (Thread-4), pid 27255 (o3de.MinProject)
````

Full log here: 
[GalaxyS21 Crash.txt](https://github.com/o3de/o3de/files/8630042/GalaxyS21.Crash.txt)

NOTE: Other android devices don't show this crash. For example I couldn't reproduce this crash on an Oculus Quest 2.

**Steps to reproduce**
1. Build O3DE for Android
2. Run a level on an Android device (Galaxy S21)
3. Wait some time (1 minute for example)

**Expected behavior**
O3DE doesn't crash

**Actual behavior**
O3DE crashes after some time running the level.

**Desktop/Device (please complete the following information):**
 - Device: Samsung S21
 - OS: Android
 - Version: Android 12

### PR DESCRIPTION
**Pull request by moraaar**
Signed-off-by: moraaar <moraaar@amazon.com>

## What does this PR do?

Fixes #9397

When android is in landscape, vulkan indicates that the swapchain needs a 90 degree rotation. We're setting the identity flag to its `preTransform` property, which means the device will handle internally that rotation for us. Since the android render engine is doing the rotation, vulkan reports during `present()` that it's suboptimal and we're recreating the swapchain unnecessarily.

Since this pretransform rotation is a unique situation for android platform a trait has been added so only on Android it doesn't recreate the swapchain on suboptimal flags. This fixes that the swapchain is not created every frame for Android, which leads to a crash after 10 seconds on my Samsung device.

Other minor improvements:
- The native window on android was always initialized to 1920x1080, but that's not the native resolution of the phone and it's not the right aspect ratio either. Now using the native resolution of the device if available.
- Minor improvement setting matrices to srg in View class, removed unnecessary operations.
- Unify the creation of default swapchain in window context class, so it's the same procedure as the VR creation swapchains. The viewport and scissor are set inside the swapchain creation function. Also the initialization of swapchains can modify the values of the descriptor, so to get the latest value it's necessary to query the descriptor after initializing it.

## How was this PR tested?

Run default level on Android phone and Quest 2, checked swapchain is not created every frame and there are no crashes.

Performance:
- Samsung Galaxy S21 with swapchain of 2325x1080 runs at 9fps when looking at the floor, 22fps when looking at the sky
- Quest 2 (not vr mode) with swapcahin of 1000x625 runs at 16fps when looking at the floor, 27fps when looking at the sky.

Further profiling is needed to discover what's going on with those low framerates.

### CODE REVIEW

**Review by moudgils — APPROVED** [review]

File: Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp [hunk 1]
```diff
@@ -283,11 +283,24 @@ namespace AZ
...
                 {
                     m_pendingRecreation = true;
                 }
+                else if (result == VK_SUBOPTIMAL_KHR)
+                {
+                    // On mobile platforms the swapchain won't be recreated on VK_SUBOPTIMAL_KHR.
+                    // This is because on mobiles VK_SUBOPTIMAL_KHR is returned when the swapchain's "preTransform"
+                    // doesn't match the rotation of the device and that means its render engine internally will
+                    // perform the rotation and on certain devices that's not as optimal as being handled by O3DE.
+                    // Handle the rotation ourselves is not trivial to achieve, because the viewport dimensions have
```
Comment (jeremyong-az) [inline Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp:297]: Nit: "Handling"

**Review by jeremyong-az — APPROVED** [review]

**Review by byrcolin — APPROVED** [review]

**Review by amzn-sj — APPROVED** [review]
