### PR TITLE
Fix incorrect icon rendering

### LINKED ISSUE #2759: Be This Camera - If multiple cameras are in the scene, the camera icon will jump around on camera rotation
**Describe the bug**
When using Be This Camera, component icons for other cameras in the scene will just jump around like crazy when the camera is being moved via the viewport.

**To Reproduce**
1. Open a Level
2. Add a couple cameras
3. Select a camera and click "Be This Camera"
4. Move around in the viewport

**Expected behavior**
The other camera icons stay in their place like any other entity icon.

**Screenshots**
crazy

### PR DESCRIPTION
**Pull request by hultonha**
Fixes #2759

A fix for @AMZN-daimini! 😁

This PR now contains tests to verify the behavior before and after. It required setting up a few mocks but the good news is we can not reuse these in future for additional Editor/Viewport tests.

#### Before

```
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from EditorViewportIconFixture
[ RUN      ] EditorViewportIconFixture.ViewportIconsAreNotDisplayedWhenInBetweenCameraAndNearClipPlane
D:/o3de-2/Code/Framework/AzToolsFramework/Tests/EditorViewportIconTests.cpp(96): error: Mock function called more times than expected - returning directly.
    Function call: DrawIcon(@00000071BC7AE0A0 80-byte object <A4-09 00-00 00-00 00-00 ED-8D 1D-BF F9-7F 00-00 00-00 80-3F 00-00 80-3F 00-00 80-3F 00-00 80-3F 00-00 00-00 CD-CC 4C-3D 00-00 00-00 00-00 00-00 01-43 E5-C1 F9-7F 00-00 50-EB 40-C1 F9-7F 00-00 00-00 10-42 00-00 10-42 00-00 10-42 00-00 10-42>)
         Expected: to be never called
           Actual: called once - over-saturated and active
[  FAILED  ] EditorViewportIconFixture.ViewportIconsAreNotDisplayedWhenInBetweenCameraAndNearClipPlane (2813 ms)
[ RUN      ] EditorViewportIconFixture.ViewportIconsAreNotDisplayedWhenBehindCamera
D:/o3de-2/Code/Framework/AzToolsFramework/Tests/EditorViewportIconTests.cpp(118): error: Mock function called more times than expected - returning directly.
    Function call: DrawIcon(@00000071BC7AE0A0 80-byte object <A4-09 00-00 00-00 00-00 ED-8D 1D-BF F9-7F 00-00 00-00 80-3F 00-00 80-3F 00-00 80-3F 00-00 80-3F 00-00 00-00 00-00 80-BF 00-00 00-00 00-00 00-00 01-43 E5-C1 F9-7F 00-00 50-EB 40-C1 F9-7F 00-00 00-00 10-42 00-00 10-42 00-00 10-42 00-00 10-42>)
         Expected: to be never called
           Actual: called once - over-saturated and active
[  FAILED  ] EditorViewportIconFixture.ViewportIconsAreNotDisplayedWhenBehindCamera (2 ms)
[----------] 2 tests from EditorViewportIconFixture (2817 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (2820 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] EditorViewportIconFixture.ViewportIconsAreNotDisplayedWhenInBetweenCameraAndNearClipPlane
[  FAILED  ] EditorViewportIconFixture.ViewportIconsAreNotDisplayedWhenBehindCamera
```

#### After

```
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from EditorViewportIconFixture
[ RUN      ] EditorViewportIconFixture.ViewportIconsAreNotDisplayedWhenInBetweenCameraAndNearClipPlane
[       OK ] EditorViewportIconFixture.ViewportIconsAreNotDisplayedWhenInBetweenCameraAndNearClipPlane (1 ms)
[ RUN      ] EditorViewportIconFixture.ViewportIconsAreNotDisplayedWhenBehindCamera
[       OK ] EditorViewportIconFixture.ViewportIconsAreNotDisplayedWhenBehindCamera (0 ms)
[----------] 2 tests from EditorViewportIconFixture (2 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (3 ms total)
[  PASSED  ] 2 tests.
```

### CODE REVIEW

**Review by cgalvan — APPROVED** [review]

File: Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/Mocks/MockEditorViewportIconDisplayInterface.h [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+
+        void Register()
+        {
+            AZ::Interface<EditorViewportIconDisplayInterface>::Register(this);
+        }
+
+        void Deregister()
+        {
+            AZ::Interface<EditorViewportIconDisplayInterface>::Unregister(this);
+        }
```
Comment (moraaar) [inline Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/Mocks/MockEditorViewportIconDisplayInterface.h:30]: In case you find this useful, the class could inherit from `public AzToolsFramework::EditorViewportIconDisplayInterface::Registrar` and it would the the registration automatically for you on instantiation/destruction, functions `Register` and `Deregister` could be removed.

**Review by moraaar — APPROVED** [review]
Looks great. Just one suggestion, but nothing blocking.

File: Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/Mocks/MockEditorViewportIconDisplayInterface.h (hunk 1 above)
Comment (hultonha) [reply Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/Mocks/MockEditorViewportIconDisplayInterface.h:30]: Oh interesting! I was not aware of this, I can make this update as it avoids some additional boilerplate, thanks for the suggestion! 👍

**Review by moraaar — APPROVED** [review]
