### PR TITLE
Stop Non-Net Prefabs from Producing Network.Spawnable 

### LINKED ISSUE #11405: Multiplayer: Prefabs Without Any Network Components Produce .Network.Spawnables
**Describe the bug**
Levels without any network components produce a .network.spawnables file

**Steps to reproduce: Create a Level**
1. Open Editor.exe
2. Create a new level
3. Save the new level
4. Open cache folder and find the new level

**Steps to reproduce: Create a Prefab**
1. Open Editor.exe
2. Create a new prefab
3. Open cache folder and find the new prefab

**Expected behavior**
Cache folder only contains a .spawnable file

**Actual behavior**
Cache folder contains a .spawnable file and .network.spawnable file even though there are no network entities

**Found in Branch**
development

image

### PR DESCRIPTION
**Pull request by AMZN-Gene**
## What does this PR do?
Stop asset processor from producing network spawnable for non-net prefabs

Fixes #11405 

## How was this PR tested?
Created a network prefab and non-network prefab and make sure network.spawnable is only created for the network prefab.

### CODE REVIEW

File: Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp [hunk 1]
```diff
@@ -183,6 +186,11 @@ namespace Multiplayer
             context,
             networkSpawnableAssetId);
 
+        if (networkInstance.GetEntityAliasCount() == 0 && networkInstance.GetNestedEntityAliasCount() == 0)
```
Comment (srikappa-amzn) [inline Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp:189]: You can just use GetNestedEntityIds() and provide a callback that increments count for this purpose.

**Review by srikappa-amzn — COMMENTED** [review]
A unit test to check that '.network.spawnable' doesn't get created for regular prefabs would be good to add with this change.

**Review by kberg-amzn — COMMENTED** [review]
Is this the correct branch? This looks like your log scrape removal test changes. I'm totally okay with combining the two fixes together, but you might want to update the title and description of the pull-request.

**Comment by AMZN-Gene** [comment]
> Is this the correct branch? This looks like your log scrape removal test changes. I'm totally okay with combining the two fixes together, but you might want to update the title and description of the pull-request.

That was an accident! I'll clean up this branch, ha!

File: Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp (hunk 1 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp:189]: I just noticed that GetEntityAliasCount exists, so seems like we should do the same for GetNestedEntityAliasCount. Iterating each would work, but felt too obfuscated. Thoughts?

Comment (srikappa-amzn) [reply Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp:189]: What you are getting here is the count of number of nested instances, which won't give you the correct number of nested entities anyway. Each nested instance can have any number of entities under them. You'd need to implement a recursive logic like GetNestedEntitiyIds() does. But since that function already exists and serves the exact problem you are looking to use, you can avoid creating this new function altogether.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.h [hunk 2]
```diff
@@ -135,6 +135,7 @@ namespace AzToolsFramework
             * Gets the ids for the entities in the Instance DOM.  Can recursively trace all nested instances.
             */
             void GetNestedEntityIds(const AZStd::function<bool(AZ::EntityId)>& callback) const;
+            size_t GetNestedEntityAliasCount() const;
```
Comment (lmbr-pip) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.h:138]: nit: Not clear to me what the difference is between GetEntityAliasCount and GetNestedEntityAliasCount, I would consider adding public comments to clarify difference

File: Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp [hunk 3]
```diff
@@ -102,34 +102,37 @@ namespace Multiplayer
...
-                PrefabEntityId prefabEntityId;
-                prefabEntityId.m_prefabName = sourceEntity->GetName();
-                NetBindComponent* netBindComponent = netEntity->FindComponent<NetBindComponent>();
-                netBindComponent->SetPrefabAssetId(networkSpawnableAssetId);
-                netBindComponent->SetPrefabEntityId(prefabEntityId);
+                return true; // return true tells GetEntities to continue iterating over all the entities
             }
+
+            AZ::Entity* entity = sourceEntity.get();
+            AZ::Entity* netEntity = SpawnableUtils::CreateEntityAlias(
```
Comment (lmbr-pip) [inline Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp:111]: Have you ensured code above has safety checks for de-references?

File: Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp [hunk 4]
```diff
@@ -102,34 +102,37 @@ namespace Multiplayer
...
+                *rootNetworkInstance,
+                *networkInstance,
+                entity->GetId(),
+                AzToolsFramework::Prefab::PrefabConversionUtils::EntityAliasType::Replace,
+                AzToolsFramework::Prefab::PrefabConversionUtils::EntityAliasSpawnableLoadBehavior::DependentLoad,
+                NetworkEntityManager::NetworkEntityTag,
+                context);
+
+            AZ_Assert(
+                netEntity, "Unable to create alias for entity %s [%zu] from the source prefab instance", entity->GetName().c_str(),
```
Comment (lmbr-pip) [inline Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp:124]: do we need to include source prefab instance identifier here for debugging?

File: Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp (hunk 1 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp]: Thank you! That explanation helps :)
Checkout the latest, I just track network entities in the pre-existing loop. Added a unit test as well called NetworkPrefabProcessor_ProcessPrefabEntityHierarchy_NestedNetworkEntityIsFound

File: Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.h (hunk 2 above)
Comment (AMZN-Gene) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.h]: Removed entirely as it's not needed

**Comment by AMZN-Gene** [comment]
> A unit test to check that '.network.spawnable' doesn't get created for regular prefabs would be good to add with this change.

Unit tested added to make sure. Also added unit tests in general for network spawnables as the file existed, but wasn't actually being used (or compile).

File: Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp (hunk 3 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp:121]: Good question! The GetEntities() method will not callback for null entities :)

File: Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp (hunk 4 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp]: Good catch! I've added the source prefab name here :)

**Review by SergeyAMZN — APPROVED** [review]

File: Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp [hunk 5]
```diff
@@ -173,6 +196,7 @@ namespace Multiplayer
         AZ::Data::AssetId networkSpawnableAssetId(context.GetSourceUuid(), AzFramework::SpawnableAssetHandler::BuildSubId(uniqueName));
```
Comment (srikappa-amzn) [inline Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp:196]: Because of the way the code is written (lot of output parameters), this is currently hard to refactor. So, this is something that you can look into as a follow up. But everything here technically can be skipped if there are no network entities to begin with.

File: Gems/Multiplayer/Code/Tests/PrefabProcessingTests.cpp [hunk 6]
```diff
@@ -247,4 +283,46 @@ namespace UnitTest
...
+        Multiplayer::NetworkPrefabProcessor processor;
+        processor.Process(prefabProcessorContext);
+        AzToolsFramework::Prefab::PrefabConversionUtils::PrefabCatchmentProcessor prefabCatchmentProcessor;
+        prefabCatchmentProcessor.Process(prefabProcessorContext);
+        EXPECT_TRUE(prefabProcessorContext.HasCompletedSuccessfully());
+
+        // Verify entities are ordered by parent/child hierarchy
+        const auto& processedObjects = prefabProcessorContext.GetProcessedObjects();
+
+        // Verify that the nested network entity was discovered and 2 processed objects (spawnable and network.spawnable) were created
```
Comment (srikappa-amzn) [inline Gems/Multiplayer/Code/Tests/PrefabProcessingTests.cpp:325]: comment looks incorrect. You are not verifying that the network entity is present in the network spawnable. You can probably create helper functions  and share it with the other tests:

- Helper to verify that a non-networked entity is in a non-networked spawnable
- Helper to verify that a networked entity is in a networked spawnable.

Maybe both of them can be merged into a single helper (spawnable has an entity)

**Review by srikappa-amzn — APPROVED** [review]
Looks good to me. Thanks for incorporating the test suggestions.
