### PR TITLE
Document Property Editor Map Improvements

### LINKED ISSUE #16770: DPE: Elements of sets are not displayed correctly and are read-only
**Describe the bug**
When the DPE is enabled, elements of sets become read-only.
Numerical values (`size_t`) are displayed incorrectly (looking random / corrupted).

**Assets required**
Any component with field of type `AZStd::set<size_t>` exposed in Edit Context. 

**Steps to reproduce**

1. Create empty level.
2. Create a new entity, and add component with `AZStd::set<size_t>`
3. Add some elements to the set. 

**Expected behavior**
Added elements are visible in the set. They can be modified. Number of elements is consistent with number of "add" operations.

**Actual behavior**
Value is not added correctly to the set. It is displayed incorrectly, and changes each time the entity is opened in the Inspector.  
With DPE disabled it is visible as 0, regardless of user input during insert. After the first value is inserted, the next "add" operation doesn't add a value.

Numerical values already present in the set (added when DPE was disabled) are displayed incorrectly as well.

**Screenshots/Video**

DPE enabled:
image

Note: the index displayed here is always 0, regardless of the number of elements. This window is also scaled incorrectly.
image

DPE disabled:
This is the same set, the values were preserved when DPE was enabled and are now correctly visible again
image
There is no index displayed:
image

**Found in Branch**
[o3de/stabilization2310](https://github.com/o3de/o3de/tree/stabilization/2310) with https://github.com/o3de/o3de/pull/16764 applied.

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/pull/16764/commits/53d2071a87236a2ffe252ef59282aafdf00c2cf7

**Desktop/Device (please complete the following information):**
 - Device: AORUS
 - OS: Ubuntu 
 - Version 22.04
 - CPU 12th Gen Intel® Core™ i5-12500H × 16
 - GPU  NVIDIA GeForce RTX 4060 Laptop GPU
 - Memory 64.0 GiB

### LINKED ISSUE #16771: DPE: Maps are displayed incorrectly.
**Describe the bug**
When the DPE is enabled, some maps are displayed incorrectly: 
- the key is not displayed at all, just the value
- numerical (`size_t`) values look incorrect, as in https://github.com/o3de/o3de/issues/16770

**Assets required**
Any component with field of type `AZStd::unordered_map<AZ::EntityId, size_t>` exposed in Edit Context. 

**Steps to reproduce**

1. Create empty level.
2. Create a new entity, and add component with `AZStd::unordered_map<AZ::EntityId, size_t>`
3. Add some elements to the map (to avoid [16769](https://github.com/o3de/o3de/issues/16769) set them as default in component's code or disable DPE for a moment)

**Expected behavior**
Added elements are visible in the map. Values can be changed, and behave normally.

**Actual behavior**
The keys are not displayed at all. 
Numerical values seem random/corrupt and change each time Inspector is opened on the entity.

**Screenshots/Video**

DPE enabled:
image

DPE disabled:
image

With field of type `AZStd::unordered_map<size_t, size_t>`:
DPE enabled:
image
DPE disabled:
image

Note: with `AZStd::unordered_map<int, int>` everything seems to work correctly.

**Found in Branch**
[o3de/stabilization2310](https://github.com/o3de/o3de/tree/stabilization/2310) with https://github.com/o3de/o3de/pull/16764 applied.

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/pull/16764/commits/53d2071a87236a2ffe252ef59282aafdf00c2cf7

**Desktop/Device (please complete the following information):**
 - Device: AORUS
 - OS: Ubuntu 
 - Version 22.04
 - CPU 12th Gen Intel® Core™ i5-12500H × 16
 - GPU  NVIDIA GeForce RTX 4060 Laptop GPU
 - Memory 64.0 GiB

### PR DESCRIPTION
**Pull request by lumberyard-employee-dm**
Added support to the Legacy Reflection Bridge to access Enum options reflected to the Serialize Context, to allow an enum value to be displayed as string instead of a number

Added support for a ToString attribute which works with both the EditContext and SerializeContext, that can be used to convert a type instance to a string.

So far the AZStd::pair reflection has a `ToString` attribute which can convert both elements of a pair to a string.

The Legacy Reflection Bridge associative container support has been updated to query the `ToString` attribute for any key it is processing and use that attribute function to convert the key to a string.

This allows aggregate types like a pair to be convertable to a label that is displayable in the DPE.

fixes #16771
fixes #16770

## How was this PR tested?

Verified the associative container changes in the `DPEDebugViewStandalone` application
image

### CODE REVIEW

File: Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp [hunk 1]
```diff
@@ -818,11 +981,6 @@ namespace AZ::Reflection
                 {
                     StackEntry& parentData = m_stack.back();
 
-                    if (!parentData.m_group.empty())
-                    {
-                        EndNode();
-                    }
-
```
Comment (cgalvan) [inline Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp:825]: Is this going to prevent an empty group name from closing a group?

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h [hunk 2]
```diff
@@ -354,31 +366,60 @@ namespace AzToolsFramework
...
+                    typeId = AZ::Dom::Utils::DomValueToTypeId(typeIdAttribute->second);
+                }
+                else if (value.has_value())
+                {
+                    typeId = AZ::Dom::Utils::GetValueTypeId(value.value());
+                }
+                if (!typeId.IsNull())
+                {
+                    m_proxyClassElement.m_genericClassInfo = serializeContext->FindGenericClassInfo(typeId);
+                }
```
Comment (cgalvan) [inline Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h:422]: I think this should be OK, a quick verification would be to check if setting/clearing a mesh asset still works.

**Review by cgalvan — APPROVED** [review]

**Comment by apmontgo** [comment]
Any idea  why all the Pair  elements in the screenshot say "2 elements" even though they seemingly only have one?

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h (hunk 2 above)
Comment (lumberyard-employee-dm) [reply Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h:422]: Actually this doesn't affect clearing an asset. The logic that handles that case was in the the ReflectionAdapter using JSON Serialization to copy new Dom updated Dom::Value with the Asset reference being cleared to the Dom::Value object representing the instance data.

The AssetJsonSerializer previously would call `AssetJsonSerializer::Store` which works to store an AssetID with guid of all's 0 (a null GUID), but the `AssetJsonSerializer::Load` would check if GUID is null and if so it would clear out the instance being loaded into.
Here is the old code for reference: https://github.com/o3de/o3de/blob/152bc0a1851d881fe735adf54ec93e1ad7875b11/Code/Framework/AzCore/AzCore/Asset/AssetJsonSerializer.cpp#L133-L142

I fixed that issue in this PR https://github.com/o3de/o3de/commit/3393f127db73e410449a06e5daa417786c06c4c2.

Now on the subject of setting the Asset reference, that occurs in a different function `PropertyEditorAPI_Internals.h`.
The [RpePropertyHandlerWrapper::OnValueChanged](https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h#L508-L540) function is where a storing convertible type such as an `Asset<MeshAsset>` into an `Asset<AssetData>` occurs.

**Comment by lumberyard-employee-dm** [comment]
> Any idea why all the Pair elements in the screenshot say "2 elements" even though they seemingly only have one?

Because a pair always has 2 elements, the `first` and the `second` elements of the pair are always there.
There is no way to have a pair of 0 or 1 element. It is a [fixed size container](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Serialization/AZStdContainers.inl#L1098-L1117).

For when it is viewed as an associative container element, we hide the showing the `first` element because that is the key of an associative element and instead only show the `second` element which is the value. 
We use the `first` element as the label for the `second` element to get it to show on one line.

**Comment by alexmontAmazon** [comment]
> > Any idea why all the Pair elements in the screenshot say "2 elements" even though they seemingly only have one?
> 
> Because a pair always has 2 elements, the `first` and the `second` elements of the pair are always there. There is no way to have a pair of 0 or 1 element. It is a [fixed size container](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Serialization/AZStdContainers.inl#L1098-L1117).
> 
> For when it is viewed as an associative container element, we hide the showing the `first` element because that is the key of an associative element and instead only show the `second` element which is the value. We use the `first` element as the label for the `second` element to get it to show on one line.

Interesting, I've always thought of a pair as a singular object with two halves, much like I'd expect a map that had one entry of <key, value> to report a size() of 1. I guess it doesn't really matter, since a std::pair isn't really a container at all, and doesn't seem to have a size() in the standard c++ library...

**Review by alexmontAmazon — APPROVED** [review]
looks good to me -- a major upgrade in fact!

**Comment by lumberyard-employee-dm** [comment]
> > > Any idea why all the Pair elements in the screenshot say "2 elements" even though they seemingly only have one?
> > 
> > 
> > Because a pair always has 2 elements, the `first` and the `second` elements of the pair are always there. There is no way to have a pair of 0 or 1 element. It is a [fixed size container](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Serialization/AZStdContainers.inl#L1098-L1117).
> > For when it is viewed as an associative container element, we hide the showing the `first` element because that is the key of an associative element and instead only show the `second` element which is the value. We use the `first` element as the label for the `second` element to get it to show on one line.
> 
> Interesting, I've always thought of a pair as a singular object with two halves, much like I'd expect a map that had one entry of <key, value> to report a size() of 1. I guess it doesn't really matter, since a std::pair isn't really a container at all, and doesn't seem to have a size() in the standard c++ library...

A pair actual does have a size in the standard library.
It is retrievable using the `std::tuple_size` template and it is always [2](https://en.cppreference.com/w/cpp/utility/pair/tuple_size)
