### PR TITLE
NetworkSpawnable Added To Ensure Designers Only Select Network Spawnables

### LINKED ISSUE #9513: NetworkPlayerSpawnerComponent Allows Users to Select Non-Network Prefabs
**Describe the bug**
NetworkPlayerSpawnerComponent allows users to select non-network prefabs, Net-players will always need a net-binding so we should enforce only prefabs which contain a .network product. 

**Steps to reproduce**
1. Add an entity with NetworkPlayerSpawnerComponent 
2. Select a non-network prefab for the SpawnableAsset field

**Expected behavior**
Editor should give a warning, or block the user from selecting non-net prefabs

**Actual behavior**
Editor gladly accepts an non-net prefab

**Found in Branch**
development 5/10/2022

### PR DESCRIPTION
**Pull request by AMZN-Gene**
## What does this PR do?
Creates a new Multiplayer wrapper class called NetworkSpawnable which Multiplayer auto-components can use to make sure the editor only allows selecting .network.spawnable assets (not normal .spawnable assets)

image
image

Fixes #9513

## How was this PR tested?
Updated Multiplayer Sample NetworkPlayerSpawner to use the new NetworkSpawnable type and see that a warning popup occurs when selecting a normal spawnable.

### CODE REVIEW

File: Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerTypes.h [hunk 1]
```diff
@@ -189,6 +210,54 @@ namespace Multiplayer
...
+
+    inline AZ::Outcome<void, AZStd::string> NetworkSpawnable::ValidatePotentialSpawnableAsset(void* newValue, const AZ::Uuid& valueType) const
+    {
+        if (azrtti_typeid<AZ::Data::Asset<AzFramework::Spawnable>>() != valueType)
+        {
+            AZ_Assert(false, "Unexpected value type");
+            return AZ::Failure(AZStd::string("Trying to set an network spawnable to something that isn't a spawnable!"));
+        }
+
+        const auto potentialNetworkSpawnable = static_cast<AZ::Data::Asset<AzFramework::Spawnable>*>(newValue);
```
Comment (lumberyard-employee-dm) [inline Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerTypes.h:250]: This should be a reinterpret_cast in this case since it is casting from a void*

**Review by kberg-amzn — APPROVED** [review]
Awesome change. Other than Derric's observations this looks great.

File: Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerTypes.h [hunk 2]
```diff
@@ -8,16 +8,24 @@
 
 #pragma once
 
+
+#include <AzCore/Asset/AssetCommon.h>
```
[the remark this answers is not in the document]
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerTypes.h]: thank you! fixed!

File: Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerTypes.h [hunk 3]
```diff
@@ -189,6 +206,54 @@ namespace Multiplayer
...
+            }
+        }
+    }
+
+    inline AZ::Outcome<void, AZStd::string> NetworkSpawnable::ValidatePotentialSpawnableAsset(void* newValue, const AZ::Uuid& valueType) const
+    {
+        if (azrtti_typeid<AZ::Data::Asset<AzFramework::Spawnable>>() != valueType)
+        {
+            AZ_Assert(false, "Unexpected value type");
+            return AZ::Failure(AZStd::string("Trying to set an network spawnable to something that isn't a spawnable!"));
```
Comment (AMZN-puvvadar) [inline Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerTypes.h:243]:
```suggestion
            return AZ::Failure(AZStd::string("Trying to set a network spawnable to something that isn't a spawnable!"));
```
NP: Typo

File: Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerTypes.h [hunk 4]
```diff
@@ -189,6 +206,54 @@ namespace Multiplayer
...
+        }
+
+        const auto potentialNetworkSpawnable = static_cast<AZ::Data::Asset<AzFramework::Spawnable>*>(newValue);
+        if (!potentialNetworkSpawnable->GetHint().ends_with(NetworkSpawnableFileExtension))
+        {
+            return AZ::Failure(AZStd::string::format(
+                "Normal spawnable (%s) was selected! Please select a network spawnable with a %s file extension.",
```
Comment (lmbr-pip) [inline Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerTypes.h:250]: "Normal Spawnable" sounds a little odd? What is "Normal" here? Consider 
```suggestion
                "Non-network spawnable (%s) was selected! Please select a network spawnable with a %s file extension.",
```

File: Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerTypes.h (hunk 1 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerTypes.h:246]: I think static_cast is cooler here right; more restrictive = safer? Leave reinterpret_cast for wild-west "convert anything to anything because I know it's weird, but I know what I'm doing". Like when wanting to cast a int* to an float* or something :P 
Thoughts?

File: Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerTypes.h (hunk 4 above)
Comment (AMZN-Gene) [reply Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerTypes.h]: thank you! fixed!

**Review by lumberyard-employee-dm — APPROVED** [review]
