### PR TITLE
Action Manager - Migrate the Viewport ToolBar to use the new system (Part 1)

### LINKED ISSUE #12561: Action Manager: "Go to Position" does not function from the Viewport Camera dropdown menu
**Describe the bug**
"Go to Position" does not function from the Viewport Camera dropdown menu. Without the Action Manager active, this option opens a dialog to enter coordinates to go to. With the Action Manager active, the option does nothing.

**Steps to reproduce**
1. Launch the Editor with the new Action Manager created Menus active:
```
Editor.exe --regset=O3DE/ActionManager/EnableNewActionManager=true
```
2. To the top-right of the Viewport, click the Camera icon, and then select Go to position.

**Expected behavior**
A dialog opens allowing the user to enter coordinates to go to.

**Actual behavior**
No dialog opens.

**Screenshots/Video**
Attached video shows the option not working with Action Manager active, and then working with the Action Manager disabled.

https://user-images.githubusercontent.com/82226555/195388441-73f806d3-00af-4914-88ca-1fbe06c9fa6d.mp4

**Found in Branch**
development@ 221cd9e5c29ecc480d9cb0155c00a6280e678c2f

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

### PR DESCRIPTION
**Pull request by AMZN-daimini**
## What does this PR do?

Migrates the Viewport ToolBar to the Action Manager system.
Includes Prefab widgets (breadcrumbs and edit mode visualization selector) and part of the menus (helpers, debug and part of the camera).

ViewportToolBar

A follow-up PR will also migrate the remaining menus (will need to consult @o3de/sig-ui-ux before that work is started).

## How was this PR tested?
Manual testing.

Fixes #12561 and #12541

### CODE REVIEW

File: Code/Editor/Core/EditorActionsHandler.cpp [hunk 1]
```diff
@@ -89,6 +93,39 @@ static constexpr AZStd::string_view PlayControlsToolBarIdentifier = "o3de.toolba
 
 static const int maxRecentFiles = 10;
 
+class EditorViewportDisplayInfoHandler
+: private AZ::AtomBridge::AtomViewportInfoDisplayNotificationBus::Handler
```
Comment (amzn-tmryan) [inline Code/Editor/Core/EditorActionsHandler.cpp:97]: nit: Missing indent before inheritance expression.

File: Code/Editor/Core/EditorActionsHandler.h [hunk 2]
```diff
@@ -118,6 +120,8 @@ class EditorActionsHandler
     MainWindow* m_mainWindow;
     QtViewPaneManager* m_qtViewPaneManager;
 
+    EditorViewportDisplayInfoHandler* m_editorViewportDisplayInfoHandler = nullptr;
```
Comment (amzn-tmryan) [inline Code/Editor/Core/EditorActionsHandler.h:123]: Could this be a AZStd::unique_ptr?

File: Code/Editor/Core/EditorActionsHandler.cpp [hunk 3]
```diff
@@ -1778,6 +1833,13 @@ void EditorActionsHandler::OnOnlyShowHelpersForSelectedEntitiesChanged([[maybe_u
     m_actionManagerInterface->TriggerActionUpdater(OnlyShowHelpersForSelectedEntitiesIdentifier);
 }
 
+/*
+void EditorActionsHandler::OnViewportInfoDisplayStateChanged([[maybe_unused]] AZ::AtomBridge::ViewportInfoDisplayState state)
+{
+    m_actionManagerInterface->TriggerActionUpdater(ViewportDisplayInfoStateChangedUpdaterIdentifier);
+}
+*/
+
```
Comment (dtamkin1) [inline Code/Editor/Core/EditorActionsHandler.cpp:1842]: Is this meant to be commented out here?

File: Code/Editor/Core/Widgets/PrefabEditVisualModeWidget.h [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+
+#include <AzToolsFramework/Prefab/PrefabFocusNotificationBus.h>
+#include <AzQtComponents/Components/Widgets/ComboBox.h>
+
+#include <QComboBox>
+#include <QLabel>
+#include <QWidget>
+
+// Widget to select the Prefab Edit mode visualization.
+class PrefabEditVisualModeWidget
```
Comment (amzn-tmryan) [inline Code/Editor/Core/Widgets/PrefabEditVisualModeWidget.h:19]: Just curious. Why does this need to go in Editor/Core instead of in AzQtComponents?

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp [hunk 5]
```diff
@@ -551,7 +631,7 @@ namespace AzToolsFramework
         {
             s_prefabFocusPublicInterface->FocusOnOwningPrefab(AZ::EntityId());
         }
-
+
```
Comment (dtamkin1) [inline Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp:634]: Not sure but this looks like weird spacing here?

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.h [hunk 6]
```diff
@@ -63,6 +69,10 @@ namespace AzToolsFramework
             void OnStartPlayInEditorBegin() override;
             void OnStopPlayInEditor() override;
 
+            // PrefabFocusNotificationBus
```
Comment (dtamkin1) [inline Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.h:72]: nit: PrefabFocusNotificationBus overrides

**Review by cgalvan — APPROVED** [review]

File: Code/Editor/Core/EditorActionsHandler.cpp (hunk 3 above)
Comment (AMZN-daimini) [reply Code/Editor/Core/EditorActionsHandler.cpp:1842]: No, I had deleted it but forgot to push the change. Fixed!

**Review by amzn-tmryan — APPROVED** [review]

**Review by dtamkin1 — APPROVED** [review]

File: Code/Editor/Core/EditorActionsHandler.cpp (hunk 1 above)
Comment (AMZN-daimini) [reply Code/Editor/Core/EditorActionsHandler.cpp:97]: Fixed!

File: Code/Editor/Core/Widgets/PrefabEditVisualModeWidget.h (hunk 4 above)
Comment (AMZN-daimini) [reply Code/Editor/Core/Widgets/PrefabEditVisualModeWidget.h:19]: AzQtComponents contains widgets that can be used as a base for UI elements - so they are not tied to specifics (like for example the Prefab system, in this case). This widget is specific to the prefab edit visualization, so it should live in the Editor side of things.

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp (hunk 5 above)
Comment (AMZN-daimini) [reply Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp:634]: Fixed!

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.h (hunk 6 above)
Comment (AMZN-daimini) [reply Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.h:72]: Fixed, thanks!

**Comment by hultonha** [comment]
@AMZN-daimini There seems to be quite a lot of options missing from the camera drop down (e.g. speed and fov etc...) Is this system still off by default so those won't disappear for users? Just want to double check! 😅 Thanks!

File: Code/Editor/Core/EditorActionsHandler.cpp [hunk 7]
```diff
@@ -158,6 +198,11 @@ EditorActionsHandler::~EditorActionsHandler()
         AzToolsFramework::EditorEntityContextNotificationBus::Handler::BusDisconnect();
         AzToolsFramework::EditorEventsBus::Handler::BusDisconnect();
         AzToolsFramework::ActionManagerRegistrationNotificationBus::Handler::BusDisconnect();
+
+        if (m_editorViewportDisplayInfoHandler)
+        {
+            delete m_editorViewportDisplayInfoHandler;
+        }
```
Comment (hultonha) [inline Code/Editor/Core/EditorActionsHandler.cpp:205]: nit: It's not necessary to check if a pointer is null before deleting it, deleting a nullptr is just a noop

File: Code/Editor/Core/EditorActionsHandler.cpp [hunk 8]
```diff
@@ -146,6 +183,9 @@ void EditorActionsHandler::Initialize(MainWindow* mainWindow)
     AzToolsFramework::EditorEntityContextNotificationBus::Handler::BusConnect();
     AzToolsFramework::ToolsApplicationNotificationBus::Handler::BusConnect();
     AzToolsFramework::ViewportInteraction::ViewportSettingsNotificationBus::Handler::BusConnect(DefaultViewportId);
+
+    m_editorViewportDisplayInfoHandler = new EditorViewportDisplayInfoHandler();
```
Comment (hultonha) [inline Code/Editor/Core/EditorActionsHandler.cpp:187]: question: This is likely moot now given @burelc-amzn's recent change that makes `aznew` obsolete but I wanted to check if we should use that here? (maybe we could do an audit to delete references to it if it's no longer required in a separate PR - this suggestion is for Chris 😛)

File: Code/Editor/ViewPane.cpp [hunk 9]
```diff
@@ -142,65 +157,287 @@ class ViewportTitleExpanderWatcher
...
+
+        m_actionManagerInterface->RegisterCheckableAction(
+            EditorMainWindowActionContextIdentifier,
+            actionIdentifier,
+            actionProperties,
+            [viewportTitleDlg = m_viewportTitleDlg]
+            {
+                viewportTitleDlg->SetNormalViewportInfo();
+            },
+            []() -> bool
```
Comment (hultonha) [inline Code/Editor/ViewPane.cpp:315]: nit: the `-> bool` should be redundant and can be omitted if desired

**Review by hultonha — APPROVED** [review]
Updates look great! There's some changes I wanted to make in the camera drop-down soon but they can wait until this is complete. My suggestions were only nits and can be done in a follow-up PR if possible

File: Code/Editor/Core/EditorActionsHandler.cpp (hunk 8 above)
Comment (AMZN-daimini) [reply Code/Editor/Core/EditorActionsHandler.cpp:187]: That's what I did at first but VS gave me errors, so I just resorted to new.

File: Code/Editor/ViewPane.cpp (hunk 9 above)
Comment (AMZN-daimini) [reply Code/Editor/ViewPane.cpp:315]: Yeah I tend to leave it by force of habit, and I like that it makes it more readable on which one is the behavior and which one is the callback.

File: Code/Editor/Core/EditorActionsHandler.cpp (hunk 8 above)
Comment (hultonha) [reply Code/Editor/Core/EditorActionsHandler.cpp:187]: Hmm maybe was missing an include, shouldn't matter either way soon 👍

**Comment by AMZN-daimini** [comment]
> @AMZN-daimini There seems to be quite a lot of options missing from the camera drop down (e.g. speed and fov etc...) Is this system still off by default so those won't disappear for users? Just want to double check! 😅 Thanks!

This is part 1, I will handle those in part 2 :D

I see there's like 3 different UIs for float and bool property selectors in that menu so I am trying to set up a UX discussion about it before working on the rest, in order to try and save iteration time and standardize the UX.
Let me know if you would want to be looped into that chat when it happens!

**Comment by AMZN-daimini** [comment]
(Oh and yes this is all only available when the ActionManager setreg is enabled, which is off by default)

**Comment by hultonha** [comment]
> > @AMZN-daimini There seems to be quite a lot of options missing from the camera drop down (e.g. speed and fov etc...) Is this system still off by default so those won't disappear for users? Just want to double check! 😅 Thanks!
> 
> This is part 1, I will handle those in part 2 :D
> 
> I see there's like 3 different UIs for float and bool property selectors in that menu so I am trying to set up a UX discussion about it before working on the rest, in order to try and save iteration time and standardize the UX. Let me know if you would want to be looped into that chat when it happens!

Haha okay excellent thanks for clarifying 😅 Much appreciated! Happy to join but it's fine if I can't make it, I'd be interested to hear whatever you decide 👍
