### PR TITLE
Script Canvas: Add translation support to method node execution slots

### LINKED ISSUE #13692: Script Canvas: Modifications made to "Entry" and "Exit" translation data are not reflected on the node
**Describe the bug**
Modifying the _Entry_ or _Exit_ translation date does not modify the node in Script Canvas. 
Additionally, the default tooltip values on the _Entry_ and _Exit_ pins are not reflected on the node. This results in the nodes which use the _entry_ / _exit_ parameters are missing their tooltips and the custom pin names.

Please note that modifying other values (i.e. _params_) correctly changes the on-node values in Script Canvas.

Refer to the attached video for more details.

**Steps to reproduce**
1. Launch Script Canvas.
2. Right click any node in the Node Palette and select _Generate Translation_ (I have used the _Exists_ node from _Entity/Entity_ category in the video).
3. Once the File Explorer opens, edit the selected .names file in any text editor.
4. Search for the selected node's name in the file (i.e. _Exists_).
5. Modify the _name_ and _tooltip_ values under the _entry_ and _exit_ parameter.
6. Save the file.
7. Restart Script Canvas.
8. Add the modified node to the graph area.

**Expected behavior**
Modifications made to "Entry" and "Exit" translation data are correctly reflected on the node.

**Actual behavior**
Modifications made to "Entry" and "Exit" translation data are not reflected on the node.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/207586462-5d726a5c-484e-480d-85cf-5e7897f580d5.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
35ee631

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

### PR DESCRIPTION
**Pull request by lsemp3d**
## What does this PR do?

Add translation support to method node execution slots. 

Closes #13692

### CODE REVIEW

File: Gems/ScriptCanvas/Code/Editor/Nodes/NodeDisplayUtils.cpp [hunk 1]
```diff
@@ -464,6 +464,32 @@ namespace ScriptCanvasEditor::Nodes
...
+                else
+                {
+                    AZStd::string direction = (slot.IsInput()) ? "entry" : "exit";
+
+                    // Get the translated value for the execution slot
+                    key.clear();
+                    key << context << className << "methods" << updatedMethodName << direction << "name";
+
+                    bool success = false;
+                    AZStd::string result = "";
```
Comment (gadams3) [inline Gems/ScriptCanvas/Code/Editor/Nodes/NodeDisplayUtils.cpp:476]:
```suggestion
                    AZStd::string result;
```

**Review by gadams3 — APPROVED** [review]

**Review by dtamkin1 — APPROVED** [review]
