### PR TITLE
Settings registry notification deadlock fix

### LINKED ISSUE #3066: Settings Registry notification event signaling blocks other threads from updating/querying the Settings Registry
**Describe the bug**
The Settings Registry sends out notification event for when a particular setting is modified within the Settings Registry.
It does this under the [m_settingsMutex](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.h#L104) lock.

The issue is that the handlers of the notification event is not controlled by the Settings Registry, so the handlers can perform all sorts of logic such as attempting to acquire mutexes that other threads have locked at the time.

If a connected notification handler on thread `#1` tries to acquire the `AssetCatalogRequests` EBus mutex, while another thread(`#2`)  that has acquired the `AssetCatalogRequests` lock.
If thread `#2` attempts to query a value from the Settings Registry it will lead to a deadlock, as querying the settings registry attempts to lock the `m_settingsMutex`

**To Reproduce**
1. Create a .cfg file inside of a project's that contains a LoadLevel command that loads an existing level
1. Launch the GameLauncher on Mac and supply the `--console-command-file` option the created .cfg file
1. Notice deadlock on startup

**Expected behavior**
GameLauncher launches on Mac without deadlock

**Screenshots**
image

**Desktop/Device (please complete the following information):**
 - Device: [Mac,] 
 - OS: [macOS,]
 - Version [Bug Sur]

**Additional context**
None

### PR DESCRIPTION
**Pull request by lumberyard-employee-dm**
- Added a `StealHandlers` function to AZ::Event to allow one event to "steal" all the handlers from another event.
- Split the Settings Registry mutex out to a setting modification mutex and a notification event mutex
- Wrapped the Settings Registry notification event signaling into a function that uses a lock and swap algorithm to allow signaling connected event handlers without having any mutex locked
- Added more fine-grained locking of the Settings Registry modification mutex to reduce lock time.

resolves #3066

### CODE REVIEW

**Review by cgalvan — APPROVED** [review]

File: Code/Framework/AzCore/AzCore/EBus/Event.h [hunk 1]
```diff
@@ -58,6 +58,12 @@ namespace AZ
 
         Event& operator=(Event&& rhs);
 
+        //! Take the handlers registered with the other event
+        //! and move them to this event. The other will event
+        //! will be cleared after call
+        //! @param other event to move handlers
+        Event& StealHandlers(Event&& other);
```
Comment (AMZN-koppersr) [inline Code/Framework/AzCore/AzCore/EBus/Event.h:65]: Nitpick: "Steal" sounds so sinister. How about "ClaimHandlers"?

File: Code/Framework/AzCore/AzCore/EBus/Event.inl [hunk 2]
```diff
@@ -207,6 +207,32 @@ namespace AZ
     }
 
 
+    template <typename... Params>
+    auto Event<Params...>::StealHandlers(Event&& other) -> Event&
+    {
+        decltype(other.m_handlers) handlers = AZStd::move(other.m_handlers);
+        decltype(other.m_addList) addList = AZStd::move(other.m_addList);
```
Comment (AMZN-koppersr) [inline Code/Framework/AzCore/AzCore/EBus/Event.inl:214]: Can't `auto` be used here instead of the `decltype`?

File: Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.cpp [hunk 3]
```diff
@@ -217,18 +216,43 @@ namespace AZ
...
+        AZStd::scoped_lock lock(m_notifierMutex);
         m_notifiers.DisconnectAllHandlers();
     }
 
+    void SettingsRegistryImpl::SignalNotifier(AZStd::string_view jsonPath, Type type)
+    {
+        // Move the Notifier AZ::Event to a local AZ::Event in order to allow
+        // the notifier handlers to be signaled outside of the notifier mutex
+        // This allows other threads to register notifiers while this thread
+        // is invoking the handlers
```
Comment (AMZN-koppersr) [inline Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.cpp:236]: Note: seems like the idea of a thread safe AZ::Event needs to be revisited again. Would be better imho to have this logic captured in a thread safe AZ::Event instead of partly here and partly in the normal AZ::Event (the StealHandlers call).

**Review by AMZN-koppersr — APPROVED** [review]

File: Code/Framework/AzCore/AzCore/EBus/Event.h (hunk 1 above)
Comment (lumberyard-employee-dm) [reply Code/Framework/AzCore/AzCore/EBus/Event.h:65]: Yes, I will change the name to sound less malicious

File: Code/Framework/AzCore/AzCore/EBus/Event.inl (hunk 2 above)
Comment (lumberyard-employee-dm) [reply Code/Framework/AzCore/AzCore/EBus/Event.inl:214]: Yes it can be used here.

File: Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.cpp (hunk 3 above)
Comment (lumberyard-employee-dm) [reply Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.cpp:236]: Not only should thread safety be a talking point, but the ability to asynchronously launch the handlers in parallel should also be one as well.

In the SignalHandlers function in the Settings Registry, the registered notifies could safely run in parallel.
