### PR TITLE
Fixes ComponentApplication shutdown in Launcher

### LINKED ISSUE #11004: Launcher: AutomatedTesting.GameLauncher is crashing at quit
**Describe the bug**
AutomatedTesting.GameLauncher is crashing at quit.

**Steps to reproduce**
1. Launch AutomatedTesting.GameLauncher through Visual Studio.
2. Open the Console (~) and type quit.

**Expected behavior**
Launcher quits cleanly.

**Actual behavior**
Launcher throws an exception on close:

```
 	AutomatedTesting.GameLauncher.exe![thunk]:AzFramework::ApplicationLifecycleEvents::`vcall'{80,{flat}}' }'()	C++
>	[Inline Frame] AutomatedTesting.GameLauncher.exe!AZStd::Internal::INVOKE(void(AZ::ComponentDescriptor::*)() &) Line 177	C++
 	[Inline Frame] AutomatedTesting.GameLauncher.exe!AZStd::invoke(void(AZ::ComponentDescriptor::*)() &) Line 54	C++
 	[Inline Frame] AutomatedTesting.GameLauncher.exe!AZ::EBusEventProcessingPolicy::Call(void(AZ::ComponentDescriptor::*)() &) Line 437	C++
 	AutomatedTesting.GameLauncher.exe!AZ::Internal::EBusContainer<AZ::ComponentDescriptor,AZ::ComponentDescriptorBusTraits,1,0>::Dispatcher<AZ::EBus<AZ::ComponentDescriptor,AZ::ComponentDescriptorBusTraits>>::Broadcast<void (__cdecl AZ::ComponentDescriptor::*)(void)>(void(AZ::ComponentDescriptor::*)() && func) Line 968	C++
 	AutomatedTesting.GameLauncher.exe!AZ::ComponentApplication::Destroy() Line 776	C++
 	AutomatedTesting.GameLauncher.exe!AzFramework::Application::Stop() Line 257	C++
 	AutomatedTesting.GameLauncher.exe!O3DELauncher::Run(const O3DELauncher::PlatformMainInfo & mainInfo) Line 615	C++
 	AutomatedTesting.GameLauncher.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 35	C++
 	[External Code]	

```

[Game.log](https://github.com/o3de/o3de/files/9235715/Game.log)

**Found in Branch**
development@ 7e98b5064643f31efb82979795833130bccca158

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

### PR DESCRIPTION
**Pull request by amzn-phist**
- AutoGen ScriptCanvas components weren't being properly unregistered
  from the Component Application.
- Cache component descriptors so when a node registry is unregistered it
  can unregister the descriptors too.

## What does this PR do?

fixes #11004 

## How was this PR tested?

Ran AutomatedTesting.GameLauncher, open Console, type "quit".  Ensured clean shutdown.

### CODE REVIEW

File: Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasAutoGenRegistry.h [hunk 1]
```diff
@@ -40,9 +40,13 @@ namespace ScriptCanvas
     class ScriptCanvasRegistry
     {
     public:
+        virtual ~ScriptCanvasRegistry() = default;
         virtual void Init(NodeRegistry* nodeRegistry) = 0;
         virtual void Reflect(AZ::ReflectContext* context) = 0;
         virtual AZStd::vector<AZ::ComponentDescriptor*> GetComponentDescriptors() = 0;
+
+    protected:
+        AZStd::vector<AZ::ComponentDescriptor*> m_cachedDescriptors;
```
Comment (lumberyard-employee-dm) [inline Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasAutoGenRegistry.h:49]: Be careful, the AZ::SystemAllocator might not be available depend on where this AutoGen registry resides at.

Due to static destruction order, the AZ::Environment might have been detached at that point.

A way to avoid any of these issues, can be to cached the descriptors in an `AZStd::fixed_vector<AZ::ComponentDescriptors, 64>` instead.

File: Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasAutoGenRegistry.cpp [hunk 2]
```diff
@@ -171,6 +172,16 @@ namespace ScriptCanvas
...
     void AutoGenRegistryManager::UnregisterRegistry(const char* registryName)
     {
-        m_registries.erase(registryName);
+        auto it = m_registries.find(registryName);
+        if (it != m_registries.end())
+        {
+            auto componentDescriptors = it->second->GetComponentDescriptors();
+            for (auto descriptor : componentDescriptors)
+            {
+                descriptor->ReleaseDescriptor();
```
Comment (onecent1101) [inline Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasAutoGenRegistry.cpp:181]: for safety concern you could do a nullptr check before calling ReleaseDescriptor

File: Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasGrammarRegistry_Source.jinja [hunk 3]
```diff
@@ -87,7 +87,9 @@ namespace ScriptCanvas
 
     AZStd::vector<AZ::ComponentDescriptor*> {{autogenTargetName}}GrammarRegistry::GetComponentDescriptors()
     {
-        return AZStd::vector<AZ::ComponentDescriptor*>({
+        if (m_cachedDescriptors.empty())
+        {
+            AZStd::vector<AZ::ComponentDescriptor*> descriptors({
```
Comment (onecent1101) [inline Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasGrammarRegistry_Source.jinja:92]: instead of creating a temporary variable, you should be able to do something like
```
m_cachedDescriptors = {
...
};
```

**Review by onecent1101 — APPROVED** [review]
In general, looks good to me

File: Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasAutoGenRegistry.h (hunk 1 above)
Comment (amzn-phist) [reply Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasAutoGenRegistry.h:48]: This is stuff that @onecent1101 added recently.  The lifetime of these ScriptCanvasRegistry objects is tied to that of modules related to Script Canvas and Script Canvas itself.  AZ::Environment and AZ::SystemAllocator should be available throughout.

**Review by lumberyard-employee-dm — APPROVED** [review]

File: Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasAutoGenRegistry.cpp (hunk 2 above)
Comment (amzn-phist) [reply Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasAutoGenRegistry.cpp:180]: Probably not necessary.  Nothing should be setting a descriptor in the `m_cachedDescriptors` to nullptr, and if it's an address pointing to bad memory, we'd want to crash.

File: Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasGrammarRegistry_Source.jinja (hunk 3 above)
Comment (amzn-phist) [reply Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasGrammarRegistry_Source.jinja:92]: I changed it to move from the temporary into the cached member, but I'll try this out.

Comment (amzn-phist) [reply Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasGrammarRegistry_Source.jinja]: Done

**Review by lumberyard-employee-dm — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]
