### PR TITLE
Fix the crash when switching between sim obj and physix layout in animation editor.

### LINKED ISSUE #4165: The Editor crashes after removing the actor instance and changing the EMotionFX layout
**Describe the bug**
A crash occurs if the actor instance is deleted with unsaved changes, and the layout is switched from Physics to SimulatedObjects. The changes made to the actor must be discarded. If the crash does not occur, then switching the layout back to Physics, undoing the actor deletion, and repeating the process will crash the Editor.

**To Reproduce**
1. Open the Animation Editor.
2. Switch to the Physics layout.
3. Load the Cowboy actor.
4. Press the RMB on any joint and select "Add to Ragdoll".
5. Navigate to the Actor Manager pane and delete the actor instance from it.
6. Discard the changes.
7. Switch the layout to the SimulatedObjects.

(additional steps if the crash does not occur after step 7)

8. Switch the layout back to Physics. (the crash may occur in this step)
9. Undo the deletion of the actor.
10. Delete the actor.
11. Switch the layout to the SimulatedObjects.

**Expected behavior**
The layout can be switched without issues.

**Call Stack Trace:**
```
25) 00007FF863A5C347 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FF8660151B0 (ntdll) : memset
23) 00007FF865FFC766 (ntdll) : _C_specific_handler
22) 00007FF8660120CF (ntdll) : _chkstk
21) 00007FF865FC1454 (ntdll) : RtlRaiseException
20) 00007FF866010BFE (ntdll) : KiUserExceptionDispatcher
19) 00007FF82EC76583 (Qt5Core) : QSortFilterProxyModel::parent
18) 00007FF82EC75582 (Qt5Core) : QSortFilterProxyModel::mapToSource
17) 00007FF82EC7347F (Qt5Core) : QSortFilterProxyModel::data
16) 00007FF82EC4E04A (Qt5Core) : QModelIndex::data
15) C:\O3DE\o3de\Gems\EMotionFX\Code\Source\Editor\SkeletonModelJointWidget.cpp (104) : EMotionFX::SkeletonModelJointWidget::Reinit
14) 00007FF836E480A4 (Qt5Widgets) : QWidget::event
13) 00007FF836E249B0 (Qt5Widgets) : QApplicationPrivate::notify_helper
12) 00007FF836E23A33 (Qt5Widgets) : QApplication::notify
11) 00007FF82EC91B4A (Qt5Core) : QCoreApplication::notifyInternal2
10) 00007FF836E5A1A0 (Qt5Widgets) : QWidgetPrivate::show_helper
 9) 00007FF836E58548 (Qt5Widgets) : QWidgetPrivate::setVisible
 8) 00007FF836E582EE (Qt5Widgets) : QWidget::setVisible
 7) 00007FF836E59E6A (Qt5Widgets) : QWidgetPrivate::showChildren
 6) 00007FF836E5A034 (Qt5Widgets) : QWidgetPrivate::show_helper
 5) 00007FF836E58548 (Qt5Widgets) : QWidgetPrivate::setVisible
 4) 00007FF836E582EE (Qt5Widgets) : QWidget::setVisible
 3) 00007FF836E59E6A (Qt5Widgets) : QWidgetPrivate::showChildren
 2) 00007FF836E5A034 (Qt5Widgets) : QWidgetPrivate::show_helper
 1) 00007FF836E59E60 (Qt5Widgets) : QWidgetPrivate::showChildren
```

**Screenshots**

https://user-images.githubusercontent.com/86952009/133590635-1b20bc0d-4f44-4db5-85da-7b74d2183263.mp4

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version 10
- CPU Intel I5-9600k
- GPU RTX 2060
- Memory 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/7176712/Editor.log)
[error.log](https://github.com/o3de/o3de/files/7176714/error.log)
[dump.zip](https://github.com/o3de/o3de/files/7176715/dump.zip)

### PR DESCRIPTION
**Pull request by amzn-rhhong**
Resolves #4165

### CODE REVIEW

**Comment by amzn-rhhong** [comment]
The problem is that m_selectedModelIndices became stall when switching actors (also when deleting it).
The selection model should store the correct selection indices already, so we should just queue that every time we call reinit.

**Review by amzn-jillich — APPROVED** [review]

**Review by AMZN-Gene — APPROVED** [review]

File: Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeWidget.cpp [hunk 1]
```diff
@@ -116,7 +116,8 @@ namespace EMotionFX
 
     void RagdollNodeWidget::InternalReinit()
     {
-        if (m_selectedModelIndices.size() == 1)
+        const QModelIndexList& selectedModelIndices = GetSelectedModelIndices();
```
Comment (amzn-jillich) [inline Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeWidget.cpp:119]: This is not safe. GetSelectedModelIndices() is returning a copy now. The returned copy might get destructed after this line and the reference might be invalid. Can you remove the ref here?

**Review by amzn-jillich — CHANGES_REQUESTED** [review]

**Review by amzn-jillich — APPROVED** [review]

File: Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeWidget.cpp (hunk 1 above)
Comment (amzn-jillich) [reply Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeWidget.cpp:119]: Ah ok, good to know. I wasn't sure that all compilers are safe using that. Just shipped, still would prefer to just hold a copy in this case as the copy will be hold by the compiler internally anyway to make it safe while it seems kind of hidden when looking at the code that it is returning a copy.
