### PR TITLE
[development] updated editor event handling with respect to imgui

### LINKED ISSUE #4366: ImGUI CPU Profiler window has focus issues
**Describe the bug**
The **ImGUI CPU Profiler** seems to lose focus on certain actions, these are:
* Holding Right-Mouse Button and moving the mouse to move the **Visualizer** graph.
* Scroll the Mouse Wheel to scroll through the **Visualizer** graph.
* Typing into the **Statistics Filter** Text Field is not possible, even though it's selected.

It should be noted that e.g. holding Left-Mouse Button on the slider and moving it by hand works to scroll the **Visualizer**/**Statistics**. Scrolling Mouse Wheel in the **Statistics moves** the list, and all buttons seem to be responding fine. If the input has an equivalent in the Viewport and the user performs any action listed above, it will be executed as well (e.g. if the Mouse Wheel is scrolled, the Viewport Camera will zoom in and out).

**To Reproduce**
1. In the Viewport, press the Home key to bring up the ImGUI.
2. In the **ImGUI** go to **Atom Tools** > **Cpu Profiler**.
3. Press **Swap to visualizer** button and then the Pause button.
4. Attempt to move the graph by holding the Right-Mouse Button and moving the mouse.
5. Attempt to scroll through the graph using the Mouse Wheel.
6. Press **Swap to statistics** button.
7. Select the **Filter** text field and attempt to type something in.

**Expected behavior**
The **ImGUI CPU Profiler** window is focused correctly.

**Video**

https://user-images.githubusercontent.com/86952082/135066939-077b3966-e6a3-4ad0-920e-83bf8c5e8313.mp4

Desktop
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

### PR DESCRIPTION
**Pull request by AMZN-ScottR**
Fixes #4366

- Added support for sending text events from the Qt event mapper
- Fixed several issues found while running the Profiler gem in debug
- Added ability to track AZ-consumed events in the Qt event mapper
- Minor clean up to input handling in ImGuiManager
- Select ImGui mouse events can now be properly consumed during AZ-input processing in the editor viewport
- Added tests for the Qt event mapper

Signed-off-by: AMZN-ScottR <24445312+AMZN-ScottR@users.noreply.github.com>

### CODE REVIEW

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp [hunk 1]
```diff
@@ -208,10 +214,15 @@ namespace AzToolsFramework
...
+        {
+            AzFramework::InputChannelNotificationBus::Handler::BusConnect();
+        }
+        else
         {
             // Clear input channels to reset our input state if we're disabled.
             ClearInputChannels(nullptr);
+            AzFramework::InputChannelNotificationBus::Handler::BusDisconnect();
         }
     }
```
Comment (bosnichd) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:227]: Do we want to do all this if m_enabled == enabled? From the looks of it all this will be redundant (albeit benign) if so.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp [hunk 2]
```diff
@@ -408,32 +439,76 @@ namespace AzToolsFramework
 
     void QtEventToAzInputMapper::HandleKeyEvent(QKeyEvent* keyEvent)
     {
-        // Ignore key repeat events, they're unrelated to actual physical button presses.
+        const Qt::Key key = static_cast<Qt::Key>(keyEvent->key());
+        const QEvent::Type eventType = keyEvent->type();
+
+        // special handling for text events in edit mode
+        {
+            static Qt::Key lastKey = key;
```
Comment (bosnichd) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:447]: Would this be better as a member variable instead of a static? I doubt there will ever be multiple instances of QtEventToAzInputMapper in existence, but you never know.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp [hunk 3]
```diff
@@ -408,32 +439,76 @@ namespace AzToolsFramework
...
+            static bool consumeAsText = false;
```
Comment (bosnichd) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:448]: Does this need to be static?

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp [hunk 4]
```diff
@@ -408,32 +439,76 @@ namespace AzToolsFramework
...
-                        keyChannel->UpdateState(true);
-                    }
-                    else
-                    {
-                        keyChannel->UpdateState(false);
-                    }
-
+                    const bool isKeyPressed = (eventType == QEvent::Type::KeyPress) || (eventType == QEvent::Type::ShortcutOverride);
+                    keyChannel->UpdateState(isKeyPressed);
                     NotifyUpdateChannelIfNotIdle(keyChannel, keyEvent);
```
Comment (bosnichd) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:512]: Do we need/want to do the same this here as for mouse events and check if the event was consumed?

File: Gems/ImGui/Code/Source/ImGuiManager.cpp [hunk 5]
```diff
@@ -401,60 +401,65 @@ bool ImGuiManager::OnInputChannelEventFiltered(const InputChannel& inputChannel)
...
-        }
-        else if (inputChannelId == InputDeviceKeyboard::Key::ModifierAltL
-                 || inputChannelId == InputDeviceKeyboard::Key::ModifierAltR)
-        {
-            io.KeyAlt = inputChannel.IsActive();
-        }
-        else if (inputChannelId == InputDeviceKeyboard::Key::ModifierCtrlL
-                 || inputChannelId == InputDeviceKeyboard::Key::ModifierCtrlR)
+        // Handle Keyboard Modifier Keys
+        else
```
Comment (bosnichd) [inline Gems/ImGui/Code/Source/ImGuiManager.cpp:434]: I might just not be reading the scopes here correctly, but it looks like the behavior has changed here in that we're no longer handling modifier keys or setting io.KeysDown if (inputChannel.IsStateBegan()) - removing the else would retain the same behavior as before?

**Review by bosnichd — APPROVED** [review]
Nice, thanks!

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp [hunk 6]
```diff
@@ -317,6 +328,20 @@ namespace AzToolsFramework
         return false;
     }
 
+    AZ::s32 QtEventToAzInputMapper::GetPriority() const
+    {
+        return AzFramework::InputChannelEventListener::GetPriorityLast();
+    }
+
+    void QtEventToAzInputMapper::OnInputChannelEvent(const AzFramework::InputChannel& inputChannel,
+                                                     bool& o_hasBeenConsumed)
```
Comment (hultonha) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:337]: update: `o_` I do not believe is something in the coding standards (nor is `out`). This would be better as just `hasBeenConsumed`, the type information alone is enough to let us know this can be modified by the caller. Also here we use `o_` but this is an in/out parameter as we read it here and never write to it, so the 'hungarian-style' notation is not accurate. It would be good at the API to call out this is an inout parameter and leave the name as just `hasBeenConsumed`.

nit: Please can you run clang-format on this file, it does not use this alignment style and so will cause unnecessary changes on the next edits to this file (we have already run it on these files. You can do this from Visual Studio by running `Ctrl-K, D`. Thanks!

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp [hunk 7]
```diff
@@ -357,16 +382,22 @@ namespace AzToolsFramework
 
             if (buttonChannel)
             {
-                if (mouseEvent->type() != QEvent::Type::MouseButtonRelease)
+                // reset the consumed event cache
+                m_lastConsumedInputChannelEvent = nullptr;
+
+                const bool buttonActive = (mouseEvent->type() != QEvent::Type::MouseButtonRelease);
```
Comment (hultonha) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:388]: nit: Redundant parens, prefer `const bool buttonActive = mouseEvent->type() != QEvent::Type::MouseButtonRelease;`

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp (hunk 2 above)
Comment (hultonha) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:447]: +1 - we generally want to avoid function level statics unless used for something like a singleton for initialization. This will break horribly if were ever decide to have another instance of `QtEventToAzInputMapper` which could potentially happen in future

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp (hunk 3 above)
Comment (hultonha) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:448]: +1

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp [hunk 8]
```diff
@@ -408,32 +439,76 @@ namespace AzToolsFramework
...
+            QString keyText = keyEvent->text();
+            if (key == Qt::Key_Backspace)
+            {
+                keyText = "\b";
+            }
+
+            if (!keyText.isEmpty())
+            {
+                // key events are first sent as shortcuts, if accepted they are then resent as traditional key
+                // down events.  dispatching the key event as text on shortcut (and auto-repeat press) ensures
```
Comment (hultonha) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:459]: question: is `text on shortcut` correct? I'm not sure I understand that part

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp [hunk 9]
```diff
@@ -408,32 +439,76 @@ namespace AzToolsFramework
...
+                    );
+                    consumeAsText = textConsumed;
+                }
+                // follow up events from accepting the previous key event also need to be accepted without
+                // dispatching the text event, otherwise the key event will be processed twice: once for the
+                // previous text event, then again as a normal key event which can lead to odd behaviour
+                // during text edit
+                else
+                {
+                    consumeAsText &= (lastKey == key);
```
Comment (hultonha) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:478]: update: Please don't use bitwise operations for boolean tests such as this, this should be

`consumeAsText = consumeAsText && lastKey == key;`

There are some subtle bugs that can creep in when mixing boolean and bitwise operations.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp [hunk 10]
```diff
@@ -408,32 +439,76 @@ namespace AzToolsFramework
...
+            }
+
+            lastKey = key;
+
+            if (consumeAsText)
+            {
+                keyEvent->accept();
+                return;
+            }
+        }
```
Comment (hultonha) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:493]: There is a lot of code added here and it would likely be best moved to its own function rather than making this one much longer. 

If this is then written as a free function taking inputs as parameters, it is pretty easy to then write a test to ensure you get the write behavior coming out of the function. I would highly recommend doing this as the input code is pretty hairy and there have been subtle bugs introduced before. Writing tests for these changes I think is well worth the investment.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp [hunk 11]
```diff
@@ -408,32 +439,76 @@ namespace AzToolsFramework
...
-                    if (keyEvent->type() == QEvent::Type::KeyPress || keyEvent->type() == QEvent::Type::ShortcutOverride)
-                    {
-                        keyChannel->UpdateState(true);
-                    }
-                    else
-                    {
-                        keyChannel->UpdateState(false);
-                    }
-
+                    const bool isKeyPressed = (eventType == QEvent::Type::KeyPress) || (eventType == QEvent::Type::ShortcutOverride);
```
Comment (hultonha) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:510]: nit: redundant parens (this is sort of style thing so you can ignore but they weren't there before this change - sometimes they are of course needed, but otherwise they just add additional visual noise and clutter and don't add anything).

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.h [hunk 12]
```diff
@@ -69,6 +71,12 @@ namespace AzToolsFramework
         //! \param event The underlying Qt event that triggered this change, if applicable.
         void InputChannelUpdated(const AzFramework::InputChannel* channel, QEvent* event);
 
+    protected:
+        //! \ref AzFramework::InputChannelNotifications::GetPriority
+        AZ::s32 GetPriority() const override;
+        //! \ref AzFramework::InputChannelNotifications::OnInputChannelEvent
+        void OnInputChannelEvent(const AzFramework::InputChannel& inputChannel, bool& o_hasBeenConsumed) override;
```
Comment (hultonha) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.h:78]: update: Here I believe the preferred style is to just name the bus these overrides come from like so...

```
//  AzFramework::InputChannelNotificationBus overrides ...
AZ::s32 GetPriority() const override;
void OnInputChannelEvent(const AzFramework::InputChannel& inputChannel, bool& o_hasBeenConsumed) override;
```

We want the name to match the bus type that is inherited from, these makes searching for the definitions much easier in the file

**Review by hultonha — COMMENTED** [review]
Overall looking good, there's a few things I have questions about and a few changes that would be great.

I also would strongly be in favour of spending some additional time writing some tests to cover the changes to `AzQtEventInputMapper` - please feel free to reach out to me about this as I've already setup a number of tests cases that use this in a test harness. It's not too hard and should help us catch any issues that may crop up in future. Also by refactoring some of the changes to free functions we can test them in isolation too which tends to make things even simpler.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp (hunk 1 above)
Comment (AMZN-ScottR) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:227]: Shouldn't hurt to add that guard in.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp (hunk 2 above)
Comment (AMZN-ScottR) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:447]: Sounds good, will promote to member variable.

File: Gems/ImGui/Code/Source/ImGuiManager.cpp (hunk 5 above)
Comment (AMZN-ScottR) [reply Gems/ImGui/Code/Source/ImGuiManager.cpp:434]: You would be correct the behaviour changed by mistake, will remove the else here.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp (hunk 4 above)
Comment (AMZN-ScottR) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:512]: We certainly can but speaking specifically from an ImGui perspective, it's not necessary.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp (hunk 6 above)
Comment (AMZN-ScottR) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:337]: For clarify, the naming style came from the input API directly but will update here accordingly.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp (hunk 3 above)
Comment (AMZN-ScottR) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:448]: As it turns out, the logic here is being overly greedy with consuming key events in their translation to text events.  Neither of these statics are necessary and will be removed.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp (hunk 9 above)
Comment (AMZN-ScottR) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:478]: Fair point but as mentioned in another comment thread, this logic was extraneous and removed.

File: Gems/ImGui/Code/Source/ImGuiManager.cpp [hunk 13]
```diff
@@ -496,32 +499,30 @@ bool ImGuiManager::OnInputChannelEventFiltered(const InputChannel& inputChannel)
...
-    if (InputDeviceMouse::IsMouseDevice(inputDeviceId))
+    else if (InputDeviceMouse::IsMouseDevice(inputDeviceId))
     {
         const int mouseButtonIndex = GetAzMouseButtonIndex(inputChannelId);
         if (0 <= mouseButtonIndex && mouseButtonIndex < AZ_ARRAY_SIZE(io.MouseDown))
         {
             io.MouseDown[mouseButtonIndex] = inputChannel.IsActive();
+
+            // only consume the event during edit mode in the editor so the viewport doesn't also respond to it
+            consumeEvent = gEnv->IsEditing() && io.WantCaptureMouse;
```
Comment (bosnichd) [inline Gems/ImGui/Code/Source/ImGuiManager.cpp:513]: Why only in edit mode? Could be wrong but I think this would be fine to consume in all cases where io.WantCaptureMouse == true

**Review by bosnichd — APPROVED** [review]

File: Gems/ImGui/Code/Source/ImGuiManager.cpp (hunk 13 above)
Comment (AMZN-ScottR) [reply Gems/ImGui/Code/Source/ImGuiManager.cpp:513]: Doing so would break the "ImGui & Game" input model.  This does too but edit mode is special in that some events manipulate the mouse state so it needs to otherwise ImGui won't function properly.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp [hunk 14]
```diff
@@ -317,6 +319,19 @@ namespace AzToolsFramework
...
+        return AzFramework::InputChannelEventListener::GetPriorityLast();
+    }
+
+    void QtEventToAzInputMapper::OnInputChannelEvent(const AzFramework::InputChannel& inputChannel, bool& hasBeenConsumed)
+    {
+        if (m_enabled && hasBeenConsumed)
+        {
+            m_lastConsumedInputChannelEvent = &inputChannel;
+        }
+    }
```
Comment (lumberyard-employee-dm) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:333]: It seems dangerous to store a pointer to a `const&` reference parameter.

What if a temporary AzFramework::InputChannel is created when invoke the this event?

Comment (bosnichd) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:333]: This is a virtual function, we can't change the signature. It should be fine because all InputChannels are created at input device creation which happens at startup, although it isn't outside the realm of possibility that InputChannels could have a different lifecycle under some circumstances, so your concern (while unlikely to transpire) is valid. Storing a temporary InputChannel isn't really feasible because they can only be constructed using a reference to their parent InputDevice, but we could easily store the corresponding AzFramework::InputChannelId and achieve the same goal.

Comment (AMZN-ScottR) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:333]: I don't believe that's possible on the temporary, @bosnichd would be able to confirm.  As for changing the argument type would be a large sweeping API change.

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp (hunk 6 above)
Comment (hultonha) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp]: Okay perfect thanks, apologies I wasn't aware of that (potentially something we can update in the API in future)

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp (hunk 8 above)
Comment (hultonha) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:452]: Ah okay, potentially we could update it to read...

```
dispatching the key event as text during a shortcut
```

or

```
dispatching the key event as text on the shortcut event
```

Also we should update `resent` to `re-sent` (resent is to feel bitterness or indignation 😛)

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp (hunk 9 above)
Comment (hultonha) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp]: Okay good to know thanks 👍

File: Code/Framework/AzToolsFramework/Tests/Input/QtEventToAzInputMapperTests.cpp [hunk 15]
```diff
@@ -0,0 +1,535 @@
...
+            m_inputChannelMapper.reset();
+
+            m_rootWidget.reset();
+
+            AllocatorsTestFixture::TearDown();
+        }
+
+        void OnInputChannelEvent(const AzFramework::InputChannel& inputChannel, bool& hasBeenConsumed) override
+        {
+            ASSERT_FALSE(hasBeenConsumed);
```
Comment (hultonha) [inline Code/Framework/AzToolsFramework/Tests/Input/QtEventToAzInputMapperTests.cpp:117]: comment: I've never a fan of having test assertions in other functions, it's usually better to have the assert in a test body so if it fails it's clear the reason why. Not a huge deal and you can leave this as-is but something to keep in mind. Another option is just to make this an `AZ_Assert` if it really should never happen and it's not a test assertion/expectation.

File: Code/Framework/AzToolsFramework/Tests/Input/QtEventToAzInputMapperTests.cpp [hunk 16]
```diff
@@ -0,0 +1,535 @@
...
+                }
+            }
+            else if (AzFramework::InputDeviceKeyboard::IsKeyboardDevice(inputDeviceId))
+            {
+                m_azChannelEvents.push_back(AzEventInfo(inputChannel));
+                hasBeenConsumed = m_captureAzEvents;
+            }
+        }
+
+        void OnInputTextEvent(const AZStd::string& textUTF8, bool& hasBeenConsumed) override
```
Comment (hultonha) [inline Code/Framework/AzToolsFramework/Tests/Input/QtEventToAzInputMapperTests.cpp:142]: uber nit: Coding standards advice to use `CamelCase` even for acronyms, so this would be `textUtf8`

File: Code/Framework/AzToolsFramework/Tests/Input/QtEventToAzInputMapperTests.cpp [hunk 17]
```diff
@@ -0,0 +1,535 @@
...
+        {
+            ASSERT_FALSE(hasBeenConsumed);
+
+            m_azTextEvents.push_back(textUTF8);
+            hasBeenConsumed = m_captureTextEvents;
+        }
+
+        struct QtEventInfo
```
Comment (hultonha) [inline Code/Framework/AzToolsFramework/Tests/Input/QtEventToAzInputMapperTests.cpp:150]: suggestion: Comment here detailing usage could be helpful (and again could be moved out to a util class in future).

File: Code/Framework/AzToolsFramework/Tests/Input/QtEventToAzInputMapperTests.cpp [hunk 18]
```diff
@@ -0,0 +1,535 @@
...
+        EXPECT_EQ(m_signalEvents[2].m_scrollPhase, Qt::ScrollEnd);
+
+        // az validation
+        ASSERT_EQ(m_azChannelEvents.size(), 3);
+
+        EXPECT_STREQ(m_azChannelEvents[0].m_inputChannelId.GetName(), mouseWheelChannelName);
+
+        EXPECT_STREQ(m_azChannelEvents[1].m_inputChannelId.GetName(), mouseWheelChannelName);
+
+        EXPECT_STREQ(m_azChannelEvents[2].m_inputChannelId.GetName(), mouseWheelChannelName);
```
Comment (hultonha) [inline Code/Framework/AzToolsFramework/Tests/Input/QtEventToAzInputMapperTests.cpp:255]: uber nit: Line breaks seem excessive here but it's not a big deal at all (repeated in a few spots)

File: Code/Framework/AzToolsFramework/Tests/Input/QtEventToAzInputMapperTests.cpp [hunk 19]
```diff
@@ -0,0 +1,535 @@
...
+        AzFramework::InputChannelId m_az;
+    };
+
+    class MouseButtonParamQtEventToAzInputMapperFixture
+        : public QtEventToAzInputMapperFixture
+        , public ::testing::WithParamInterface<MouseButtonIdsParam>
+    {
+    };
+
+    TEST_P(MouseButtonParamQtEventToAzInputMapperFixture, MouseClick_NoAzHandlers_ReceivedTwoSignalAndZeroAzChannelEvents)
```
Comment (hultonha) [inline Code/Framework/AzToolsFramework/Tests/Input/QtEventToAzInputMapperTests.cpp:302]: suggestion: It might be worth adding some brief comments/descriptions to the tests for added context. The test names are helpful but it's not always clear why what they're testing is important. Some additional context for the reader could be really helpful (especially when one of these inevitably fails in future 😛)

**Review by hultonha — APPROVED** [review]
Change looks great and fantastic work on the extensive test coverage, really awesome to see 😄 

I have a few minor comments/suggestions but nothing major that's blocking. It might be worth giving @NicholasVanSickle a poke to give this a quick once over too but otherwise it's looking brilliant!

File: Code/Framework/AzToolsFramework/Tests/Input/QtEventToAzInputMapperTests.cpp (hunk 16 above)
Comment (AMZN-ScottR) [reply Code/Framework/AzToolsFramework/Tests/Input/QtEventToAzInputMapperTests.cpp:142]: Another case of the original API using this casing but will change.

**Review by hultonha — APPROVED** [review]
Thanks very much for making the updates, looks great! 👍

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp [hunk 20]
```diff
@@ -366,7 +408,16 @@ namespace AzToolsFramework
                     buttonChannel->UpdateState(false);
                 }
 
-                NotifyUpdateChannelIfNotIdle(buttonChannel, mouseEvent);
+                if (m_lastConsumedInputChannelIdCrc32 == buttonChannel->GetInputChannelId().GetNameCrc32())
```
Comment (NicholasVanSickle) [inline Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:411]: This  (and the other location)could use a comment - the logic makes sense to me now, but it's non-obvious that `m_lastConsumedInputChannelIdCrc32` will be updated here.

**Review by NicholasVanSickle — APPROVED** [review]
Looks good to me, one nit. Thanks for adding tests!

File: Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp (hunk 20 above)
Comment (AMZN-ScottR) [reply Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp:411]: That's fair, will update the comments a few lines above where the resetting happens to mention how it gets updated.

File: Gems/Profiler/Code/Source/ImGuiCpuProfiler.cpp [hunk 21]
```diff
@@ -643,7 +646,9 @@ namespace Profiler
                 }
             }
         }
-        ImGui::EndChild();
+        ImGui::EndChild(); // "Timeline"
+
+        ImGui::EndChild(); // "Options and Statistics"
```
[the remark this answers is not in the document]
Comment (lumberyard-employee-dm) [reply Gems/Profiler/Code/Source/ImGuiCpuProfiler.cpp:651]: A Scoped RAII wrapper around the `ImGui::BeginChild` and `ImGui::EndChild` seems useful.

**Review by lumberyard-employee-dm — APPROVED** [review]
