### PR TITLE
Fixed group and bookmark display on graph load

### LINKED ISSUE #6524: Groups, Notes and Bookmarks are not loaded in Script Canvas
**Describe the bug**
Saving a Script Canvas with bookmarks, nodes and grouped nodes does not work correctly.
 After loading the Script Canvas file there are no bookmarks and notes in it and Nodes are not grouped. Different changes made to the file are saved. This issue occurs also for Script Canvas file that had grouped nodes. When they are loaded Only nodes and connections are displayed in viewport.
 Please refer to the attached video for more information.
 
**Steps to reproduce**
1. Open the Script Canvas tool.
2. Load any Script Canvas file or create a new one.
3. Add a bookmark, a note and create a group of nodes.
4. Save the Script Canvas file.
5. Close and reopen the Script Canvas tool.
6. Load the same Script Canvas file.

**Expected behavior**
Script Canvas file is loaded in the same state as it was saved.

**Actual behavior**
Script Canvas file is loaded without groups, notes and bookmarks.

**Video**

https://user-images.githubusercontent.com/86953282/146926740-aa159c1a-6b6f-4be8-be74-5b14a0ded5b5.mp4

**Found in Branch**
 Development (366a711)
 
 **Desktop/Device:**
 • Device: PC
 • OS: Windows
 • Version: 10 Pro
 • CPU: Intel i7 8700k
 • GPU: Nvidia RTX 2080
 • Memory: 16GB

### LINKED ISSUE #7336: Script Canvas: Node Group Disappears
**Describe the bug**
Node groups disappear after saving the graph, closing graph, and re-opening the graph

**Steps to reproduce**
1. Add a grouping to your graph
image

2. Save
3. Close graph canvas
4. Reopen graph
5. See that group is gone
image

**Expected behavior**
Node groups remain.

**Actual behavior**
Node groups disappear

**Found in Branch**
Feb 1 2021 development

### LINKED ISSUE #7454: Script Canvas: Groups are gone after saving and re-opening the graph
**Describe the bug**
After adding a group containing a few nodes, saving the graph, closing the graph and re-opening it, the group is gone.

**Steps to reproduce**
1. Open Script Canvas Editor
2. Add a new nodes
3. Select more than two nodes
4. Right click to activate the context menu, select Group -> Type
5. Add some text/name to the group and press enter
6. File -> Save the graph to a file
7. Close SC editor
8. Open SC editor and load the saved/close graph.

**Expected behavior**
The group should be back after loading the graph.

**Actual behavior**
Group is not visible/there anymore.

**Found in Branch**
development

### PR DESCRIPTION
**Pull request by lsemp3d**
Closes #7454 
Closes #7336 
Closes #6524

Signed-off-by: lsemp3d <58790905+lsemp3d@users.noreply.github.com>

### CODE REVIEW

**Review by carlitosan — APPROVED** [review]

File: Gems/GraphCanvas/Code/Source/Components/SceneComponent.cpp [hunk 1]
```diff
@@ -1286,6 +1286,10 @@ namespace GraphCanvas
     {
         GRAPH_CANVAS_PROFILE_FUNCTION();
         const SceneComponentSaveData* saveData = saveDataContainer.FindSaveDataAs<SceneComponentSaveData>();
```
Comment (onecent1101) [inline Gems/GraphCanvas/Code/Source/Components/SceneComponent.cpp:1288]: nit: don't see this get used later, so it is just for a quick check? so move it inside if condition scope?

**Review by onecent1101 — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]
