### PR TITLE
Camera locking when its transform is locked

### LINKED ISSUE #5477: Camera locking does not work
**Describe the bug**
If I want to position a camera and ensure that it stays locked to its position, there is no way to ensure a lock. There is a context menu item you can get by right clicking over Translate or rotate in the Transform component (on an entity that contains an added Camera)- selecting "Lock Transform Values" grays out the transform values so that they are not editable by numerical input into the fields, but this doesn't stop you from tumbling in the viewport and changing those values unimpeded.

**Steps to reproduce**
1. Create a new entity
2. Add a camera component to the entity and click on the "Be this Camera" button
3. Move it to a new position
4. Right click in the Transform Component on the Translate or Rotate Values and select "Lock Transform Values"
5. Now try to move in the viewport- you will see the position change in the supposed locked values

**Expected behavior**
Once locked, you should not be able to move in the viewport unless you switch cameras into one that is NOT locked

**Actual behavior**
The locking functionality locks the input field, but not the camera.

**Assets required**
You can test this on a completely empty scene and verify just by watching recorded translational/rotational values

**Found in Branch**
Latest Development

**Desktop/Device (please complete the following information):**
 - PC
 - Windows
 - 10
 - Intel(R) Core(TM) i9-9820X CPU @ 3.30GHz   3.30 GHz
 - NVidia GeForce RTX 2080
 - 64.0 GB

**Additional context**

### PR DESCRIPTION
**Pull request by AMZN-Igarri**
This fixes #5477
There is some notes to this fix:
1 - When you lock the camera transform in "Be this camera" mode you can still move around but the camera transform won't be updated, once you unlock the camera transform and move while still being that camera will update its position to the current view.
2 - If you have moved while being this camera and with the transform locked, if you switch to another camera and return to the locked one will return to that camera locked transform.

Suggestions:
It would be worth thinking about having a button in the camera component that would let you recenter the current view to the camera's transform, so when you move when the transform locked you can return to the view. I've heard this from @HogJonny-AMZN and this could be expanded to a "look through entity" button that can be very useful when positioning lights in a level for example.

https://user-images.githubusercontent.com/82394219/143864719-1c2a73d0-35f6-4066-a8da-5c28e91f4f1d.mp4

### CODE REVIEW

File: Gems/Camera/Code/Source/CameraComponentController.cpp [hunk 1]
```diff
@@ -154,6 +154,11 @@ namespace Camera
         m_shouldActivateFn = shouldActivateFunction;
     }
 
+    void CameraComponentController::SetIsLockedFunction(AZStd::function<bool()> isLockedFunction)
+    {
+        m_isLockedFn = isLockedFunction;
```
Comment (hultonha) [inline Gems/Camera/Code/Source/CameraComponentController.cpp:159]: nit: As we're passing the std::function by value and storing it we can add `AZStd::move` here to prevent an additional copy.

**Review by hultonha — APPROVED** [review]
LGTM 👍 Definitely worth a follow-up but this does improve the behavior that's there now and makes destructive operations to Entity transform values harder which is absolutely a good think 🙂

**Review by tjmichaels — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]
