### PR TITLE
Fixed slow Script Canvas loading by moving error icon construction in NodePaletteTreeItem.

### LINKED ISSUE #3738: Script Canvas start-up time
### Problem description

When first opening Script Canvas it can take nearly 60 seconds (!) to open. This is incredibly painful if you ever do need to close it or restart the Editor. I have no idea why it take this long (this isn't even loading a graph, it's just opening it with no script loaded).

Update: This did seem to suddenly improve on Friday (no idea what changed but start-up times did seem a lot faster, will report back if things slow down again).

Update #2: This came back again randomly and it went back to taking approx 1 min to open

Reported by @hultonha through LY game jam

### PR DESCRIPTION
**Pull request by cgalvan**
Fixes #3738 

Identified slow-down in Script Canvas tool being loaded due to the construction of a `QIcon` for the error icon of every node palette tree item (which is then x3 because the node palette is created for the actual node palette widget, the scene context menu, and connection context menu). This error icon isn't actually needed unless there is an error on the tree item, so moved the construction to the case when it actually needs to be displayed. This reduced the load time from ~1500ms to ~300ms, an improvement of ~80%.

Also added some `AZ_PROFILE_FUNCTION` calls that helped narrow down the source of the delay.

Signed-off-by: Chris Galvan <chgalvan@amazon.com>

### CODE REVIEW

**Review by hultonha — APPROVED** [review]
LGTM 👍 🥳

**Review by AMZN-daimini — APPROVED** [review]

**Review by gadams3 — APPROVED** [review]

**Review by lsemp3d — APPROVED** [review]

File: Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/NodePalette/TreeItems/NodePaletteTreeItem.cpp [hunk 1]
```diff
@@ -88,7 +91,7 @@ namespace GraphCanvas
             case Qt::DecorationRole:
                 if (HasError())
                 {
-                    return m_errorIcon;
+                    return QIcon(":/GraphCanvasEditorResources/toast_error_icon.png");
```
Comment (NicholasVanSickle) [inline Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/NodePalette/TreeItems/NodePaletteTreeItem.cpp:94]: Awesome fix! Consider caching this somewhere global to avoid calling QIcon's weirdly slow constructor at all if you ever see this show up in a profile again.

**Review by NicholasVanSickle — APPROVED** [review]

**Review by carlitosan — APPROVED** [review]
Beautiful.

File: Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/NodePalette/TreeItems/NodePaletteTreeItem.cpp (hunk 1 above)
Comment (cgalvan) [reply Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/NodePalette/TreeItems/NodePaletteTreeItem.cpp:94]: Good call! And yeah I want to dig further to see why the constructor is so slow too
