### PR TITLE
Fixes ctrl-g crash with an installer when the server launcher is not found. Clarified error message.

### LINKED ISSUE #8230: Editor CTRL+G multiplayer experience crashes when using O3DE installer because it looks in the wrong location for the server launcher
**Describe the bug**
If a project is using O3DE installer to develop a multiplayer project, then Editor ctrl+g crashes when `editorsv_enabled=true` is enabled.

```
[Error] (MultiplayerEditor) - LaunchEditorServer failed! The ServerLauncher binary is missing! (C:\git\o3de\install\bin\Windows\profile\Default\MyProject.ServerLauncher.exe)  Please build server launcher.
```

**Steps to reproduce**
1. clone development branch of o3de
2. build INSTALL target
3. register the installer from \git\o3de\install
4. register a project against \git\o3de\install
5. launch Editor
6. set `editorsv_enabled=true`
7. ctrl+g

**Expected behavior**
Server process starts and the Editor connects to it as a client.

**Actual behavior**
Editor crashes in
>	Multiplayer.Editor.dll!Multiplayer::MultiplayerEditorSystemComponent::LaunchEditorServer() Line 251	C++
because outProcess is null

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU Ryzen 5900x
 - GPU NVidia RTX 3090
 - Memory 64GB

### PR DESCRIPTION
**Pull request by AMZN-Olex**
Fixes #8230

Test with a local install build.

When the server launcher isn't found, a more useful error is printed, for example:
 
[Error] (MultiplayerEditor) - The ServerLauncher binary is missing! (), (C:\git\o3de\install\bin\Windows\profile\Default\MyProject.ServerLauncher.exe) and (C:\git\myproject\build\bin\profile\MyProject.ServerLauncher.exe) were tried. Please build server launcher or specify using editorsv_process.

Signed-off-by: Olex Lozitskiy <5432499+AMZN-Olex@users.noreply.github.com>

### CODE REVIEW

**Review by lumberyard-employee-dm — APPROVED** [review]

File: Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp [hunk 1]
```diff
@@ -237,17 +237,20 @@ namespace Multiplayer
 
         AZ_Error(
             "MultiplayerEditor", processLaunchInfo.m_launchResult != AzFramework::ProcessLauncher::ProcessLaunchResult::PLR_MissingFile,
-            "LaunchEditorServer failed! The ServerLauncher binary is missing! (%s)  Please build server launcher.", serverPath.c_str())
+            "LaunchEditorServer failed! The ServerLauncher binary is missing! (%s)  Please build server launcher or specify using editorsv_process.", serverPath.c_str());
```
Comment (lumberyard-employee-dm) [inline Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp:240]: Before attempting to Launch the Server Process, a file exist check should be performed above to make sure the path exist.

That can also be used to search for other candidate paths where the ServerLauncher can exist

```
if (!AZ::IO::SystemFile::Exists(serverPath.c_str()))
{
    serverPath = AZ::IO::FixedMaxPath{ AZ::Utils::GetExecutableDirectory() } / "bin" / AZ_TRAIT_OS_PLATFORM_NAME / AZ_BUILD_CONFIGURATION_TYPE;
    serverPath /= serverProcess + AZ_TRAIT_OS_EXECUTABLE_EXTENSION;
}

if (!AZ::IO::SystemFile::Exists(serverPath.c_str()))
{
    // Now try with the "Default" permutation
    constexpr const char* BuildPermutation = "Default";

    serverPath = AZ::IO::FixedMaxPath{ AZ::Utils::GetExecutableDirectory() } / "bin" / AZ_TRAIT_OS_PLATFORM_NAME / AZ_BUILD_CONFIGURATION_TYPE / BuildPermutation;
    serverPath /= serverProcess + AZ_TRAIT_OS_EXECUTABLE_EXTENSION;
}

if (!AZ::IO::SystemFile::Exists(serverPath.c_str()))
{
    AZ_Error("MultiplayerEditor", false, "Cannot locate the ServerLauncher binary at path %s", serverPath.c_str());
    return;
}
```

Comment (AMZN-Olex) [reply Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp]: Thanks! Updated using your suggestion.

**Review by lumberyard-employee-dm — APPROVED** [review]

File: Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp [hunk 2]
```diff
@@ -194,23 +195,63 @@ namespace Multiplayer
...
+    bool MultiplayerEditorSystemComponent::FindServerLauncher(AZ::IO::FixedMaxPath& serverPath)
     {
-        // Assemble the server's path
-        AZ::CVarFixedString serverProcess = editorsv_process;
-        AZ::IO::FixedMaxPath serverPath;
-        if (serverProcess.empty())
+        serverPath.clear();
+
+        // 1. Try the path from `editorsv_process` cvar.
+        const AZ::IO::FixedMaxPath serverPathFromCvar{ AZ::CVarFixedString(editorsv_process).c_str()};
```
Comment (AMZN-Gene) [inline Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp:203]: Nice! I didn't even realize _editorsv_process_ was an option

**Review by AMZN-Gene — APPROVED** [review]

**Review by AMZN-puvvadar — APPROVED** [review]
