### PR TITLE
Fix for a generic handling of invokable attributes

### LINKED ISSUE #15717: DPE Inspector: Camera component has duplicate "Match Viewport" buttons
**Describe the bug**
Camera component has duplicate "Match Viewport" buttons.

**Steps to reproduce**
1. Launch the Editor with the DPE enabled:
```
Editor.exe --ed_enableDPE=true
```
2. Expand the Default Level Environment entity hierarchy.
3. Select the "Camera" entity.
 
**Expected behavior**
Component properties are listed only once.

**Actual behavior**
The "Match Viewport" button is duplicated on the component.

**Screenshots/Video**
image

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
0fa6eea55514ef710fa4a0d40ea31ad43b181de9

### PR DESCRIPTION
**Pull request by cgalvan**
## What does this PR do?

Fixes #15717, #15660

Added handling in `LegacyAttributeToDomValue` to check if the attribute is an invokable function as opposed to a value passed directly. This will fix several cases where attributes such as `Visibility` and `ButtonText` are supplied as a function.

Also added some additional properties to the DPE standalone view to exercise these paths.

DPEInvokableAttributes

## How was this PR tested?

Tested the properties in the DPE standalone, as well as the buttons in the Camera component and Landscape Canvas component.

### CODE REVIEW

**Review by forkercat — APPROVED** [review]

**Review by dtamkin1 — APPROVED** [review]

File: Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.h [hunk 1]
```diff
@@ -200,6 +200,11 @@ namespace AZ::DocumentPropertyEditor
             {
                 return AZ::Reflection::ReadGenericAttributeToDomValue(instance, attribute).value_or(AZ::Dom::Value());
             }
+            // Handle the attribute providing an invokable function instead of the value directly
```
Comment (alexmontAmazon) [inline Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.h:203]: I'm slightly concerned how this would affect attributes that are intended to by invokable always, like changeNotify. In that case, calling LegacyAttributeToDomValue wouldn't give the DomValue for the callable attribute, but instead attempt to call it itself to retrieve a value that was not intended. Have you tried making this the final else case, like putting it below at line 214?
Something like:
if (!reader.Read<AttributeType>(value))
{
   if (attribute->CanDomInvoke(Dom::Value(Dom::Type::Array)))
    {
        return attribute->DomInvoke(instance, Dom::Value(Dom::Type::Array));
    }
   else
   {
    return AZ::Dom::Value();
    }

that way it would attempt to read the regular value first, and if it failed, it would try to invoke the attribute to get the result it was looking for.

Comment (cgalvan) [reply Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.h]: Good call, updated!

**Review by alexmontAmazon — APPROVED** [review]
awesome, thanks!
