### PR TITLE
Fix Vulkan version handling

### LINKED ISSUE #18165: Crash on Android due to mismatching Vulkan device and instance API versions
stabilization/2409 on Android:

According to Vulkan documentation for VkPhysicalDeviceProperties, "The value of apiVersion may be different than the version returned by vkEnumerateInstanceVersion; either higher or lower" ( https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceProperties.html ).
This doesn't seem to be handled right in O3DE, at least in cases where instance apiVersion is lower than physical device apiVersion. For example, on Huawei phones with HarmonyOS 4.x VkPhysicalDeviceProperties returns API 1.2 but vkEnumerateInstanceVersion returns 1.1, as allowed by the Vulkan spec. However O3DE then ends up creating a Vulkan validation error (below), and later a segfault (overriding the instance version passed to CreateInstance() with 1.2 is a workaround that confirms the problem):

vkDebugMessage org.o3de.MyProject I Trace::Error
C:/dev/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/Vulkan.cpp(262): 'VkBool32 AZ::Vulkan::Debug::MessageCallbak(VkDebugUtilsMessageSeverityFlagBitsEXT, VkDebugUtilsMessageTypeFlagsEXT, const VkDebugUtilsMessengerCallbackDataEXT , void )'
vkDebugMessage org.o3de.MyProject I [ERROR][Validation] Validation Error: [ VUID-VkDeviceCreateInfo-pNext-pNext ] Object 0: handle = 0x7d825a7240, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x901f59ec | vkCreateDevice: Includes a pNext pointer (pCreateInfo->pNext) to a VkStructureType (VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES) which was added in VK_API_VERSION_1_2 but the current effective API version is 1.1.0 (0x00401000). The Vulkan spec states: Each pNext member of any structure (including this one) in the pNext chain must be either NULL or a pointer to a valid instance of ...

### PR DESCRIPTION
**Pull request by akioCL**
## What does this PR do?

Vulkan app API version was not being considered when calculating the Vulkan version of the physical device. According to the standard "The Khronos validation layers will treat apiVersion as the highest API version the application targets, and will validate API usage against the minimum of that version and the implementation version (instance or device, depending on context). If an application tries to use functionality from a greater version than this, a validation error will be triggered."

Fixes #18165

## How was this PR tested?

Run Vulkan PC and Android.

### CODE REVIEW

**Review by moudgils — APPROVED** [review]

File: Gems/Atom/RHI/Vulkan/Code/Source/RHI/Instance.cpp [hunk 1]
```diff
@@ -79,48 +79,57 @@ namespace AZ
...
+            // vkEnumerateInstanceVersion is a Vulkan 1.1 function
             // so if it's not available we assume Vulkan 1.0
-            if (GetContext().EnumerateInstanceVersion && GetContext().EnumerateInstanceVersion(&apiVersion) != VK_SUCCESS)
+            if (GetContext().EnumerateInstanceVersion)
             {
-                AZ_Warning("Vulkan", false, "Failed to get instance version.");
-                return false;
+                if (GetContext().EnumerateInstanceVersion(&m_instanceVersion) != VK_SUCCESS)
+                {
+                    AZ_Warning("Vulkan", false, "Failed to get instance version.");
```
Comment (spham-amzn) [inline Gems/Atom/RHI/Vulkan/Code/Source/RHI/Instance.cpp:91]: Should this be an error? There looks like a lot of initialization that is skipped if this fails.
