### PR TITLE
Fix entity selection when parent instance is the root

### LINKED ISSUE #13415: Prefabs: With overrides enabled, selecting an entity in the Viewport selects its root entity
**Describe the bug**
With overrides enabled, selecting an entity in the Viewport selects its root entity.

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
1. Launch the Editor with prefab overrides enabled:
```
Editor.exe --regset=O3DE/Preferences/Prefabs/EnableOverridesUx=true
```
2. Create a new level.
3. Create an entity hierarchy in the level with a parent, child, and grandchild.
4. Move the entities so they're not on top of each other.
5. In the Viewport, select the grandchild entity.

**Expected behavior**
Grandchild entity is selected.

**Actual behavior**
The Parent entity is selected.

**Screenshots/Video**
https://user-images.githubusercontent.com/82226555/204357919-76388673-aa25-46e7-970f-94ffe591c0d9.mp4

**Found in Branch**
development@ 4f2ce1cda6d8fd986c7fcae9c0d6e2eaded453c8

**Additional context**
1. This does not occur if the user drags in the Viewport to select rather than directly clicking the entity.
2. This does not occur if the user selects entities in the Entity Outliner.

### PR DESCRIPTION
**Pull request by michabr**
Signed-off-by: michabr <82236305+michabr@users.noreply.github.com>

## What does this PR do?

This PR fixes some of the entity selection logic for when prefab override UX is enabled. It was not allowing descendant entities to be selected in the viewport for entities whose owning instance is the root (level).

Fixes #13415.

## How was this PR tested?

Manual testing in Editor.

### CODE REVIEW

**Review by dtamkin1 — APPROVED** [review]

**Review by lsemp3d — APPROVED** [review]

**Review by AMZN-daimini — APPROVED** [review]
Looks good, thanks for fixing this!

**Comment by hultonha** [comment]
Any chance we could add a test for this at the same time @michabr? 😁

**Comment by michabr** [comment]
> Any chance we could add a test for this at the same time @michabr? 😁

@hultonha OK I'll look into adding a test now before submitting.

File: Code/Framework/AzToolsFramework/AzToolsFramework/ContainerEntity/ContainerEntitySystemComponent.cpp [hunk 1]
```diff
@@ -128,36 +128,32 @@ namespace AzToolsFramework
...
-            AZ::EntityId lastOpenContainerBeforeSelection = entityId;
+            // Return the highest unselected ancestor container of the entity, or the entity if none is found.
+            AZ::EntityId highestUnselectedAncestorContainer = entityId;
 
             // Skip the queried entity, as we only want to check its ancestors.
             AZ::TransformBus::EventResult(entityId, entityId, &AZ::TransformBus::Events::GetParentId);
 
-            // Assumption - there are no closed containers. This is due to the way PrefabEditScope::NESTED_INSTANCES works,
-            // since we open all descendant containers of the focused prefab.
-            // If this is no longer the case, this code will need a rewrite.
```
Comment (forkercat) [inline Code/Framework/AzToolsFramework/AzToolsFramework/ContainerEntity/ContainerEntitySystemComponent.cpp:140]: question: Since we are removing these comments, would it be good to update the API comment to describe the "no closed container" case? It looks like if the override flag is on, the lines after 160 won't be executed at all.

```cpp
//! Detects if one of the ancestors of entityId is a closed container entity.
//! @return The highest closed entity container id if any, or entityId otherwise.
virtual AZ::EntityId FindHighestSelectableEntity(AZ::EntityId entityId) const = 0;
```

**Review by forkercat — APPROVED** [review]
Thanks for fixing this!

**Comment by hultonha** [comment]
> > Any chance we could add a test for this at the same time @michabr? 😁
> 
> @hultonha OK I'll look into adding a test now before submitting.

Amazing thank you, let me know if you run into any problems trying to set it up and I'll see if I can help. Writing tests can sometimes be more of a pain than fixing the bug but long term they're incredible valuable to help ensure the software is continuing to do what we think it should be doing. Thanks for taking a look!

**Comment by michabr** [comment]
> 

It looks like there's already a test for this but it didn't catch the issue because PrefabOverridesEnabled is false in the tests. I'm going to create a new ticket/PR to change the logic so that it doesn't rely on that flag.

File: Code/Framework/AzToolsFramework/AzToolsFramework/ContainerEntity/ContainerEntitySystemComponent.cpp (hunk 1 above)
Comment (michabr) [reply Code/Framework/AzToolsFramework/AzToolsFramework/ContainerEntity/ContainerEntitySystemComponent.cpp:140]: I'm making a follow up ticket to change the logic so that there's no branching on PrefabsOverridesEnabled flag.

**Comment by hultonha** [comment]
> > 
> 
> It looks like there's already a test for this but it didn't catch the issue because PrefabOverridesEnabled is false in the tests. I'm going to create a new ticket/PR to change the logic so that it doesn't rely on that flag.

Okay cool good to hear, if you can link the ticket here once it's created that'd be great! Thanks for investigating @michabr :+1:
