### PR TITLE
Fixes the bug causing asset browser to be unable to delete/move/etc.

### LINKED ISSUE #15671: [Bug Report] Asset Browser cannot delete asset
**Describe the bug**
I'm unable to delete an asset using the Asset Browser. Specifically, I tried to delete a material and a folder of textures.

**Assets required**
Any assets

**Steps to reproduce**
1. Go to **Asset Browser**
2. Locate an asset and delete it by doing either one of the following:
    - Right-click on an asset to open the context menu and click **Delete asset**
    - Click on an asset and press **Del** key

**Expected behavior**
The asset deletes.

**Actual behavior**
The asset does not delete. As a workaround, I deleted the asset from the file explorer.

**Screenshots/Video**

https://user-images.githubusercontent.com/75444793/231247156-73430cca-7112-4e64-ba47-222d1fc3b9db.mp4

**Found in Branch**
branch: `development`

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
latest commit: `4244bc287a7418c49f4eba569a245b40b9aeda28`

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

### LINKED ISSUE #15712: Only empty folders can be renamed in the Asset Browser
**Describe the bug**
Assets and folders that contain assets cannot be renamed in the Asset Browser. Rename text box can be accessed, but it does not retain changes.

This issue also occurs on Windows.

This issue also occurs on the Development (0fa6eea) branch.

**Assets required**
* An empty folder visible in the Asset Browser.
* A folder containing files visible in the Asset Browser.
* Any asset visible in the Asset Browser.

**Steps to reproduce**
1. Attempt to rename any of the folders or asset mentioned in the **Assets required** section, within the *Asset Browser* (right-click > *Rename asset/Folder*, or select asset/folder and press F2).

**Expected behavior**
Folders/asset is renamed.

**Actual behavior**
Only the empty folder can be renamed.

**Video**

https://user-images.githubusercontent.com/86952082/232005525-6ff796cb-1152-4aea-bc5f-3ad9389bf9b0.mp4

**Found in Branch**
Stabilization/2305 (9b1b23c)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
9b1b23c0593aaaa04891c2d3eb524b5e7ae8539e

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.1 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

### LINKED ISSUE #16328: Bug Report: Asset Browser not working change file names on linux
**Describe the bug**
only works to change the names of the folder and the rest does not work

**Steps to reproduce**
1. Select rename example AnimGraph or LuaScript
2. The result has not changed

**Screenshots/Video**

https://github.com/o3de/o3de/assets/17591539/af771e89-cc2a-486c-aaea-f2f90ecfa422

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
c56e2b987caca1200ed55cdf35c6a6be3391859f (o3de development)

**Desktop/Device (please complete the following information):**
 - Device: Linux
 - OS: Fedora
 - Version 37
  - CPU AMD Ryzen 3 3100
 - GPU AMD RT 5500 XT (8GB)
 - Memory 16GB

### LINKED ISSUE #16998: Unable to name, rename, move or delete assets from the Asset Browser
**Description the bug**
I am unable to name, rename, move or delete assets from the Asset Browser.

**Assets required**
Just create a new Script Canvas.

**Steps to reproduce**
Steps to reproduce the Name behavior:
1. Create a Script Canvas.
2. Type ne name of your choice.
3. Asset is still named "NewScript"

Steps to reproduce the Rename behavior:
1. Create a Script Canvas.
2. Right Click on newly created Script Canvas
3. Select "Rename asset"
4. Type the name of your choice
5. Asset is still named "NewScript"

Steps to reproduce the Delete behavior:
1. Create a Script Canvas.
2. Right Click on newly created Script Canvas
3. Select "Delete asset"

Steps to reproduce the Move behavior:
1. Create a Script Canvas.
2. Right Click on newly created Script Canvas
3. Select "Move to"

**Expected behavior**
The Asset should be named, renamed, move or deleted.

**Actual behavior**
The Asset is not named, renamed moved or deleted.

**Screenshots/Video**
https://youtu.be/M7GWKPXdG5c

**Found in**
Editor version 23.10

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU Ryzen 9 5950X
 - GPU NVidia RTX 3080
 - Memory 64GB

**Additional context**
The error seems to come from Perforce. But I am not using any version control, nor it is mentionned in the System Requirements.

### PR DESCRIPTION
**Pull request by nick-l-o3de**
## What does this PR do?

* Fixes #15671 - [Bug Report] Asset Browser cannot delete asset
* Fixes #16998
* Fixes #16328
* possibly fixes #15712
* possible fix for #13469 but I don't have P4 to test :)
 
* Adds missing functionality from the Linux ProcessWatcher to indicate the difference between a different problem launching program, and the program not being found.
* Fixes the workflow of the Move/Delete/Rename operations in the Asset Browser to properly return the appropriate error when Source Control is not properly configured.
* Adds a toggle for source control notification in AP, so that if you toggle the Editor to not use Source Control, the AP will not either.
* Uses the same setting in AP as the Editor, to determine whether Source Control should be used or not, and sets it to false by default, just like the Editor.

## How was this PR tested?
Manual ad-hoc testing on linux, running all the tests on linux (CI_Build complete run) to success.
Manual ad-hoc testing included moving, rename, delete, copy, with and without the source control plugin active.  It also involved turning the source control on and off LIVE and making sure it immediately starts working.

### CODE REVIEW

**Review by AMZN-daimini — APPROVED** [review]

File: Code/Editor/MainStatusBar.cpp [hunk 1]
```diff
@@ -342,7 +357,19 @@ void SourceControlItem::InitMenu()
 
         connect(m_settingsAction, &QAction::triggered, this, [&]()
         {
-            GetIEditor()->GetSourceControl()->ShowSettings();
+            // LEGACY note - GetIEditor and GetSourceControl are both legacy functions
+            // but are currently the only way to actually show the source control settings.
+            // They come from an editor plugin which should be moved to a gem eventually instead.
```
Comment (lsemp3d) [inline Code/Editor/MainStatusBar.cpp:362]: We should create a GHI to capture this (if there isn't one already)

**Review by lsemp3d — APPROVED** [review]

File: Code/Editor/MainStatusBar.cpp (hunk 1 above)
Comment (nick-l-o3de) [reply Code/Editor/MainStatusBar.cpp:362]: Will do.

Comment (nick-l-o3de) [reply Code/Editor/MainStatusBar.cpp:362]: Its actually really tempting too since there are only 4 remaining plugins and besides the Component Property Editor (which maybe is replaced by DPE?) the others are just a handful of lines of code.  Eliminateing them  would allow us to remove the entire legacy plugin system.

Comment (nick-l-o3de) [reply Code/Editor/MainStatusBar.cpp:362]: https://github.com/o3de/o3de/issues/17571
