### PR TITLE
AnimGraph: Make it possible for a node in a group to be assigned to another group (#13373)

### LINKED ISSUE #13373: AnimGraph nodes cannot be directly moved to another node group when already in a node group.
**Describe the bug**
When multiple node groups are present, right-clicking on a node in an existing node group should give an option to move the node to another node group.

This behavior was requested in #10961 

**Steps to reproduce**
1. Open the Animation Editor
2. Set Animation Editor to **AnimGraph** mode 
3. Select the AnimGraph panel
4. Add a few nodes
5. Create multiple node groups
6. Right-click a node in an existing node group and attempt to move it to another node group.

**Expected behavior**
Right-click context menu provides an option to move the node to another existing node group.

**Actual behavior**
Right-click context menu does not provide the option to move the node to another existing node group.

**Screenshots/Video**
3AE84629-E842-441E-B487-49B278C10867

**Found in Branch**
Development

**Workaround**
You can relocate a node to another node group by removing it from its current node group before assigning it to another node group.

### PR DESCRIPTION
**Pull request by aambrosano**
Signed-off-by: Alessandro Ambrosano <1006222+aambrosano@users.noreply.github.com>

## What does this PR do?

Fixes #13373

Nodes in an animation graph couldn't be assigned to any other node group once they were assigned the first time.

This PR makes it possible to let a node switch the groups to which it belongs.

## How was this PR tested?

Manually switching graph nodes from a group to another through the menu.

https://user-images.githubusercontent.com/1006222/204567271-669dd4ed-07ef-422f-8073-6b0d77c193e7.mp4

Fixes #13373

### CODE REVIEW

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp [hunk 1]
```diff
@@ -65,8 +65,14 @@ namespace EMStudio
...
                 QAction* nodeGroupAction = nodeGroupMenu->addAction(QIcon(new SolidColorIconEngine(nodeGroupColor)), nodeGroup->GetName());
+                nodeGroupAction->setCheckable(true);
                 nodeGroupAction->setData(qulonglong(i + 1)); // index of the menu added, not used
-                connect(nodeGroupAction, &QAction::triggered, this, &BlendGraphWidget::AssignSelectedNodesToGroup);
+                if (currentlyAssignedGroup == nodeGroup) {
+                    nodeGroupAction->setChecked(true);
+                }
+                else {
+                    connect(nodeGroupAction, &QAction::triggered, this, &BlendGraphWidget::AssignSelectedNodesToGroup);
+                }
```
Comment (cgalvan) [inline Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp:75]: Nit: Coding standard `{` on newlines

**Review by cgalvan — APPROVED** [review]

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp (hunk 1 above)
Comment (aambrosano) [reply Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp:75]: of course

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp [hunk 2]
```diff
@@ -65,8 +65,14 @@ namespace EMStudio
                 AZ::Color nodeGroupColor;
                 nodeGroupColor.FromU32(nodeGroup->GetColor());
                 QAction* nodeGroupAction = nodeGroupMenu->addAction(QIcon(new SolidColorIconEngine(nodeGroupColor)), nodeGroup->GetName());
+                nodeGroupAction->setCheckable(true);
                 nodeGroupAction->setData(qulonglong(i + 1)); // index of the menu added, not used
-                connect(nodeGroupAction, &QAction::triggered, this, &BlendGraphWidget::AssignSelectedNodesToGroup);
+                if (currentlyAssignedGroup == nodeGroup) {
+                    nodeGroupAction->setChecked(true);
+                }
+                else {
```
Comment (Be-ing) [inline Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp:73]: The checked action currently doesn't do anything; it's only a visual indicator of what group the node is currently in, which is also apparent from looking at the graph. I think this should either do something useful by removing from the group when clicked, or skip creating the action in this case.

Comment (aambrosano) [reply Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp:73]: Indeed, removing the node from the checked group on click is what I had in mind when adding the checkable action.
Whether that should be implemented at all, or in this patch specifically, is something I would like to discuss first because there's no clear indication of the UX for removing a node from a group.

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp [hunk 3]
```diff
@@ -65,8 +65,14 @@ namespace EMStudio
...
+                    connect(nodeGroupAction, &QAction::triggered, this, &BlendGraphWidget::AssignSelectedNodesToGroup);
```
[the remark this answers is not in the document]
Comment (aambrosano) [reply Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp:74]: `AssignSelectedNodesToGroup` could take care of that, but there's no clear indication of whether a group should be removed when empty or there should be any other explicit mechanism to remove groups.

[the remark this answers is not in the document]
Comment (Be-ing) [reply Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp:74]: There is no explicit mechanism for removing groups. Groups are deleted automatically by the "Remove Node From Group" action when the group becomes empty:

https://github.com/o3de/o3de/blob/a881574f5608e11fdd86b26b50a0a74c3cef58d4/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp#L409

So I think the behavior should match here when removing a node from a group by moving it to another group.

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp (hunk 2 above)
Comment (Be-ing) [reply Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp:73]: @bhanuja-s Do you have an opinion on this?

**Review by amzn-rhhong — APPROVED** [review]

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp (hunk 2 above)
Comment (hultonha) [inline Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp:73]: nit/standards: Brace placement

**Review by hultonha — APPROVED** [review]

**Comment by hultonha** [comment]
The updated video looks great @aambrosano, thanks for adding it 👍

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphWidget.cpp [hunk 4]
```diff
@@ -1243,6 +1243,15 @@ namespace EMStudio
...
         }
+
+        for (int i = 0; i < animGraph->GetNumNodeGroups(); i++)
+        {
+            if (animGraph->GetNodeGroup(i)->GetNumNodes() == 0)
+            {
+                animGraph->RemoveNodeGroup(i);
+                i--;
+            }
+        }
```
Comment (hultonha) [inline Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphWidget.cpp:1254]: suggestion: A slight alternative to this could be...

```
for (int i = 0; i < animGraph->GetNumNodeGroups();)
{
    if (animGraph->GetNodeGroup(i)->GetNumNodes() == 0)
    {
        animGraph->RemoveNodeGroup(i);
    }
    else
    {
        i++;
    }
}
```

Which is maybe a little clear but not a huge deal

Comment (hultonha) [reply Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphWidget.cpp:1254]: (not sure how node groups are stored under the hood but this can also be an n^2 operation if there are a lot of node groups to remove and they're stored in a vector, so an erase/remove idiom can often be waaaay faster in practice - API might make it hard to do here but just wanted to mention it as something to consider)

**Review by hultonha — APPROVED** [review]

**Comment by hultonha** [comment]
Just kicked off a build - https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-13416/2/pipeline

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphWidget.cpp (hunk 4 above)
Comment (aambrosano) [reply Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphWidget.cpp:1254]: It is like you said. Could be worth implementing it in the animgraph itself entirely (something like `AnimGraph::ClearEmptyNodeGroups`). Just didn't want to introduce too much extra API , but I can do that here too if you like.

Comment (Be-ing) [reply Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphWidget.cpp:1254]: It's unlikely that the number of groups to be deleted is large. In the unlikely worst case, it would be equal to the number of nodes being assigned to a new group. More commonly it is probably only 1 group that needs to be deleted.

**Comment by FuzzyCarterAWS** [comment]
@hultonha @aambrosano 

Updated the workflow docs in o3de/sig-simulation#22

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphWidget.cpp (hunk 4 above)
Comment (hultonha) [reply Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphWidget.cpp:1254]: Yeah this is fine as-is, sorry more just musing out loud, thanks for checking

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp (hunk 2 above)
Comment (Be-ing) [reply Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp]: Implemented here: https://github.com/o3de/o3de/pull/13470

**Comment by FuzzyCarterAWS** [comment]
@hultonha @aambrosano 

verified fixed.
