### PR TITLE
Do not activate graphs on CreateJobs(), which results in not loading assets.

### LINKED ISSUE #10972: Script Canvas builder loads other product assets during the CreateJobs phase
**Describe the bug**
It's noticed that the Script Canvas builder tries to load all the assets referenced in the graph during the CreateJobs phase. This could be a problem since there's no guarantee that the referenced assets have been processed when AP create jobs for the script canvas asset

**Assets required**
- https://github.com/o3de/o3de/blob/development/AutomatedTesting/Levels/Navigation/NavigationSample/move_cursor.scriptcanvas
- https://github.com/o3de/o3de/blob/development/AutomatedTesting/Levels/Navigation/NavigationSample/move_cursor.scriptcanvas

**Steps to reproduce**
1. Set a breakpoint at https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Asset/AssetManager.cpp#L968 (inside the GetAssetInternal function) in visual studio
2. Modify https://github.com/o3de/o3de/blob/development/Registry/AssetProcessorPlatformConfig.setreg#L74 to change the maxjobs to 1
4. Launch the Asset Processor and attach a debuger to the AssetBuidler.exe
5. Add the required assets to your current project (They're from the AutomatedTesting project) or remove move_cursor.scriptcanvas from your project folder and add it back again. AP will reprocess move_cursor.scriptcanvas in this case.

**Expected behavior**
The breakpoint is not hit during the CreateJobs phase. Script Canvas builder shouldn't read any other product asset content during createjobs.

**Actual behavior**
The breakpoint is hit during the CreateJobs phase. Check the screenshot below.

**Screenshots/Video**
image (7)

**Found in Branch**
Development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

### PR DESCRIPTION
**Pull request by carlitosan**
Signed-off-by: carlitosan <82187351+carlitosan@users.noreply.github.com>

## What does this PR do?

After deserialization, the source graphs are no longer activated, which stops their script event assets from loading if they are present.

Fixes #10972 

## How was this PR tested?

All SC assets were rebuilt, editor tests were successful.

### CODE REVIEW

**Review by lsemp3d — APPROVED** [review]

**Review by AMZN-daimini — APPROVED** [review]

**Review by lawsonamzn — APPROVED** [review]

File: Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderWorker.h [hunk 1]
```diff
@@ -68,7 +68,7 @@ namespace ScriptCanvasBuilder
         ExecutionStateAsLightUserdata,
         UpdateDependencyHandling,
         AddExplicitDestructCallForMemberVariables,
-
+        DoNotLoadScriptEventsDuringCreateJobs,
```
Comment (junbo75) [inline Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderWorker.h:71]: Nit: Maybe change it to something like "DoNotLoadReferencedAssetsDuringCreateJobs"? I assume that other type resources are loaded as well without this change.

**Review by junbo75 — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]

**Review by onecent1101 — APPROVED** [review]
