### PR TITLE
Show search results in Asset Browser Thumbnail View (#14003)

### LINKED ISSUE #14002: Asset Browser - Thumbnail View: some assets have children with wrong data
Sometimes assets show an arrow on their right, meaning that they have children items in the asset model, but when opening the children frame the data shown is inconsistent, and sometimes the application crashes.

Image

### PR DESCRIPTION
**Pull request by aambrosano**
Refactor a bit the underlying model to derive from QIdentityProxyModel and using roles for special functions such as visibility of single  items when filtering with a search string.

After the refactoring also #14002 is fixed.

Add a context menu when showing search results, to allow navigating to the parent folder of a result item.

Signed-off-by: Alessandro Ambrosano <1006222+aambrosano@users.noreply.github.com>

## What does this PR do?

Implements showing search results on the thumbnail view, and adds a context menu for navigating to the parent folder of a search result.

It also refactors the model behind the thumbnail view to make it more robust and appropriate for the search results use case.

Also fixes a crash sometimes happening when expanding source assets (#14002).

Fixes #14002 #14003.

## How was this PR tested?

Manual testing

https://user-images.githubusercontent.com/1006222/212896105-900c752f-624c-49b8-bba2-8dde76e558d7.mp4

### CODE REVIEW

File: Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp [hunk 1]
```diff
@@ -448,6 +449,14 @@ namespace AzQtComponents
         return rect.translated(-horizontalOffset(), -verticalOffset());
     }
 
+    void AssetFolderThumbnailView::setRootIndex(const QModelIndex& index) {
+        if (index != rootIndex()) {
```
Comment (cgalvan) [inline Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp:453]: Nit: `{` on newlines

File: Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp [hunk 2]
```diff
@@ -521,20 +530,25 @@ namespace AzQtComponents
...
-        }
+        // const auto translatedRect = rect.translated(horizontalOffset(), verticalOffset());
+
+        // for (auto it = m_itemGeometry.constBegin(); it != m_itemGeometry.constEnd(); ++it)
+        // {
+        //     if (it.value().intersects(translatedRect))
+        //     {
+        //         selectionModel()->select(it.key(), flags);
+        //     }
+        // }
```
Comment (cgalvan) [inline Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp:551]: Would prefer to delete this code instead of commenting it out, we can always look back to previous versions in the git history.

File: Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp [hunk 3]
```diff
@@ -770,7 +814,26 @@ namespace AzQtComponents
...
+
+        const QSize itemSize{ m_config.rootThumbnail.width, m_config.rootThumbnail.height + 4 + fontMetrics().height() };
+        const int rowHeight = itemSize.height() + m_config.topItemsVerticalSpacing;
+
+        if (m_showSearchResultsMode || !rootIndex().isValid()) {
+            updateGeometriesInternal(model()->index(0, 0, {}), x, y);
+        }
+        else {
+            updateGeometriesInternal(rootIndex(), x, y);
+        }
```
Comment (cgalvan) [inline Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp:828]: Nit: `{` on newlines

**Review by cgalvan — APPROVED** [review]

**Review by gadams3 — APPROVED** [review]

**Review by jjjoness — APPROVED** [review]
Agree with all the above nits.

**Review by dtamkin1 — APPROVED** [review]

File: Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp (hunk 1 above)
Comment (aambrosano) [reply Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp]: Done

File: Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp (hunk 2 above)
Comment (aambrosano) [reply Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp]: Done

File: Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp (hunk 3 above)
Comment (aambrosano) [reply Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp]: Done

**Comment by cgalvan** [comment]
@aambrosano Latest build has the following error:

```
[2023-01-17T17:54:22.098Z] /data/workspace/o3de/Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserFolderWidget.cpp:32:35: error: allocating an object of abstract class type 'AzQtComponents::AssetFolderThumbnailView'
[2023-01-17T17:54:22.098Z]             , m_thumbnailView(new AzQtComponents::AssetFolderThumbnailView(this))
[2023-01-17T17:54:22.098Z]                                   ^
[2023-01-17T17:54:22.098Z] /data/workspace/3rdParty/packages/qt-5.15.2-rev8-linux/qt/include/QtWidgets/qabstractitemview.h:293:18: note: unimplemented pure virtual method 'setSelection' in 'AssetFolderThumbnailView'
[2023-01-17T17:54:22.098Z]     virtual void setSelection(const QRect &rect, QItemSelectionModel::SelectionFlags command) = 0;
[2023-01-17T17:54:22.098Z]                  ^
[2023-01-17T17:54:22.098Z] 1 error generated.
```
