### PR TITLE
Fix blue outline when thumbnail selection changes

### LINKED ISSUE #14400: Asset Browser: Blue selection highlight on assets in Thumbnail View frequently remains partially visible on deselected assets
**Describe the bug**
Blue selection highlight on assets in Thumbnail View frequently remains partially visible on deselected assets.

**Steps to reproduce**
1. Launch the Editor and enable WIP Asset Browser features via the Console:
```
ed_useWIPAssetBrowserDesign true
```
2. Open the Asset Browser, and switch to Thumbnail View if necessary.
3. Switch to a directory with several assets.
4. Click around several different assets in the directory, noting the selection highlighting.

**Expected behavior**
Blue highlight clearly denotes the selected asset.

**Actual behavior**
Portions of the blue highlight frequently remain on deselected assets.

**Screenshots/Video**
https://user-images.githubusercontent.com/82226555/216683807-68702be5-054b-4c19-8a70-043ca2d3943b.mp4

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
c8d69fb61c196601651391f4e22d1408971052d8

### PR DESCRIPTION
**Pull request by dtamkin1**
## What does this PR do?

Updates the view when a new item is selected, also clears the current selection and updates the view if the index clicked is invalid.
Fixes #14400.

## How was this PR tested?

Locally, blue highlight updates properly and all other selection features work

### CODE REVIEW

**Review by AMZN-daimini — APPROVED** [review]

**Review by lsemp3d — APPROVED** [review]

File: Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp [hunk 1]
```diff
@@ -742,13 +742,14 @@ namespace AzQtComponents
...
         // No need to do computations on m_itemGeometry entries since we handled the expand/collapse button with the case above
+        auto idx = indexAtPos(p);
         {
-            auto idx = indexAtPos(p);
 
             if (idx.isValid())
             {
                 selectionModel()->select(idx, QItemSelectionModel::SelectionFlag::ClearAndSelect);
                 emit clicked(idx);
+                update();
```
Comment (cgalvan) [inline Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp:752]: We shouldn't need this `update()` here. When the selection changes, the previous selection and new selection should get repainted automatically:

```
void QAbstractItemView::selectionChanged(const QItemSelection &selected, const QItemSelection &deselected)
{
    Q_D(QAbstractItemView);
    if (isVisible() && updatesEnabled()) {
        d->viewport->update(visualRegionForSelection(deselected) \| visualRegionForSelection(selected));
    }
}
```

Might be worth doing a quick check to see why that logic isn't getting triggered. This is OK as-is, but it's a little inefficient because it's going to repaint the whole (visible) thumbnail view instead of just repainting what was changed.

File: Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp [hunk 2]
```diff
@@ -773,6 +774,17 @@ namespace AzQtComponents
...
+
+        {
+            if (!idx.isValid())
+            {
+                selectionModel()->clear();
+                update();
+                return;
+            }
+        }
+
```
Comment (cgalvan) [inline Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp:787]: Can omit the outer scoped braces here.

**Review by cgalvan — APPROVED** [review]

File: Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp (hunk 2 above)
Comment (dtamkin1) [reply Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp]: Fixed!
