### PR TITLE
Fix folder creation in WIP Asset Browser

### LINKED ISSUE #14136: Create new folder doesn't work in the new Asset Browser
**Describe the bug**

Asset Browser's create new folder doesn't display the newly created folder in the new WIP asset browser while project and source asset filter is enabled.

**Steps to reproduce**
1. Open the console variables
2. Enable the WIP Asset Browser
3. Try to create a new folder in tree view or thumbnail view

**Expected behavior**
New folder is created and displayed

**Actual behavior**
No new folder is displayed

### PR DESCRIPTION
**Pull request by dtamkin1**
Signed-off-by: Daniel Tamkin <jotamkin@amazon.com>

## What does this PR do?

Resolves #14136.
The filter in place was only allowing source assets to be displayed,
fixes folder creation by changing the filter to an inverse product filter, allowing empty folders to be displayed.

## How was this PR tested?

Locally, tested that folders can now be created

### CODE REVIEW

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/SearchWidget.cpp [hunk 1]
```diff
@@ -169,10 +169,12 @@ namespace AzToolsFramework
...
-            auto sourceFilter = new EntryTypeFilter();
-            sourceFilter->SetName("Source");
-            sourceFilter->SetEntryType(AssetBrowserEntry::AssetEntryType::Source);
-            m_projectSourceFilter->AddFilter(FilterConstType(sourceFilter));
+            auto productFilter = new EntryTypeFilter();
+            productFilter->SetName("Product");
+            productFilter->SetEntryType(AssetBrowserEntry::AssetEntryType::Product);
+            auto inverseProductFilter = new InverseFilter();
+            inverseProductFilter->SetFilter(FilterConstType(productFilter));
+            m_projectSourceFilter->AddFilter(FilterConstType(inverseProductFilter));
```
Comment (cgalvan) [inline Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/SearchWidget.cpp:177]: This works. A more explicit alternative would be a composite of `Source` and `Folder` types, in case we add any additional entry types in the future (e.g. currently there is also a `Root` type, which I think you probably want to display but I'm not certain).

```
EntryTypeFilter* foldersFilter = new EntryTypeFilter();
                foldersFilter->SetEntryType(AssetBrowserEntry::AssetEntryType::Folder);
```

**Review by cgalvan — APPROVED** [review]

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/SearchWidget.cpp (hunk 1 above)
Comment (gadams3) [reply Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/SearchWidget.cpp:177]: Yes, that is the way it's generally done.

**Review by gadams3 — APPROVED** [review]

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/SearchWidget.cpp (hunk 1 above)
Comment (dtamkin1) [reply Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/SearchWidget.cpp:177]: Thanks, I will update it
