### PR TITLE
fix for crash from delayed refresh on deleted adapters

### LINKED ISSUE #17070: DPE Inspector crash if I duplicate multiple entities at once in Entity Outliner
**Describe the bug**

DPE Inspector would crash if I duplicate more than one entity at once in Entity Outliner.

```
Flags:
- ed_enableOutlinerOverrideManagement=ON
- ed_enableDPE=ON
- ed_enableInspectorOverrideManagement=ON
```

It still crashes if I turn off `ed_enableInspectorOverrideManagement`.

**Steps to reproduce**
1. Create 3 entities
1. Select one of them and duplicate (no crash)
2. Select more than one of them and duplicate (crash)

**Expected behavior**

No crash

**Actual behavior**

Read-access-violation Crash

**Screenshots/Video**

https://github.com/o3de/o3de/assets/11157226/a669c76b-85cb-4173-afbe-fc53abcd47ff

Note that it is not consistent. It doesn't crash when I duplicate two entities (BUT the crash can happen).

**Found in Branch**

https://github.com/o3de/o3de/tree/point-release/23101

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**

https://github.com/o3de/o3de/commit/cfa481a2359ca1645963a942a524a0182037613c

**Desktop/Device**
* Device: PC
* OS: Windows 11
* CPU: AMD Ryzen 5950x
* GPU: NVIDIA RTX 3070
* Memory: 64 GB

**Additional Context**

<details>
  <summary><i>CLICK ME TO SEE THE CALL STACK</i></summary>

```
>	ComponentEntityEditorPlugin.dll!AZ::DocumentPropertyEditor::DocumentAdapter::NotifyResetDocument(AZ::DocumentPropertyEditor::DocumentAdapter::DocumentResetType resetType) Line 111	C++
[Inline Frame] Qt5Core.dll!QtPrivate::QSlotObjectBase::call(QObject *) Line 398	C++
Qt5Core.dll!QMetaCallEvent::placeMetaCall(QObject * object) Line 622	C++
Qt5Core.dll!QObject::event(QEvent * e) Line 1314	C++
Qt5Widgets.dll!QApplicationPrivate::notify_helper(QObject * receiver, QEvent * e) Line 3632	C++
Qt5Widgets.dll!QApplication::notify(QObject * receiver, QEvent * e) Line 3584	C++
Qt5Core.dll!QCoreApplication::notifyInternal2(QObject * receiver, QEvent * event) Line 1063	C++
[Inline Frame] Qt5Core.dll!QCoreApplication::sendEvent(QObject *) Line 1458	C++
Qt5Core.dll!QCoreApplicationPrivate::sendPostedEvents(QObject * receiver, int event_type, QThreadData * data) Line 1817	C++
[External Code]	
Qt5Core.dll!QEventDispatcherWin32::processEvents(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 530	C++
[External Code]	
[Inline Frame] Qt5Core.dll!QEventLoop::processEvents(QFlags<enum QEventLoop::ProcessEventsFlag>) Line 139	C++
Qt5Core.dll!QEventLoop::exec(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 232	C++
Qt5Core.dll!QCoreApplication::exec() Line 1371	C++
EditorLib.dll!CryEditMain(int argc, char * * argv) Line 3837	C++
[Inline Frame] Editor.exe!AZStd::Internal::INVOKE(int(*)(int, char * *) &) Line 208	C++
[Inline Frame] Editor.exe!AZStd::invoke(int(*)(int, char * *) &) Line 54	C++
Editor.exe!main(int argc, char * * argv) Line 31	C++
Editor.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 97	C++
[External Code]	
```
</details>

### PR DESCRIPTION
**Pull request by alexmontAmazon**
## What does this PR do?
- fix for delayed refresh working on deleted adapters
- Fixes #17070

## How was this PR tested?
locally, in the Editor project

### CODE REVIEW

**Review by forkercat — APPROVED** [review]

File: Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.cpp [hunk 1]
```diff
@@ -39,11 +39,16 @@ namespace AZ::DocumentPropertyEditor
         if (m_componentId == componentId)
         {
             m_queuedRefreshLevel = AzToolsFramework::PropertyModificationRefreshLevel::Refresh_Values;
+            QPointer<QObject> stillAlive(&m_stillAlive);
```
Comment (lumberyard-employee-dm) [inline Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.cpp:42]: So abuse of [QPointer guarded pointer](https://doc.qt.io/qt-6/qpointer.html#details) is being used to detect if the instance of this ComponentAdapter has has been deleted.
I guess that works

**Review by lumberyard-employee-dm — APPROVED** [review]
