### PR TITLE
EMotion FX: Selecting Motion Properties crashes the Editor

### LINKED ISSUE #3002: Selecting Motion Properties crashes the Editor
**Describe the bug**
Selecting Motion Properties in Animation Editor tool Motions window crashes the Editor. 
Please refer to the attached video for more details.

**To Reproduce**
1.	Launch the Editor.
2.	Open tools menu.
3.	Select Animation Editor and open Motions window in it.
4.	 Select Motion Properties with LMB and wait a few seconds.

**Expected behavior**
The Editor does not crash.

**Video**
 
https://user-images.githubusercontent.com/86953282/128860958-0dd1fe9c-8af7-406d-8c30-2a4550a4e0d4.mp4

**Desktop/Device (please complete the following information):**
•	Device: PC
•	OS: Windows
•	Version 10
•	CPU Intel i7 8700k
•	GPU Nvidia RTX 2080
•	Memory 16 GB

**Attachments**
[error.log](https://github.com/o3de/o3de/files/6961363/error.log)
[Editor.log](https://github.com/o3de/o3de/files/6961364/Editor.log)

### PR DESCRIPTION
**Pull request by amzn-jillich**
Fixes #3002

Signed-off-by: Benjamin Jillich <jillich@amazon.com>

### CODE REVIEW

File: Gems/EMotionFX/Code/MysticQt/Source/DialogStack.cpp [hunk 1]
```diff
@@ -498,7 +498,7 @@ namespace MysticQt
         }
         if (findPreviousMaximizedDialogNeeded)
         {
-            for (auto curDialog = AZStd::make_reverse_iterator(dialog) + 1; curDialog != m_dialogs.rend(); ++curDialog)
+            for (auto curDialog = AZStd::make_reverse_iterator(dialog); curDialog != m_dialogs.rend(); ++curDialog)
```
Comment (burelc-amzn) [inline Gems/EMotionFX/Code/MysticQt/Source/DialogStack.cpp:501]: Hm, this is a bug introduced by the MCore::Array -> AZStd::vector conversion. The old code did this:
```cpp
const uint32 dialogIndex = FindDialog(button);
// ... snip ...
for (int32 i = dialogIndex - 1; i >= 0; --i)
```

`dialogIndex` is now an iterator instead of an index:
```cpp
const auto dialog = AZStd::find_if(begin(mDialogs), end(mDialogs), [button](const Dialog& dialog)
{
    return dialog.mButton == button;
});
```

To do the reverse iteration, I used `make_reverse_iterator`, and *to skip the current element, I used `+ 1`*. The `+ 1` is incorrect, since:
> For a reverse iterator `r` constructed from an iterator `i`, the relationship `&*r == &*(i-1)` is always true

So the `- 1` offset in the original code is built in to the reverse view.

**Review by burelc-amzn — APPROVED** [review]
There's two hard things in computer science:
1. Cache invalidation
2. Naming things
3. Off-by-one errors

**Review by lsemp3d — APPROVED** [review]

**Review by amzn-rhhong — APPROVED** [review]
