### PR TITLE
Removed the Python SerializeContextTools smoke test

### LINKED ISSUE #11794: AR Bug Report: Intermittent test failure, SmokeTest
**Describe the bug**
Test failure on an AR run with unrelated changes.
`AutomatedTesting::SmokeTest.smoke::TEST_RUN` failed on the test case `test_CLITool_SerializeContextTools_Works.py::TestCLIToolSerializeContextToolsWorks::test_CLITool_SerializeContextTools_Works `
**Failed Jenkins Job Information:**
[Failed pipeline] https://jenkins.build.o3de.org/job/O3DE/job/PR-11793/1/)
Windows/test_cpu_profile failed.

**Attachments**
[log.txt](https://github.com/o3de/o3de/files/9506778/log.txt)

**Additional context**
This error has been reported before [here](https://github.com/o3de/o3de/issues/10711)

### PR DESCRIPTION
**Pull request by lumberyard-employee-dm**
Registered a C++ SerializeContextTools test that validates the `--help` argument.

Fixed the logic in ly_add_target to associate the `AZ_TEST_EXECUTABLE` define with an executable target that depends on AzTest.

fixes #11794 

Signed-off-by: lumberyard-employee-dm <56135373+lumberyard-employee-dm@users.noreply.github.com>

## How was this PR tested?

Invoked ctest with the regular expression filter of AZ::SerializeContextTools and validated that the test executable completed successfully
```powershell
PS C:\code\o3de> ctest --test-dir .\build\windows -C profile -R AZ::SerializeContextTools.Tests
```

### CODE REVIEW

File: Code/Tools/SerializeContextTools/Runner.cpp [hunk 1]
```diff
@@ -0,0 +1,203 @@
+/*
```
Comment (lumberyard-employee-dm) [inline Code/Tools/SerializeContextTools/Runner.cpp:1]: The entirety of the contents of this file was moved from main.cpp.
There are no code changes within this file.

**Review by hultonha — APPROVED** [review]
Thanks for fixing this! 🥳

**Review by spham-amzn — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]
