### PR TITLE
Fix issues with audio localization bank switching

### LINKED ISSUE #2912: Localized soundbanks are not discovered properly
**Describe the bug**
Localized soundbanks are not discovered properly for display in Audio Controls Editor.  This can lead to downstream problems.

**To Reproduce**
1. Make sure you have localized banks (i.e. /Sounds/wwise/English(US)/my_bank.bnk)
2. Open Audio Controls Editor

**Expected behavior**
The my_bank.bnk should be highlighted blue to denote a localized bank.
Mapping the bank should properly serialize the library to set the localized attribute to true.

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10 21H1
 - CPU Ryzen 3970X
 - GPU NVidia RTX 3070
 - Memory 64 GB

**Additional context**

### PR DESCRIPTION
**Pull request by amzn-phist**
- Fixes an issue with g_languageAudio cvar not being updated when user hasn't specified it.
- Fixes the discovery of localized audio banks for audio controls editor.
- Simplifies the g_languageAudio cvar handling in the Wwise gem.

Fixes #2912

### CODE REVIEW

File: Code/Legacy/CrySystem/SystemInit.cpp [hunk 1]
```diff
@@ -896,16 +896,14 @@ void CSystem::InitLocalization()
     if (auto console = AZ::Interface<AZ::IConsole>::Get(); console != nullptr)
     {
         AZ::CVarFixedString languageAudio;
-        if (auto result = console->GetCvarValue("g_languageAudio", languageAudio); result == AZ::GetValueResult::Success)
+        console->GetCvarValue("g_languageAudio", languageAudio);
+        if (languageAudio.size() == 0)
```
Comment (lawsonamzn) [inline Code/Legacy/CrySystem/SystemInit.cpp:900]: nit - if (string.empty()) is preferred when checking for is empty...

File: Code/Legacy/CrySystem/SystemInit.cpp [hunk 2]
```diff
@@ -896,16 +896,14 @@ void CSystem::InitLocalization()
...
-            if (languageAudio.size() == 0)
-            {
-                console->PerformCommand(AZStd::string::format("g_languageAudio %s", language.c_str()).c_str());
-            }
-            else
-            {
-                language.assign(languageAudio.data(), languageAudio.size());
-            }
+            console->PerformCommand(AZStd::string::format("g_languageAudio %s", language.c_str()).c_str());
+        }
```
Comment (lawsonamzn) [inline Code/Legacy/CrySystem/SystemInit.cpp:903]: I take it the assumption here is that it will cause a trigger to occur that will change the language audio, so it doesn't have to also call  language.assign?

**Review by lawsonamzn — APPROVED** [review]

File: Code/Legacy/CrySystem/SystemInit.cpp (hunk 2 above)
Comment (amzn-phist) [reply Code/Legacy/CrySystem/SystemInit.cpp:903]: This `PerformCommand` just sets the audio language cvar to whatever the general language is.  This is occurring before audio gems start getting initialized so later there's an explicit call to update the audio language.

The `language` here is just a local string that was set to the value of `g_language` cvar - the general language setting.  If it sees a value in `g_languageAudio` it writes that value to the `language` variable, then passes it to `OpenLanguageAudioPak`.  So either you're passing the value of `g_language` or `g_languageAudio` to `OpenLanguageAudioPak`.

Regardless, this is legacy Cry localization handling, with it's own assumptions about pak file names and locations.  It all needs to get scrapped anyways.  This update was just meant to fix it enough to propagate the setting to Wwise properly.

File: Code/Legacy/CrySystem/SystemInit.cpp (hunk 1 above)
Comment (amzn-phist) [reply Code/Legacy/CrySystem/SystemInit.cpp:900]: Will update, thanks.

**Review by lumberyard-employee-dm — APPROVED** [review]
