### PR TITLE
[DPE] Fix handling of pending/disabled components

### LINKED ISSUE #16807: Restarting the Editor with two incompatible components present on an entity and then deleting them causes asserts to be printed to the Console and inconsistently causes crashing
**Describe the bug**
If an Editor is restarted when there is an entity with incompatible components present, then interacting with that entity and components after restarting causes issues. Selecting such entity after restarting causes the following assert to be printed to the *Console*:

*Assert#1 information*:
File:
```
/home/gpc-800/builds/o3de/Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabComponentAdapter.cpp
```
Condition:
```
(139843966205184) 'virtual void AzToolsFramework::Prefab::PrefabComponentAdapter::SetComponent(AZ::Component *)'

PrefabComponentAdapter::SetComponent - Component alias should not be empty.
```
Line: 60

Furthermore, on an example shown in the video following assert is printed to the *Console* after deleting the *Light* component from an entity (a component that does not have incompatibility issues):

*Assert#2 information*:
File:
```
/home/gpc-800/builds/o3de/Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
```
Condition:
```
(139843966205184) 'virtual void AzToolsFramework::DPELayout::setGeometry(const QRect &)'

widget in layout was not found in row's dom list!
```
Line: 255

Additionally, there was one more assert found in the Editor.log after crash shown on the video:

*Assert#3 information*:
File:
```
/home/gpc-800/builds/o3de/Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorComponentBase.cpp
```
Condition:
```
(139843966205184) 'auto AzToolsFramework::Components::EditorComponentBase::GenerateComponentSerializedIdentifier()::(anonymous class)::operator()(const AZStd::vector<AZ::Component *> &) const'

GenerateComponentSerializedIdentifier - Attempting to generate an identifier for a component that is already owned by the entity. 
```
Line: 92

Deleting an incompatible component from the entity (Del key, Right-mouse button > *Delete* or *Delete component* button) can also inconsistently (around 70% issue reproduction rate) lead to a crash:
```
Call Stack Trace:
10) 00007FF8F607DEA7 (KERNELBASE) : UnhandledExceptionFilter
 9) 00007FF8F5486A06 (InProcessClient64) : (function-name not available)
 8) 00007FF8F5486A98 (InProcessClient64) : (function-name not available)
 7) 00007FF8F5486961 (InProcessClient64) : (function-name not available)
 6) 00007FF8F8295330 (ntdll) : memset
 5) 00007FF8F827C876 (ntdll) : _C_specific_handler
 4) 00007FF8F829221F (ntdll) : _chkstk
 3) 00007FF8F82414B4 (ntdll) : RtlRaiseException
 2) 00007FF8F8290D2E (ntdll) : KiUserExceptionDispatcher
 1) 0000022A0467D040 (module-name not available) : (function-name not available)
```

It should be noted that the issue was also noticed on the *Vegetation Position Modifier*+*Vegetation Layer Blocker* entity, so it is not exclusive to the *Light*+*X Shape*+*Y Shape* components described in the **Steps to reproduce** section.

**Steps to reproduce**
1. Create an entity and add *Light* component to it.
2. Set the *Light type* property to *Spot (disk)*.
3. Add a *Sphere Shape* component to the entity.
4. Save the level.
5. Close the Editor.
6. Launch the Editor and open the level saved in step 4.
7. Select the entity created in step 1 (an assert will be printed to the *Console*).
8. Delete the *Light* component (another assert will be printed to the *Console*).
9. Delete the incompatible components (if crash does not occur, *Undo* actions and delete them again).

**Expected behavior**
Editor remains stable.

**Actual behavior**
Asserts are printed to the *Console* and the Editor can crash.

**Video, Editor.log, error.log, and error.dmp**
0:36 to 2:29 in the video can be skipped:

https://github.com/o3de/o3de/assets/86952082/d81b6b2f-c16f-450f-a82b-7d994353a4ed

[Editor.log](https://github.com/o3de/o3de/files/12728305/Editor.log) - `Edtior.log` from the attached video.

Files from a Windows machine after reproducing the crash:
[Editor.log](https://github.com/o3de/o3de/files/12728318/Editor.log) 
[error.log](https://github.com/o3de/o3de/files/12728319/error.log)
[error.zip](https://github.com/o3de/o3de/files/12728320/error.zip) - contains `error.dmp` file.

**Found in Branch**
Stabilization/2310 (6f4ea1d)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
6f4ea1dbf9f084abdfdfabd3f43109eab2142188

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.3 LTS
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

### PR DESCRIPTION
**Pull request by mbalfour-amzn**
## What does this PR do?

In #16807 , if a Light, Disk, and Sphere component are all added to an entity, saved out, reloaded, and the Light is deleted, warnings and asserts occur. This fixes the warnings but not the asserts.

The warning `FindComponent failed - could not find component pointer from componentId provided.` happens when the DPE tries to look up a component to apply override displays but it isn't active because it's pending/disabled. The fix is to have the prefab code also take pending and disabled components into account when doing the lookup.

## How was this PR tested?

* Followed the steps in the bug and verified the warning no longer prints.
* Ran the unit tests and verified that nothing obviously broke from the change

### CODE REVIEW

File: Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.cpp [hunk 1]
```diff
@@ -130,6 +130,10 @@ namespace AZ::DocumentPropertyEditor
         // This lets the DPE and proxy adapters listen for patches that have valid indices instead of EndOfArray entries.
         Dom::Patch tempDenormalizedPatch;
 
+        // Send out the change signal *before* updating any cached contents so that nested updates don't try to apply
+        // the patch to the new data prematurely.
+        m_changedEvent.Signal(*appliedPatch);
```
Comment (AMZN-alexpete) [inline Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.cpp:135]: This comment is good, though it might be a good idea in a future PR to rename `m_changeEvent` to something like `m_prePatchEvent` or similar so the event name itself indicates if it is pre/post patch application.

**Review by AMZN-alexpete — APPROVED** [review]

File: Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.cpp [hunk 2]
```diff
@@ -159,7 +163,6 @@ namespace AZ::DocumentPropertyEditor
                 AZ_Warning("DPE", valuesMatch, "DocumentAdapter::NotifyContentsChanged: DOM patches applied, but the new model contents don't match the result of GenerateContents");
             }
         }
-        m_changedEvent.Signal(*appliedPatch);
```
Comment (lumberyard-employee-dm) [inline Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.cpp:162]: Can you rename this variable to m_preChangedEvent?

Also we would need to re-add back your previous change to NotifyResetDocument to trigger this event before updating the m_cachedContents member

**Review by gadams3 — APPROVED** [review]

**Comment by mbalfour-amzn** [comment]
I'm closing this PR. While it fixes the specific bug, it seems very likely that it will introduce new bugs in the other 5 places that call ConnectChangedHandler() and rely on this event. There appears to be inconsistent assumptions between the different change handlers as to whether or not GetContents() would contain pre-change or post-change data, and consequently whether or not the patch data should be forward or inverted patch data.

File: Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.cpp (hunk 1 above)
Comment (mbalfour-amzn) [reply Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.cpp]: I removed this change entirely from this PR. It will need a larger change in a different PR.

File: Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.cpp (hunk 2 above)
Comment (mbalfour-amzn) [reply Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.cpp]: I removed this change from this PR.

**Review by lumberyard-employee-dm — APPROVED** [review]
