### PR TITLE
ScriptCanvas: Fix default file path when saving a new graph

### LINKED ISSUE #13163: Bug Report: Incorrectly save script canvas in default O3DE SDK root path and not in current project on linux
**Describe the bug**
Run o3de editor create script canvas saving wrong to path default sdk root not current project on linux

**Steps to reproduce**
1. Run O3DE Editor
2. Open script canvas
3. Save script canvas
4. Default sdk path is wrong

**Screenshots/Video**

https://user-images.githubusercontent.com/17591539/201545732-d5995ddd-6cff-458b-8f04-bad1cd29da3e.mp4

https://user-images.githubusercontent.com/17591539/201545980-7e1b2312-6dd0-4273-b181-22a32a077ad7.mp4

**Found in Branch**
development: ff129eef52fbe6933fb29f5c06a6173c5349cf40

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Fedora
 - Version 36

### LINKED ISSUE #13616: Editor (Script Canvas, Material Editor, Etc): Weird Default Save Location
**Describe the bug**
The default save location when saving something in Editor is inside the o3de installer directory instead of the project.

**Steps to reproduce**
1. Use an o3de sdk or installer to create a new project
2. Open Editor > Script Canvas
3. Save a new script canvas
4. Notice the default save location

**Expected behavior**
The default save location in a new project should be in the project folder

**Actual behavior**
The default save location is in the installer folder

**Screenshots/Video**
image

**Found in Branch**
development 

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
076fd1943f87323993fa564c3b16e1b24b083d21 
Tue Dec 6 2022

### PR DESCRIPTION
**Pull request by lsemp3d**
## What does this PR do?

When saving a new file in ScriptCanvas it would sometimes go to the executable's folder instead of the project's root folder. The problem was that we'd send `AzQtComponents::FileDialog::GetSaveFileName` an invalid filename and the function would handle that by returning the executable's folder.

This change stores the suggested filename that was used when creating the new asset and using it for the open save file dialog but also it ensures that the folder that we specify exists.

Also removed some additional file name validation, the `AzQtComponents::FileDialog::GetSaveFileName` already verifies that the filename is valid.

Closes #13616 
Closes #13163

### CODE REVIEW

File: Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp [hunk 1]
```diff
@@ -1652,7 +1653,7 @@ namespace ScriptCanvasEditor
         bool isValidFileName = false;
 
         AZ::IO::FixedMaxPath projectSourcePath = AZ::Utils::GetProjectPath();
-        projectSourcePath /= "ScriptCanvas//";
+        projectSourcePath /= "Assets/ScriptCanvas";
```
Comment (guillaume-haerinck) [inline Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp:1656]: Hey ! What happens if the Assets/ScriptCanvas folder does not exist ? Isn't the windows file explorer will still go to the root

Comment (lsemp3d) [reply Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp:1656]: It verifies if it exists, if not, it creates the folder:

```
            QDir dir(suggestedDirectoryPath.c_str());
            if (!dir.exists())
            {
                auto result = AZ::IO::SystemFile::CreateDir(suggestedDirectoryPath.c_str());
                if (!result)
                {
                    AZ_Error("Script Canvas", false, "Failed to make new folder: %s", suggestedDirectoryPath.c_str());
                    return false;
                }
            }
```

**Review by guillaume-haerinck — APPROVED** [review]

File: Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp (hunk 1 above)
Comment (guillaume-haerinck) [reply Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp:1656]: Oh right I read the review too fast this morning, cool change
