### PR TITLE
change matrix serialization to use array rather than scale, rotation …

### LINKED ISSUE #10341: MathMatrixSerializer does not work with all matrices
MathMatrixSerializer always attempts to convert matrices to a quaternion and scale representation. Only matrices which are a scalar multiple of an orthogonal matrix can be represented this way, others will lose information.

### PR DESCRIPTION
**Pull request by greerdv**
…and translation

Signed-off-by: greerdv <greerdv@amazon.com>

## What does this PR do?
Changes serialization for Matrix3x3, Matrix3x4 and Matrix4x4 to store arrays of values, rather than storing as scale, rotation and translation (a representation which will only work for certain matrices). Fixes #10341. There is already existing code for loading from arrays, so that part didn't need to be updated.

## How was this PR tested?
Ran updated unit tests. Made a level with a rigid body component and modified its inertia tensor (which is serialized as Matrix3x3), inspected prefab and verified it was correctly serialized, entered game mode and verified inertia tensor was correctly set in simulation using PhysX visual debugger.

### CODE REVIEW

**Review by moraaar — APPROVED** [review]
LGTM. Great change! Thanks @greerdv

**Review by hultonha — COMMENTED** [review]
Changes look great but just want to check does this handle existing serialized data okay when people open levels saved with the old format?

**Comment by greerdv** [comment]
> Changes look great but just want to check does this handle existing serialized data okay when people open levels saved with the old format?

Yeah, the method to load from rotation, scale and translation is still there. I think the serialization system in general is designed to handle a variety of inputs, so it can do either that or an array, depending on what is in the json. Some of the existing tests deserialize data in that format and they're still working.

**Comment by hultonha** [comment]
> > Changes look great but just want to check does this handle existing serialized data okay when people open levels saved with the old format?
> 
> Yeah, the method to load from rotation, scale and translation is still there. I think the serialization system in general is designed to handle a variety of inputs, so it can do either that or an array, depending on what is in the json. Some of the existing tests deserialize data in that format and they're still working.

Ah perfect thanks, sounds good 👍

**Review by hultonha — APPROVED** [review]

File: Code/Framework/AzCore/AzCore/Math/MathMatrixSerializer.cpp [hunk 1]
```diff
@@ -306,77 +306,34 @@ namespace AZ::JsonMathMatrixSerializerInternal
...
-    {
-        namespace JSR = JsonSerializationResult; // Used remove name conflicts in AzCore in uber builds.
-        AZ_UNUSED(valueTypeId);
+        constexpr size_t ElementCount = RowCount * ColumnCount;
+        static_assert(ElementCount == 9 || ElementCount == 12 || ElementCount == 16,
+            "MathMatrixSerializer only support Matrix3x3, Matrix3x4 and Matrix4x4.");
 
         const MatrixType* matrix = reinterpret_cast<const MatrixType*>(inputValue);
-        AZ_Assert(matrix, "Input value for JsonMatrixSerializer can't be null.");
+        AZ_Assert(matrix, "Input value for JsonVector%zux%zuSerializer can't be null.", RowCount, ColumnCount);
```
Comment (lumberyard-employee-dm) [inline Code/Framework/AzCore/AzCore/Math/MathMatrixSerializer.cpp:320]: The assert text should be `JsonMatrix%zux%zuSerializer` instead JsonVector...

**Review by lumberyard-employee-dm — APPROVED** [review]
You might want to mention in the PR description that the Load code already knows how de-serialize a matrix from an array and that is the reason it doesn't need to be updated
