### PR TITLE
[development] update mobile settings editor tool to support new project path structure

### LINKED ISSUE #2087: Platform Settings crashes the editor.
"File->Edit Platform Settings..." crashes the editor.

Reproducible at least on c9ff63408 commit.

() - 00007FF93609C247 (KERNELBASE) : UnhandledExceptionFilter
() - 00007FF938795270 (ntdll) : memset
() - 00007FF93877C776 (ntdll) : _C_specific_handler
() - 00007FF93879217F (ntdll) : _chkstk
() - 00007FF938741454 (ntdll) : RtlRaiseException
() - 00007FF938790CAE (ntdll) : KiUserExceptionDispatcher
() - D:\o3de\o3de\Code\Framework\AzCore\AzCore\std\string\string.h (1851) : AZStd::operator+<char,AZStd::char_traits<char>,AZStd::allocator>
() - D:\o3de\o3de\Code\Editor\Plugins\ProjectSettingsTool\ProjectSettingsToolWindow.cpp (671) : ProjectSettingsTool::ProjectSettingsToolWindow::PlatformEnabled
() - D:\o3de\o3de\Code\Editor\Plugins\ProjectSettingsTool\ProjectSettingsToolWindow.cpp (51) : ProjectSettingsTool::ProjectSettingsToolWindow::ProjectSettingsToolWindow
() - D:\o3de\o3de\Code\Editor\QtViewPaneManager.cpp (147) : QtViewPane::CreateWidget
() - D:\o3de\o3de\Code\Editor\QtViewPaneManager.cpp (663) : QtViewPaneManager::OpenPane
() - D:\o3de\o3de-packages\packages\qt-5.15.2-rev4-windows\qt\include\QtCore\qobjectdefs_impl.h (443) : QtPrivate::QFunctorSlotObject<<lambda_94629051ac44815935e26f4617d34052>,0,QtPrivate::List<>,void>::impl
() - 00007FF8EB4E0DB9 (Qt5Core) : QObject::qt_static_metacall
() - 00007FF91EFB5DCF (Qt5Widgets) : QAction::activate
() - 00007FF91F10C698 (Qt5Widgets) : QMenu::actionGeometry
() - 00007FF91F10C473 (Qt5Widgets) : QMenu::actionGeometry
() - 00007FF91F111C51 (Qt5Widgets) : QMenu::mouseReleaseEvent
() - 00007FF91EFE7B02 (Qt5Widgets) : QWidget::event
() - 00007FF91F10DC37 (Qt5Widgets) : QMenu::event
() - 00007FF91EFC49B0 (Qt5Widgets) : QApplicationPrivate::notify_helper
() - 00007FF91EFC28D0 (Qt5Widgets) : QApplication::notify
() - 00007FF8EB4C1B4A (Qt5Core) : QCoreApplication::notifyInternal2
() - 00007FF91EFC5BC5 (Qt5Widgets) : QApplicationPrivate::sendMouseEvent
() - 00007FF91F01024A (Qt5Widgets) : QSizePolicy::QSizePolicy
() - 00007FF91F00E80E (Qt5Widgets) : QSizePolicy::QSizePolicy

### PR DESCRIPTION
**Pull request by AMZN-ScottR**
Fixes #2087

Signed-off-by: AMZN-ScottR <24445312+AMZN-ScottR@users.noreply.github.com>

### CODE REVIEW

File: Code/Editor/Plugins/ProjectSettingsTool/ProjectSettingsToolWindow.cpp [hunk 1]
```diff
@@ -647,33 +648,38 @@ namespace ProjectSettingsTool
...
+            };
+
+            for (auto relPath : searchPaths)
             {
-                const AZStd::string filename = m_projectRoot + "/Gem/Resources/IOSLauncher/Info.plist";
-                if (CFileUtil::FileExists(filename.c_str()))
+                AZ::IO::FixedMaxPath projectPlist{ m_projectRoot };
+                projectPlist /= relPath;
+
+                if (CFileUtil::FileExists(projectPlist.c_str()))
```
Comment (lumberyard-employee-dm) [inline Code/Editor/Plugins/ProjectSettingsTool/ProjectSettingsToolWindow.cpp:675]: This could use `AZ::SystemFile::Exists`.
That could remove a dependency on Util/FileUtil.h

File: Code/Editor/Plugins/ProjectSettingsTool/ProjectSettingsToolWindow.cpp [hunk 2]
```diff
@@ -647,33 +648,38 @@ namespace ProjectSettingsTool
...
                 {
-                    return "/Gem/Resources/IOSLauncher/Info.plist";
+                    return projectPlist.LexicallyNormal().c_str();
```
Comment (lumberyard-employee-dm) [inline Code/Editor/Plugins/ProjectSettingsTool/ProjectSettingsToolWindow.cpp:677]: A slightly more efficient operations is to call `.String()`
```suggestion
                    return projectPlist.LexicallyNormal().String();
```

**Review by lumberyard-employee-dm — APPROVED** [review]

File: Code/Editor/Plugins/ProjectSettingsTool/ProjectSettingsToolWindow.cpp (hunk 1 above)
Comment (AMZN-ScottR) [reply Code/Editor/Plugins/ProjectSettingsTool/ProjectSettingsToolWindow.cpp:675]: Good catch, will do.

**Review by AMZN-nggieber — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]

**Review by AMZN-Phil — APPROVED** [review]
