### PR TITLE
Fixes for `CameraInput` handling

### LINKED ISSUE #6388: Viewport selection sometimes does not respond to input
**Describe the bug**

It is possible to get the O3DE Viewport into a state where no mouse input appears to be handled other than controlling the camera.

**Steps to reproduce**

1. Attempt moving the camera with WASD while using Pan or Look (MMB and RMB)
2. Try changing focus while this is happening

__Note: This is not 100% reproducible or reliable, it can just happen randomly from time to time__

**Expected behavior**

Viewport always responds to input

**Actual behavior**

It can sometimes be impossible to select things in the viewport (only control the camera)

**Found in Branch**

Development

**Additional context**

The reason for this bug is one of the `CameraInput` behaviors (specifically `TranslateCameraInput`) gets 'stuck' in an `Active` state even when it should no longer be active. This causes the camera system to report the `ViewportControllerPriority` for `ModularViewportCameraController` is `AzFramework::ViewportControllerPriority::Highest`. This is needed for situation where the camera should eat input (e.g. When pressing and holding RMB) but in this case it should have dropped back to `AzFramework::ViewportControllerPriority::Normal` to ensure input can make it to the viewport before being intercepted as a camera input.

The most likely reason for the issue is an input even it 'lost' and so the camera never transitions back to the inactive state. There needs to be a way to catch and self correct the camera system is this happens.

### PR DESCRIPTION
**Pull request by hultonha**
Fixes #6388 

This PR fixes some subtle issues with how `CameraInput` types would move between states. It was possible for cameras to occasionally get into 'invalid' states (e.g. Not being 'Idle' in the idle camera list). This PR fixes these issues and adds additional tests to guarantee this behavior is maintained and not broken in future

Before fixes

```
[ RUN      ] CameraInputFixture.InvalidTranslationInputKeyCannotBeginTranslateCameraInputAgain
D:/o3de/Code/Framework/AzFramework/Tests/CameraInputTests.cpp(431): error: Value of: m_firstPersonTranslateCamera->Beginning()
Expected: is false
  Actual: true (of type bool)
D:/o3de/Code/Framework/AzFramework/Tests/CameraInputTests.cpp(432): error: Value of: m_firstPersonTranslateCamera->Active()
Expected: is true
  Actual: false (of type bool)
[  FAILED  ] CameraInputFixture.InvalidTranslationInputKeyCannotBeginTranslateCameraInputAgain (2 ms)
[ RUN      ] CameraInputFixture.InvalidTranslationInputKeyDownCannotBeginTranslateCameraInputAgain
D:/o3de/Code/Framework/AzFramework/Tests/CameraInputTests.cpp(446): error: Value of: m_firstPersonTranslateCamera->Beginning()
Expected: is false
  Actual: true (of type bool)
D:/o3de/Code/Framework/AzFramework/Tests/CameraInputTests.cpp(447): error: Value of: m_firstPersonTranslateCamera->Active()
Expected: is true
  Actual: false (of type bool)
[  FAILED  ] CameraInputFixture.InvalidTranslationInputKeyDownCannotBeginTranslateCameraInputAgain (1 ms)
[ RUN      ] CameraInputFixture.InvalidTranslationInputKeyUpDoesNotAffectTranslateCameraInputEnd
[       OK ] CameraInputFixture.InvalidTranslationInputKeyUpDoesNotAffectTranslateCameraInputEnd (0 ms)
[ RUN      ] CameraInputFixture.OrbitCameraInputCannotBeLeftInInvalidStateIfItCannotFullyBeginAfterInputChannelBegin
D:/o3de/Code/Framework/AzFramework/Tests/CameraInputTests.cpp(476): error: Value of: m_orbitCamera->Beginning()
Expected: is false
  Actual: true (of type bool)
D:/o3de/Code/Framework/AzFramework/Tests/CameraInputTests.cpp(477): error: Value of: m_orbitCamera->Idle()
Expected: is true
  Actual: false (of type bool)
[  FAILED  ] CameraInputFixture.OrbitCameraInputCannotBeLeftInInvalidStateIfItCannotFullyBeginAfterInputChannelBegin (1 ms)
[ RUN      ] CameraInputFixture.OrbitCameraInputCannotBeLeftInInvalidStateIfItCannotFullyBeginAfterInputChannelBeginAndEnd
D:/o3de/Code/Framework/AzFramework/Tests/CameraInputTests.cpp(490): error: Value of: m_orbitCamera->Ending()
Expected: is false
  Actual: true (of type bool)
D:/o3de/Code/Framework/AzFramework/Tests/CameraInputTests.cpp(491): error: Value of: m_orbitCamera->Idle()
Expected: is true
  Actual: false (of type bool)
[  FAILED  ] CameraInputFixture.OrbitCameraInputCannotBeLeftInInvalidStateIfItCannotFullyBeginAfterInputChannelBeginAndEnd (1 ms)
[----------] 20 tests from CameraInputFixture (28 ms total)
[----------] Global test environment tear-down
[==========] 20 tests from 1 test case ran. (30 ms total)
[  PASSED  ] 16 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] CameraInputFixture.InvalidTranslationInputKeyCannotBeginTranslateCameraInputAgain
[  FAILED  ] CameraInputFixture.InvalidTranslationInputKeyDownCannotBeginTranslateCameraInputAgain
[  FAILED  ] CameraInputFixture.OrbitCameraInputCannotBeLeftInInvalidStateIfItCannotFullyBeginAfterInputChannelBegin
[  FAILED  ] CameraInputFixture.OrbitCameraInputCannotBeLeftInInvalidStateIfItCannotFullyBeginAfterInputChannelBeginAndEnd
```

After fixes

```
[ RUN      ] CameraInputFixture.InvalidTranslationInputKeyCannotBeginTranslateCameraInputAgain
[       OK ] CameraInputFixture.InvalidTranslationInputKeyCannotBeginTranslateCameraInputAgain (0 ms)
[ RUN      ] CameraInputFixture.InvalidTranslationInputKeyDownCannotBeginTranslateCameraInputAgain
[       OK ] CameraInputFixture.InvalidTranslationInputKeyDownCannotBeginTranslateCameraInputAgain (0 ms)
[ RUN      ] CameraInputFixture.InvalidTranslationInputKeyUpDoesNotAffectTranslateCameraInputEnd
[       OK ] CameraInputFixture.InvalidTranslationInputKeyUpDoesNotAffectTranslateCameraInputEnd (0 ms)
[ RUN      ] CameraInputFixture.OrbitCameraInputCannotBeLeftInInvalidStateIfItCannotFullyBeginAfterInputChannelBegin
[       OK ] CameraInputFixture.OrbitCameraInputCannotBeLeftInInvalidStateIfItCannotFullyBeginAfterInputChannelBegin (0 ms)
[ RUN      ] CameraInputFixture.OrbitCameraInputCannotBeLeftInInvalidStateIfItCannotFullyBeginAfterInputChannelBeginAndEnd
[       OK ] CameraInputFixture.OrbitCameraInputCannotBeLeftInInvalidStateIfItCannotFullyBeginAfterInputChannelBeginAndEnd (0 ms)
[----------] Global test environment tear-down
[==========] 20 tests from 1 test case ran. (33 ms total)
[  PASSED  ] 20 tests.
```

### CODE REVIEW

File: Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp [hunk 1]
```diff
@@ -213,9 +213,9 @@ namespace AzFramework
...
     Camera Cameras::StepCamera(const Camera& targetCamera, const ScreenVector& cursorDelta, const float scrollDelta, const float deltaTime)
     {
-        for (int i = 0; i < m_idleCameraInputs.size();)
+        for (int idleIndex = 0; idleIndex < m_idleCameraInputs.size();)
         {
-            auto& cameraInput = m_idleCameraInputs[i];
+            auto& cameraInput = m_idleCameraInputs[idleIndex];
             const bool canBegin = cameraInput->Beginning() &&
                 AZStd::all_of(m_activeCameraInputs.cbegin(), m_activeCameraInputs.cend(),
                               [](const auto& input)
```
Comment (moraaar) [inline Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp:221]: Nit: This part of the condition
````
(!cameraInput->Exclusive() || (cameraInput->Exclusive() && m_activeCameraInputs.empty()))
````
can be simplified to
````
(!cameraInput->Exclusive() || m_activeCameraInputs.empty())
````

**Review by moraaar — APPROVED** [review]
LGTM. Just a small improvement suggestion.

**Review by amzn-rhhong — APPROVED** [review]

File: Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp (hunk 1 above)
Comment (hultonha) [reply Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp:221]: Ah good spot! You're quite right, will update 👍 Thanks!
