### PR TITLE
Fixed Gradient Baker not updating its dependency monitor when the configuration changes

### LINKED ISSUE #10381: Gradient Baker: Node preview doesn't update until a property on the component is updated
**Describe the bug**
Gradient Baker node preview doesn't update until a property on the component is updated.

**Steps to reproduce**
1. Launch the Editor and open a new or existing level in the AutomatedTesting project or another project with Landscape Canvas/Gradient Gems built.
2. Add a Box Shape node, Fast Noise node, and Gradient Baker node to the graph, and connect them like so:

* Box Shape Node Bounds slot -> Fast Noise Preview Bounds slot & Gradient Baker Input Bounds slot
* Fast Noise Outbound Gradient slot -> Gradient Baker Inbound Gradient slot

3. Observe the the Gradient Baker node preview now matches the Fast Noise Gradient node's preview.
4. Make a change to the Fast Noise component configuration.
5. Observe the previews for the nodes now differ.
6. Change a property on the Gradient Baker component (e.g. Resolution or Output Format)

**Expected behavior**
Gradient Baker node preview updates with changes to the gradient fed to it.

**Actual behavior**
Gradient Baker node preview updates with changes to the gradient fed to it only after the component properties are changed.

**Screenshots/Video**
image

**Found in Branch**
development@ 9b18abe78b849b3ec05223b6c3eaf4b6c90c3c21

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

### PR DESCRIPTION
**Pull request by cgalvan**
## What does this PR do?

Fixes #10381

The gradient baker component doesn't inherit from the `EditorGradientComponentBase` since it's an Editor-only component, so it was missing the logic that re-configures the dependency monitor when the configuration changes. The issue was noticed in the gradient baker node because if you created a new one (as per the steps in #10381), it's preview wouldn't be updated when there were changes in its dependencies because the dependency monitor wasn't being re-setup. The gradient baker node did function properly if you were loading a graph of an existing gradient baker component that had already been configured.

## How was this PR tested?

Ran unit tests and the repro steps in #10381. Here's gif of it working, where previously the gradient baker node preview would stay static when the random seed button was being pushed on the FastNoise gradient.

BakerNodeUpdateOnDependencyChange

Signed-off-by: Chris Galvan <chgalvan@amazon.com>

### CODE REVIEW

File: Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.cpp [hunk 1]
```diff
@@ -588,6 +596,10 @@ namespace GradientSignal
         // Cancel any pending preview refreshes before locking, to help ensure the preview itself isn't holding the lock
         auto entityIds = CancelPreviewRendering();
 
+        // Re-setup the dependency monitor when the configuratio changes because the gradient sampler
```
Comment (mbalfour-amzn) [inline Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.cpp:599]: "configuratio" -> "configuration"

**Review by mbalfour-amzn — APPROVED** [review]

**Review by invertednormal — APPROVED** [review]

File: Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.cpp (hunk 1 above)
Comment (cgalvan) [reply Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.cpp]: Thanks, fixed!
