### PR TITLE
Fix double deletion of entities when unloading a level

### LINKED ISSUE #8696: Switching level causes an Atom crash
**Describe the bug**
Calling LoadLevel the second time to a different level causes an Atom crash.

**Steps to reproduce**
1. create two levels, both can be empty levels
2. start a game launcher
3. loadlevel first level
4. loadlevel second level
5. See crash

**Expected behavior**
Second level loads to replace the first level

**Actual behavior**
Crashes
```
>	Atom_RPI.Private.dll!AZ::Job::Job(bool isAutoDelete, AZ::JobContext * context, bool isCompletion, char priority) Line 25	C++
 	Atom_RPI.Private.dll!AZ::JobCompletion::JobCompletion(AZ::JobContext * context) Line 28	C++
 	[Inline Frame] Atom_RPI.Private.dll!AZ::RPI::Scene::SimulateJobs() Line 433	C++
 	Atom_RPI.Private.dll!AZ::RPI::Scene::Simulate(AZ::RHI::JobPolicy jobPolicy, float simulationTime) Line 487	C++
 	Atom_RPI.Private.dll!AZ::RPI::RPISystem::SimulationTick() Line 279	C++
 	Atom_RPI.Private.dll!AZ::RPI::RPISystemComponent::OnSystemTick() Line 111	C++
 	[Inline Frame] MyProject.GameLauncher.exe!AZStd::Internal::INVOKE(void(AZ::SystemTickEvents::*)() &) Line 177	C++
 	[Inline Frame] MyProject.GameLauncher.exe!AZStd::invoke(void(AZ::SystemTickEvents::*)() &) Line 55	C++
 	[Inline Frame] MyProject.GameLauncher.exe!AZ::EBusEventProcessingPolicy::Call(void(AZ::SystemTickEvents::*)() &) Line 437	C++
 	MyProject.GameLauncher.exe!AZ::Internal::EBusContainer<AZ::SystemTickEvents,AZ::SystemTickEvents,0,1>::Dispatcher<AZ::EBus<AZ::SystemTickEvents,AZ::SystemTickEvents>>::Broadcast<void (__cdecl AZ::SystemTickEvents::*)(void)>(void(AZ::SystemTickEvents::*)() && func) Line 1360	C++
 	MyProject.GameLauncher.exe!AZ::ComponentApplication::TickSystem() Line 1357	C++

```
[crashlog_switching_levels.txt](https://github.com/o3de/o3de/files/8412311/crashlog_switching_levels.txt)

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU Ryzen 5900x
 - GPU NVidia RTX 3090
 - Memory 64GB

### PR DESCRIPTION
**Pull request by michabr**
When unloading a level (root spawnable), the ReleaseRootSpawnable call already deletes that level's entities and removes them from the game entity context, so there should no longer be a need to also call ResetGameContext.

Calling ResetGameContext results in entities being deleted that are still being referenced in the spawn ticket. Later on when the spawn ticket is released via ReleaseRootSpawnable, the entities get deleted again causing crashes etc.

Fixes #8696.

Signed-off-by: abrmich <abrmich@amazon.com>

### CODE REVIEW

**Review by NicholasVanSickle — APPROVED** [review]
We'll want to do some runtime testing after this gets merged.

As a data point, it'd be helpful to know if the double delete also happens if we trigger `ResetGameContext` after calling `ReleaseRootSpawnable`.

**Comment by michabr** [comment]
> We'll want to do some runtime testing after this gets merged.
> 
> As a data point, it'd be helpful to know if the double delete also happens if we trigger `ResetGameContext` after calling `ReleaseRootSpawnable`.

It will also happen if we trigger ResetGameContext afterward because the ReleaseRootSpawnable doesn't happen right away. It gets put on a processing queue.

**Comment by michabr** [comment]
If we find we need to reset the entity context (I don't think we do because there won't be any slices being spawned since we no longer provide that option), we could probably wait for a callback for when the spawnable is done deleting.

**Comment by NicholasVanSickle** [comment]
Ah right the queue - I think this is OK as-is, we'll just want to keep an eye on any potentially related bugs. Thanks for the clarification!

File: Code/Legacy/CrySystem/LevelSystem/SpawnableLevelSystem.cpp [hunk 1]
```diff
@@ -547,6 +544,7 @@ namespace LegacyLevelSystem
 
         OnUnloadComplete(m_lastLevelName.c_str());
 
+        // Delete level entities and prefab instances and remove them from the game entity context
```
Comment (srikappa-amzn) [inline Code/Legacy/CrySystem/LevelSystem/SpawnableLevelSystem.cpp:547]: In game mode, the editor entities and prefabs would be converted to flattened list of entities under the root spawnable. So, its better to avoid referring to prefabs whenever possible. I suggest changing this to "Delete level entities and remove..."

File: Code/Legacy/CrySystem/LevelSystem/SpawnableLevelSystem.cpp [hunk 2]
```diff
@@ -536,9 +536,6 @@ namespace LegacyLevelSystem
 
         const AZ::TimeMs beginTimeMs = AZ::GetRealElapsedTimeMs();
 
-        // Clear level entities and prefab instances.
-        EBUS_EVENT(AzFramework::GameEntityContextRequestBus, ResetGameContext);
```
Comment (srikappa-amzn) [inline Code/Legacy/CrySystem/LevelSystem/SpawnableLevelSystem.cpp:540]: Good catch. This change makes sense to me but I'd like to gather some more information to avoid possible bugs.

ResetGameContext() also calls CreateRootSlice() down the line. I think this is required so that further level loads can use this root slice. Since you said that it fixes the https://github.com/o3de/o3de/issues/8696 bug, does that mean that when the second level is loaded, a new root slice is created or the existing one is used?

Comment (michabr) [reply Code/Legacy/CrySystem/LevelSystem/SpawnableLevelSystem.cpp:540]: > Good catch. This change makes sense to me but I'd like to gather some more information to avoid possible bugs.
> 
> ResetGameContext() also calls CreateRootSlice() down the line. I think this is required so that further level loads can use this root slice. Since you said that it fixes the #8696 bug, does that mean that when the second level is loaded, a new root slice is created or the existing one is used?

When the second level is loaded, the existing root slice is used. A new one is not created, however the number of entities on the existing root slice have been cleared to 0.

File: Code/Legacy/CrySystem/LevelSystem/SpawnableLevelSystem.cpp (hunk 1 above)
Comment (michabr) [reply Code/Legacy/CrySystem/LevelSystem/SpawnableLevelSystem.cpp:547]: Makes sense. I will change that comment.

**Review by srikappa-amzn — APPROVED** [review]
After further discussions, change seems stable enough to go to stabilization branch. I recommend doing one more round of testing around game launcher workflows to be sure.
