### PR TITLE
13234 fix shaking inspector layout

### LINKED ISSUE #13234: Incorrect layout in anim graph parameter edit window when putting text
## Steps to reproduce
1. Open Animation Editor
2. Open some animation asset (e.g. AutomatedTesting\Animations\AnimationEditorFiles\sample0.animgraph
3. In Parameters window choose the "movement speed" parameter
4. In the edit window in the inspector, start editing the name field

## Expected result
Layout of the edit window doesn't change when editing the name field

## Actual result
Layout changes in such a way, that the edit window takes only half of the width of the inspector:

https://user-images.githubusercontent.com/104767/202230524-9cace091-b15d-4468-b1b9-7e013bc199dc.mp4

### PR DESCRIPTION
**Pull request by aambrosano**
## What does this PR do?

This change fixes a bug where the Inspector layout was shaking when a parameter name was being edited.

Fixes #13234 

## How was this PR tested?

The PR was tested by adding a new parameter and editing its name, the layout is not shaking anymore.

### CODE REVIEW

**Comment by hultonha** [comment]
@aambrosano It looks like this change was started from the wrong branch, it has lots more changes in it seems (that seem to be @ablepharus' changes. Can you please create a fresh PR from development instead please? Thanks!

**Comment by hultonha** [comment]
@aambrosano Could you please add a video of the fix please to show how it's working now. Thanks!

**Review by hultonha — APPROVED** [review]
Change looks good to me but as mentioned it'd be great to see a video of things working in action. Much appreciated!

**Comment by aambrosano** [comment]
Before:
Before

After:
After

**Comment by hultonha** [comment]
Awesome thank you @aambrosano! 🙂

**Review by SergeyAMZN — APPROVED** [review]

File: Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphNodeGroup.h [hunk 1]
```diff
@@ -174,13 +174,26 @@ namespace EMotionFX
...
+         * Returns the id of the parent AnimGraphNode to which this group belongs.
+         * If the group belongs to the root level, this function will return an invalid id.
+         * This function is used to make sure that groups can be filtered by level.
+         */
+        AnimGraphNodeId ParentNodeId() const;
+
+        /**
+         * Sets the id of the parent AnimGraphNode for this group.
+         */
+        void SetParentNodeId(AnimGraphNodeId nodeId);
```
Comment (moraaar) [inline Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphNodeGroup.h:187]: Since there is the setter `SetParentNodeId` please name the getter `GetParentNodeId` instead of `ParentNodeId`.

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp [hunk 2]
```diff
@@ -43,18 +43,37 @@ namespace EMStudio
...
+                nodeGroupColor.FromU32(nodeGroup->GetColor());
+                QAction* nodeGroupAction = nodeGroupMenu->addAction(QIcon(new SolidColorIconEngine(nodeGroupColor)), nodeGroup->GetName());
+                nodeGroupAction->setData(qulonglong(i + 1)); // index of the menu added, not used
+                connect(nodeGroupAction, &QAction::triggered, this, &BlendGraphWidget::AssignSelectedNodesToGroup);
+                validGroupCount++;
+            }
         }
 
-        menu->addMenu(nodeGroupMenu);
+        if (validGroupCount > 0) {
```
Comment (moraaar) [inline Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp:74]: [standards] Open braces on a new line, and flush with the outer block's indentation

https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md#positioning-of-curly-braces

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp [hunk 3]
```diff
@@ -43,18 +43,37 @@ namespace EMStudio
...
         for (size_t i = 0; i < numNodeGroups; ++i)
         {
             EMotionFX::AnimGraphNodeGroup* nodeGroup = animGraph->GetNodeGroup(i);
+            auto* activeGraph = GetActiveGraph();
+
+            auto nodeGroupParentId = nodeGroup->ParentNodeId();
+            auto currentLevelParentIndex = activeGraph->GetAnimGraphModel().GetFocus();
+            auto currentLevelParentId = currentLevelParentIndex.isValid()
+                ? currentLevelParentIndex.data(AnimGraphModel::ROLE_ID).value<EMotionFX::AnimGraphNodeId>()
+                : EMotionFX::AnimGraphNodeId{};
```
Comment (moraaar) [inline Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp:59]: Seems like the following code can be moved outside the loop and therefore only done once.

````
            auto* activeGraph = GetActiveGraph();
            auto currentLevelParentIndex = activeGraph->GetAnimGraphModel().GetFocus();
            auto currentLevelParentId = currentLevelParentIndex.isValid()
                ? currentLevelParentIndex.data(AnimGraphModel::ROLE_ID).value<EMotionFX::AnimGraphNodeId>()
                : EMotionFX::AnimGraphNodeId{};
````

File: Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphNodeGroup.h (hunk 1 above)
Comment (aambrosano) [reply Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphNodeGroup.h]: Not relevant here, I mistakenly force pushed changes from a different PR here.

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp (hunk 2 above)
Comment (aambrosano) [reply Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp]: Not relevant here, I mistakenly force pushed changes from a different PR here.

File: Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp (hunk 3 above)
Comment (aambrosano) [reply Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp]: Not relevant here, I mistakenly force pushed changes from a different PR here.

**Review by moraaar — APPROVED** [review]
