### PR TITLE
EMotion FX: Simple motion component blend out time not working (+some more fixes)

### LINKED ISSUE #5977: [Animation] Add the simple motion component and add the walk animation model of the root motion. When the value of Blend Out Time is changed to a value greater than 0, the animation does not change.
**Describe the bug**
[Animation] Add the simple motion component and add the walk animation model of the root motion. When the value of Blend Out Time is changed to a value greater than 0, the animation does not change.

**Steps to reproduce**
1. Add the simple motion component, add the walk animation model of the root motion, and adjust the values of Blend In Time and Blend Out Time to be greater than 0.

**Expected behavior**
1. The mixed-in and mixed-out time takes effect, and the animation changes obviously.

**Actual behavior**
1. The animation changes obviously, but the animation does not change when you adjust the value of Blend Out Time to a value greater than 0.

 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel Xeon Gold 6234]
 - GPU [NVidia RTX 5000]
 - Memory [32GB]
 - Working Branch: Main branch e7f7875

**Additional context**

### PR DESCRIPTION
**Pull request by amzn-jillich**
* Blend out time was not working previously.
* Added the freeze at last frame option to the UI. If disabled, the character goes back to bind pose after the motion ended. If enabled, it stays at the last frame of the animation in case it is not looping.
* Hiding the freeze at last frame option in case the loop option is enabled.
* Showing the blend out option only in case looping and freezing at last frame are disabled. Hiding otherwise.

Resolves #5977

https://user-images.githubusercontent.com/43751992/155109641-f41a1b24-28af-48d7-a539-1e6a8fc7ea30.mp4

Signed-off-by: Benjamin Jillich <jillich@amazon.com>

### CODE REVIEW

File: Gems/EMotionFX/Code/EMotionFX/Source/MotionLayerSystem.cpp [hunk 1]
```diff
@@ -157,10 +157,7 @@ namespace EMotionFX
                 if (source->GetBlendOutBeforeEnded())
                 {
                     // if the motion has to stop
-                    if ((!source->GetIsPlayingForever() &&
-                        (source->GetNumCurrentLoops() >= source->GetMaxLoops()) &&
-                        (source->GetTimeDifToLoopPoint() <= source->GetFadeTime()) &&
-                        !source->GetFreezeAtLastFrame()) ||
+                    if ((!source->GetIsPlayingForever() && source->GetTimeDifToLoopPoint() <= source->GetFadeTime() && !source->GetFreezeAtLastFrame()) ||
```
Comment (amzn-rhhong) [inline Gems/EMotionFX/Code/EMotionFX/Source/MotionLayerSystem.cpp:160]: NIT: This is a bit difficult to read, I personally don't like super long if statement.
I'd rather have something like this:
bool motionHasToStop = false;
if ((!source->GetIsPlayingForever() && source->GetTimeDifToLoopPoint() <= source->GetFadeTime() && !source->GetFreezeAtLastFrame())
{ motionHasToStop = true; }
else if(source->GetHasEnded() && !source->GetFreezeAtLastFrame()))
{ motionHasToStop = true; }

then if(motionHasToStop)
{
...
}

**Review by amzn-rhhong — APPROVED** [review]

File: Gems/EMotionFX/Code/EMotionFX/Source/MotionLayerSystem.cpp (hunk 1 above)
Comment (amzn-jillich) [reply Gems/EMotionFX/Code/EMotionFX/Source/MotionLayerSystem.cpp]: Simplified it and fixed the tests (they were checking something wrong). Also uploaded a video demonstrating all the modes and settings working correctly.

**Review by lsemp3d — APPROVED** [review]
