### PR TITLE
Fix "index out of range" error in AssetProcessor

### LINKED ISSUE #2343: Asset Processor is crashing on new projects
**Describe the bug**
When AssetProcessor is running, after some time a ASSERT error is displayed on my screen.
`Qt-Fatal: ASSERT failure in QVector<T>::at: "index out of range`
Sometimes the error below is ocurred:
`Qt-Fatal: ASSERT: first <= rowCount(parent)`
**To Reproduce**
1. Create a New Project on Launcher
2. Rebuild
3. Open Project and wait for the AssetProcessor start.

**Expected behavior**
No Crash is expected

**Screenshots**
image
image
Assertion Error is occured here:
image

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel i7-7500U
 - GPU: AMD Radeon - R7 M340
 - Memory: 8gb
 - Working Branch: stabilization/2106

**Additional context**
- AutomatedTesting is not occurs this behaviour
- This behaviour occurs on `o3de-atom` project and `sample-viewer`

### PR DESCRIPTION
**Pull request by brakhane**
When the parent is the tree root element, beginInsertRows must be
called with an invalid (but legal) index. A QModelIndex with a row
index of zero when the parent has no children is an illegal index
and will result in "undefined behavior", like the "index out of
range" one.

Therefore, if our parent is the tree root element, we use QModelIndex()
instead.

Fixes #2343

This PR also contains two other commits which are not strictly necessary, one
makes the code more in line with Qt best practices, the other adds some debugging
asserts.

### CODE REVIEW

**Review by AMZN-daimini — APPROVED** [review]

**Comment by AMZN-daimini** [comment]
Looks good to me, I started the Automated Review and added some more reviewers.

File: Code/Tools/AssetProcessor/native/ui/ProductAssetTreeModel.cpp [hunk 1]
```diff
@@ -205,7 +208,8 @@ namespace AssetProcessor
             {
                 if (!modelIsResetting)
                 {
-                    QModelIndex parentIndex = createIndex(parentItem->GetRow(), 0, parentItem);
+                    QModelIndex parentIndex = parentItem == m_root.get() ? QModelIndex() : createIndex(parentItem->GetRow(), 0, parentItem);
+                    Q_ASSERT(checkIndex(parentIndex));
```
Comment (lumberyard-employee-dm) [inline Code/Tools/AssetProcessor/native/ui/ProductAssetTreeModel.cpp:212]: This would explain those Qt Asserts that occur in the AssetProcessor when running Debug

**Review by lumberyard-employee-dm — APPROVED** [review]

**Review by spham-amzn — APPROVED** [review]

**Review by lawsonamzn — APPROVED** [review]
