### PR TITLE
Fixed reading of `long/unsigned long` Attributes in the AttributeReader on Linux/Android

### LINKED ISSUE #16534: Linux: DPE Inspector: DepthOfField component does not have upper bound on Quality Level property
**Describe the bug**
There is no upper bound on the *Quality Level* property in the *DepthOfField* component while DPE is enabled. Exceeding the [0 - 1] bound set on it by default causes the Editor to crash.

This issue occurs only on Linux.

It should be noted that the crash that occurs does not generate any error.log, and Editor.log does not contain any additional information.

**Steps to reproduce**
1. Execute `ed_enableDPE 1` command in the *Console*.
2. Create an entity, add *DepthOfField* and *PostFX Layer* components to it.
3. In the *DepthOfField* component, select the *Camera* entity for the *Camera Entity* property.
4. Enable the *Enable Depth of Field* property.
5. Set the *Quality Level* property above 1.

**Expected behavior**
*Quality Level* cannot be set above 1.

**Actual behavior**
*Quality Level* changes, causing a crash in process.

**Video**

https://github.com/o3de/o3de/assets/86952082/6b8b9a4d-7629-4953-98b2-98a45040b104

**Found in Branch**
Development (c43aa0f)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
c43aa0f0ba9d907f841ac7276bb6389fa26c5cb8

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.2 LTS
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

### PR DESCRIPTION
**Pull request by lumberyard-employee-dm**
### AttributeReader fixes
The AttributeReader had a feature gap that attempting to read an attribute that was of type `long` and `unsigned long` wasn't possible.

This issue is more apparent on Linux where the DPE stores it's attributes in a Dom::Value where it uses the standard C type aliases  of `int64_t` and `uint64_t`

However, while the standard type aliases are always 64-bits across platforms, they are *NOT* the same underlying type.

So on Windows `int64_t` and `uint64_t` are of type `long long` and `unsigned long long` respectively.

However on Linux and Android `int64_t` and `uint64_t` are of type `long` and `unsigned long long` respectively.

#Depth of field setting fixes
Clamped the setting of the Depth of Field Settings m_qualityLevel to [0, 2)

The DepthOfFieldSettings `m_qualityLevel` value is used to index into an array with 2 elements, however the `DepthOfFieldSettings::SetQualityLevel` function did not validate that the value was < 2, therefore a crash occurs when indexing out of bounds of the array.

fixes #16534 

### Explanation of what caused the crash

The underlying issue that caused the crash is that the [DepthOfFieldSettings::SetQualityLevel](https://github.com/o3de/o3de/blob/development/Gems/Atom/Feature/Common/Code/Source/PostProcess/DepthOfField/DepthOfFieldSettings.cpp#L287-L293) function accepted a qualityLevel integer and used that to index into an array of size 2.

However if the quality level value was >=2, it would index out of bounds of the array and cause a crash.
So the fix for the crash was to make sure to clamp the `m_qualityLevel` value to fit within the bounds of the array.

Now the user facing issue is that the user was able to use the IntSlider in the Editor move the slider values above 1 for the quality level.

The reason for this was that the `Min` and `Max` attribute in the Document Property Editor are stored in `Dom::Value` objects.

Now a Dom::Value stored its integer types under the hood as a `int64_t` and `uint64_t`.

However the AZ::AttributeReader only supported reading from an AZ::s64/AZ::u64 which was always `long long` and `unsigned long long` respectively.
On Linux/Android 64-bit, type instead use `long` and `unsigned long` for the `int64_t` and `uint64_t` type aliases and therefore the AttributeReader would failed

## How was this PR tested?

Validated that moving the Int slider for the "Quality Level" field for the Depth Of Field Component in the Editor only allowed for values of 0 and 1 when the DPE was enabled.

### CODE REVIEW

File: Code/Framework/AzCore/AzCore/Utils/Utils.cpp [hunk 1]
```diff
@@ -17,6 +19,57 @@
...
+        }
+    }
+    AZ_CONSOLEFREEFUNC("os_GetEnv", GetEnv, AZ::ConsoleFunctorFlags::DontReplicate,
+        "Queries the OS for an environment variable with the specified name(s).\n"
+        "Each argument is the name of the environment variable to query.\n"
+        "Multiple arguments can be specified and each of their values are output on separate lines.\n"
+        "Usage: os_GetEnv PATH\n"
+        "Usage: os_GetEnv LD_LIBRARY_PATH HOME\n");
+}
+
```
Comment (cgalvan) [inline Code/Framework/AzCore/AzCore/Utils/Utils.cpp:72]: Looks like this snuck in from https://github.com/o3de/o3de/pull/16586.  But I'm OK with it coming along for the ride :)

**Review by cgalvan — APPROVED** [review]

**Review by alexmontAmazon — APPROVED** [review]

File: Code/Framework/AzCore/AzCore/Utils/Utils.cpp (hunk 1 above)
Comment (lumberyard-employee-dm) [reply Code/Framework/AzCore/AzCore/Utils/Utils.cpp:72]: Ahh that is because my branch is based on development

I'll rebase and push new changes only based on stabilization.

File: Gems/Atom/Feature/Common/Code/Source/PostProcess/DepthOfField/DepthOfFieldSettings.cpp [hunk 2]
```diff
@@ -286,10 +286,11 @@ namespace AZ
 
         void DepthOfFieldSettings::SetQualityLevel(uint32_t qualityLevel)
         {
-            m_qualityLevel = qualityLevel;
-            m_sampleRadialDivision2 = DepthOfField::QualitySet[qualityLevel].sampleRadialDivision2;
-            m_sampleRadialDivision4 = DepthOfField::QualitySet[qualityLevel].sampleRadialDivision4;
-            m_sampleRadialDivision8 = DepthOfField::QualitySet[qualityLevel].sampleRadialDivision8;
+            // Clampe quality level to be less than the size of the QualitySet array
```
Comment (moudgils) [inline Gems/Atom/Feature/Common/Code/Source/PostProcess/DepthOfField/DepthOfFieldSettings.cpp:289]: Typo -> Clamp

Comment (lumberyard-employee-dm) [reply Gems/Atom/Feature/Common/Code/Source/PostProcess/DepthOfField/DepthOfFieldSettings.cpp:289]: It's French.

File: Code/Framework/AzCore/AzCore/Utils/Utils.cpp (hunk 1 above)
Comment (lumberyard-employee-dm) [reply Code/Framework/AzCore/AzCore/Utils/Utils.cpp]: It has been rebased on stabilization/2310

**Review by cgalvan — APPROVED** [review]
