### PR TITLE
fix: Do not use dangling ptr for EditorTransform when echap key is hit

### LINKED ISSUE #17264: Entity Outliner: Editor freezes when an entity selection is canceled
**Describe the bug**
The editor freezes when trying to exit from the entity selection mode using the ESC key.

**Steps to reproduce**
1. Select any entity in the Entity Outliner
2. Press the pick icon at the right of the `Parent Entity` field
3. Press ESC to cancel the action

**Expected behavior**
Operation must be canceled and no entity is selected anymore, as in version 2305.

**Actual behavior**
The editor freezes.

**Screenshots**
Enter in entity selection mode:
entity-freeze-1

System error after pressing ESC:
entity-freeze-2

**Found in Branch**
point-release/23101

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
f0c150d75722b3302753972b28d73a8036b70b31

**Device:**
 - Device: PC
 - OS: Linux

### PR DESCRIPTION
**Pull request by guillaume-haerinck**
## What does this PR do?

Fix #17264.

Issue occured because the Action callback for `o3de.action.edit.deselectAll` was capturing a pointer of the current `EditorTransformComponentSelection`. Problem is that this class is destroyed and re-created anytime `PropertyEntityIdCtrl::StartEntityPickMode()` is called, thus the dangling pointer.

The fix proposal is to rely on the EditorTransform event bus, which will call the last valid instance of the class. There might be a better approach to prevent this problem that I'm not aware of.

If this is the way to go, I'll update the PR to add the unit test for the new command.
I believe that I should also update the other action callbacks in this class that are also capturing `this`.

## How was this PR tested?

1. Open a level with some content
2. Select an entity
3. Pick the reparent icon on the transform component
4. Press the "echap" key on your keyboard

image

### CODE REVIEW

**Review by gadams3 — APPROVED** [review]

File: Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp [hunk 1]
```diff
@@ -1728,34 +1728,6 @@ namespace AzToolsFramework
         }
     }
 
-    void EditorTransformComponentSelection::DeselectEntities()
```
Comment (spham-amzn) [inline Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp:1731]: Looks like this method was just moved? Probably better not to move unless needed to make reviews a little clearer, but not a big deal.

**Review by spham-amzn — APPROVED** [review]

File: Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp (hunk 1 above)
Comment (guillaume-haerinck) [reply Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp]: Updated :)
