### PR TITLE
Fixed crash and asserts when heightfield is used without Terrain World

### LINKED ISSUE #7238: Terrain: The Editor crashes when an Axis Aligned Box Shape component is added to an entity with PhysX Heightfield Collider and Terrain Physics Heightfield Collider in a Level without a Terrain World component
**Describe the bug**
Adding an **Axis Aligned Box Shape** component to an entity with **PhysX Heightfield Collider** and T**errain Physics Heightfield Collider** components on a Level without a **Terrain World** component crashes the Editor.

The issue was observed on PC, Linux and macOS versions of the Editor.

For further information please refer to the attached video file and crash logs.

**Prerequisites**

* Terrain Gem is enabled and built for the active project.

**Steps to reproduce**

1. Launch the Editor and create a new level.
2. Create an new entity and add **PhysX Heightfield Collider** and **Terrain Physics Heightfield Collider** components to it.
3. Add a **Axis Aligned Box Shape** component to the entity.

**Expected behavior**
The Editor remains stable.

**Actual behavior**
The Editor crashes.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953456/151554833-f98f8688-8707-4d6a-8b0b-69c8ae8f2568.mp4

**Found in Branch**
Development (e19dc40)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 7 2700X
- GPU: AMD Radeon Pro Duo
- Memory: 16GB

**Additional context**
[error.log](https://github.com/o3de/o3de/files/7958930/error.log)

[Editor.log](https://github.com/o3de/o3de/files/7958934/Editor.log)

[error.zip](https://github.com/o3de/o3de/files/7958937/error.zip)

### LINKED ISSUE #7241: Terrain: The Editor crashes when a Terrain World component is removed from the level entity if an entity with specific terrain components is present in the level
**Describe the bug**
Removing a **Terrain World** component from the _Level_ prefab entity will crash the Editor if an entity with **PhysX Heightfield Collider**, **Terrain Physics Heightfield Collider** and **Axis Aligned Box Shape** components is present in the level.

The issue was observed on PC, Linux and macOS versions of the Editor.

For further information please refer to the attached video file and crash logs.

**Prerequisites**

* Terrain Gem is enabled and built for the active project.

**Steps to reproduce**

1. Launch the Editor and create a new level.
2. Select the _Level_ prefab entity in the Entity Outliner and add a **Terrain World** component to it.
3. Create a new entity and add  **PhysX Heightfield Collider**, **Terrain Physics Heightfield Collider** and **Axis Aligned Box Shape** components to it.
4. Remove a **Terrain World** component from the _Level_ prefab entity.

**Expected behavior**
The Editor remains stable.

**Actual behavior**
The Editor crashes.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953456/151566541-cf1d9dc5-2fa3-4189-8e0a-20dde0507a1a.mp4

**Found in Branch**
Development (e19dc40)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 7 2700X
- GPU: AMD Radeon Pro Duo
- Memory: 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/7959464/Editor.log)

[error.log](https://github.com/o3de/o3de/files/7959465/error.log)

[error.zip](https://github.com/o3de/o3de/files/7959466/error.zip)

### PR DESCRIPTION
**Pull request by SergeyAMZN**
Signed-off-by: Sergey Pereslavtsev <pereslav@amazon.com>
Closes #7238 
Closes #7241

### CODE REVIEW

**Review by cgalvan — APPROVED** [review]

**Review by mbalfour-amzn — APPROVED** [review]

File: Gems/PhysX/Code/Editor/DebugDraw.cpp [hunk 1]
```diff
@@ -694,7 +694,12 @@ namespace PhysX
             const float minYBounds = -(numRows * heightfieldShapeConfig.GetGridResolution().GetY()) / 2.0f;
 
             auto heights = heightfieldShapeConfig.GetSamples();
-            
+
+            if (heights.empty())
+            {
+                return;
+            }
```
Comment (moraaar) [inline Gems/PhysX/Code/Editor/DebugDraw.cpp:701]: nit: This could be moved at the beginning of the function to avoid doing all the previous operations when there are no samples.

**Review by moraaar — APPROVED** [review]
