### PR TITLE
fixed joint crash when no lead entity is selected

### LINKED ISSUE #2474: PhysX Fixed Joint will crash editor if no Lead Entity selected
**Describe the bug**
PhysX Fixed Joint will crash editor if no Lead Entity selected

**To Reproduce**
Add a PhysX Fixed Joint (Other Joints maybe effected with issue as well). 

**Expected behavior**
Will not crash editor

**Screenshots**
Lead_Entity

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel I9-9900k 
 - GPU NVidia RTX
 - Memory 16GB

**Additional context**

### PR DESCRIPTION
**Pull request by amzn-sean**
Fixes #2474 
Also fixed joint global constraints when no lead entity was selected
Added tests for global constraints on ball and hinge joints.

Signed-off-by: amzn-sean <75276488+amzn-sean@users.noreply.github.com>

### CODE REVIEW

File: Gems/PhysX/Code/Source/BallJointComponent.cpp [hunk 1]
```diff
@@ -46,11 +46,20 @@ namespace PhysX
...
         }
 
+        // if there is no lead body, this will be a constraint of the followers global position, so use invalid body handle.
+        AzPhysics::SimulatedBodyHandle parentHandle = AzPhysics::InvalidSimulatedBodyHandle;
+        if (leadFollowerInfo.m_leadBody != nullptr)
+        {
+            parentHandle = leadFollowerInfo.m_leadBody->m_bodyHandle;
+        }
+        AZ_Warning("PhysX", parentHandle == AzPhysics::InvalidSimulatedBodyHandle, "Entity [%s] Ball Joint component missing lead entity.", GetEntity()->GetName().c_str());
+
```
Comment (moraaar) [inline Gems/PhysX/Code/Source/BallJointComponent.cpp:62]: This chunk of code is repeated multiple times. Maybe it could be moved to a function.

File: Gems/PhysX/Code/Tests/PhysXJointsTest.cpp [hunk 2]
```diff
@@ -209,6 +209,60 @@ namespace PhysX
...
+
+        auto jointLimits = AZStd::make_shared<JointLimitProperties>();
+        jointLimits->m_isLimited = false;
+
+        auto followerEntity = AddBodyColliderEntity<BallJointComponent>(
+            m_testSceneHandle, followerPosition, followerInitialLinearVelocity, jointConfig, nullptr, jointLimits);
+
+        const AZ::Vector3 followerEndPosition = RunJointTest(m_defaultScene, followerEntity->GetId());
+
+        EXPECT_TRUE(followerEndPosition.GetZ() > followerPosition.GetZ());
```
Comment (moraaar) [inline Gems/PhysX/Code/Tests/PhysXJointsTest.cpp:236]: `EXPECT_GT` could be used instead and will provide more information on failure.

Same in the other unit test.

**Review by moraaar — APPROVED** [review]

File: Gems/PhysX/Code/Source/BallJointComponent.cpp (hunk 1 above)
Comment (amzn-sean) [reply Gems/PhysX/Code/Source/BallJointComponent.cpp:62]: i'll look into this in another PR there is more room for de-duplication that could be done with the joints code.

File: Gems/PhysX/Code/Tests/PhysXJointsTest.cpp [hunk 3]
```diff
@@ -206,7 +206,61 @@ namespace PhysX
...
+            m_testSceneHandle, followerPosition, followerInitialLinearVelocity, jointConfig, nullptr, jointLimits);
+
+        const AZ::Vector3 followerEndPosition = RunJointTest(m_defaultScene, followerEntity->GetId());
+
+        EXPECT_GT(followerEndPosition.GetZ(), followerPosition.GetZ());
+    }
+
+    TEST_F(PhysXJointsTest, Joint_HingeJoint_GlobalConstraint)
+    {
+        // Place lead on top of follower, tie them together with ball joint and send the follower moving sideways in the X and Y directions.
```
Comment (greerdv) [inline Gems/PhysX/Code/Tests/PhysXJointsTest.cpp:241]: Similar comments about the wording of the comments.

**Review by greerdv — APPROVED** [review]

File: Gems/PhysX/Code/Source/BallJointComponent.cpp [hunk 4]
```diff
@@ -46,11 +46,20 @@ namespace PhysX
...
             return;
         }
 
+        // if there is no lead body, this will be a constraint of the followers global position, so use invalid body handle.
+        AzPhysics::SimulatedBodyHandle parentHandle = AzPhysics::InvalidSimulatedBodyHandle;
+        if (leadFollowerInfo.m_leadBody != nullptr)
+        {
+            parentHandle = leadFollowerInfo.m_leadBody->m_bodyHandle;
+        }
+        AZ_Warning("PhysX", parentHandle == AzPhysics::InvalidSimulatedBodyHandle, "Entity [%s] Ball Joint component missing lead entity.", GetEntity()->GetName().c_str());
```
[the remark this answers is not in the document]
Comment (amzn-sean) [reply Gems/PhysX/Code/Source/BallJointComponent.cpp:61]: good point, i'll downgrade this log and make the message a bit clearer

File: Gems/PhysX/Code/Tests/PhysXJointsTest.cpp (hunk 3 above)
Comment (amzn-sean) [reply Gems/PhysX/Code/Tests/PhysXJointsTest.cpp:241]: copy pasta from the other tests. i'll clean this up
