### PR TITLE
Fix Client Connecting to Server During Server Level Load

### LINKED ISSUE #17180: Multiplayer Simulation Broken if Server and Game are Launched Simultaneously
If a server is launched and a game connects to it around the same time, the game won't get any network updates.

I first noticed the problem while testing GameLift Flexmatch; oftentimes the 1st client to trigger a new game sessions fail to join a server's network simulation. However, once a player was into the match, other players could join and leave without problems. 

**Steps to reproduce**
1. Run the server and game at the same time
Example Powershell command to start a headless server in another terminal, and then launch/connect a game client:
Set Sleep -Seconds to 0 in order to repro the bug
`
Start-Process wt -ArgumentList "c:\prj\o3de-multiplayersample\build\windows\bin\profile\MultiplayerSample.HeadlessServerLauncher.exe --rhi=null -NullRenderer --console-command-file=launch_server.cfg --sv_terminateOnPlayerExit=false -bg_ConnectToAssetProcessor=0"; Start-Sleep -Seconds 10; .\build\windows\bin\profile\MultiplayerSample.GameLauncher.exe --connect -bg_ConnectToAssetProcessor=0
`

**Expected behavior**
Ideally, game connects and is able to play the game

**Actual behavior**
Game connects, but fails to receive any valid network information. No player is loaded. Game hangs. 

image

**Found in Branch**
development

5c46d85984eb3e8f048b4768dbaed926c07f65bc
Dec 2 2023

### PR DESCRIPTION
**Pull request by AMZN-Gene**
Allows players to connect to a server during a server level load. 
The server will wait to spawn the player once the level entities are finished activating
Fixes #17180

## How was this PR tested?
Check that #17180 is resolved
Run client-server mode and ensure player still spawns

### CODE REVIEW

**Review by gadams3 — APPROVED** [review]

File: Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp [hunk 1]
```diff
@@ -748,6 +748,17 @@ namespace Multiplayer
     {
         reinterpret_cast<ServerToClientConnectionData*>(connection->GetUserData())->SetProviderTicket(packet.GetTicket().c_str());
 
+        const char* levelName = AZ::Interface<AzFramework::ILevelSystemLifecycle>::Get()->GetCurrentLevelName();
+        if (!levelName || strlen(levelName) == 0)
```
Comment (spham-amzn) [inline Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp:752]: You probably don't even need `strlen` if you dont care about trimming or spaces:
```suggestion
        if (!levelName || *levelName == '\0')
```

**Review by spham-amzn — APPROVED** [review]
