### PR TITLE
Type name generation updates

### LINKED ISSUE #9488: AZStd::tuple has inconsistent and abbreviated names generated in BehaviorContext
**Describe the bug**
When AZStd::pair<int, float> is reflected to the behavior context, it gets the name `AZStd::pair<int, float>`. However, when `AZStd::tuple<int, float>` is reflect to the behavior context, it gets the name `tuple<int float >`. It is missing the AZStd:: prefix, commas between the template parameters, and has a trailing space after the last template parameter.

Also, if the name becomes longer than 128 characters, the name gets truncated, which makes construction of different types of tuples that only vary at the final parameters impossible through the BehaviorContext.

**Steps to reproduce**
1. Call `serializeContext.RegisterGenericType<AZStd::tuple<int, float>>();`
2. From Python, call `test_tuple = azlmbr.object.create('AZStd::tuple<int, float>')`

**Expected behavior**
The create call produces a valid tuple.

**Actual behavior**
No tuple is produced because the name is incorrect. You need to instead use:
`test_tuple = azlmbr.object.create('tuple<int float >')`

### PR DESCRIPTION
**Pull request by lumberyard-employee-dm**
Updated the type name generation in AzTypeInfo to be consistent for aggregate types such as tuple.
Updated the AzTypeInfo::Name() function to be constexpr, as well as the TYPEINFO_Name() function that gets added by the AZ_TYPE_INFO macro.
Updated the TypeInfo names of AZStd container types to be consistent across the board.

Removed parentheses around type names.

resolves #9488

The StdoutStream now overrides the GetFilename function to return a filename of "" instead of "".
Added a ConvertToAbsolutePath overload which returns a boolean and accepts an AZ::IO::FixedMaxPath output parameter by reference.

### CODE REVIEW

File: Gems/Maestro/Code/Source/Cinematics/AnimSplineTrack.h [hunk 1]
```diff
@@ -26,7 +26,24 @@ class TAnimSplineTrack
...
-    AZ_RTTI((TAnimSplineTrack, "{6D72D5F6-61A7-43D4-9104-8F7DCCC19E10}", Vec2), IAnimTrack)
+    AZ_RTTI((TAnimSplineTrack, "{6D72D5F6-61A7-43D4-9104-8F7DCCC19E10}", ValueType), IAnimTrack);
+
+    static constexpr void DeprecatedTypeNameVisitor(
+        const AZ::DeprecatedTypeNameCallback& visitCallback)
+    {
+        // TAnimSplineTrack previously restricted the typename to 128 bytes
+        AZStd::array<char, 128> deprecatedName{};
+
+        // The old TAnimSplineTrack TypeName mistkanely used Vec2 as the template parameter and not ValueType
```
Comment (mbalfour-amzn) [inline Gems/Maestro/Code/Source/Cinematics/AnimSplineTrack.h:37]: "mistkanely" -> "mistakenly"

**Review by mbalfour-amzn — APPROVED** [review]
This is magical and beautiful, thank you for doing this!

File: Gems/Maestro/Code/Source/Cinematics/AnimSplineTrack.h (hunk 1 above)
Comment (lumberyard-employee-dm) [reply Gems/Maestro/Code/Source/Cinematics/AnimSplineTrack.h:37]: Will fix
