### PR TITLE
Fix ChangeValidate functions not triggering in Property Editors

### LINKED ISSUE #16961: DPE Inspector: ChangeNotify events aren't being triggered
**Describe the bug**
The ChangeNotify events don't seem to be triggered when editing values in the DPE Inspector.

**Steps to reproduce**
1. Create a level.
2. Add a Terrain World Component to the Level Entity.
3. Change the Min Height to 2048.

**Expected behavior**
A Min Height that is greater than the Max Height should be disallowed (see TerrainWorldComponent.cpp).

**Actual behavior**
Value is accepted with no validation.

**Found in Branch**
point-release/23101

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
426a5f2c4a4312891f20bcc2cf229373307f3204

**Desktop/Device (please complete the following information):**
PC / Windows

### PR DESCRIPTION
**Pull request by lumberyard-employee-dm**
Both the Reflected Property Editor and Document Property Editor weren't not triggering ChangeValidate events.

For the Reflected Property Editor, the reason why it wasn't triggering ChangeValidate events was that the
`PropertyRowWidget::HandleChangeValidateAttribute` function incorrectly casted the ChangeValidate attribute function to a function that returned a `bool` type. However all of the Change Validate functions return the type of `AZ::Outcome<void, AZStd::string>`.

The Document Property Editor issue was more involved.

First the signature of the ChangeValidate functions had the form of `AZ::Outcome<void, AZStd::string>(C::*)(void*, const Uuid&)`.

Now the way the DomUtils API works now when it comes to storing non-builtin types such as Uuids, it uses Json Serialization to map a Uuid to an `AZ::Dom::Value`. Now the Json Serializer for a Uuid writes it out as just a string.

Now when the DocumentSchema tries to invoke the ChangeValidate attribute callback, it tries to convert the Dom::Value into the **exact** type of the function signature.

Now as the Dom::Value is stores a string of a Uuid such as "{EA2C3E90-AFBE-44d4-A90D-FAAF79BAF93D}" it would use the Uuid Json Deserializer to convert the string into an `AZ::Uuid`.

However the DomUtils ValueToType uses special case logic when it tries to convert the Dom Value back it a C++ type which is a reference. In this case as the second parameter to ChangeValidate is a `const Uuid&` it triggers the special case logic.

What that logic does, is instead of trying to use Json Serialization system to "deserialize" the Uuid string back into an AZ::Uuid it tries to return a reference to an AZ::Uuid stored in the Dom Value.

Now because Uuid uses Json Serialization, it is not directly stored in the Dom::Value as a type, so reference for it cannot be retrieved. Due to this the conversion from the Dom Value to `const Uuid&` fails.

The fix for the issue is to take the `ChangeValidate` function that gets specified in the `EditContext::Attribute` function and wrap it in a lambda with the signature of
`AZ::Outcome<void,AZStd::string>(C*, void*, Uuid)` where the Uuid is accepted by value.

In order to support calling the lambda using the DomInvoke API, the AttributeInvocable class needs to be able to check if the object it is storing can be called in a member function like manner. As the AttributeInvocable can store either a raw function pointer, member function pointer, member data pointer, or a C++ type with an `operator()`, a `GetPotentialClassType` function has been added to return the class type if the AttributeInvocable is storing a member function pointer or a member data pointer. Or if the AttributeInvocable is storing a function object with an `operator()` it returns the type of the first argument to that function if that argument is a C++ class.

fixes #16961

## How was this PR tested?

Verified that the ChangeValidate function was triggering for the TerrainWorldComponent min and max height field when the Document Property Editor is enabled as well as when the Document Property Editor was invoked.

Updated the AttributeDomInteropTests to make sure they pass with the changes made to the `AZ::Attribute` classes in ReflectContext.h

RPE Change Validate
DPE Change Validate

### CODE REVIEW

File: Code/Framework/AzCore/AzCore/RTTI/ReflectContext.h [hunk 1]
```diff
@@ -601,21 +629,114 @@ namespace AZ
...
+                {
+                    // Grab the first argument and check if it the class type
+                    using FirstArgType = AZStd::function_traits_get_arg_t<Invocable, 0>;
+                    using CandidateClassType = AZStd::remove_pointer_t<AZStd::remove_cvref_t<FirstArgType>>;
+                    if constexpr (AZStd::is_class_v<CandidateClassType>)
+                    {
+                        // Now check if the instanceObject is derived from the first argument of the function object
+                        // If so, it will be assumed to be the instance field in the created Dom::Value
+                        auto rttiHelper = AZ::GetRttiHelper<CandidateClassType>();
+                        if (void* castAddress = rttiHelper != nullptr ? rttiHelper->Cast(instanceObject.m_address, instanceObject.m_typeId) : nullptr;
```
Comment (gadams3) [inline Code/Framework/AzCore/AzCore/RTTI/ReflectContext.h:728]: Just for readability,, I recommend wrapping all occurrences of this check in parentheses or removing != nullptr

```suggestion
                        if (void* castAddress = (rttiHelper != nullptr0 ? rttiHelper->Cast(instanceObject.m_address, instanceObject.m_typeId) : nullptr;
```

**Review by gadams3 — APPROVED** [review]

File: Code/Framework/AzCore/AzCore/RTTI/ReflectContext.h (hunk 1 above)
Comment (lumberyard-employee-dm) [reply Code/Framework/AzCore/AzCore/RTTI/ReflectContext.h:728]: Noted, but I think the readability in this case is subjective.

**Review by alexmontAmazon — COMMENTED** [review]
This seems great, but are we going to have the same problem with this attribute?
CallbackAttributeDefinition<void(const Dom::Value&, ValueChangeType)>("OnChanged");
If so, could you include the special case for that handler in here as well? If this has the chance of happening again, could we possibly compiler-enforce CallbackAttributeDefinitions to not take functions with reference parameters?

**Comment by lumberyard-employee-dm** [comment]
> This seems great, but are we going to have the same problem with this attribute? CallbackAttributeDefinition<void(const Dom::Value&, ValueChangeType)>("OnChanged"); If so, could you include the special case for that handler in here as well? If this has the chance of happening again, could we possibly compiler-enforce CallbackAttributeDefinitions to not take functions with reference parameters? I'm not sure if that's possible, but if anyone could do it, it would be you...

There is not a problem with `const Dom::Value&` because it is has a specialization in the DomWrapperType type alias in DomUtils.h to use it directly as is: https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/DOM/DomUtils.h#L90-L103

The DomUtils [ValueToType](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/DOM/DomUtils.h#L272-L276) function is special cased to return a copy of the Dom::Value

**Review by alexmontAmazon — APPROVED** [review]
I'm still a bit concerned about new developers adding callbacks with reference parameters and not realizing that they have to special case them like ChangeValidate, but this a great improvement either way...
