### PR TITLE
connect collider and rigid body components to visibility bounds

### LINKED ISSUE #2466: PhysX Force Region disappears depending on camera orientation
PhysX Force Region disappears depending on camera orientation

**To Reproduce**
ForceFields_lq

**Expected behavior**
Force field is always visible and just gets skipped to render when the debug visualization is fully out of the view frustum

### PR DESCRIPTION
**Pull request by greerdv**
Signed-off-by: greerdv <greerdv@amazon.com>

## What does this PR do?
Connects PhysX Collider and PhysX Rigid Body components to visibility bounds bus. Fixes #2466

## How was this PR tested?
Tested in editor, with variety of different collider geometries, position and rotation offsets, transform rotation, translation and scale, with and without non-uniform scale, single and multiple colliders, with and without rigid body component.

### CODE REVIEW

File: Gems/PhysX/Code/Source/EditorColliderComponent.cpp [hunk 1]
```diff
@@ -1570,6 +1572,22 @@ namespace PhysX
         m_shapeConfiguration.m_cylinder.m_configuration = Utils::CreatePxCookedMeshConfiguration(samplePoints, scale).value();
     }
 
+    AZ::Aabb EditorColliderComponent::GetWorldBounds()
+    {
+        return GetAabb();
```
Comment (SergeyAMZN) [inline Gems/PhysX/Code/Source/EditorColliderComponent.cpp:1577]: Do we need to have `IsValid()` check for the world bounds like we do in `GetLocalBounds` or the visibility system is OK about dealing with invalid AABBs?

**Review by SergeyAMZN — APPROVED** [review]

**Review by hultonha — APPROVED** [review]
Looks great! Thanks for adding this @greerdv 👍

**Review by moraaar — APPROVED** [review]

File: Gems/PhysX/Code/Source/EditorColliderComponent.cpp (hunk 1 above)
Comment (greerdv) [reply Gems/PhysX/Code/Source/EditorColliderComponent.cpp:1577]: The visibility system is fine with invalid AABBs. The reason I put the IsValid check in the other place was just in case anything weird could happen if you inverse transform a null AABB.
