### PR TITLE
Fixes a crash on AP shutdown

### LINKED ISSUE #13124: Bug Report - AP Crash on shutdown
**Describe the bug**
AP crashes on shutdown on rare occasions in response to a file monitor event

**Steps to reproduce**
Unknown, beyond running AP and shutting it down (ctrl+Q) while having a debugger attached

**Expected behavior**
AP shuts down cleanly

**Actual behavior**
On rare occasions, AP crashes on shutdown with the following callstack:

```
 	Qt5Core.dll!QObject::thread() Line 1487	C++
 	Qt5Core.dll!QMetaObject::invokeMethodImpl(QObject * object, QtPrivate::QSlotObjectBase * slot, Qt::ConnectionType type, void * ret) Line 1532	C++
 	[Inline Frame] AssetProcessor.exe!QMetaObject::invokeMethod(QObject *) Line 525	C++
>	AssetProcessor.exe!`ApplicationManagerBase::InitFileMonitor'::`10'::<lambda_2>::operator()(QString path) Line 484	C++
 	[Inline Frame] AssetProcessor.exe!QtPrivate::FunctorCall<QtPrivate::IndexesList<0>,QtPrivate::List<QString>,void,`ApplicationManagerBase::InitFileMonitor'::`10'::<lambda_2>>::call(ApplicationManagerBase::InitFileMonitor::__l10::<lambda_2> &) Line 146	C++
 	[Inline Frame] AssetProcessor.exe!QtPrivate::Functor<`ApplicationManagerBase::InitFileMonitor'::`10'::<lambda_2>,1>::call(ApplicationManagerBase::InitFileMonitor::__l10::<lambda_2> &) Line 256	C++
 	AssetProcessor.exe!QtPrivate::QFunctorSlotObject<`ApplicationManagerBase::InitFileMonitor'::`10'::<lambda_2>,1,QtPrivate::List<QString>,void>::impl(int which, QtPrivate::QSlotObjectBase * this_, QObject * r, void * * a, bool * ret) Line 449	C++
 	[Inline Frame] Qt5Core.dll!QtPrivate::QSlotObjectBase::call(QObject *) Line 398	C++
 	Qt5Core.dll!doActivate<0>(QObject * sender, int signal_index, void * * argv) Line 3886	C++
 	AssetProcessor.exe!FileWatcher::fileModified(QString _t1) Line 204	C++
 	[Inline Frame] AssetProcessor.exe!AZStd::Internal::INVOKE(void(FileWatcher::*)(QString) &) Line 177	C++
 	[Inline Frame] AssetProcessor.exe!AZStd::invoke(void(FileWatcher::*)(QString) &) Line 54	C++
 	[Inline Frame] AssetProcessor.exe!FileWatcher::{ctor}::__l2::<lambda_1>::()::__l2::<lambda_1>::operator()(QString path) Line 72	C++
 	[Inline Frame] AssetProcessor.exe!QtPrivate::FunctorCall<QtPrivate::IndexesList<0>,QtPrivate::List<QString>,void,``FileWatcher::FileWatcher'::`2'::<lambda_1>::operator()<void (__cdecl FileWatcher::*)(QString)>'::`2'::<lambda_1>>::call(FileWatcher::{ctor}::__l2::<lambda_1>::()::__l2::<lambda_1> &) Line 146	C++
 	[Inline Frame] AssetProcessor.exe!QtPrivate::Functor<``FileWatcher::FileWatcher'::`2'::<lambda_1>::operator()<void (__cdecl FileWatcher::*)(QString)>'::`2'::<lambda_1>,1>::call(FileWatcher::{ctor}::__l2::<lambda_1>::()::__l2::<lambda_1> &) Line 256	C++
 	AssetProcessor.exe!QtPrivate::QFunctorSlotObject<``FileWatcher::FileWatcher'::`2'::<lambda_1>::operator()<void (__cdecl FileWatcher::*)(QString)>'::`2'::<lambda_1>,1,QtPrivate::List<QString>,void>::impl(int which, QtPrivate::QSlotObjectBase * this_, QObject * r, void * * a, bool * ret) Line 443	C++
 	[Inline Frame] Qt5Core.dll!QtPrivate::QSlotObjectBase::call(QObject *) Line 398	C++
 	Qt5Core.dll!QMetaCallEvent::placeMetaCall(QObject * object) Line 622	C++
 	Qt5Core.dll!QObject::event(QEvent * e) Line 1314	C++
 	Qt5Widgets.dll!QApplicationPrivate::notify_helper(QObject * receiver, QEvent * e) Line 3632	C++
 	Qt5Widgets.dll!QApplication::notify(QObject * receiver, QEvent * e) Line 3584	C++
 	Qt5Core.dll!QCoreApplication::notifyInternal2(QObject * receiver, QEvent * event) Line 1063	C++
 	[Inline Frame] Qt5Core.dll!QCoreApplication::sendEvent(QObject *) Line 1458	C++
 	Qt5Core.dll!QCoreApplicationPrivate::sendPostedEvents(QObject * receiver, int event_type, QThreadData * data) Line 1817	C++
 	qwindows.dll!00007ffca7c537bf()	Unknown
 	Qt5Core.dll!QEventDispatcherWin32::processEvents(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 530	C++
 	qwindows.dll!00007ffca7c53799()	Unknown
 	[Inline Frame] Qt5Core.dll!QEventLoop::processEvents(QFlags<enum QEventLoop::ProcessEventsFlag>) Line 139	C++
 	Qt5Core.dll!QEventLoop::exec(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 232	C++
 	Qt5Core.dll!QCoreApplication::exec() Line 1371	C++
 	AssetProcessor.exe!GUIApplicationManager::Run() Line 349	C++
 	AssetProcessor.exe!main(int argc, char * * argv) Line 37	C++
 	AssetProcessor.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 97	C++
 	[Inline Frame] AssetProcessor.exe!invoke_main() Line 102	C++
 	AssetProcessor.exe!__scrt_common_main_seh() Line 288	C++
 	kernel32.dll!00007ffd04cc74b4()	Unknown
 	ntdll.dll!00007ffd05b626a1()	Unknown

```

The crash occurs somewhere in this block:

```
[[maybe_unused]] bool result = QMetaObject::invokeMethod(
m_assetProcessorManager,
[this, path]
{
    m_assetProcessorManager->AssessModifiedFile(path);
},
Qt::QueuedConnection);
```

With this error:

`Exception thrown at 0x00007FFCA5C6C468 (Qt5Core.dll) in AssetProcessor.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.`

**Found in Branch**
development

**Additional context**
The last time this occurred, the file which caused it was `D:\LyGit\o3de\AutomatedTesting\user\Metrics\core_metrics.AssetBuilder.profile.32464.json`.  AP was idle before shutting down.

### PR DESCRIPTION
**Pull request by lawsonamzn**
## What does this PR do?
fixes #13124
The file monitor is now destroyed up front during shutdown so that it can no longer generate extra events during shutdown.

## How was this PR tested?

Tested while the crash was active.  It no longer crashes.

Signed-off-by: lawsonamzn <70027408+lawsonamzn@users.noreply.github.com>

### CODE REVIEW

**Comment by lawsonamzn** [comment]
Note that this fix does not stop files from being opened or modified during shutdown - it just makes the AP not crash if that occurs.

**Review by dtamkin1 — APPROVED** [review]

**Review by lumberyard-employee-dm — APPROVED** [review]

File: Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp [hunk 1]
```diff
@@ -894,6 +894,10 @@ void ApplicationManagerBase::Destroy()
     delete m_assetRequestHandler;
     m_assetRequestHandler = nullptr;
 
+    // Destroy file monitor early so now new events get generated to propogate through
```
Comment (lumberyard-employee-dm) [inline Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp:897]: nitpick: typo: now -> no, propogate -> propagate
```suggestion
    // Destroy file monitor early so no new events get generated to propagate through
```

**Review by AMZN-stankowi — APPROVED** [review]

File: Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp (hunk 1 above)
Comment (lawsonamzn) [reply Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp:897]: whoops!  I'll fix this typo

**Review by amzn-mike — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]
