### PR TITLE
EMotion FX: Deleting a corresponding anim graph when a Reference node is open crashes the Editor

### LINKED ISSUE #3883: EMotion FX: Deleting a corresponding anim graph when a Reference node is open crashes the Editor
**Describe the bug**
It has been noticed that deleting or changing the assigned anim graph when the **Reference** node is open crashes the Editor.

**To Reproduce**
1. Open the **Animation Editor**.
2. Create an anim graph.
3. Add a **Reference** node to it.
4. Assign the **sample1.animgraph** file to the node.
5. Open the **Reference** node.
6. In the **Attributes** pane, delete the assigned anim graph.

**Expected behavior**
The anim graph cannot be deleted when the **Reference** node is open or the anim graph preview is closed afterwards.
The Editor remain stable.

**Call stack trace:**
 ```
	0000000000000000()	Unknown
>	EMotionFX.Editor.dll!EMStudio::AnimGraphModel::data(const QModelIndex & index, int role) Line 377	C++
 	[External Code]	
 	EMotionFX.Editor.dll!EMStudio::AnimGraphItemDelegate::sizeHint(const QStyleOptionViewItem & option, const QModelIndex & index) Line 62	C++
 	[External Code]	
 	EMotionFX.Editor.dll!EMStudio::AnimGraphModel::Edited(EMotionFX::AnimGraphObject * animGraphObject, const QVector<int> & roles) Line 1394	C++
 	EMotionFX.Editor.dll!EMStudio::AnimGraphModel::OnSyncVisualObject(EMotionFX::AnimGraphObject * object) Line 864	C++
 	[Inline Frame] EMotionFX.Editor.dll!AZStd::Internal::INVOKE(void(EMotionFX::AnimGraphNotifications::*)(EMotionFX::AnimGraphObject *) &) Line 177	C++
 	[Inline Frame] EMotionFX.Editor.dll!AZStd::invoke(void(EMotionFX::AnimGraphNotifications::*)(EMotionFX::AnimGraphObject *) &) Line 38	C++
 	[Inline Frame] EMotionFX.Editor.dll!AZ::EBusEventProcessingPolicy::Call(void(EMotionFX::AnimGraphNotifications::*)(EMotionFX::AnimGraphObject *) &) Line 446	C++
 	EMotionFX.Editor.dll!AZ::Internal::EBusContainer<EMotionFX::AnimGraphNotifications,EMotionFX::AnimGraphNotifications,0,1>::Dispatcher<AZ::EBus<EMotionFX::AnimGraphNotifications,EMotionFX::AnimGraphNotifications>>::Broadcast<void (__cdecl EMotionFX::AnimGraphNotifications::*)(EMotionFX::AnimGraphObject *),EMotionFX::AnimGraphObject *>(void(EMotionFX::AnimGraphNotifications::*)(EMotionFX::AnimGraphObject *) && func, EMotionFX::AnimGraphObject * && <args_0>) Line 1360	C++
 	[Inline Frame] EMotionFX.Editor.dll!EMotionFX::AnimGraphObject::SyncVisualObject() Line 248	C++
 	EMotionFX.Editor.dll!EMotionFX::AnimGraphNode::SetNodeInfo(const AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator> & info) Line 2339	C++
 	EMotionFX.Editor.dll!EMotionFX::AnimGraphReferenceNode::OnAnimGraphAssetReady() Line 818	C++
 	EMotionFX.Editor.dll!EMotionFX::AnimGraphReferenceNode::LoadAnimGraphAsset() Line 709	C++
 	EMotionFX.Editor.dll!AzToolsFramework::PropertyRowWidget::DoPropertyNotify(unsigned __int64 optionalIndex) Line 1276	C++
 	EMotionFX.Editor.dll!AzToolsFramework::ReflectedPropertyEditor::Impl::RequestWrite(QWidget * editorGUI) Line 1450	C++
 	[Inline Frame] EditorLib.dll!AZStd::Internal::INVOKE(void(AzToolsFramework::PropertyEditorGUIMessages::*)(QWidget *) &) Line 177	C++
 	[Inline Frame] EditorLib.dll!AZStd::invoke(void(AzToolsFramework::PropertyEditorGUIMessages::*)(QWidget *) &) Line 38	C++
 	[Inline Frame] EditorLib.dll!AZ::EBusEventProcessingPolicy::Call(void(AzToolsFramework::PropertyEditorGUIMessages::*)(QWidget *) &) Line 446	C++
 	EditorLib.dll!AZ::Internal::EBusContainer<AzToolsFramework::PropertyEditorGUIMessages,AzToolsFramework::PropertyEditorGUIMessages,0,1>::Dispatcher<AZ::EBus<AzToolsFramework::PropertyEditorGUIMessages,AzToolsFramework::PropertyEditorGUIMessages>>::Broadcast<void (__cdecl AzToolsFramework::PropertyEditorGUIMessages::*)(QWidget *),AzToolsFramework::PropertyAssetCtrl * const &>(void(AzToolsFramework::PropertyEditorGUIMessages::*)(QWidget *) && func, AzToolsFramework::PropertyAssetCtrl * const & <args_0>) Line 1360	C++
 	[Inline Frame] EditorLib.dll!MotionPropertyWidgetHandler::CreateGUI::__l2::<lambda_1>::operator()(AZ::Data::AssetId) Line 22	C++
 	[Inline Frame] EditorLib.dll!QtPrivate::FunctorCall<QtPrivate::IndexesList<0>,QtPrivate::List<AZ::Data::AssetId>,void,`MotionPropertyWidgetHandler::CreateGUI'::`2'::<lambda_1>>::call(MotionPropertyWidgetHandler::CreateGUI::__l2::<lambda_1> &) Line 146	C++
 	[Inline Frame] EditorLib.dll!QtPrivate::Functor<`MotionPropertyWidgetHandler::CreateGUI'::`2'::<lambda_1>,1>::call(MotionPropertyWidgetHandler::CreateGUI::__l2::<lambda_1> & f, void *) Line 256	C++
 	EditorLib.dll!QtPrivate::QFunctorSlotObject<`MotionPropertyWidgetHandler::CreateGUI'::`2'::<lambda_1>,1,QtPrivate::List<AZ::Data::AssetId>,void>::impl(int which, QtPrivate::QSlotObjectBase * this_, QObject * r, void * * a, bool * ret) Line 443	C++
 	[External Code]	
 	[Inline Frame] EditorLib.dll!AzToolsFramework::PropertyAssetCtrl::OnAssetIDChanged(AZ::Data::AssetId) Line 351	C++
 	EditorLib.dll!AzToolsFramework::PropertyAssetCtrl::SetSelectedAssetID(const AZ::Data::AssetId & newID) Line 851	C++
 	EditorLib.dll!AzToolsFramework::PropertyAssetCtrl::ClearAssetInternal() Line 592	C++
 	EditorLib.dll!AzToolsFramework::PropertyAssetCtrl::OnClearButtonClicked() Line 813	C++
 	[External Code]	
 	EditorLib.dll!CryEditMain(int argc, char * * argv) Line 4123	C++
 	[Inline Frame] Editor.exe!AZStd::Internal::INVOKE(int(*)(int, char * *) &) Line 208	C++
 	[Inline Frame] Editor.exe!AZStd::invoke(int(*)(int, char * *) &) Line 38	C++
 	Editor.exe!main(int argc, char * * argv) Line 32	C++
 	Editor.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 97	C++
 	[External Code]	
```
**Desktop/Device:**
**Device:** PC
**OS:** Windows
**Version:** 10
**CPU:** Intel I5-9600k
**GPU:** RTX 2060
**Memory:** 16GB
**Additional context**

https://user-images.githubusercontent.com/86952009/131824550-118be071-8e0a-43bf-aa33-7c1104d36ccb.mp4

[dump.zip](https://github.com/o3de/o3de/files/7098024/dump.zip)
[Editor.log](https://github.com/o3de/o3de/files/7098025/Editor.log)
[error.log](https://github.com/o3de/o3de/files/7098031/error.log)

### PR DESCRIPTION
**Pull request by amzn-jillich**
Resolves #3883

Signed-off-by: Benjamin Jillich <jillich@amazon.com>

### CODE REVIEW

File: Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphReferenceNode.cpp [hunk 1]
```diff
@@ -644,6 +644,7 @@ namespace EMotionFX
     {
         ReleaseAnimGraphInstances();
 
+        AnimGraphNotificationBus::Broadcast(&AnimGraphNotificationBus::Events::OnReferenceAnimGraphAboutToBeChanged, this);
```
Comment (amzn-rhhong) [inline Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphReferenceNode.cpp:647]: Shouldn't this be called before ReleaseAnimGraphInstances()?
Look at the OnAssetReady() and OnAssetReload(), it seems like the AboutToBeChanged is fired before.

**Review by amzn-rhhong — CHANGES_REQUESTED** [review]
OnReferenceAnimGraphAboutToBeChanged i think should be called before ReleaseInstances. Please check and verify.

File: Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphReferenceNode.cpp (hunk 1 above)
Comment (amzn-jillich) [reply Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphReferenceNode.cpp]: Good call, changed.

**Review by amzn-rhhong — APPROVED** [review]

**Review by lsemp3d — APPROVED** [review]
