### PR TITLE
Fixed segfault caused by resizing a non-existent tab

### LINKED ISSUE #16410: Bug Report - Random Segfault
**Describe the bug**
After all the assets get processed, O3DE crashes with a segfault.

**Required assets**
This was happening to me when trying to run the new Robotec ROSCon demo:
https://github.com/RobotecAI/ROSCon2023Demo

**Steps to reproduce**
Clone the repository, follow the build guide from it, run the project.

**Expected behavior**
The project opens.

**Actual behavior**
A segfault.

Segfault

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
e6f25478821875375f209b79cd2cbc1f69829b93
I have also had this happen on various different commits

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Ubuntu
 - Version 22.04.2 lts
 - CPU 12th Gen Intel® Core™ i5-12500H × 16
 - GPU NVIDIA GeForce RTX 4060 Laptop GPU
 - Memory 64GiB

**Additional context**
This issue is solved by this PR:
https://github.com/o3de/o3de/pull/16409

### PR DESCRIPTION
**Pull request by Antoni-Robotec**
In line 348, ResizeTabs is connected to the function currentChanged.
However, currentChanged returns -1 in case there is no new current widget:
https://doc.qt.io/qt-5/qtabwidget.html#currentChanged
This will cause a segfault, as the function ResizeTabs was not prepared to handle this case. This PR fixes that.

Issue:
resolves #16410

### CODE REVIEW

File: Code/Editor/Plugins/ProjectSettingsTool/ProjectSettingsToolWindow.cpp [hunk 1]
```diff
@@ -364,6 +364,12 @@ namespace ProjectSettingsTool
             }
         }
 
+        if (index == -1)
+        {
+            // If there is no current tab, return
+            return;
+        }
+
```
Comment (cgalvan) [inline Code/Editor/Plugins/ProjectSettingsTool/ProjectSettingsToolWindow.cpp:372]: Should this logic moved to the top of `ResizeTabs`, or do we want the tabs to be given the `Ignored` size policy when no tabs are selected?

Comment (lumberyard-employee-dm) [reply Code/Editor/Plugins/ProjectSettingsTool/ProjectSettingsToolWindow.cpp:372]: I think in the case that the index is 0 the `m_ui->platformTabs` container would have a size of 0

**Review by dtamkin1 — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]
