### PR TITLE
Fix Mac warnings as errors

### LINKED ISSUE #13697: macOS: Building Development and PhysX5Support branch builds fails due to failed AzFramework.Tests and AzToolsFramework.Tests  commands
**Describe the bug**
CMake fails to build Development and PhysX5Support branches on MacBook Pro 2020 and MacBook Air 2020 macOS machines due to the following errors:

**MacBook Air 2020**
```
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/macpro15/o3de/osx_build/build/AzFramework.Tests.build/profile/Objects-normal/x86_64/unity_1_cxx.o /Users/macpro15/o3de/osx_build/Code/Framework/AzFramework/CMakeFiles/AzFramework.Tests.dir/Unity/unity_1_cxx.cxx normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'AzFramework.Tests' from project 'O3DE')
(1 failure)
Elapsed time: 882 s. (time), 0.060312 s. (clock)
```
**MacBook Pro 2020**
```
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/macpro13/o3de/osx_build/Code/Framework/AzToolsFramework/O3DE.build/profile/AzToolsFramework.Tests.build/Objects-normal/x86_64/unity_10_cxx.o /Users/macpro13/o3de/osx_build/Code/Framework/AzToolsFramework/CMakeFiles/AzToolsFramework.Tests.dir/Unity/unity_10_cxx.cxx normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'AzToolsFramework.Tests' from project 'O3DE')
(1 failure)
Elapsed time: 8845 s. (time), 0.129916 s. (clock)
```

The exact software specifications of the machines are:

* MacBook Pro 2020 (Intel Core i5, Big Sur 11.3.1,XCode 13.0, Xcode 13.2.1, CMake 3.22.0 on AutomatedTesting and New projects
* MacBook Air 2020 (M1 chipset, Ventura 13.0.1 , XCode 14.2 , CMake 3.25.0 on AutomatedTesting and New projects

Please note that prior to updating MacBook Air 2020 from  (M1 chipset, Monterey 12.6 , XCode 14.0.1 , CMake 3.24.3) to
 (M1 chipset, Ventura 13.0.1 , XCode 14.2 , CMake 3.25.0) on Development (35ee631) and PhysX5Support (c885bb7) this particular machine was able to build the Editor but it was crashing on launch with _RPI System Could not initialize_ correctly error,
however MacBook Pro 2020 machine was already failing the building with AzToolsFramework.Tests then.

For further information please refer to the attached failed build logs and failed launch logs.

**Steps to reproduce**
1. Obtain the Development branch build via GitHub.
2. Create a new or move your preexisting 3rdParty folder containing CMake into the o3de folder.
3. Obtain python packages with the _get_python.sh_ script located in the _o3de/python_ directory.
4. Create the _osx_build_ folder under the o3de location.
5. Set the following temporary environment variables in the Terminal:
```
export PATH=$PATH:/Users/<home_folder_name>/o3de/3rdParty/CMake/CMake.app/Contents/bin
export LY_3RDPARTY_PATH=/Users/<home_folder_name>/o3de/3rdParty
export LY_PACKAGE_SERVER_URLS=https://d2c171ws20a1rv.cloudfront.net
```
6. Configure and generate the Xcode solution with the following command:
`cmake .. -G "Xcode" -DLY_3RDPARTY_PATH=$LY_3RDPARTY_PATH -DLY_PROJECTS=AutomatedTesting -DLY_UNITY_BUILD=1`

7. Build Mac binaries with the following command:
`cmake -E time cmake --build . --target ALL_BUILD --config profile`

**Expected behavior**
Building process finishes successfully without errors.

**Actual behavior**
Building fails.

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
976601b

**Desktop/Device (please complete the following information):**
- Device: Mac
- OS: macOS
- Version: Ventura 13.0.1
- CPU: M1
- GPU: M1
- Memory: 16GB

**Additional context**
[Development  976601b failed build log MacBook Air.txt](https://github.com/o3de/o3de/files/10228197/Development.976601b.failed.build.log.MacBook.Air.txt)
[Development_976601b_building_failed_log MacBookPro.txt](https://github.c
[PhysX5Support 83d53ad branch failed build log MacBook Air.txt](https://github.com/o3de/o3de/files/10228294/PhysX5Support.83d53ad.branch.failed.build.log.MacBook.Air.txt)
om/o3de/o3de/files/102
[Editor PhysXSupport5(c885bb7) building but not launching prior to update terminal log MacBook Air.txt](https://github.com/o3de/o3de/files/10228297/Editor.PhysXSupport5.c885bb7.building.but.not.launching.prior.to.update.terminal.log.MacBook.Air.txt)
28199/Development_976601b_building_failed_log.MacBookPro.txt)

### PR DESCRIPTION
**Pull request by moraaar**
Signed-off-by: moraaar <moraaar@amazon.com>

## What does this PR do?

Fixes #13697

Fixes for the following compilation errors:

````
/Users/macpro/Desktop/build/o3de/Code/Framework/AzCore/Tests/AZStd/Bitset.cpp:27:30: error: implicit conversion loses integer precision: 'const testing::WithParamInterface<unsigned long>::ParamType' (aka 'const unsigned long') to 'AZ::u32' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
            m_unsignedLong = GetParam();
                           ~ ^~~~~~~~~~
1 error generated.
````

````
/Users/moraaar/Amazon/o3de/Code/Framework/AzCore/Tests/JSON.cpp:124:43: error: implicit conversion loses integer precision: 'size_t'
      (aka 'unsigned long') to 'rapidjson_ly::SizeType' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
                author.SetString(lbuffer, static_cast<size_t>(len), document.GetAllocator());
                       ~~~~~~~~~          ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
````

````
In file included from /Users/moraaar/Amazon/o3de/Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/AzToolsFrameworkTestHelpers.h:46:
In file included from /Users/moraaar/.o3de/3rdParty/packages/qt-5.15.2-rev8-mac/qt/lib/QtTest.framework/Headers/QtTest:11:
/Users/moraaar/.o3de/3rdParty/packages/qt-5.15.2-rev8-mac/qt/lib/QtTest.framework/Headers/qtest.h:100:34: error: implicit conversion
      loses integer precision: 'qsizetype' (aka 'long long') to 'int' [-Werror,-Wshorten-64-to-32]
        str[i] = "01"[ba.testBit(i)];
                         ~~~~~~~ ^
````

````
In file included from /Users/moraaar/Amazon/o3de/Gems/ScriptCanvasDeveloper/Code/Editor/Source/EditorAutomation/EditorAutomationActions/EditorKeyActions.cpp:11:
In file included from /Users/moraaar/Amazon/o3de/AutomatedTesting/build/mac/bin/profile/QtTest.framework/Headers/qtest.h:449:
In file included from /Users/moraaar/Amazon/o3de/AutomatedTesting/build/mac/bin/profile/QtTest.framework/Headers/qtestsystem.h:45:
/Users/moraaar/Amazon/o3de/AutomatedTesting/build/mac/bin/profile/QtCore.framework/Headers/qtestsupport_core.h:79:30: error: implicit
      conversion loses integer precision: 'qint64' (aka 'long long') to 'int' [-Werror,-Wshorten-64-to-32]
        remaining = deadline.remainingTime();
                  ~ ~~~~~~~~~^~~~~~~~~~~~~~~
````

````
/Users/moraaar/Amazon/o3de/Code/Tools/AssetProcessor/native/unittests/FileWatcherUnitTests.cpp:303:39: error: implicit conversion
      loses integer precision: 'unsigned long' to 'int' [-Werror,-Wshorten-64-to-32]
            EXPECT_STREQ(m_filesAdded[fileIndex].toUtf8().constData(), filename.toUtf8().constData());
                         ~~~~~~~~~~~~ ^~~~~~~~~
````

## How was this PR tested?

Built Mac ALL_BUILD target.

### CODE REVIEW

**Review by rgba16f — APPROVED** [review]

**Review by AMZN-daimini — APPROVED** [review]

File: Code/Tools/AssetProcessor/native/unittests/FileWatcherUnitTests.cpp [hunk 1]
```diff
@@ -300,10 +300,10 @@ namespace FileWatcherTests
         {
             QString filename = QDir(m_assetRootPath).absoluteFilePath(QString("test%1.tif").arg(fileIndex));
             filename = QDir::toNativeSeparators(filename);
-            EXPECT_STREQ(m_filesAdded[fileIndex].toUtf8().constData(), filename.toUtf8().constData());
+            EXPECT_STREQ(m_filesAdded[static_cast<unsigned int>(fileIndex)].toUtf8().constData(), filename.toUtf8().constData());
```
Comment (hultonha) [inline Code/Tools/AssetProcessor/native/unittests/FileWatcherUnitTests.cpp:303]: nit: Don't feel the need to change this now but I think it's generally preferred to use `uint32_t` as opposed to `unsigned int` (much less typing for one thing 😅)

**Review by hultonha — APPROVED** [review]
Thanks for fixing these! Much appreciated 🥳

**Review by cgalvan — APPROVED** [review]

File: Code/Tools/AssetProcessor/native/unittests/FileWatcherUnitTests.cpp (hunk 1 above)
Comment (lumberyard-employee-dm) [reply Code/Tools/AssetProcessor/native/unittests/FileWatcherUnitTests.cpp:303]: The warning says is about a cast from` unsigned long` to **signed** `int`, not `unsigned int`.

Comment (moraaar) [reply Code/Tools/AssetProcessor/native/unittests/FileWatcherUnitTests.cpp:303]: I tried `unsigned int` first to cover more numbers from `unsigned long` and since it didn't complain anymore I left it with unsigned. Maybe the compiler is then converting it to signed, but it's not complaining anymore.
