### PR TITLE
MikkT tangent generation support

### LINKED ISSUE #2229: Tangents are not automatically generated in case there are none in the source asset
Tangents and bitangents are not generated automatically for source assets resulting in incorrect lighting for some assets.

We have a MikkT tangents generation component that runs but the generated scene graph nodes for the the tangents are not used by the model asset builder. The tangents need to get generated before the mesh optimizations and also the behavior of how we modify the scene graph needs to change. Rather than adding new scene graph nodes, the already existing nodes' data should get modified and only in case there are no nodes for tangents and bitangents, add them.

Before

### PR DESCRIPTION
**Pull request by amzn-jillich**
* MikkT generator fills given tangent data rather than creating a new scene node.
* Removed emfx legacy tangent generation settings from tangents rule.
* Register tangents rule for mesh groups, so users can add it to the scene settings.
* Default setting when no tangents rule: MikkT tangents.
* Calculates tangents/bitangents for all available uv sets.
* Creates tangent/bitangent data in in case they are not existing yet (as in: the source scene contains tangents/bitangents)
* Overwrites the tangent/bitangent data from the source scene in case MikkT is wished.
* Added helper functions to create tangent/bitangent scene nodes, finding tangent/bitangent data for a given uv layer and calculating the number of uv layers provided by the mesh scene node.

**Broken source asset tangents:**
Before:
Before
After (MikkT tangents):
After

**Rin:**
Source tangents:
SourceTangents

Rin MikkT tangents:
MikkTTangents

Resolves #2229

### CODE REVIEW

File: Gems/SceneProcessing/Code/Source/Generation/Components/TangentGenerator/TangentGenerateComponent.cpp [hunk 1]
```diff
@@ -191,95 +184,175 @@ namespace AZ::SceneGenerationComponents
...
-                case AZ::SceneAPI::DataTypes::TangentSpace::FromSourceScene:
+                    AZ_TracePrintf(AZ::SceneAPI::Utilities::LogWindow, "Using source scene tangents and bitangents for uv set %zu for mesh '%s'.\n",
+                        uvSetIndex, scene.GetGraph().GetNodeName(nodeIndex).GetName());
+                    continue;
+                }
+                else
                 {
-                    allSuccess &= true;
+                    // In case there are no tangents/bitangents while the user selected to use the source ones, default to MikkT.
+                    AZ_TracePrintf(AZ::SceneAPI::Utilities::WarningWindow, "Cannot use source scene tangents as there are none in the asset for mesh '%s' for uv set %zu. Defaulting to generating tangents using MikkT.\n",
```
Comment (amzn-rhhong) [inline Gems/SceneProcessing/Code/Source/Generation/Components/TangentGenerator/TangentGenerateComponent.cpp:228]: I think this should be a warning. It's likely user has a misunderstanding when selecting this option, or this rule is applied but the source asset has changed.

File: Gems/SceneProcessing/Code/Source/Generation/Components/TangentGenerator/TangentGenerateComponent.cpp [hunk 2]
```diff
@@ -191,95 +184,175 @@ namespace AZ::SceneGenerationComponents
...
+                if (!AZ::SceneGenerationComponents::TangentGenerateComponent::CreateTangentLayer(scene.GetManifest(), nodeIndex, meshData->GetVertexCount(), uvSetIndex,
+                    tangentSpace, graph, &tangentData))
                 {
-                    allSuccess &= AZ::TangentGeneration::Mesh::MikkT::GenerateTangents(
-                        scene.GetManifest(), graph, nodeIndex, const_cast<AZ::SceneAPI::DataTypes::IMeshData*>(meshData), uvSetIndex);
-                    for (AZ::SceneData::GraphData::BlendShapeData* blendShape : blendShapes)
-                    {
-                        allSuccess &= AZ::TangentGeneration::BlendShape::MikkT::GenerateTangents(blendShape, uvSetIndex);
-                    }
+                    AZ_TracePrintf(AZ::SceneAPI::Utilities::ErrorWindow, "Failed to create tangents data set for mesh %s for uv set %zu.\n",
```
Comment (amzn-rhhong) [inline Gems/SceneProcessing/Code/Source/Generation/Components/TangentGenerator/TangentGenerateComponent.cpp:239]: Same here. In the az standard coding practice
AZ_TracePrintF - "Programmers might find this useful/It is possible something is incorrect"
AZ_Error - "Somethings wrong with the data.  We'll continue, but certain stuff is broken.  Generally, whoever made the offending file / asset / etc must fix it, but it won't require a code change to fix"
AZ_Warning - "Everything should still function, but sub-optimally.  It won't require a code change to fix, its a data problem"

I'd argue this is more of an AZ_Error?

File: Gems/SceneProcessing/Code/Source/Generation/Components/TangentGenerator/TangentGenerateComponent.cpp [hunk 3]
```diff
@@ -191,95 +184,175 @@ namespace AZ::SceneGenerationComponents
...
+            bitangentData->SetTangentSpace(tangentSpace);
 
-                // If we use EMotion FX calculated tangents, we don't need to generate this here.
-                case AZ::SceneAPI::DataTypes::TangentSpace::EMotionFX:
-                    allSuccess &= true;
-                    break;
+            switch (tangentSpace)
+            {
+            // If we want source scene tangents, we don't need to do anything for that.
+            case AZ::SceneAPI::DataTypes::TangentSpace::FromSourceScene:
```
Comment (amzn-rhhong) [inline Gems/SceneProcessing/Code/Source/Generation/Components/TangentGenerator/TangentGenerateComponent.cpp:260]: Looking at the code above, this probably is unachievable code? Because had the user select the fromSourceScene option, either it will hit continue or it will be forced to use MikkT. I think when code reach this point the space option will always be mikkt.
We can keep the default check here to other tagent space option added.

**Review by amzn-rhhong — APPROVED** [review]
approve with minor issues.

File: Code/Tools/SceneAPI/SceneData/Rules/TangentsRule.cpp [hunk 4]
```diff
@@ -143,11 +43,8 @@ namespace AZ
                     return;
                 }
 
-                serializeContext->Class<TangentsRule, DataTypes::IRule>()->Version(2)
-                    ->Field("tangentSpace", &TangentsRule::m_tangentSpace)
-                    ->Field("bitangentMethod", &TangentsRule::m_bitangentMethod)
-                    ->Field("normalize", &TangentsRule::m_normalize)
-                    ->Field("uvSetIndex", &TangentsRule::m_uvSetIndex);
+                serializeContext->Class<TangentsRule, DataTypes::IRule>()->Version(3)
+                    ->Field("tangentSpace", &TangentsRule::m_tangentSpace);
```
Comment (lsemp3d) [inline Code/Tools/SceneAPI/SceneData/Rules/TangentsRule.cpp:47]: This may need a version converter in case any existing data is referencing the EmotionFX tangentSpace, or is that case safeguarded somewhere else?

File: Gems/SceneProcessing/Code/Source/Generation/Components/TangentGenerator/TangentGenerateComponent.cpp (hunk 3 above)
Comment (amzn-jillich) [reply Gems/SceneProcessing/Code/Source/Generation/Components/TangentGenerator/TangentGenerateComponent.cpp:260]: Good spot, removed

**Review by antonmic — APPROVED** [review]
Just want to point out that if we default to MikkT generation, some users may have their source tangents overridden by MikkT tangents when they don't want it, and this will not be immediately noticeable. Probably not a big deal since UV derived tangents is almost always what you want, but might be an issue for someone at some point?

File: Gems/SceneProcessing/Code/Source/Generation/Components/TangentGenerator/TangentGenerateComponent.cpp (hunk 1 above)
Comment (AMZN-koppersr) [reply Gems/SceneProcessing/Code/Source/Generation/Components/TangentGenerator/TangentGenerateComponent.cpp:228]: Within the SceneAPI AZ_Warning and AZ_Error have (had?) a different meaning. To get reporting to work correctly AZ_TracePrintf should always be used but with specific windows (the first parameter). So in this case `AZ_TracePrintf(AZ::SceneAPI::Utilities::WarningWindow` is equivalent to calling AZ_Warning.

Comment (amzn-jillich) [reply Gems/SceneProcessing/Code/Source/Generation/Components/TangentGenerator/TangentGenerateComponent.cpp]: Changed to AZ_Warning/AZ_Error and tested the effects, they show up as warnings/errors in the AP the same way. I was following the pattern that we use across the scene api with the traceprintfs.

File: Code/Tools/SceneAPI/SceneData/Rules/TangentsRule.cpp (hunk 4 above)
Comment (amzn-jillich) [reply Code/Tools/SceneAPI/SceneData/Rules/TangentsRule.cpp:47]: The .assetinfo files are now stored as json and don't use the version converters. The json deserializer will just throw away data that is not reflected without the need to remove the elements in a version converter (they are not even called).

**Comment by amzn-jillich** [comment]
After further consideration together with the rendering team we switched the default to using source tangents. This makes most sense from a UX point of view as well. When adding the tangents rule, MikkT is the default. We later on can introduce a setreg using which users can specify to auto add the tangents rule (defaulting to MikkT) in case wished. We don't automatically add the tangents rule for now.
